### ISSUE TITLE
support local CouchDB in place of Cloudant

### ISSUE THREAD

**Issue by sjfink** [openwhisk/openwhisk#1]
Add an option to deploy openwhisk pointing to a CouchDB installation rather than requiring a Cloudant account.

**Comment by psuter** [comment]
Just a quick note that I've been working on this and got all the tests in `DataStoreTests.scala` to pass in my branch psuter/openwhisk@d75f18772bd7be7c112bf7ff19ab914ab8303767. The plan is now to unify the Cloudant/CouchDB classes to avoid the duplication I introduced, and to improve the setup scripts.

**Comment by psuter** [comment]
Also, one point we should discuss is whether we want to make a CouchDB container an (optional) part of the deployment, or whether we "just" want to support connections to databases that users set up themselves.

**Comment by mbehrendt** [comment]
@psuter can you pls document all changes you had to make for supporting couchdb?

to your 2nd point....how much effort would that be? i guess no code changes?

**Comment by mbehrendt** [comment]
just looked at the branch, seems like there were no real changes needed?

**Comment by rabbah** [comment]
@psuter is head of my changes, I am working off his fork.

**Comment by rabbah** [comment]
Here are two patches required to get the CLI tests to pass on the couchdb-in-a-box branch.

```
diff --git a/common/scala/src/whisk/core/entity/WhiskStore.scala b/common/scala/src/whisk/core/entity/WhiskStore.scala
index 661c7ba..eebc1bb 100644
--- a/common/scala/src/whisk/core/entity/WhiskStore.scala
+++ b/common/scala/src/whisk/core/entity/WhiskStore.scala
@@ -80,7 +80,7 @@ protected[core] object Util {
         if(config.dbProvider == "Cloudant") {
             new CloudantStore[RawDocument, DocumentAbstraction](config.dbUsername, config.dbPassword, name(config))
         } else {
-            new CouchDbStore[RawDocument, DocumentAbstraction](config.dbHost, config.dbPort.toInt, config.dbUsername, config.dbPassword, config.dbAuths)
+            new CouchDbStore[RawDocument, DocumentAbstraction](config.dbHost, config.dbPort.toInt, config.dbUsername, config.dbPassword, name(config))
         }
     }
 }
```

```
diff --git a/tools/db/couchdb/createAdmin.sh b/tools/db/couchdb/createAdmin.sh
index e6c7917..bbe3093 100755
--- a/tools/db/couchdb/createAdmin.sh
+++ b/tools/db/couchdb/createAdmin.sh
@@ -45,3 +45,7 @@ CURL="curl -k"
 #   - an output of "" is a good sign.
 #   - an output of {"error": ...} is not a good sign. 
 ${CURL} -X PUT https://${COUCHDB_HOST}:${COUCHDB_PORT}/_config/admins/${COUCHDB_USER} -d "\"${COUCHDB_PASS}\""
+
+# Disable reduce limit on views
+echo ${CURL} -X PUT https://${COUCHDB_HOST}:${COUCHDB_PORT}/_config/query_server_config/reduce_limit -d '"false"' -u ${COUCHDB_USER}:${COUCHDB_PASS}
+${CURL} -X PUT https://${COUCHDB_HOST}:${COUCHDB_PORT}/_config/query_server_config/reduce_limit -d '"false"' -u ${COUCHDB_USER}:${COUCHDB_PASS}
```

The reduce_limit is set false to suppress couch's heuristic for map/reduce on views (which detect if a view is not reducing to a scalar). As this scripts will require further refactoring to restructure the build and deployment, I'm providing a patch for @psuter to merge as part of the ongoing work.

**Comment by psuter** [comment]
The branch at psuter/openwhisk@5226d62ae337f290d3ab7d90b494ddac11ff0b23 passes all tests using either Cloudant or a generic CouchDB installation as the database backend. The database code is shared to the extent possible, considering the Java APIs for Cloudant and CouchDB are type-incompatible.

We still need to make a pass on all comments and documentation elements that are Cloudant-specific. We also need to consider how the refactoring (in particular of environment variables shell scripts) affects our various builds.

**Comment by psuter** [comment]
The code has made it to master, and Travis continuous integration testing is now done on the full test suite, using CouchDB as store. Keeping this issue open to remind me to document the setup for interested CouchDB users.

**Comment by sjfink** [comment]
Docs checked in -- closing as fixed
