### ISSUE TITLE
Update CLI to reflect that rules are now enable/active on creation

### ISSUE THREAD

**Issue by csantanapr** [openwhisk/openwhisk#1015]
The backend will be change so rules on creation will be active/enable by default #1008 
The CLI will need to be updated to change this.

This change is based on user feedback, that they always expect rules to be active/enable on creation time.

The proposal is to remove the flag `--enable` from the `wsk rule create` command.
Not introduce a a new flag (i.e. ``--not-enable`) as this is confusing, and not a feature requested by users.
Is user wants to disable a rule when creating they can run the disable command `wsk rule disable`
For example 
```
wsk rule create rule1 trigger1 action1
wsk rule disable rule1
```
To re-enable the rule
```
wsk rule enable rule1
```

This depends on #1008

**Comment by csantanapr** [comment]
If after a while there is feedback on requesting some type of flag `--not-enable` then this can be added to the CLI, but for now I prefer to not implement until we hear feedback from real users using the new behavior.

I know choosing default values are a pain to get right, but waiting some time and  feedback/analytics is a good way to land in correct place.

**Comment by dubeejw** [comment]
@csantanapr, will we also need a command to enable a rule after it has been disabled? Ex:

```wsk rule enable rule1```

**Comment by csantanapr** [comment]
@dubeejw enable and disable command already exist today

**Comment by rabbah** [comment]
To summarize: we agreed to remove `--enable` from the CLI for `rules` and do nothing else.

**Comment by dubeejw** [comment]
@rabbah, I don't believe ```rule update``` currently has the ```--enable``` flag.
