### ISSUE TITLE
No way to determine that actions part of rules didn't invoke because of DoS

### ISSUE THREAD

**Issue by ioana-blue** [openwhisk/openwhisk#1017]
@psuter and I were thinking about implementing a specialized crawler using OW. We imagined the workers using a DB to coordinate the work. Imagine we have a rule that gets triggered whenever a new item is added to this database (db feed). Since in this example presumably there are 100s of actions running at the same time on behalf of the same user, we may reach DoS limits. Currently there is no way to tell that one of the actions didn't run (in effect, there is no way to figure out that one of the items in the DB was not operated on).

**Comment by rabbah** [comment]
wouldn't it be a form of dos for whisk to record throttled activations and theirs trigger input? I would view it differently. The feed (service broker or provider) should retry or track these for you, or we can offer a queued mode to soften these effects by queuing activations until the window rolls over.

**Comment by ioana-blue** [comment]
I was thinking about this and realized that as a user you could code your action in such a way that you record (somewhere externally) when an action completes. Then compare the actions that were supposed to run and the ones that did run. I think one needs to do this anyway since our model is `run at most once`. @rabbah opened another issue about queuing activations, so I'm closing this one.
