### ISSUE TITLE
Wrong Context Class Loader in Java actions

### ISSUE THREAD

**Issue by glikson** [openwhisk/openwhisk#1020]
The Context Class Loader visible within Java actions is the one that loads the wrapper/proxy code (as opposed to the JarLoader that loads the action class itself). This is both a potential security hole (exposing Whisk internals to the Java action code), and may cause the action code that actually tries to use the context class loader to misbehave (e.g., an attempt to use it in order to load additional classes from the provided action jar would cause ClassNotFound exception).

The solution seems to be to set the context class loader (before invoking the main method of the action class) to the same class loader that is used to load the action jar (and potentially to restore it to the original one after main method is over).

`Thread.currentThread().setContextClassLoader(loader)`

**Comment by psuter** [comment]
If I understand correctly, we should be able to reproduce by building one jar with two classfiles, where `main` from class 1 attempts to dynamically load class 2?

**Comment by glikson** [comment]
yes, using the context class loader - e.g., `Thread.currentThread().getContextClassLoader().loadClass("second.class.name")`. Other class loaders might work -- I am not entirely sure.

**Comment by psuter** [comment]
Issue reproduced in a unit test. Note that `Class.forName("second.class.name")` selects the right classloader and works.
