### ISSUE TITLE
Doc rate limits for action invocations and trigger fires

### ISSUE THREAD

**Issue by csantanapr** [openwhisk/openwhisk#1025]
Document was already implemented here:     https://github.com/openwhisk/openwhisk/blob/master/core/controller/src/main/scala/whisk/core/entitlement/Entitlement.scala#L86

```
private val invokeRateThrottler = new RateThrottler(config, 120, 3600)
private val triggerRateThrottler = new RateThrottler(config, 60, 720)
```

**Comment by rabbah** [comment]
closed with #1101.
