### ISSUE TITLE
Unable to use the same jar in multiple Java actions

### ISSUE THREAD

**Issue by glikson** [openwhisk/openwhisk#1026]
I would like to use the same jar for two Java actions, each with a slightly different 'main' class/method (but sharing the rest of the jar).
Today (with wsk CLI) this does not seem possible, because I can pass only one JAR (which must include all the dependencies etc), and the CLI 'guesses' the main class (by analyzing the jar and picking the first class with proper 'main' method signature).

Related to #1018

**Comment by psuter** [comment]
As an (unsatisfactory) workaround, you can make the REST call yourself; run `wsk -v` to get the payload once, then post it again changing the name of the action and of the main class.

**Comment by csantanapr** [comment]
This will require to allow user to specify the method and class to use from the jar. 
This is useful when you don't want cli to guess, and user knows what's doing.

**Comment by psuter** [comment]
Fixed by #1544.
