### ISSUE TITLE
Travis CI constantly fails. on docker run couchdb

### ISSUE THREAD

**Issue by houshengbo** [openwhisk/openwhisk#1027]
Travis ci raises this error constantly:

```
TASK [couchdb : (re)start CouchDB] *********************************************

Tuesday 09 August 2016  17:48:32 +0000 (0:00:00.085)       0:00:01.090 ******** 

fatal: [172.17.42.1]: FAILED! => {"changed": false, "failed": true, "msg": "ConnectionError(ProtocolError('Connection aborted.', error(111, 'Connection refused')),)"}
```

**Comment by csantanapr** [comment]
sounds like docker-engine problems in travis VM

**Comment by csantanapr** [comment]
Here is one example:
https://travis-ci.org/openwhisk/openwhisk/builds/150994577

**Comment by csantanapr** [comment]
it will be useful to see the version of docker travis is using, we should stick to 1.9.1

**Comment by markusthoemmes** [comment]
The docker version is printed in the log: `Docker version 1.9.1, build a34a1d5`.

We do stick to 1.9.1, docker is setup in `tools/travis/setup.sh`

**Comment by csantanapr** [comment]
We sent email to Travis support to report the problem.

**Comment by csantanapr** [comment]
To stay tune you can create a github trigger in OpenWhisk 😸

**Comment by csantanapr** [comment]
Closing with PR #1030
