### ISSUE TITLE
Provide ansible playbook for common tasks during deployment

### ISSUE THREAD

**Issue by domdom82** [openwhisk/openwhisk#103]
Provide an ansible playbook that runs common steps during whisk deployment:

- deployDatabase
- installCatalog
- buildCLI

Purpose of this playbook is to replace the ant targets

`installCatalog`
`deployDatabase`
`buildCLI`

in `build.xml`

**Comment by lehoanganh** [comment]
already merger with issue #187, therefore closing this issue.
