### ISSUE TITLE
swift action docker image build failure

### ISSUE THREAD

**Issue by rabbah** [openwhisk/openwhisk#1036]
Starting with a clean docker image cache, I cannot build a new `whisk/swiftaction` docker image due to this failure:

```
E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/main/g/gcc-4.8/libobjc4_4.8.4-2ubuntu1~14.04.1_amd64.deb  404  Not Found [IP: 91.189.88.152 80]

E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/main/g/gcc-4.8/libobjc-4.8-dev_4.8.4-2ubuntu1~14.04.1_amd64.deb  404  Not Found [IP: 91.189.88.152 80]

E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
The command '/bin/sh -c apt-get -y install build-essential wget clang libedit-dev libicu52 libxml2-dev' returned a non-zero code: 100
```

--fix-missing does not help, and installing a new version of `clang` (e.g., 3.8) appears to be incompatible.

FYI @paulcastro

**Comment by paulcastro** [comment]
We should update to the Swift 2.2.1 release from 5-03.

**Comment by rabbah** [comment]
Sterlizing got me through. Will leave open and coopt for @paulcastro's upgrades.

**Comment by paulcastro** [comment]
Checking into "no such module 'Foundation' " when using latest Swift 2.2.1 release.  Tried earlier Swift 2.2 release and get same error.

**Comment by paulcastro** [comment]
Per discussion with @rabbah, we will maintain 1-11a support until Swift 3 GA.   We will drop Swift 2  and Swift 3 will become default.

**Comment by rabbah** [comment]
@paulcastro do we need to repurpose this issue for your comment above?

**Comment by paulcastro** [comment]
Close and continue discussion on #1133 ?
