### ISSUE TITLE
implement internal kafka roundtrip latency test within controller

### ISSUE THREAD

**Issue by rabbah** [openwhisk/openwhisk#1042]
The controller should measure and monitor its observed kafka round trip latency (by posting to a dedicated topic and reading from it) and adjusting active ack/split phase monitoring accordingly. This allows the controller to back off active ack if there's a kafka anomaly detected.

**Comment by markusthoemmes** [comment]
This is already done with the newest health protocol, isn't it?

**Comment by rabbah** [comment]
The health protocol informs the controller of invoker health - which might as well be kafka health if there are no messages received. I intended in this issue to also tie that to the active ack short circuiting and fall over to the datastore for activations. You're pointing out that the period for which this would be an issue with the new health protocol is much shorter than the previous 30 seconds. I agree.
