### ISSUE TITLE
adjust ERROR log levels in core components

### ISSUE THREAD

**Issue by rabbah** [openwhisk/openwhisk#1044]
Adjust log level on the following log messages from ERROR to INFO:

- [x] `[ERROR][CouchDbRestStore] [marker:database_getDocument_error] [GET] failure: 'requirement failed: document type class whisk.core.entity.WhiskTrigger did not match expected type class whisk.core.entity.WhiskAction.'`

this is a user error that arises when retrieving an entity with the wrong type.

`[ERROR] [KafkaProducerConnector] sending message on topic '...' failed: org.apache.kafka.common.errors.RecordTooLargeException: The message is xxx bytes when serialized which is larger than the maximum request size you have configured with the max.request.size configuration.` (see https://github.com/openwhisk/openwhisk/issues/1044#issuecomment-239485437)

this can arise if sending a large payload during invoke - should adjust the log level but also short circuit the post and reject earlier in the route.

- [x] `[ERROR] [RemoteEntitlementService] [marker:controller_checkEntitlement_error] failed while checking entitlement: Status: 401 Unauthorized`
- [x] `[ERROR] [NamespacesApi] [GET] namespaces failed: Status: 401 Unauthorized`
- [x] `[ERROR][PackagesApi] [LIST] namespaces lookup failed: Status: 401 Unauthorized`
- [x] `[ERROR] [PackageCollection] entitlement check on package failed: not found on 'get'`

authorization errors should be at INFO level.

- [x] `[ERROR] [RulesApi] [POST] rule update failed: not found on 'get'`
- [x] `[ERROR] [ActionsApi] [DEL] entity failed: Unexpected http response code: 409 Conflict`
- [x] `[ERROR] [ActionsApi] [POST] action activation failed: org.apache.kafka.common.errors.RecordTooLargeException:`

these are likely user error (e.g., deleting while updating it) and should be at INFO level.

**Comment by markusthoemmes** [comment]
Voting to short-circuit early and leave 

```
[ERROR] [KafkaProducerConnector] sending message on topic '...' failed: org.apache.kafka.common.errors.RecordTooLargeException: The message is xxx bytes when serialized which is larger than the maximum request size you have configured with the max.request.size configuration.
```

an error, because it shouldn't happen once short-circuited?
