### ISSUE TITLE
Controller logs not fully following format

### ISSUE THREAD

**Issue by markusthoemmes** [openwhisk/openwhisk#1045]
The controller has some logs like these:

```
sslConfig.config.loose.disableSNI = false
```

They don't follow our log format. We should either silence them or adjust them to fit the layout.

**Comment by markusthoemmes** [comment]
Another one not being caught properly:

```
[2016-08-12T08:10:50.456Z] [WARN] [#tid_424] [TriggersApi] action guest/A_del could not be invoked due to Status: 404 Not Found
Body: {
  "error": "The requested resource does not exist.",
  "code": 426
}
```

**Comment by markusthoemmes** [comment]
SNI messages are from: https://github.com/typesafehub/ssl-config/issues/41

Updating akka.

**Comment by rabbah** [comment]
@psuter FYI (since I had mentioned this before in case it's already resolved).

**Comment by rabbah** [comment]
clarifying this comment: https://github.com/openwhisk/openwhisk/issues/1045#issuecomment-239391555 per discussion with @markusthoemmes:

1. warn should be info (user deleted their action - will open separate issue for cleaning up asset lifecycle)
2. multi line log message
