### ISSUE TITLE
wsk CLI subcommands should include more help text

### ISSUE THREAD

**Issue by hassenius** [openwhisk/openwhisk#1050]
The main commands (action,activation,namespace,package,rule,trigger,sdk,property,list) have help text associated with them, but the subcommands do not. 
Would be very useful to be able to type "wsk help action", or "wsk action help", to get some further information on input and syntax.

**Comment by hassenius** [comment]
Realized I was using the depricated Python CLI.
The new Go CLI has this capability

**Comment by csantanapr** [comment]
Hi @hassenius you can access help by using the flag `-h` or `--help`
It's context aware

**Comment by csantanapr** [comment]
Try on any of the two CLIs `wsk action create --help`
It will give you help specific on the create of actions
