### ISSUE TITLE
 nuke our kafka monitor

### ISSUE THREAD

**Issue by rabbah** [openwhisk/openwhisk#1052]
Right now we have our own special monitor server in the kafka container. It is mostly rotted and only provided `ping` route that we rely on. The kafka monitor was intended to display the cursor for each topic - and of course the list of topics. There are other solutions to this that are under investigation.

We should remove the monitor and deploy a "standard" kafka image so we can upgrade kafka easily, or even try a kafka service. So we need to divorce the "monitor" from the kafka container in general and it's not clear that we need it.

**Comment by perryibm** [comment]
Right.  I think we were going to do it but kafka instability (unexplained delays) caused us to put it off.

**Comment by markusthoemmes** [comment]
Do we have an answer on the "waitFor" for kafka without the ping route? I believe we used that to determine in our deployment when kafka is fully up and ready.

**Comment by perryibm** [comment]
We talked about relocating this outside the container but were a bit vague about how to do it.  One way we could do it is to post to a dedicated "isAlive" topic and also consume from it as a form of ping.  Presumably, this would be some side script that ansible would have to call.

**Comment by markusthoemmes** [comment]
Gone as of 41bd5f4719503a689afb6ad45db26ad84027c80c
