### ISSUE TITLE
Why is system/pipe hard coded in action.go?

### ISSUE THREAD

**Issue by houshengbo** [openwhisk/openwhisk#1057]
I think this is a kind of issue that we hard coded "system/pipe" at Line 533 of openwhisk/tools/go-cli/go-whisk-cli/commands/action.go.

If this action is missing, some of our test cases have to fail, because they are unable to create the sequence of actions. All the test cases we have now cannot access the system auth key, which means they are unable to create fixture for this system/pipe action.

I propose to change this way of implementation, at least by replacing it with a parameter/variable(we can keep the system/pipe action as default), so that we can specify a "mocking pipe" action in the test cases.

**Comment by houshengbo** [comment]
@rabbah @jasonpet @csantanapr @markusthoemmes @dubeejw @mdeuser 
Anyone knows the reason? Thinks we should change?

**Comment by markusthoemmes** [comment]
I do believe that action is always there, it's not related to things like a catalog (hence its in the `system` package)

This is related to #995 where the need of `pipe.js` will go away. @ioana-blue to comment.

**Comment by rabbah** [comment]
The CLI shall remove all references to pipe.js.

**Comment by rabbah** [comment]
@houshengbo use the python CLI as a temporary workaround.

**Comment by rabbah** [comment]
We need to fix this because go cli is otherwise not properly testing sequences.

**Comment by ioana-blue** [comment]
Somehow I missed this discussion and I just got bitten by this issue. I was trying to debug my new code that implements sequences only to realize that my code was not called at all. After some digging, the only sequence test we have uses the go-cli which hardcodes the `pipe.js` hack. It took me some time to understand what was going on since I was still looking at the python cli. For now, locally, I'll make the test use the python cli, but it would be nice if we fix this because the only sequence test we have right now is actually not exercising the code that (currently) implements sequences.

**Comment by mdeuser** [comment]
@rabbah - Can you provide or point to an overview of the python CLI solution to provide a backdrop for the implementation in the above mentioned commit.  Thanks!

**Comment by rabbah** [comment]
See the commit I linked above from the relevant pull request. The essence of the change:

```
         elif args.sequence:
-            pipeAction = '/whisk.system/system/pipe'
-            exe = self.getActionExec(args, props, pipeAction)
+            exe['kind'] = 'sequence'
+            exe['components'] = self.csvToQualifiedActions(props, args.artifact)
```

**Comment by dubeejw** [comment]
@rabbah, could we have had a test that would have discovered this issue?

**Comment by perryibm** [comment]
This is a transitional state because we will eventually delete the pipe file and then the issue would be discovered.  However, the UI was (is?) still depending on this.  @starpit - can you confirm?

**Comment by starpit** [comment]
correct, the UI right now still uses the old pipe implementation.

**Comment by rabbah** [comment]
we can add a test that does wsk action create --sequence followed by wsk action get and confirm the schema is the new one (exec kind is sequence, has components, and there is no pipe).
