### ISSUE TITLE
installWeather has a invalid JSON in the package annotations

### ISSUE THREAD

**Issue by starpit** [openwhisk/openwhisk#1065]
https://github.com/openwhisk/openwhisk/blob/master/catalog/installWeather.sh#L17

notice how the parameters annotation is not valid JSON, it is missing the open { before "name".

**Comment by rabbah** [comment]
#883 add json validation - unfortunately https://github.com/openwhisk/openwhisk/commit/d5f9ae4277ca3f0ff5f7ca8b8a6815468b9b440e snuck in incorrectly.

**Comment by rabbah** [comment]
Merged #883 which includes a fix for this defect. @starpit confirm and close.

**Comment by starpit** [comment]
Goody
