### ISSUE TITLE
Change the Invoker Health protocol

### ISSUE THREAD

**Issue by markusthoemmes** [openwhisk/openwhisk#1073]
Today, we have a "manual" health protocol between the controller and the invokers. Every invoker writes his current timestamp (in an endless loop, every 2 seconds) to the consul Key/Value store. This is putting a lot of load onto the KV store.

Instead, we're proposing to use consul's service list and health checks consul itself is sending to our services to determine wether the components are up. Bonus points for having a more meaningful `/ping` endpoint which actually does checks for the component (for example the controller checking its connectivity)

**Comment by rabbah** [comment]
Is this still valid? (Rest is covered by #1711?)
