### ISSUE TITLE
iOS SDK App not compiling

### ISSUE THREAD

**Issue by csantanapr** [openwhisk/openwhisk#1074]
[xcode-errors.txt](https://github.com/openwhisk/openwhisk/files/422823/xcode-errors.txt)
## Environment details:

* Mac OS El Capitan
* XCode 7.3.1
* WSK CLI version `2016-08-10T15:49:14+00:00`

## Steps to reproduce the issue:

1.   Run `wsk sdk install iOS`
2.   Unzip `OpenWhiskIOSStarterApp.zip`
3.   Run `pod install`
4.   Open with XCode 7.3.1 `OpenWhiskStarterApp.xcworkspace`
5.   Build and Run target/scheme `OpenWhiskStarterApp`

## Provide the expected results and outputs:

```
No warnings and erros, app should compile clean
```

## Provide the actual results and outputs:

```
/Users/csantana23/Documents/dev/whisk/demos/ios0817/OpenWhiskStarterApp/ViewController.swift:80:49: error: tuple pattern has the wrong length for tuple type '(description: String, statusCode: Int)'
                if case let WhiskError.HTTPError(description, statusCode, _) = error {
```

@paulcastro FYI.

**Comment by paulcastro** [comment]
Went through procedure to create starterapp.  I cannot replicate this.  Try hard clean?  You may have cached module from previous version of SDK.

**Comment by csantanapr** [comment]
Did a hard clean still didn't fix it

**Comment by csantanapr** [comment]
After working with @paulcastro it looks the `pod install` is not picking the latest version `0.1.6`

it's picking up `0.1.3`
```
$ pod install
Analyzing dependencies
Downloading dependencies
Installing OpenWhisk (0.1.3)
Generating Pods project
Integrating client project
```

leaving open as more investigation is ongoing, maybe we pinned the Podfile to specific version

**Comment by paulcastro** [comment]
Just to note, this issue is specific to the local dev environment, I haven't seen this problem in mine.    Its best to pin the SDK version in the Podfile regardless so its explicit what version the starter app is using.  That will make it clearer if the developer's pod install is not installing the required version.

**Comment by csantanapr** [comment]
this is fix, I was using old version of SDK
