### ISSUE TITLE
Get all activations of a specific trigger

### ISSUE THREAD

**Issue by tareqmamari** [openwhisk/openwhisk#1085]
I am not pretty sure if this has been already discussed here. As an Openwhisk user, I would like to use an API endpoint to get all activations of a specific entity as an example Triggers. This will allow other applications who want to poll events of specific trigger with no additional operations in the client side (filtering activations).

**Comment by rabbah** [comment]
You may filter activation by name. From the cli or directly against the API.

**Comment by tareqmamari** [comment]
Thanks Rabbah, 
I got it, by using name parameter !
