### ISSUE TITLE
Activations of same actions name in different namespaces can not be differentiated

### ISSUE THREAD

**Issue by tareqmamari** [openwhisk/openwhisk#1087]
Can't differentiate between activations of actions with same names in different namespaces.

One good feature Openwhisk provide is Sharing, where actions and packages can be publically shared. As an example of current famous shared package is the samples package within `whisk.system` namespace. The problem I am facing now is how to differentiate between activations of actions with identical names in different namespaces. As an example, consider the echo action, I have an echo action within my namespace (`/talmaam@de.ibm.com_mainSpace/echo`), and as we all know there is an echo action within (`/whisk.system/samples/echo`). I can't differentiate between the activations of both.

`{
    "activationId": "10444cfad8634e2d8d1e51fed38bb0da",
    "annotations": [],
    "end": 1471608692451,
    "logs": [],
    "name": "echo",
    "namespace": "talmaam@de.ibm.com",
    "publish": false,
    "response": {
        "result": {},
        "status": "success",
        "success": true
    },
    "start": 1471608692375,
    "subject": "talmaam@de.ibm.com",
    "version": "0.0.61"
}
`

and
`{
    "activationId": "ac7095589227473ca66bbc0b52b04ca1",
    "annotations": [],
    "end": 1471608817977,
    "logs": [],
    "name": "echo",
    "namespace": "talmaam@de.ibm.com",
    "publish": false,
    "response": {
        "result": {},
        "status": "success",
        "success": true
    },
    "start": 1471608817323,
    "subject": "talmaam@de.ibm.com",
    "version": "0.0.1"
}
`

**Comment by markusthoemmes** [comment]
Good catch, thanks for surfacing that. This is due to all activations going to the users default namespace (`_`) currently. We got it on our list to fix.

**Comment by markusthoemmes** [comment]
Fixed per namespace/key mapping.
