### ISSUE TITLE
cleanup warnings for ios starter app

### ISSUE THREAD

**Issue by csantanapr** [openwhisk/openwhisk#1088]
## Environment details:
- XCode 7.3 
## Steps to reproduce the issue:
1.   Run `wsk sdk install iOS`
2.   Unzip Starter App
3.   Use Cocoapods or Carthage to add OpenWhisk framework
4.   Build Starter App
## Provide the expected results and outputs:

Expect to have a clean install with no Warnings
## Provide the actual results and outputs:

Build prints 2 warnings
1. FilterForecast.swift

```
OpenWhiskStarterApp/FilterForecast.swift:39:50: warning: conditional cast from '[String : AnyObject]' to '[String : AnyObject]' always succeeds
                if let forecast = forecasts[day] as? [String:AnyObject] {
                                                 ^
```
1. Utils.swift

```
OpenWhiskStarterApp/Utils.swift:46:46: warning: conditional cast from '[String : Any]' to '[String : Any]' always succeeds
            if let forecast = forecasts[day] as? [String:Any] {
                                             ^
```

FYI: @paulcastro @bjustin-ibm

**Comment by rabbah** [comment]
@paulcastro is this still valid?
also can we move the starer app to its own repo to permit developers to just check that out without the extra baggage? this might require some dependence management for the cli since it installs the bundle via one of its install commands.

**Comment by paulcastro** [comment]
No, this isn't valid anymore.  I'll close.

We can migrate the starter app - yes, the location of the stater app zipfile may be affected by this.
