### ISSUE TITLE
Change Podfile for iOS StaterApp

### ISSUE THREAD

**Issue by paulcastro** [openwhisk/openwhisk#1090]
Regarding PR https://github.com/openwhisk/openwhisk-client-swift/pull/17 on iOS SDK, using the simplified Pods setup requires change in Podfile and any associated documentation

**Comment by csantanapr** [comment]
fixed by https://github.com/openwhisk/openwhisk/commit/fc66e6d1208373f2052433123d1d4cdcbdc14694
