### ISSUE TITLE
controller read system overload from consul but could get it from loadbalancer directly

### ISSUE THREAD

**Issue by rabbah** [openwhisk/openwhisk#1092]
In some cases, the controller and loadbalancer are in the same process and can communicate directly (method call/memory) eschewing the need to read from consul. Of course the loadbalancer still needs to report its health to the consul. A fast path should be added to the controller/loadbalancer interface to allow consul bypass where possible.

@perryibm FYI.

**Comment by markusthoemmes** [comment]
The `ActivationThrottle` reads all the activations from consul anyway. It got recently promoted into the Controller code directly. I think it's very simple to add a method there where the controller could potentially ask for system-overload.

**Comment by markusthoemmes** [comment]
@rabbah is this done as of 2fdeb1f935940153de8b9d6df92e326968c4ff67?

**Comment by markusthoemmes** [comment]
Attaching PR for reference: #1191

**Comment by markusthoemmes** [comment]
Done as of 86956e277b69cc033f452b0d86ab4495250f29f8
