### ISSUE TITLE
Java actions fail after 2 minutes

### ISSUE THREAD

**Issue by glikson** [openwhisk/openwhisk#1099]
- Environment: Bluemix
- Steps to reproduce:
  - create a Java action that performs a sleep of more than 2 minutes (e.g., 150 seconds)
  - configure the action timeout to be more than the sleep duration above (e.g., 5 minutes)
  - invoke the action
- Result:
  - `error: 500 Error: Failed to establish a backside connection`

**Comment by glikson** [comment]
Sounds related to the 2 min timeout of DataPower documented at https://new-console.ng.bluemix.net/docs/security/index.html#functional-security

**Comment by markusthoemmes** [comment]
Thanks for your report.

To clarify: Are you invoking the action blockingly?

**Comment by glikson** [comment]
yes

**Comment by rabbah** [comment]
This is specific to Bluemix not openwhisk - moving to appropriate repository.
