### ISSUE TITLE
Write documentation for Java actions

### ISSUE THREAD

**Issue by glikson** [openwhisk/openwhisk#1104]
It seems that static fields in Java actions are initialized only on first invocation of an action.
- Environment: Bluemix
- Steps to reproduce:
  - create a Java action with the code below
  - invoke it multiple times
  - observe that the returned 'value' is increasing by one every invocation

``` Java
import com.google.gson.JsonObject;
public class Static {
    static int field = 0;
    public static JsonObject main(JsonObject args) {
        JsonObject response = new JsonObject();
        response.addProperty("value", field++);
        return response;
    }
}
```

``` sh
$ jar cf static.jar Static.class 
$ wsk action create static static.jar 
ok: created action static
$ wsk action invoke static --blocking --result
{
    "value": 0
}
$ wsk action invoke static --blocking --result
{
    "value": 1
}
$ wsk action invoke static --blocking --result
{
    "value": 2
}
```

Not entirely sure whether this is a bug or a feature (that should be properly documented), and whether it is environment-dependent.

**Comment by rabbah** [comment]
This is working as designed. The static field is "state" and if your action ends up reusing a container, state from previous invocations carries over to newer ones. You should not count on the container reuse but you can check for it (i.e. using a static). If you don't want this behavior then all static fields should be final and immutable.

**Comment by glikson** [comment]
OK, thanks. Sounds interesting. Is it documented somewhere?

**Comment by rabbah** [comment]
not yet.

**Comment by sjfink** [comment]
Changing title to reflect the actionable work: Document Java

**Comment by SyCode7** [comment]
Is there a basic example for deploying a java application somewhere yet ?

**Comment by glikson** [comment]
https://github.com/openwhisk/openwhisk/blob/master/docs/actions.md#creating-java-actions

**Comment by rabbah** [comment]
@psuter has a recent blog post as well: https://psuter.net/2017/01/20/openwhisk-java-gradle
