### ISSUE TITLE
Authentication Keys bound to specific Namespaces

### ISSUE THREAD

**Issue by markusthoemmes** [openwhisk/openwhisk#1107]
# Namespace Keys
## Problem statement

Currently, we issue one username/password pair per subject, which is used via HTTP Basic Authentication to authenticate users using OpenWhisk.

The **Entitlement Service** component of the Controller correlates every single subject in our database with N namespaces, potentially coming from a third party Entitlement services (see **Remote Entitlement Service**.

The 1:N mapping of subject (read: auth-key) to namespaces induces problems in **Activation correlation**: When an action is invoked, it is not clear in which namespace the activation record should live. If User X invokes the action _/namespace1/action1_ intuitively that activation should go in _/namespace1_. But if that user invokes the **shared** action _/whisk.system/util/date_, where does that activation live? It shouldn't live in _/whisk.system_ for sure, as that's a shared entity which shouldn't know of any details provided by the caller of the action. Currently, this is worked-around by having all activation of a subject live in the _default namespace_ (equals to the name of the subject). This is very unintuitive and ultimately has an impact on causality in your system, as you cannot correlate which namespace issued which invocations. Depending on your namespace source, that might or might not be awkward.
## Proposed solution

To solve the issue, we resolve the 1:N mapping of auth-key to namespaces by introducing one auth-key per namespace. To do that, we introduce 1 key per namespace per subject.

The status quo of the subject record is something like:

```
{
  "id": "subjectName",
  "uuid": "something-totally-random",
  "key: "somerandomthing"
}
```

Which then evolves to:

```
{
  "id": "subjectName",
  "namespaces": [
    {
      "name": "A human readable name",
      "uuid": "some-guid-maybe",
      "key": "somerandomthing"
    }
  ]
}
```

(`namespaceName` could equal `subjectName` to reflect current behaviour)

In the `namespaces` map, we then have a Namespace -> auth-key mapping, which can be of arbitrary size. Different users being part of the same namespace don't necessarily need to have the same key for said namespace, leading for a safer system with less key-sharing involved.

API authentication continues to be HTTP Basic Authentication.

With this change in place, every invocation can be tied the namespace associated with the key the invocation was authenticated with. The activation records will then live in that namespace and will only be accessible through `wsk activation list` using a valid key for that namespace.

An important aspect to note here is, that unlike in the status quo of the system, there is no longer a master key for a subject to access every resource in the namespaces he has access to. For each operation on a namespace (except listing namespaces themselves, see below) you need to authenticate using an auth-key associated to that namespace.
#### How do I change namespaces?

The CLI currently has a `wsk namespace list` and `wsk property set --namespace` command. They conveniently list all namespaces a user has access to make it very easy to switch namespaces. This behaviour can still be accomplished by giving each Namespace key the ability to see its peer Namespace keys. That means, `wsk namespace list` (or `GET /api/v1/namespaces`) with a valid Namespace key will return all the other Namespace keys in the subject record of the user. `wsk property set --namespace` then simply sets `AUTH=my-other:ns-key` to `~/.wskprops` instead of setting `NAMESPACE=myNamespace` (which in fact can completely go away)
## Issues not solved by this

**Access control:** Each Namespace key is still able to get access to every entity the user has access to. To solve this is out of scope of this proposal.

**Comment by g12megha** [comment]
Can you explain the authentication mechanism which will be provided by this change. I was under the assumption that we can create multiple users under a namespace but when i run the command wskadmin user list #{namespace}, it just displays the current user. For example. i created a user Test1 under Namespace1, so now i change my context using wsk property set --auth {Auth key for Test1}. When i run wsk user list, only the Test1 will be displayed even if i have created Test2 under namespace1. In .wskprops file, namespace will be Namespace1 but when i do wsk namespace list, it will displayTest1 as namespace.

**Comment by rabbah** [comment]
I'm not sure I followed but this does help?

```bash
# create guest 1&2 accounts
$ wskadmin user create guest1 -ns shared
...
$ wskadmin user create guest2 -ns shared
...

# create action in /shared namespace
$ wsk action create /shared/a --docker b -u `wskadmin user get guest1 -ns shared`
ok: created action a

# confirm you can access action in /shared namespace
$ wsk action list /shared -u `wskadmin user get guest1 -ns shared`
/shared/a                                                              private blackbox
$ wsk action list /shared -u `wskadmin user get guest2 -ns shared`
/shared/a                                                              private blackbox
```

**Comment by g12megha** [comment]
I m executing the following series of actions 
wskadmin user create guest1 -ns shared
--
wskadmin user create guest2 -ns shared
--
 wskadmin user list shared
*************************************************   guest1

So it just listed out 1 user in namespace "shared" . Is this how this should work ? I was expecting that we have created 2 users guest1 and guest1 in namespace shared. So the wskadmin user list command should list both users.
Another doubt which i have is after running the following command, it says namespace exists .Why ?
wskadmin user create guest1 -ns shared
Namespace already exists


What i was understanding guest1/guest2 are users in namespace shared right ? Can you explain the relation ship between users and namespace and what context is used in the wsk commands ?

**Comment by rabbah** [comment]
`wskadmin user list shared -p 2`

and for reference:

```
> wskadmin user list -h
usage: wskadmin user list [-h] [-p N] [-k] namespace

positional arguments:
  namespace       the namespace to lookup

optional arguments:
  -h, --help      show this help message and exit
  -p N, --pick N  show no more than N identities
  -k, --key       show only the keys
```

the default is 1 for `pick`.

**Comment by g12megha** [comment]
great i got the point now ! Another doubt which is have is when one executes the command wsk namespace list <namespace name> , does it list the current user which is being set in property for the namespace ?
Because in wsk.props file, it correctly mentions the namespace but in command wsk namespace list <name> , it gives the name of user under tht namespace.

**Comment by rabbah** [comment]
A user (more appropriately a subject) is an account (associated with an identity). A namespace is logical structure for organizing assets. A subject may have more than one namespace.

A namespace may be shared, so when a subject lists assets in a namespace, they see all the assets stored there. (Think of namespace as a directory with group permissions - anyone in the group can list its contents.)

`wsk namespace list` currently lists ALL namespaces that a subject has rights to (think of this as the equivalent of `groups <userid>` in UNIX. This command I should add may be going away soon though - to be replaced with tooling specific to a identity management service instead.

**Comment by g12megha** [comment]
But when one creates a user/subject in a particular namespace, it will have its own authkey. So the command wsk namespace list will list the namespace under which the current user is created. How does a particular user have access to multiple namespace when the auth key is different. Or how do u create access for the current user in multiple namespaces ?

**Comment by rabbah** [comment]
See pr https://github.com/openwhisk/openwhisk/pull/1914. Once merged the key will only see its namespace.

**Comment by g12megha** [comment]
currently how is a user/subject identified in different namespaces ?

**Comment by markusthoemmes** [comment]
@g12megha currently there is a bit of ambiguity with regards to access to namespaces. Currently, a subject has access to each namespace in its subject record with each of the keys stored in there.

#1914 will get away with this and only make the namespace accessible that corresponds to the API key you use (modulo public packages etc. of course)

**Comment by cclauss** [comment]
Status on this issue?
