### ISSUE TITLE
loadbalancer dockerfile should contain CMD with start script

### ISSUE THREAD

**Issue by domdom82** [openwhisk/openwhisk#111]
controller and loadbalancer are currently started in different ways:

controller dockerfile contains `CMD controller/bin/controller` that allows us to simply do
```
docker run -d ... whisk/controller
```

in loadbalancer we have no CMD directive which is inconsistent.
here we have to do
```
docker run -d ... whisk/loadbalancer loadbalancer/bin/loadbalancer
```

We should aim to be consistent on our docker image semantics.

Will attach PR to fix this.

**Comment by rabbah** [comment]
Are you going to normalize all the containers this way?

**Comment by markusthoemmes** [comment]
I think that's not possible with Dispatcher today since we need to tell it wether it's an Activator or an Invoker.

**Comment by rabbah** [comment]
you will be happy soon then.
