### ISSUE TITLE
Sendgrid/Twilio SDK package not working in actions

### ISSUE THREAD

**Issue by saschoff91** [openwhisk/openwhisk#1113]
## Environment details:

I try to create actions with the package including of sendgrid and twilio, but it does not work.
The Response in OW Dashboard ist 
`Error: Cannot find module 'twilio'`
`Error: Cannot find module 'sendgrid'`

The PR #829 and #774 are already closed and the OW Doc was updated, but it doesnt affect the package including.

**Comment by rabbah** [comment]
@saschoff91 I think you were using the deployment on bluemix which might lag a bit behind the master branch. Try again?

**Comment by rabbah** [comment]
This should now be addressed in bluemix as well.
