### ISSUE TITLE
buildAndPush.sh from dockerSkeleton is not executable

### ISSUE THREAD

**Issue by csantanapr** [openwhisk/openwhisk#1129]
## Environment details:
- Mac El Capitan
- whisk CLI version         2016-08-25T15:59:36+00:00
- whisk API build       2016-08-25T17:04:25Z
- whisk API build number    whisk-build-253
## Steps to reproduce the issue:
1.   wsk sdk install docker
2.   cd dockerSkeleton
3.   ./buildAndPush.sh csantanapr/blackboxdemo
## Provide the expected results and outputs:

```
script to run with success
```
## Provide the actual results and outputs:

```
-bash: ./buildAndPush.sh: Permission denied
```
## Additional information you deem important:

$ ls -l
total 32
-rw-r--r--  1 csantanapr  staff   281 Aug 26 09:06 Dockerfile
-rw-r--r--  1 csantanapr  staff  1096 Aug 26 09:06 README.md
**-rw-r--r--  1 csantanapr  staff   507 Aug 26 09:06 buildAndPush.sh**
-rw-r--r--  1 csantanapr  staff   625 Aug 26 09:06 example.c

**Comment by csantanapr** [comment]
FYI @rabbah

**Comment by rabbah** [comment]
This appears to be a problem with the `go-cli`:

```
> go-cli/wsk --apihost 192.168.99.100 -i sdk install docker 
The docker skeleton is now installed at the current directory.
> ls -l dockerSkeleton/buildAndPush.sh 
-rw-r--r--  ... dockerSkeleton/buildAndPush.sh
> rm -rf dockerSkeleton/
> wsk --apihost 192.168.99.100 -i sdk install docker
The docker skeleton is now installed at the current directory.
> ls -l dockerSkeleton/buildAndPush.sh 
-rwxr-xr-x  ... dockerSkeleton/buildAndPush.sh
```

@dubeejw @mdeuser

**Comment by csantanapr** [comment]
Please update doc when this one get's resolve
We have this workaround in the docs `chmod +x buildAndPush.sh`

**Comment by rabbah** [comment]
Fixed by @dubeejw.
