### ISSUE TITLE
Error: image openwhisk/dockerskeleton:latest not found

### ISSUE THREAD

**Issue by csantanapr** [openwhisk/openwhisk#1130]
## Environment details:
- Mac
- whisk CLI version         2016-08-25T15:59:36+00:00
- whisk API build       2016-08-25T17:04:25Z
- whisk API build number    whisk-build-253
## Steps to reproduce the issue:
1.   wsk sdk install docker
2.   cd dockerSkeleton
3.   chmod +x ./buildAndPush.sh
4.   ./buildAndPush.sh csantanapr/blackboxdemo  
## Provide the expected results and outputs:

```
script to run to success
```
## Provide the actual results and outputs:

```
🚀  $ ./buildAndPush.sh csantanapr/blackboxdemo
Using csantanapr/blackboxdemo as the image name
Sending build context to Docker daemon 6.656 kB
Step 1 : FROM openwhisk/dockerskeleton
Pulling repository docker.io/openwhisk/dockerskeleton
Error: image openwhisk/dockerskeleton:latest not found
Docker build failed
```
## Additional information you deem important:

Base image `openwhisk/dockerskeleton`  is not found on Docker Hub https://hub.docker.com/r/openwhisk/dockerskeleton/

This is a reference `FROM openwhisk/dockerskeleton` from `Dockerfile`

```
# Dockerfile for example whisk docker action
FROM openwhisk/dockerskeleton

ENV DEBIAN_FRONTEND noninteractive

ENV FLASK_PROXY_PORT 8080

ADD example.c /action/example.c
RUN cd /action; gcc -o exec example.c

CMD ["/bin/bash", "-c", "cd actionProxy && python -u actionproxy.py"]
```

FYI: @rabbah

**Comment by rabbah** [comment]
Not reproducible.
