### ISSUE TITLE
Update wskadmin with namespace related commands

### ISSUE THREAD

**Issue by markusthoemmes** [openwhisk/openwhisk#1132]
`wskadmin` has user creation and deletion commands. With #1107 in place, we should also support namespace creation and deletion commands.

**Comment by g12megha** [comment]
Is this feature available ?If yes, which build ?

**Comment by rabbah** [comment]
Do you mean is wskadmin available already? If so yes it's in master/head in the bin directory.

**Comment by g12megha** [comment]
No i meant the feature to create namespace to the wskadmin options

**Comment by g12megha** [comment]
is it now possible to add multiple users in a namespace ? any documentation already available for using it ?

**Comment by rabbah** [comment]
not yet - could be done after this pr #1681.
