### ISSUE TITLE
Update CLI to change the namespace via changing the auth-key

### ISSUE THREAD

**Issue by markusthoemmes** [openwhisk/openwhisk#1135]
As stated in #1107, the CLI will need to change the namespace by changing authentication keys under the hood. The namespace parameter as a whole will go away and is unified with `auth`.

Python CLI used to have an interactive namespace chooser (`wsk property set --namespace`), which listed every namespace and had the user choose from them. I could invision the same, implemented in `wsk namespace change`. `wsk namespace list` can be a more manual variant of this, where each namespace + its auth-key is listed.

**Comment by csantanapr** [comment]
@markusthoemmes to be able to implemented the required UX describe above https://github.com/openwhisk/openwhisk/issues/1135#issue-173478023

There are few assumptions that need to be clarify
1. user will be able to configure CLI only specifying an authkey, this key is associated with one single namespace
  `$ wsk property set --apihost openwhisk.ng.bluemix.net --auth 1234`
2.  Any auth key allows you to get/list the other namespaces, and allows you to retrieve any of the other auth keys
```
$ wsk namespace list
namespaces  auth
===============
myorg_prod   5678
user1_dev       1234
user1_stage    9123
user1_demo    4567

```

**Comment by rabbah** [comment]
@markusthoemmes close?
