### ISSUE TITLE
Docker action times out when attempting to send email

### ISSUE THREAD

**Issue by iainhouston** [openwhisk/openwhisk#1145]
## Issue summary

A Python action can send an email; a Docker action cannot.
## Environment details:

* Local Docker (for Mac Version 1.12.0-a)   
* Openwhisk CLI
    - whisk API host		openwhisk.ng.bluemix.net
    -  whisk API version	v1
    -  whisk namespace		iainhouston_usexplore
    -  whisk CLI version	2016-08-10T15:49:14+00:00
    -  whisk API build		2016-08-25T17:04:25Z
    -  whisk API build number	whisk-build-253

## Steps to reproduce the issue:

Code and runtime commands detailed in the  `withmail` branch of https://github.com/iainhouston/dockerPython.git .   
With code you can clone, copy and paste.   

In summary:

1.   Build and run locally with `curl`
2.   Push to Docker Hub
3.   `wsk action update ...`
4.   `wsk action invoke ... `

## The expected results and outputs:

A Docker action should be able to send an email just like a Python action snippet can. (as demonstrated by Carlos Santana). So one outcome is the receipt of an email  by the `"MAIL_RECIPIENT":"known@example.com"` below.

If we do:
```
$ curl -H "Content-Type: application/json" \
  -d '{"value":{"MAIL_RECIPIENT":"known@example.com", "MAIL_SERVER":"my_smart_host", \
  "MAIL_USERNAME":"known_to_smart_host", "MAIL_PASSWORD":"known_to_smart_host", \
  "MAIL_DEFAULT_SENDER":"known@smart_host"}}' \
  -w  "%{http_code}\n"  http://localhost:8080/run

```

we should expect:

```
{
  "outcome": "Success sending mail.", 
  "value": {
    "MAIL_DEFAULT_SENDER": "as_above", 
    "MAIL_PASSWORD": "as_above", 
    "MAIL_RECIPIENT": "as_above", 
    "MAIL_SERVER": "as_above", 
    "MAIL_USERNAME": "as_above"
  }
}
200
```

as a response to the action's `/run` endpoint

## The actual results and outputs:

```
...

ok: invoked /iainhouston_usexplore/tryaction with id 175ab54a4a714afe91cf8601dff9d7ad
{
    "namespace": "iainhouston@mac.com",
    "name": "tryaction",
    "version": "0.0.24",
    "subject": "iainhouston@mac.com",
    "activationId": "175ab54a4a714afe91cf8601dff9d7ad",
    "start": 1472387421133,
    "end": 1472387481155,
    "response": {
        "status": "whisk internal error",
        "success": false,
        "result": {
            "error": "failed to obtain action invocation response"
        }
    },
    "logs": [
        "2016-08-28T12:30:18.737721428Z stderr: * Running on http://0.0.0.0:8080/ (Press CTRL+C to quit)",
        "2016-08-28T12:30:20.936684696Z stderr: 192.168.0.1 - - [28/Aug/2016 12:30:20] \"POST /init HTTP/1.1\" 200 -"
    ]
}

...
```
Notice that it never gets any response from `/run` ... before it times out?
 
## Additional information you deem important:
* issue happens always (when attempting to send email message) please see the  `withmail` branch of https://github.com/iainhouston/dockerPython.git 
* a working example (without trying to send email) is in the `master` branch of https://github.com/iainhouston/dockerPython.git

**Comment by rabbah** [comment]
I spent some time investigating this because this message "failed to obtain action invocation response" indicates something is a miss during initialization - I have added some additional tests and fixed the error message reported (in pending pull request #1150).

The cause of this error is a failed initialization where the action failed to respond to `/init`.

**Comment by iainhouston** [comment]
Sorted! *Openwhisk* seemingly does not send from port 25  but making the smtp connection on port 587 works. 

In this particular app `Flask-Mail==0.9.1`  was used to send the mail, so: 

```
MAIL_PORT = 587
MAIL_USE_TLS = True
MAIL_USE_SSL = False
```

was sufficient (along with correct server / credential settings of course) for this to work:

```python
try:
	mail = Mail(app)
	msg = Message("Subject to test", recipients=[app.config['MAIL_RECIPIENT']])
	msg.body = dumps(paramd)
	mail.send(msg)
except Exception as e:
	paramd['outcome'] = 'Sorry, Exception sending mail.'
	# Server error
	return make_response(jsonify(paramd), 500)
else:
	paramd['outcome'] = 'Success sending mail.'
	# respond 200
	# jsonify wraps json.dumps
	return jsonify(paramd)
``
