### ISSUE TITLE
invoker should yield a clear error message if docker action fails to pull/run

### ISSUE THREAD

**Issue by rabbah** [openwhisk/openwhisk#1149]
If docker pull fails for blackbox action, invoker tries to run action anyway

```
> wsk action create bogus <something that doesn't exist>
> wsk action invoke bogus
```

The invoker will attempt to pull the docker image, as it should but this should fail:

```
Running command: /usr/bin/docker pull <something that doesn't exist>
> stdout: Using default tag: latest Pulling repository docker.io/library/<something that doesn't exist>
> stderr: Error: image library/<something that doesn't exist> not found 
```

The invoker continues to run the container which again tries to pull the image (run pulls if needed):

```
> stderr: Unable to find image '<something that doesn't exist>:latest' locally Pulling repository docker.io/library/<something that doesn't exist> Error: image library/<something that doesn't exist> not found
```

It might be OK to go ahead and run should pull fails (keeps the logic simpler in the invoker) but here's the activation response:

```
{
    "logs": [
        "Error starting container"
    ],
    "response": {
        "result": {
            "error": "the action did not produce a valid JSON response"
        },
        "status": "action developer error",
        "success": false
    },
}
```

The system is working as designed, the logs are consistent with the error, as is the activation response --- but we should report a more specific error message e.g., “pull from registry failed”. Arguably, we should leave the logs alone (empty) and instead use the `error` property of the activation record to report a more specific explanation.

**Comment by lzbj** [comment]
@rabbah , I can't reproduce the exact output with the latest codebase.

here is my output:

RESPONSE:
Got response with code 200
Body received:
{
  "result": {
    "error": "failed to invoke action guest/bogus: Container hash or name expected in `makeContainer`."
  },
  "success": false,
  "status": "whisk internal error"
}
========
{
    "error": "failed to invoke action guest/bogus: Container hash or name expected in `makeContainer`."
}

Is the bug fixed?
