### ISSUE TITLE
User-Management with Third-Party Integration

### ISSUE THREAD

**Issue by markusthoemmes** [openwhisk/openwhisk#1152]
# User-Management with Third-Party Integration (e.g. CloudFoundry)

In addition to the very basic, CLI based user management approach OpenWhisk supports out-of-the-box, we want to support integrations with third-party systems, that support a richer user-management approach.
## Problem statement

We need a generic way of integrating with third-party services to delegate user authentication and authorisation without impacting our own performance too much or being tightly coupled to the third-party service's uptime.

Under the assumption that "Namespace Keys" (#1107) are already implemented, a third-party service needs to provide "only" the subject record to be stored in the OpenWhisk `subjects` database. After that, we need to keep this record in sync with what the third-party service thinks the authentication and authorisation details are for that subject. Cases to consider include:
1. Creating a new user
2. Granting a user access to a new namespace
3. Removing a user's access to a certain namespace
4. Removing a user
#### 1. Creating a new user

To create a new user, that user exchanges valid access credentials to the third-party service with credentials in OpenWhisk. This means: The user passes valid credentials to OpenWhisk which it then uses to get information about the user from the third-party-service. The information needed are _username_ and _namespaces_ that user is able to access. For CloudFoundry integration this means: The users passes in a valid `accessToken` to OpenWhisk, which then talks to CloudFoundry to get your `developer_guid` (username) and Organization/Space pairs (namespaces).

OpenWhisk now takes this username, creates a subject record for it and issues a Namespace key for each namespace the user is able to access.
The resulting subject record is then returned to the user, giving him access to his initial Namespace keys.

That endpoint to trade the credentials in could be `/api/v2/authenticate`.

Technically the flow will then be:
1. Trade in valid credentials
   
   ```
   POST /api/v2/authenticate
   {
     "accessToken": "$myCloudFoundryAccessToken"
   }
   ```
2. OpenWhisk validates the credentials and gets user information
   
   ```
   GET ${CF_URL}/userinfo
   Authorization: bearer $myCloudFoundryAccessToken
   
   Response:
   {
     "user_id": $the-users-guid
     ...
   }
   ```
3. OpenWhisk gets valid namespaces
   
   ```
   GET ${CF_URL}/v2/spaces
   Authorization: bearer $cloudFoundryClientToken
   
   Response:
   [ spaces ... ]
   
   GET ${CF_URL}/v2/organizations
   Authorization: bearer $cloudFoundryClientToken
   
   Response:
   [ orgs ... ]
   ```
4. OpenWhisk creates a subject record and send it back to the user
   
   ```
   PUT ${COUCHDB}/subjects/$the-users-guid
   {
     "id": $the-users-guid,
     "namespaces": [
       {
         "name": $ORG1_$SPACE1,
         "uuid": $space1-guid,
         "key": "randomlyGeneratedSecret"
       },
       {
         "name": $ORG1_$SPACE2,
         "uuid": $space2-guid,
         "key": "randomlyGeneratedSecret2"
       }
     ]
   }
   ```
#### 2. Granting a user access to a new namespace

As noted in "Namespace Keys" (#1107) a user changes his namespace by listing the namespace he has access to using a key he already has (obtained by the call outlined above for example).

When the user is assigned to a new namespace (either by creating one or given access to an existing one in the third-party service) he'll find out about this by calling `wsk namespace list` (or the REST API equivalent). OpenWhisk can hook into this and issue an **update** request against the third-party service, essentially repeating steps 3 and 4 from above and synchronising the stored set of namespaces with the namespaces it got from the third party service.
#### 3. Removing a user's access to a certain namespace

To remove access to a certain namespace (read: remove the Namespace key for that namespace from the subject) we cannot rely on the user calling `wsk namespace list` to trigger an update.

Instead we schedule an **update** request (see steps 3 and 4 above) every `x` calls a user makes to constantly verify that _active_ users are still allowed to use the system in the bounds they are operating in. This has the caveat of being eventually consistent as the third-party system might be slow. We don't block incoming requests until the update event finishes and refreshes the subject record in the database. If this call results in a namespace being removed, the key to access that namespace will no longer work after the update being completed.
#### 4. Removing a user

If the third-party service returns "Not Found" in the **update** process outlined above, the user can be removed from our database.
### Cache considerations

As we strive for minimum latency on invocations, caches must be in place to keep us from asking external systems too much and relying on their latency.
1. **subjects database:** The code outlined above will be living in the Controller itself, which is the service that we really want to cache the subjects database in. We have full control over local caches there and the update mechanisms should invalidate when necessary.
2. **calls against the third-party system:** Those calls should at least be throttled. The cache duration at this place effectively decides how long eventual consistency is going to take to catch up with the third-party system.
### What if the third-party system is offline?

In order to sustain third-party outages, we propose to continue operating with the data that is already in our system.

The update mechanism will not touch the database at all if the third-party system is offline. One could imagine a threshold of X minutes after which OpenWhisk stops operating because it cannot safely say that users are still allowed to access the system.
### Things to watch
1. CF API is paginated. Deal with that!

**Comment by markusthoemmes** [comment]
Open questions:

1. Will we continue to prepend the entity records with the display name of the namespace (`ORG_SPACE/actionName` vs. `spaceGuid/actionName`)?

**Comment by domdom82** [comment]
^^ I would state that in the design each namespace does have a name and id (uuid) field. 
This is because we need a human-readable version of the namespace for UI + CLI.
The CF integration service then just happens to use ORG_SPACE as a display name and spaceGuid as id. 

On question 2. Internally we should operate only with the uid of the namespace. The display name can be lazily updated whenever we do synchronize with the backend on the actual namespace list.
This of course makes the assumption that a space guid does not change when the space name changes.

**Comment by markusthoemmes** [comment]
I think we pretty much agreed on the first part (as shown in the JSON examples above, the fields are considered to be there).

The second part though will be a semantic change, as we currently always operate with the human-readable way. Also note that we still do not have a central notion of a "namespace" as in: Update one record to update the display name. That might become necessary, maybe it doesn't .

Technically we need a two way lookup:
1. **uuid** to **namespace**: To be able to authenticate the user
2. **namespace human-readable-name** to **namespace**: To be able to resolve human-readable-name to uuid to be able to fetch entities (given they are prefixed with uuid instead of human-readable-name)

The latter is problematic currently (maybe not, read below), because there are **N** subject entries resolving **namespace human-readable-name** to **namespace**. We could potentially use only the entry of the current subject (making it **(human-readable-name, subject)** to **uuid**) which kinda defeats that problem. But then we strike eventual-consistency because the current subject record might not have been updated with the information from CF (see the update mechanism outlined above).

After all, having **N** entries resolving **namespace human-readable-name** to **namespace** might actually be not too problematic as that would *only* induce, that we have a timeframe where two different names are resolved to the same uuid (this timeframe is the time it takes to update every single occurrence of the old name in the system to the new name in the system) which might be indefinite. Again this could be completely irrelevant as the records with the "old" name are unused anyway (as stated by the update mechanism outlined above) hence we could ignore/accept this fact.

Having written this down, it appeals to me that "simply" having a view from **namespace human-readable-name** to **namespace** is sufficient as it it embraces the eventual-consistency introduced by the lazy update mechanism anyway. It states, that the renamed namespace will become available in OpenWhisk as soon as the **first** subject record is updated in our database which strikes me as more useful than to introduce that inconsistency for each subject record on its own.

My proposal would then be:
1. Use `namespaceUuid/actionName` internally, but the human-readable versions on the API side, resolve those internally using a view from **human-readable name** to **namespace** (thus **uuid**).
2. Renaming as stated by @domdom82 only affects the display name and should be handled as an update rather than a delete/recreate. The space guid does not change on a rename.

**Comment by markusthoemmes** [comment]
Not applicable anymore.
