### ISSUE TITLE
Finalize list of CLI installable SDKs

### ISSUE THREAD

**Issue by mdeuser** [openwhisk/openwhisk#1173]
Currently, the CLI allows for installation of a "swift" SDK; however, the results are "Swift SDK coming soon."  Need to finalize the list of downloadable artifacts via the `wsk sdk install` CLI.

## Environment details:

* local deployment, Windows, Bluemix - but should not matter

## Steps to reproduce the issue:

1.   wsk sdk install -h
2.   wsk sdk install swift

## Provide the expected results and outputs:
There is currently no Swift SDK, so remove references to it from the CLI

## Provide the actual results and outputs:

```
>wsk sdk install -h
install SDK artifacts, where valid COMPONENT values are docker, swift, iOS, and bashauto
Usage:
  wsk sdk install COMPONENT [flags]

>wsk sdk install swift
Swift SDK coming soon.
```
```

## Additional information you deem important:
* Check docs as well

**Comment by dubeejw** [comment]
Doesn't look like an Swift SDK exists.
