### ISSUE TITLE
docker lock should be wrapped with a priority queue

### ISSUE THREAD

**Issue by rabbah** [openwhisk/openwhisk#1180]
the invoker employs a docker lock to prevent unsafe concurrent docker operations - while this will improve with docker 1.12, it will still be a serial bottleneck in the invoker. there are two types of containers operations that compete for the unsafe operation lock: those stemming from the stem cell nanny and those stemming from actual load. There is currently no discrimination on priority between these and this can lead to pathologies  where the stem cell containers hog the lock ahead of user container.

@perryibm

**Comment by rabbah** [comment]
@perryibm you fixed this didn't you?

**Comment by perryibm** [comment]
yep - fixed and pushed a while ago
