### ISSUE TITLE
Second phase of kafka backpressure

### ISSUE THREAD

**Issue by markusthoemmes** [openwhisk/openwhisk#1182]
The invoker has been implemented to keep messages in kafka, if its internal queue is full. We should implement the same mechanism up to the loadbalancer to stop sending messages to an already overloaded invoker.

This would also detect a misbehaving invoker (hanging due to any reasons) and effectively taking it out of the deployment, not putting the whole system in a bad state.

**Comment by sjfink** [comment]
Let's discuss before implementing.   Work stealing may be a better option.

**Comment by markusthoemmes** [comment]
Not applicable anymore.
