### ISSUE TITLE
pip install 'requests' in Python actions Dockerfile

### ISSUE THREAD

**Issue by iainhouston** [openwhisk/openwhisk#1190]
At 9:00 this morning the action was running fine - with a python action created no more than 24 hours ago at which time the python program was able to import `requests==2.11.1` in the Openwhisk runtime context.  

After 9:00am I updated the action and now the Openwhisk runtime fails to import `requests`   

`requests`  is rather crucial  to do `curl`-like things

## Environment details:

* local deployment, vagrant, native ubuntu, Mac OS, Bluemix, ...   
* version of docker, vagrant, ubuntu, ...

## Steps to reproduce the issue:

1.   Create an action written in python that uses the `requests` library
2.   Test the action locally
3.   `wsk action invoke pyRequiresRequests --blocking --result `

## Provide the expected results and outputs:

At 9:00 am
```
sitemonitor 4e213863511a40499f081b35c05e2ccd
{
    "text": "All sites OK"
}
```

## Provide the actual results and outputs:

More recently

```
sitemonitor 98325c35ed394f6fbcc0fd94303f5642
{
    "error": "The action did not return a dictionary."
}
Logs:
-01T20:40:59.620303013Z stderr: Traceback (most recent call last):
-01T20:40:59.620386383Z stderr: File "pythonrunner.py", line 50, in run
-01T20:40:59.620406898Z stderr: exec(self.fn, namespace)
-01T20:40:59.620609563Z stderr: File "action", line 4, in <module>
-01T20:40:59.620803581Z stderr: ImportError: No module named requests
1 September 2016 21:40:59 BST
Duration: 252ms
```

## Additional information you deem important:
* issue happens recently  
* I didn't notice the `pip install requests` in the Dockerfile previously ... but *something* must have changed to make the import to be failing now

**Comment by markusthoemmes** [comment]
I believe this is due to recent changes to the python action container and a promotion of a new OpenWhisk version to Bluemix.

**Comment by rabbah** [comment]
Fixed by above commit.

**Comment by iainduncani** [comment]
@markusthoemmes I presume that question was meant for @iainhouston, I've never used python in Whisk!
