### ISSUE TITLE
Throttle limits should not be hard-coded

### ISSUE THREAD

**Issue by perryibm** [openwhisk/openwhisk#1207]
@markusthoemmes @rabbah 

Throttle limits (concurrency and rate limits) should be configurable per deployment with the intention that the limits for larger deployments be raised.  For test systems where we are explicitly testing that throttling is triggered, we may want to use lower limits.

**Comment by rabbah** [comment]
Should be doable now - these limits are set in [ansible](https://github.com/openwhisk/openwhisk/blob/master/ansible/group_vars/all) so could have overrides per deployment (@domdom82 @lehoanganh thoughts?).

**Comment by lehoanganh** [comment]
yes, from CLI such values can be overriden. But, like discussed in other issue, this is *not* human-friendly. This `limits` var has 3 layers.

**Comment by perryibm** [comment]
After reading through some points raised by @lehoanganh in other issues, @rabbah and I think the cleanest way to do this is with a default set of limits and a per deployment set of limits.  These are 2 different sets of variables and WhiskConfig will export the more specific one so we have the option of choosing whatever we want for any deployment but still have a default in case it is unspecified.

For the CI configuration, we will deliberately set lower limits so the throttle tests will work.  It also makes sense since the CI cluster is deliberately tiny.  For YS0 and YP, we will use higher limits (higher than what we currently have) so that users are not impacted.

**Comment by perryibm** [comment]
For expedience, I propose the following phased approach.  I am proceeding with this plan immediately.

1) raise existing limits unconditionally and disable throttle test for now
2) put in per deployment override (use low CI values) and re-enable throttle test
3) per subject stuff will take longer to do correctly

**Comment by sjfink** [comment]
Related proposal: let's nuke the hourly limit entirely.

**Comment by rabbah** [comment]
@perryibm done/close?

**Comment by perryibm** [comment]
done - closing
