### ISSUE TITLE
API v2: initial support for blocking calls via GET

### ISSUE THREAD

**Issue by sjfink** [openwhisk/openwhisk#1222]
We currently support invoking actions via POST on the entity that represents the action.

It has been suggested that it would be useful to support invoking an action via a GET, so that one can simply copy-paste a URL into a browser.

The initial version of this will have limitations (ugly URLs, URLs that expose credentials) but follow on work can address these individually.

So for an initial implementation I propose we do the following:
- [ ] in API v2, in our REST API, add a sub-entity to each action called 'invoke'.  To invoke an action via POST, one would POST to https://username:pw@openwhisk/api/v2/ns/package/action/invoke
- [ ] support a simple transformation to turn query parameters into a JSON object which holds action parameters.  
- [ ] support GET on action/invoke as a blocking invocation 

follow on work could implement a mapping to hide credentials and make shorter URIs by a 1-way hash function, similar in spirit to bit.ly  .    Will leave that feature for a separate issue.

**Comment by csantanapr** [comment]
Do we reserve some query parameters or do we hard code blocking=true and result=true? 
If we hardcode blocking=true and result=true then all query parameters for the GET are user defined, and they could potentially have parameters in their action named "blocking" ad "result"

**Comment by rabbah** [comment]
A get based activation should by definition be blocking and only the result returned - otherwise I don't see the point of adding this feature.

**Comment by sjfink** [comment]
@csantanapr pointed out that for a web browser GET, it would be nice to project a particular field from the result object and interpret it as HTML.

Here's a proposal:

1)  a GET on https://user:pw@ip/api/v2/ns/package/action/invoke returns the JSON object as text.
2) a GET on https://.../invoke/foo projects the foo field of the JSON object, and returns it as text.
3) a GET on https://../invoke/html projects the 'html' field of the JSON object, and returns it as HTML.

Case 3) involves magic -- we build in a convention that if a field is named 'html', then when we project it during a blocking call via GET, we return it as type HTML.    

We can add other conventions for other standard types, like images.

With this proposal, a GET on the html field of the following method will just work.

main() { return { "html" : "<html>Hello</html>" }

* [ ] Implement this proposal (if accepted)

**Comment by mdeuser** [comment]
@sjfink - I'm wondering if this work item is lower priority than - or perhaps even obviated by - the other API GW work going on.  The current target milestone date is just over 2 weeks away and no owner yet.

**Comment by sjfink** [comment]
I'd say the other work is lower priority but I'd still aim to get this done by end October.

**Comment by rabbah** [comment]
Addressed by #1715.
