### ISSUE TITLE
A broken link in tools/db/README.md

### ISSUE THREAD

**Issue by daisy-ycguo** [openwhisk/openwhisk#1223]
In the line 12, it is said "the CouchDB instance must set `reduce_limit` on views to `false` (see [this](couchdb/createAdmin.sh#L55) for how to do this via REST)"

Here, `this` is linked to couchdb/createAdmin.sh#L55 which is missing now.
According to the discussion #693 , is the item still needed here ?

**Comment by rabbah** [comment]
The change proposed in 693 is not yet implemented, so the link should be fixed for now.

**Comment by rabbah** [comment]
This just hit someone else - we need to fix the broken link. The file was deleted in the post Ant cleanup (https://github.com/openwhisk/openwhisk/commit/18f449fe9b1707b5a076b9b4d66019cb412a5f52#diff-2d5aab3d1af9a64dceb048a47df158bb).
The command to run is:
${CURL} -X PUT ${COUCHDB_PROT}://${COUCHDB_HOST}:${COUCHDB_PORT}/_config/query_server_config/reduce_limit -d '"false"' -u ${COUCHDB_USER}:${COUCHDB_PASS}
