### ISSUE TITLE
Broken ./hello script for quick starters

### ISSUE THREAD

**Issue by pedrosnk** [openwhisk/openwhisk#1227]
I'm trying to install open whisk on my machine for validation proposes

But it seems that during the process there's a command that is failing frequently when running the `./hello` from `tools/vagrant` or on my machine locally when I run `./grandlew distDocker`. My machine is a Mac OSX.

When This command is executed

`docker build -t swift3action /Users/pedro.medeiros/desenv/openwhisk/core/swift3Action`

it outputs an error, even on vangrant vm or on a docker locally

```
gpg: directory `/root/.gnupg' created
gpg: new configuration file `/root/.gnupg/gpg.conf' created
gpg: WARNING: options in `/root/.gnupg/gpg.conf' are not yet active during this run
gpg: keyring `/root/.gnupg/secring.gpg' created
gpg: keyring `/root/.gnupg/pubring.gpg' created
gpg: /root/.gnupg/trustdb.gpg: trustdb created
2016-09-08 18:36:50 URL:https://swift.org/keys/all-keys.asc [5063/5063] -> "-" [1]
gpg: key 412B37AD: public key "Swift Automatic Signing Key #1 <swift-infrastructure@swift.org>" imported
gpg: key 21A56D5F: public key "Swift 2.2 Release Signing Key <swift-infrastructure@swift.org>" imported
gpg: key 91D306C6: public key "Swift 3.x Release Signing Key <swift-infrastructure@swift.org>" imported
gpg: Total number processed: 3
gpg:               imported: 3  (RSA: 3)
gpg: refreshing 3 keys from hkp://pool.sks-keyservers.net
gpg: requesting key 412B37AD from hkp server pool.sks-keyservers.net
gpg: requesting key 21A56D5F from hkp server pool.sks-keyservers.net
gpg: requesting key 91D306C6 from hkp server pool.sks-keyservers.net
gpg: keyserver timed out
gpg: keyserver refresh failed: keyserver error
The command '/bin/sh -c wget --no-verbose -O - https://swift.org/keys/all-keys.asc | gpg --import - &&     gpg --keyserver hkp://pool.sks-keyservers.net --refresh-keys Swift' returned a non-zero code: 2
```

I'm new on open whisk so I'm doing those commands to validate the platform for a project where I work.

**Comment by sjfink** [comment]
@paulcastro this looks like swift.org was not responding perhaps.   Are you aware of any changes with the swift.org download site?

**Comment by paulcastro** [comment]
Looks like the key server did not respond.  @pedrosnk I tried to build the swift3action container just now and it appears to be working again.  Can you try again?

**Comment by pedrosnk** [comment]
First thanks for all the fast responses. [=

It is inconsistent. Sometimes works sometimes it doesn't. Worked now just fine. Which is bad for me cause I'm trying to adopt the platform with my team. It's kind a pain to tell people to install multiple times until it is installed properly. It's possible to just don't have the swift3Action at the quickstart guide?

**Comment by sjfink** [comment]
+1   We should gracefully fail if the swift servers are unresponsive.   That is ... print a warning about swift failing and finish the build anyway.

**Comment by cclauss** [comment]
Is this issue closed?

**Comment by pedrosnk** [comment]
It's ok to close it, I'm not running openwhisk  anymore.

Thanks,
