### ISSUE TITLE
Links to the documentations in the start page are broken 

### ISSUE THREAD

**Issue by kerryspchang** [openwhisk/openwhisk#1245]
## Environment details:

* local deployment, vagrant, native ubuntu, Mac OS, Bluemix, ...   
* version of docker, vagrant, ubuntu, ...

## Steps to reproduce the issue:

1.   
2.   
3.   

## Provide the expected results and outputs:

```
output comes here
```

## Provide the actual results and outputs:

```
output comes here
```

## Additional information you deem important:
* issue happens only occasionally or under certain circumstances   
* changes you did or observed in the environment

**Comment by csantanapr** [comment]
@kerryspchang Could you provide more details , what start page you are refering
and which urls are not working for you?

**Comment by kerryspchang** [comment]
https://github.com/openwhisk/openwhisk
Scroll down 
All the links under "Native development" and all the bullet points under "Learn concepts and commands" return a 404 not found.

**Comment by csantanapr** [comment]
Thank @kerryspchang for pointing it out, I don't know why is not working now. We use markdown links with relative paths. Maybe github change something recently.

But they work if you visit the README.md
https://github.com/openwhisk/openwhisk/blob/master/README.md

**Comment by csantanapr** [comment]
Looks like this got fixed later today by github backend
