### ISSUE TITLE
Deprecate the packages and actions with name convention changes in openwhisk-catalog repo

### ISSUE THREAD

**Issue by houshengbo** [openwhisk/openwhisk#1252]
The transition from the catalog under openwhisk to openwhisk-catalog repo has brought into name changes on some packages and actions. We need to create a script to deprecate them in the existing deployed openwhisk.

**Packages with names changed:**
whisk.system/util has been changed into whisk.system/utils.
All the actions under utils now used to stay with the package util, except utils/echo: cat, date, head, sort and split.

**Actions with names changed:**
samples/echo has been changed and moved into utils/echo.

**Comment by rabbah** [comment]
@houshengbo done?
