### ISSUE TITLE
core/actionProxy/Dockerfile should build from 3.5.2-alpine

### ISSUE THREAD

**Issue by iainhouston** [openwhisk/openwhisk#1259]
What is the rationale supporting using python 2.7 here?
Surely all new projects should be python 3 now?

**Comment by rabbah** [comment]
Historically the wsk CLI was in python and we didn't upgrade it to 3+ because we were transitioning to an implementation in Go. (So our base images were using 2.7.) Now that transition is mostly complete so there is no longer a dependence on 2.7.

**Comment by rabbah** [comment]
This is related to #1184.

**Comment by iainhouston** [comment]
Thanks @rabbah. Will the black box action proxy (not sure what I'm talking about here) remain in Python or  end up in go? 

As it stands it's quite convenient for a python Docker action to just to piggy back on the python image by 'pip install'-ing packages in the base Dockerfile

**Comment by rabbah** [comment]
The action proxy will remain in python (because we can leverage this in a number of action runtimes as you observe). There is no reason or rational to move it to go.

**Comment by iainhouston** [comment]
Excellent news

**Comment by cclauss** [comment]
Is this issue closed with https://github.com/openwhisk/openwhisk/commit/3a738e63b5bf4e0b042b3f8e5e5c5c063959d4c5 ?  Python 3.6.1
