### ISSUE TITLE
improvements to in-memory-cache

### ISSUE THREAD

**Issue by rabbah** [openwhisk/openwhisk#1260]
The in-memory cache used in the controller has some deficiencies that we should address:

1. it does not expire entries in the cache pro-actively, hence an inconsistency with the database will cause stale records to be observed until the controller is restarted
2. it is prone to a race between a read and write (delete or update) because the state transition modeling is not complete
3. it does not coalesce requests (no hit under miss)

@starpit FYI.

**Comment by sjfink** [comment]
4.   It does not currently support horizontal scaling of controller --- let's keep this in mind since this will come relatively soon.

**Comment by rabbah** [comment]
sketch of state diagram:
![img_6576](https://cloud.githubusercontent.com/assets/4959922/18519094/99795f42-7a70-11e6-8a8d-9a41a04c4f55.JPG)

**Comment by starpit** [comment]
edge labels:

- R_i, U_i, D_i: read, update, or delete initiated
- *_f with underbar: operation completes with failure
- *_f with overbar: operation completes with success
- exp: timed expiration

transient states:
I: invalidate cache entry, and return to S_0
FF: request fails fast, no change to state of cache entry

**Comment by starpit** [comment]
we have amended the state diagram shown in the picture so that, rather than failing fast on read-under-write, we read-around the cache. this allows us to preserve sequential consistency, meanwhile avoiding pollution of the cache with zombie entries

**Comment by psuter** [comment]
#1302 was merged and addresses the main issues described here. Horizontal scalability can be discussed e.g. in #788
