### ISSUE TITLE
openwhisk/tools/go-cli is failing the docker build due to the timeout in gradle

### ISSUE THREAD

**Issue by ddragosd** [openwhisk/openwhisk#1262]
## Environment details:
- local deployment, Mac OS  
- Docker 1.12.0
## Steps to reproduce the issue:
1.   `./gradlew distDocker`
## Provide the expected results and outputs:

```
BUILD SUCCESSFUL
```
## Provide the actual results and outputs:

```
Exception in thread "Thread-121" groovy.lang.GroovyRuntimeException: exception while reading process stream
    at org.codehaus.groovy.runtime.ProcessGroovyMethods$TextDumper.run(ProcessGroovyMethods.java:495)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.IOException: Stream closed
...
Command 'docker build -t go-cli /Projects/openwhisk/openwhisk/tools/go-cli' was killed after 840 seconds, no more retries left, aborting...
```
## Additional information you deem important:
- this happenes on a fresh new build
- my workaround was to 

```
cd ./tools/go-cli/
# comment the linux and windows parts
docker build . -t whisk/go-cli
# be patient and check back in the morning
```

I've been trying to understand why is it needed to build the cli for all the platforms during the initial build while trying to get something running locally. Is there an easier way to build things locally that I might have missed in the docs ?

**Comment by rabbah** [comment]
@ddragosd you're absolutely right about this point: we don't need to build all platforms for local dev.

**Comment by markusthoemmes** [comment]
Hi @ddragosd thanks for giving feedback.

Could you provide more of the logs of the failed build please, so we can determine which step took it so long (possibly hanging even)?

**Comment by ddragosd** [comment]
Sure, in my case it got stuck here:
https://github.com/openwhisk/openwhisk/blob/master/tools/go-cli/Dockerfile#L43-L47

**Comment by markusthoemmes** [comment]
I see, still pretty early in the process.

See #1265 for an attempt to soften the issue.

**Comment by ddragosd** [comment]
it looks like #1265 is a fix for this so we can move the conversation in there and close this issue if you want.
