### ISSUE TITLE
publish go-cli base docker image to dockerhub

### ISSUE THREAD

**Issue by rabbah** [openwhisk/openwhisk#1264]
The docker build for the go-cli can take anywhere from 5+ minutes to upwards of 14 minutes as observed in another issue. Much of this time is spent downloading go dependencies required to build the CLI. We should publish a base image to dockerhub to cut down on this build time. Since the dependencies change infrequently, when they do change, we'll have to update the image on dockerhub.

@dubeejw @csantanapr thoughts?

**Comment by dubeejw** [comment]
How much faster do you think it would be to download the Docker container containing all the dependancies instead of downloading the dependancies through github?

**Comment by rabbah** [comment]
Surely less than 5 minutes. After go and swift images, most container build times are under one minute.

**Comment by dubeejw** [comment]
I investigate. Does this mean we don't want to only build for the local environment?

**Comment by rabbah** [comment]
I think they're complementary improvements.

**Comment by csantanapr** [comment]
We have to see what are the times savings of doing this.

I think regardless the less time we spent building the none-whisk bits and instead pulling down the image it's better.

But to save manual maintenance  maybe we should have single repos for the go-cli image, and for swift3 image. Then configure docker hub to build an image automatically when a new commit get's merge into the image repo.

Another idea I discuss briefly with @dubeejw was to only build one go binary during travis. (linux/amd64). 
Also maybe parametrized this thru ansible environments the binaries to be built, we just need to cover how to handle the tests for nginx downloads

**Comment by rabbah** [comment]
related to #1649.

**Comment by rabbah** [comment]
closing as duplicate of #171.
