### ISSUE TITLE
error invoking action 

### ISSUE THREAD

**Issue by rahulguha** [openwhisk/openwhisk#127]
I installed openwhisk per https://github.com/openwhisk/openwhisk#alternate-instructions-for-mac-developers
I followed everystep but at the end I get Errno 2 - Service Not known
when I try
wsk package list or wsk action list
as I tried -v I see the apihost was blank

What would be right apihost after initial build ?

**Comment by rabbah** [comment]
Did you try these steps: https://github.com/openwhisk/openwhisk#using-cli-from-outside-vagrant-machine

**Comment by rahulguha** [comment]
My problem is NOT running from host machine.
I have installed everything and now trying to invoke the action echo from the vagrant (virtual machine) itself.

**Comment by rabbah** [comment]
Thanks for clarifying. 

It is unlikely that you ran `ant clean build deploy` successfully in that case since the end result of the deploy is to use the `wsk` CLI to install some standard assets.

Can you report the contents of `openwhisk/tools/cli/default.props` and what does this report `wsk property get --apihost`.

**Comment by rahulguha** [comment]
default.props was created by me (based on another post) as it didn't exist on default install. 

CLI_API_HOST=
WHISK_VERSION_DATE=

**Comment by rabbah** [comment]
can you attach the result of your build? The previous update suggests you did not have a successful build.

**Comment by rahulguha** [comment]
Hmm ... okay I shall build it again and send the outcome.


Thanks ...

*Rahul Guha*
Phone: *+*91 9686577645 | skype: rahul_guha
US Number: 408-418-4952
Google Voice: 813-473-7490 - leave message here

**Comment by rabbah** [comment]
If you prefer, you can send it to me privately (rodric@gmail.com).

**Comment by rabbah** [comment]
Did yo manage to invoke the action?

**Comment by sjfink** [comment]
> I followed everystep but at the end I get Errno 2 - Service Not known
another candidate for hypothetical Troubleshooting.md

**Comment by psuter** [comment]
Tooling and documentation for developers has been enhanced since: https://github.com/openwhisk/openwhisk/tree/master/tools/build 

Since we cannot reproduce the problem as described above I suggest to close?
