### ISSUE TITLE
Resolve all sequence components into fully qualified names and impose a limit on sequence length 

### ISSUE THREAD

**Issue by ioana-blue** [openwhisk/openwhisk#1274]
I'll try to do these two in one go:
1. The components are specified with fully qualified name, but `_` is used for default namespace. This needs to change to whatever the system uses internally (last time I looked, it was user name). This needs to be done on both create and update. 
2. There needs to be a limit on the number of "dynamic" actions the sequence contains. A sequence can point to sequences. For this item, I plan to "inline" all actions and count them. Once this count reaches a certain threshold, the create/update fails. Also, during this check, I'll check for recursion as well.

**Comment by ioana-blue** [comment]
The limit for the number of actions for a sequence will be a limit specified part of the configuration per deployment (as such, it's present in `WhiskConfig` and ansible all var configuration file).

**Comment by rabbah** [comment]
@ioana-blue this is completed, right?
