### ISSUE TITLE
wsk list /whisk.system does not fail as expected for guest user

### ISSUE THREAD

**Issue by rabbah** [openwhisk/openwhisk#1279]
Expect this to fail with:
> wsk list /whisk.system # using guest key 
error: The supplied authentication is not authorized to access this resource (code 584)

or with a usage error (that list doesn't accept a parameter).

But the CLI accepts the parameter and does this:
```
> wsk -iv list /whisk.system
REQUEST:
[GET]	https://192.168.99.100/api/v1/namespaces/_/
Entities in namespace: whisk.system
...
```

**Comment by dubeejw** [comment]
Using the latest CLI, I get this:
```
$ wsk namespace list /whisk.system
error: Invalid argument(s): /whisk.system. No arguments are required.
Run 'wsk --help' for usage.
```

**Comment by dubeejw** [comment]
I'll take a look.
