### ISSUE TITLE
whisk.invoke() doc needs clarification - blocking

### ISSUE THREAD

**Issue by bjustin-ibm** [openwhisk/openwhisk#1283]
User @glikson pointed out that the documentation and example in `reference.md` doesn't clearly explain the `blocking` parameter. I believe he took the current explanation to mean that the `invoke()` function itself would be synchronous if `blocking: true` which is definitely not the case.

This confusion has come up several times, and the documentation could do better to make it clear what `blocking` really means.

Also, the example code snippet doesn't return the Promise returned from `whisk.invoke()`

**Comment by rabbah** [comment]
deprecated for npm openwhisk.
