### ISSUE TITLE
whisk.invoke requires fully qualified action path even when invoking action in the same namespace

### ISSUE THREAD

**Issue by glikson** [openwhisk/openwhisk#1288]
When invoking an action programmatically from another (JS) action using `whisk.invoke()` function, it is required to specify the full path (namespace, package/binding, action), with the exception of 'default' namespace (corresponding to 'default' Bluemix space - which may not exist).
It might make sense to allow omitting the namespace/package when invoking actions in the same namespace and/or package.
It could be also useful to surface the namespace/package of the running action as part of the `whisk` context object.

**Comment by rabbah** [comment]
Duplicate of https://github.com/openwhisk/openwhisk/issues/387?

**Comment by sjfink** [comment]
Yes, I guess it's a duplicate.   Closing ... will track in #387
