### ISSUE TITLE
Windows CLI does not accept single quote as string delimiter

### ISSUE THREAD

**Issue by sjfink** [openwhisk/openwhisk#1291]
I'm creating Actions on OpenWhisk via Windows CLI. When a string is passed with single quotes, the quotes are ignored and as delimiter and treated as part of the string. If a string has a blank, then it sees as two different values and so an error occurs.

When I use double quotes, it works fine.

Linux CLI is working fine.

C:\Users\IBM_ADMIN\Desktop\OpenStack Files\Uses Case>wsk action invoke --blocking --result hello --param name 'Bernie' --param place 'Vermont'
{
"payload": "Hello, 'Bernie' from 'Vermont'"
}

C:\Users\IBM_ADMIN\Desktop\OpenStack Files\Uses Case>wsk action invoke --blocking --result hello --param name 'Bernie Sanders' --param place 'Vermont'
error: Invalid argument(s): Sanders'.
Run 'wsk --help' for usage.

C:\Users\IBM_ADMIN\Desktop\OpenStack Files\Uses Case>wsk action invoke --blocking --result hello --param name 'Bernie_Sanders' --param place 'Vermont'
{
"payload": "Hello, 'Bernie_Sanders' from 'Vermont'"
}

C:\Users\IBM_ADMIN\Desktop\OpenStack Files\Uses Case>wsk action invoke --blocking --result hello --param name "Bernie Sanders" --param place 'Vermont'
{
"payload": "Hello, Bernie Sanders from 'Vermont'"
}

**Comment by csantanapr** [comment]
@dubeejw do you have any insight on dealing with single quotes using the CLI on windows

**Comment by csantanapr** [comment]
I think we should doc the samples using double quotes until we find a solution.

**Comment by nauerz-ibm** [comment]
Since this affects the lab I plan to run in London, quick question:
May I assume that this will be solved before October, 26th?
I.e. may I assume single quotes will work again by then or do I really need to change the lab instructions?

**Comment by mdeuser** [comment]
This behavior is due to the Windows cmd command processor.  Single quotes are not treated like double quotes, but are instead treated pretty much like any other character.  So, on Windows systems, arguments requiring quoting should use double quotes.
http://stackoverflow.com/questions/24173825/what-does-single-quote-do-in-windows-batch-files

You can also validate this with a simple echoargs.bat file
```
@echo %0
@echo %1
@echo %2
@echo %3
```
```
>echoargs.bat '1 2 3'
echoargs
`1
2
3`
```
```
>echoargs "1 2 3"
echoargs
"1 2 3"
ECHO is on.
ECHO is on.
```
