### ISSUE TITLE
Enable Travis CI integration

### ISSUE THREAD

**Issue by vinodmut** [openwhisk/openwhisk#13]
@sjfink Can we enable Travis CI integration with this repo? Among other things, this will annotate pull requests with the build status of the corresponding commits.

**Comment by vinodmut** [comment]
Travis CI is configured to schedule a build for every commit and pull request. We may want to limit it to just the latter.

Currently it only builds the project. Running the tests requires we embed Cloudant credentials in the repo, so I'm considering that dependent on issue #1.

**Comment by mbehrendt** [comment]
@vinodmut shouldn't we leave this one open until #1 is closed?

**Comment by vinodmut** [comment]
Sure, we can re-open it. I don't see a way to specify dependencies among issues.

@lehoanganh Does waffle.io support dependency tracking?

**Comment by sjfink** [comment]
As the Travis CI is now doing the full build with CouchDB, I think we can close this one.
