### ISSUE TITLE
Sequences: cleanup old code

### ISSUE THREAD

**Issue by ioana-blue** [openwhisk/openwhisk#1310]
I'm currently redoing the implementation for sequences but with the old code in place. I'm leaving the previous code untouched because I'd like to run some comparisons between old and new code. 

As such, there is going to be a cleanup phase at some point. I'll keep track of items here.

**Comment by ioana-blue** [comment]
Store only one version of the components, namely the "resolved" ones.

**Comment by ioana-blue** [comment]
Current parameters for sequences are overwritten by the names of the components. Fix this!

**Comment by ioana-blue** [comment]
It turns out the two tests for sequences and parameters in ActionsApiTests are broken. The initial sequence action is never installed in the db. I'm ignoring these tests for now and fixing once I have the implementation for sequence all in.

**Comment by rabbah** [comment]
@ioana-blue status?

**Comment by ioana-blue** [comment]
I believe the cleanup happened a while ago. Closing as this issue is not actionable as is anymore.
