### ISSUE TITLE
Run activation DB write and container release in parallel

### ISSUE THREAD

**Issue by perryibm** [openwhisk/openwhisk#1340]
Currently, after the active ack, we perform a container release prior to a DB write.  We should perform these in parallel and this could be accomplished by swapping the order if the DB operation is already wrapped in a future.  If not, then we will need to wrap at least one of these ops in a future.

**Comment by markusthoemmes** [comment]
This is done I believe? @perryibm

**Comment by rabbah** [comment]
it is.
