### ISSUE TITLE
"failed to fetch action whisk.system/samples/greeting: Object Not Found"

### ISSUE THREAD

**Issue by DamianCummins** [openwhisk/openwhisk#136]
Seeing the following after completing the OpenWhisk configure cli instructions on Bluemix:

root@96eb30f5db81:/opt# wsk action get --summary /whisk.system/samples/greeting
action /whisk.system/samples/greeting: Print a friendly greeting
   (params: name place)

root@96eb30f5db81:/opt# wsk action invoke --blocking --result /whisk.system/samples/greeting
error: {
    "activationId": "358991740954436e9fc385e351990130",
    "annotations": [],
    "end": 1459261038802,
    "logs": [],
    "name": "samples",
    "namespace": "dcummin3@uk.ibm.com",
    "publish": false,
    "response": {
        "result": {
            "error": "failed to fetch action whisk.system/samples/greeting: Object Not Found"
        },
        "status": "action developer error",
        "success": false
    },
    "start": 1459261038802,
    "subject": "dcummin3@uk.ibm.com",
    "version": "0.0.1"
}

Any idea why I would be able to get the summary but not invoke the action?
This also appears to happen for watson/translate action after I've bound to the service.

Running on: Linux version 4.1.19-boot2docker (gcc version 4.9.2 (Debian 4.9.2-10) )

**Comment by DamianCummins** [comment]
Note, I am able to create and invoke my own actions.

**Comment by rabbah** [comment]
Thanks for reporting this. I will have a look.

**Comment by rabbah** [comment]
I have confirmed this is an issue and will report back when a fix is deployed.

**Comment by DamianCummins** [comment]
@rabbah Great, thanks for the prompt response.

**Comment by rabbah** [comment]
You may try again - should work for you this time.

**Comment by DamianCummins** [comment]
@rabbah yep that worked. Thanks.
