### ISSUE TITLE
Manual compilation build script in Swift 3 container is broken

### ISSUE THREAD

**Issue by paulcastro** [openwhisk/openwhisk#1360]
Possibly a bad merge.  Need to update the script to link to all the dependencies.

**Comment by paulcastro** [comment]
Its safer to return to the Swift Package Manager and remove the manual compilation.  We're vulnerable to secondary dependency changes when we deploy.  We can open a discussion around #1329 about how to avoid this.

**Comment by csantanapr** [comment]
@paulcastro should we close this now?

**Comment by paulcastro** [comment]
Yes, we can close.
