### ISSUE TITLE
Update docs with new throttle limits

### ISSUE THREAD

**Issue by csantanapr** [openwhisk/openwhisk#1365]
Recently we change the values for some throttle limits, we need to reflect the changes in the docs [reference.md#system-limits](https://github.com/openwhisk/openwhisk/blob/master/docs/reference.md#system-limits)

@rabbah would you know which ones need to be updated?

**Comment by rabbah** [comment]
pr #1364?

**Comment by csantanapr** [comment]
@rr thanks, missed that one

**Comment by rabbah** [comment]
#1507 and #1508 should be combined and address this issue.

**Comment by csantanapr** [comment]
replaced by #1532
