### ISSUE TITLE
[REST API] Inconsistent error message format

### ISSUE THREAD

**Issue by archerzz** [openwhisk/openwhisk#1367]
## Environment details:

__Irrelevant__

## Steps to reproduce the issue:

1.  Invoke different REST API and check the error messages returned.

## Provide the expected results and outputs:

```
A unified format of error
```

## Provide the actual results and outputs:

```
Some error responses only contain "error", not "code", like:
{"error":"Malformed request, did you specify a bluemix namespace?"}
```

## Additional information you deem important:
* Just want to clarify which property should be used to check whether there is an error? It seems that we should check "error", not "code", right?

**Comment by markusthoemmes** [comment]
`code` refers to the TransactionId your Transaction had and is mainly useful for the operations team to debug user issues. If you want to check if stuff went wrong, `error` will be sufficient.

**Comment by rabbah** [comment]
Any error that results from the API controller (backend) will always have both `error` and `code`. Errors that result from frontend routers will not contain `code`.

**Comment by archerzz** [comment]
Thanks for the clarification.
