### ISSUE TITLE
nofiles limit might be too low

### ISSUE THREAD

**Issue by domdom82** [openwhisk/openwhisk#1372]
We currently limit number of open files via ulimit to 64 per action on the invoker.

We have seen issues with this on user actions that load additional files.

We should discuss a reasonable limit to still keep security intact but allow more flexibility.

I vote for not making this part of the action entitlement because it is a very low-level setting unlike memory or cpu.

**Comment by sjfink** [comment]
So ... how many open files do we think the host can support?     Let's take that number, divide by the max number of live containers, and divide by some factor (2,4) to give us some slack?

**Comment by perryibm** [comment]
Also keep in mind that network connections (= file handles) are affected by this.

**Comment by domdom82** [comment]
@vodier raised this issue on dwopen with a phantomjs action that ran into 
```
QEventDispatcherUNIXPrivate(): Unable to create thread pipe: Too many open files
```

I asked him to link his code here for us to test and discuss.

@perryibm good point this is a delicate issue and we need to be diligent.

**Comment by ValentinOdier** [comment]
Hi there,

code : https://github.com/ValentinOdier/OpenWhisk-JsTesting

It's testing code ...

You can find parameters in scrapConfig.js and use them to test.

Fell free to ask anything.

**Comment by starpit** [comment]
i ran into this limit when using Xvfb -> gradle -> java+firefox

**Comment by starpit** [comment]
test case: starpit/granola on dockerhub

**Comment by perryibm** [comment]
@domdom82  Can we verify that system limits are reasonably high (64K at least)?  Then we can raise the limits to 512.

@starpit Can you write a self-contained unit test (node action that opens N files)?

**Comment by starpit** [comment]
invoke this action with `-p N 30` -> success
with `-p N 512` -> failure, specifically
```
 "result": {
            "error": {
                "code": "EMFILE",
                "errno": -24,
                "path": "DATA",
                "syscall": "open"
            }
        }
```

here is the code
```
var fs = require('fs')

function main(params) {
    return new Promise((resolve, reject) => {
	fs.writeFile('DATA', 'LOTS OF FILES!!!!', function(err) {
	    if (err) {
		reject(err);
	    }
	    
	    var latch = params.N;
	
	    function read() {
		fs.readFile('DATA', 'utf8', function(err, contents) {
		    if (err) {
			reject(err);
			
		    } else if (--latch == 0) {
			resolve({N: params.N});
		    }
		});
	    }
	    
	    for (let i = 0; i < params.N; i++) {
		read()
	    }
	});
    });
}
```

**Comment by domdom82** [comment]
assigning to @RSulzmann for investigation. can you do a full test with 512 open files on a fully-loaded invoker? thanks!

**Comment by RSulzmann** [comment]
Test environment local Whisk installation. latest driver Feb 10.
Changed line #72 in ContainerUtils.scala to :
**val fileHandleLimit = Array("--ulimit", "nofile=512:512")**

1. testet with above action code the limit boundary (before and after the code change)
2. running a load test with 8 action types to verify system behaves as before.
3. run the above action code (opening 512 file handles) during load test

All tests successful.

**Comment by RSulzmann** [comment]
agreed to lift the fileHandleLimit to 1024
repeated tests
All tests successful.

**Comment by starpit** [comment]
hi @RSulzmann 

thanks for the help with this issue! it will be very helpful. what is the status of the PR?

**Comment by rabbah** [comment]
Fixed by https://github.com/openwhisk/openwhisk/commit/aef57658891c6eba7db3c827e85803cf2be6e4af.
