### ISSUE TITLE
iOS starter carthage update fails

### ISSUE THREAD

**Issue by gconan** [openwhisk/openwhisk#1386]
## Environment details:
- carthage 0.16.2
- swift 2.2
- xcodebuild 7.3.1
## Steps to reproduce the issue:
1.   Download starter iOS app
2.   unzip
3.   run `carthage update`
## Provide the expected results and outputs:

```
carthage success
```
## Provide the actual results and outputs:

```
A shell task (/usr/bin/xcrun xcodebuild -project /Downloads/OpenWhiskIOSStarterApp/Carthage/Checkouts/openwhisk-client-swift/OpenWhisk.xcodeproj -scheme OpenWhisk watchOS -configuration Release -sdk watchos ONLY_ACTIVE_ARCH=NO BITCODE_GENERATION_MODE=bitcode CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES clean build) failed with exit code 65:
** BUILD FAILED **


The following build commands failed:
    CompileSwift normal armv7k
    CompileSwiftSources normal armv7k com.apple.xcode.tools.swift.compiler
(2 failures)
```
## Additional information you deem important:
- May want to provide a readMe or instructions on which versions of carthage, cocoaPods, swift, xcode... the user needs.

**Comment by paulcastro** [comment]
@gconan could you try adding a different tag to your Cartfile.  I see you are building for Swift 2.2.  Versions of the mobile SDK 0.2.0 and above are Swift 3.

github "openwhisk/openwhisk-client-swift.git" === 0.1.7

**Comment by paulcastro** [comment]
Will re-open if issue comes up again.
