### ISSUE TITLE
Feature request: Cloudant package, changes feed: add filtering parameters

### ISSUE THREAD

**Issue by bseyb** [openwhisk/openwhisk#1411]
## Why

I was trying to listen to changes of a cloudant feed and then send an email using sendgrid, when one flag 'process' was set to true.
For this I needed to implement one openwhisk action to filter out whether 'process' was set to true and 'mailsend' set to false.
## Suggestion

Looking at the documentation of cloudant I saw that you can add add **filter** and **doc_ids** to a changefeed. It would be very awesome to add these parameters, so that filtering can already be taken care of at the change feed instead of the user created action.
## Bonus

I also saw that you can pass **oldDoc** as a parameter. This could be helpful if you want to compare what exactly changed in an action.

**Comment by csantanapr** [comment]
Hi @bseyb I started looking into the design on providing a way to filter changes for the cloudant trigger.

Looking at the spec of the [changes API](http://docs.couchdb.org/en/latest/api/database/changes.html)

It looks like a filter and docs_id is doable, a filter will be a filter function on a design document.

What I didn't find was `oldDoc` during my testing the changes feed only provide the id and `deleted=true` and the new revision marked as deleted.

I was not able to find a reference to `oldDoc` in the changes API params.
Could share a bit more where you saw this reference?

**Comment by bseyb** [comment]
Hi @csantanapr I must have misread it, I cannot find oldDoc in the correct context either.

Having that Filter function available would help a whole lot.

**Comment by rabbah** [comment]
@csantanapr move this to openwhisk-catalog-cloudant? FYI @johnsolm @dubeejw.

**Comment by markusthoemmes** [comment]
Issue moved to [openwhisk/openwhisk-package-cloudant #68](https://github.com/openwhisk/openwhisk-package-cloudant/issues/68) via [**ZenHub**](https://www.zenhub.com/)
