### ISSUE TITLE
Update Node 6 to latest to match new LTS Release Line

### ISSUE THREAD

**Issue by csantanapr** [openwhisk/openwhisk#1418]
The jump will be from v6.7.0 to v6.9.1
More info here:
https://nodejs.org/en/blog/release/v6.9.0/
https://nodejs.org/en/blog/release/v6.9.1/

**Comment by csantanapr** [comment]
Also would be good to check if there the 0.12 need to be refresh, which is not critical since it's now deprecated. it would depend on what type of changes is contains (i.e. security, etc..)

**Comment by cclauss** [comment]
Is this issue closed?

**Comment by csantanapr** [comment]
@cclauss yes we are using 6.9.1 now
https://github.com/openwhisk/openwhisk/commit/36f272862cc07e6cb57ec7e028fbf2b4dd069350

I will open a new one to update to 6.10.1
