### ISSUE TITLE
cant import self-sign certificate because it's expired

### ISSUE THREAD

**Issue by csantanapr** [openwhisk/openwhisk#1419]
Trying to use PostMan to invoke an action locally but having problems with SSL.
PostMan points that certificate can be imported into keychain for chrome to pick it up
http://blog.getpostman.com/2014/01/28/using-self-signed-certificates-with-postman/

I was able to get the certificate to import, but it will not import because of the date expiration is back to March 16 2016
![image](https://cloud.githubusercontent.com/assets/1094878/19568408/6bfbd08e-96bf-11e6-82b8-f51d2a23a43b.png)

I think the fix is to generate new certificates with newer date
I think we can re-use the [openwhisk-key.pem](https://github.com/openwhisk/openwhisk/blob/master/ansible/roles/nginx/files/openwhisk-key.pem)
To generate a new [openwhisk-cert.pem](https://github.com/openwhisk/openwhisk/blob/master/ansible/roles/nginx/files/openwhisk-cert.pem)

@cbickel I think your work on something like this recently, can you help generate new certificate?

**Comment by rabbah** [comment]
I generated these certificates and can redo it if necessary. It will still not be trusted, does it matter for what you're doing?

**Comment by csantanapr** [comment]
@rabbah yes please re-create them. They don't have to be trusted/valid dns name wise, just the expiration date should be way in the future.

**Comment by rabbah** [comment]
Fixed by #1453.
