### ISSUE TITLE
Create communication channel from invoker back to controller

### ISSUE THREAD

**Issue by perryibm** [openwhisk/openwhisk#142]
Currently the controller polls cloudant for activation records which introduces extra DB operations (unnecessary load) and increased latency.  The invoker should signal completion (along with the activation record if small) via low-latency kafka.  This work depends on the integration of the load balancer into the controller.  This channel will also give needed information for the load balancer to do its job better as it has a more live (timely) and refined (activation-specific) view of what's still running.

**Comment by vinodmut** [comment]
+1 on sending activation completion messages over Kafka. I don't think we can get rid of Cloudant polling entirely though. It needs to be a fallback in case the controller dies before processing the message.

Also, I imagine you'd want the completion message to be directed to a particular controller rather than broadcast to all controllers.

**Comment by perryibm** [comment]
Yes, definitely to the specific originating controller using an instance topic as in the way it get to the invoker.  I think of it as a completion mechanism which happens to carry the message.  As such, I agree it will have to deal with a lack of ack if the invoker dies.

**Comment by perryibm** [comment]
A completion message is now sent back from the invoker to the controller and in a few test cases I have seen this happens faster than a cloudant poll as expected.  The next step is to enhance the response with the activation result and for the controller to use this when available to complete a blocking call.

**Comment by perryibm** [comment]
The code implementing this has been reviewed, merged, and tested.
