### ISSUE TITLE
CLI does not interpret some characters correctly

### ISSUE THREAD

**Issue by rabbah** [openwhisk/openwhisk#1420]
```
> wsk action create '.' a --docker -v
...
https://192.168.99.100/api/v1/namespaces/_/actions/?overwrite=false
...
error: Unable to create action: HTTP method not allowed, supported methods: GET, OPTIONS (code ...)
```

note the url has a missing `.`.

worse if you use `/`:

```
> wsk action create '/' a --docker -v
https://192.168.99.100/api/v1/namespaces
error: Unable to create action: HTTP method not allowed, supported methods: GET, OPTIONS (code ...)
```

In both cases the expected error should be, respectively: 
`error: Unable to create action: name '.' contains illegal characters (code ...)` 
`error: Unable to create action: name '/' contains illegal characters (code ...)`

I did not try other characters like `?` and '&` which should be checked.

**Comment by rabbah** [comment]
This seems to also affect `whisk.invoke|trigger` in the node js runtime.

**Comment by dubeejw** [comment]
@rabbah, even when the URL is correct, the backend is not returning the error that you mentioned. For example, when creating an action with just `/` as the name, the following URL should be generated. Note that the URL is missing an action name after `/actions/`.

```
https://{deployment_address}/api/v1/namespaces/{namespace}/actions/?overwrite=false
```

Here is the error returned from the server:
```
error: Unable to create action: HTTP method not allowed, supported methods: GET, OPTIONS (code 310776)
```

As you can see the illegal character error was not return. Perhaps some changes to the backend need to be made to generate the desired error. Obviously we can detect this situation with the CLI, and generate the proper error message. However, this does not help in the case where user is not using the CLI to create actions, etc.

**Comment by rabbah** [comment]
I don't follow - the URL that is sent to the controller is wrong (ignores the dot for example). The error that's returned for `https://{deployment_address}/api/v1/namespaces/{namespace}/actions/` is expected. You can only GET on that URI (it lists the actions in a package).

**Comment by dubeejw** [comment]
For the dot example, Go's built-in URL encoding is removing the dot. This happens if you put the correct URL into your browser as well. I can probably find a workaround for that.

I suppose the CLI will need to throw an error if the action name is just a forward slash before it even makes the HTTPS request.

**Comment by rabbah** [comment]
the names of entities aren't uri encoded?

**Comment by dubeejw** [comment]
Entity names are being URI encoded. It appears that the `/.?` sequence is equivalent to `/?` when requests are made via HTTP(S). This seems to be true even when I try it out in a browser.

I can throw errors when the two mentioned cases occur (dot and slash), but the error will not contain a sequence number. Ie, you would just get `error: Unable to create action: name '.' contains illegal characters` without the `(code ...)` part.

**Comment by dubeejw** [comment]
@rabbah, why is it that I can create action names with "illegal characters" when said character is not at the front of the entity name? For instance, I can create an action with a name of `action@name`. However, I cannot create an action with a name of `@name`.

**Comment by rabbah** [comment]
This is the regex for allowed names https://github.com/openwhisk/openwhisk/blob/master/common/scala/src/main/scala/whisk/core/entity/EntityPath.scala#L157.
