### ISSUE TITLE
OpenWhisk API - Cookie Domain Wrong?

### ISSUE THREAD

**Issue by jthomas** [openwhisk/openwhisk#1422]
## Environment details:

OpenWhisk on IBM Bluemix (US-South). 

## Steps to reproduce the issue:

Using the Apache HTTP Client to talk to the platform API, I noticed this line in the logs....

```
[WARN ][org.apache.http.client.protocol.ResponseProcessCookies] Cookie rejected [DPJSESSIONID="PBC5YS:1376290542", version:0, domain:whisk.ng.bluemix.net, path:/, expiry:null] Illegal 'domain' attribute "whisk.ng.bluemix.net". Domain of origin: "openwhisk.ng.bluemix.net"
```

Looking at the HTTP response headers to a sample request, the cookie returned has a domain that does not match the request domain. 

```
$ http get "https://openwhisk.ng.bluemix.net/api/v1/namespaces/james.thomas@uk.ibm.com_dev/actions?limit=30&skip=0" --auth="xxx:yyy"
HTTP/1.1 200 OK
Access-Control-Allow-Headers: Authorization, Content-Type
Access-Control-Allow-Origin: *
Connection: Keep-Alive
Content-Type: application/json; charset=UTF-8
Date: Fri, 21 Oct 2016 09:10:09 GMT
Server: nginx/1.11.1
Set-Cookie: DPJSESSIONID=PBC5YS:1376290542; Path=/; Domain=.whisk.ng.bluemix.net
Transfer-Encoding: chunked
X-Backside-Transport: OK OK
X-Global-Transaction-ID: 3486006201

...
```

**The `Domain` attribute matches *.whisk.ng.bluemix.** 
**We sent the request to openwhisk.ng.bluemix.net**

Is this a bug?

**Comment by markusthoemmes** [comment]
I'll confirm with out networking team. Seems to be a weird cookie being set by the loadbalancers.

**Comment by retinaburn** [comment]
@jthomas did you find a solution to this?
