### ISSUE TITLE
Clarification: how should I terminate a sequence early?

### ISSUE THREAD

**Issue by ind1go** [openwhisk/openwhisk#1423]
## Description

I have a question which I couldn't find a documented answer to. I hope that you may be able to answer it here or in the documentation.

I'm in the process of creating an OpenWhisk sequence that checks whether a site is up periodically. If it's not, it will send a message to Slack.

This is the sequence structure I've created:

```
Javascript action (request)
           |
           |
       Slack post
```

I only want the Slack post to occur when my Javascript action discovers that the site is down, so wish to 'terminate early' or otherwise avoid making the Slack post when the site is OK.

My current solution is to use a promise `reject()` in the Javascript action when I don't want the Slack post to occur, and to use `resolve()` when I do. However, this results in the sequence being regarded as failed in the Bluemix monitoring. Should I be doing this via an alternative method?

## Environment details:

* Bluemix

**Comment by rabbah** [comment]
See comments starting here: https://github.com/openwhisk/openwhisk/issues/995#issuecomment-241491738. This is a planned featured.

**Comment by ind1go** [comment]
Thank you! Happy to close this.
