### ISSUE TITLE
Kafka backpressure

### ISSUE THREAD

**Issue by perryibm** [openwhisk/openwhisk#143]
Currently the invoker absorbs kafka messages as fast as possible without heed to what it can truly handle.  This is bad because metrics based on kafka queues are misleading and also prevents RAS as the absorbed (yet unprocessed) messages are lost.  The load balancer is also potentially confused about how things are progressing.  Finally, the invoker can start too many activations and start thrashing and/or disrupt fairness/QoS.

The plan is to upgrade to the latest Kafka bindings which afford us to control absorption rate and then throttle this based on availability determined from the ContainerPool.  Heuristically, we probably don't want to completely throttle until there is slack but rather absorb just a few extra so activity remains pipelined.

**Comment by rabbah** [comment]
Kafka 0.9 upgrade completed, and now using explicit offset commit. Next stage is tracking activation status in the invoker and throttling consumption.
