### ISSUE TITLE
Update docker daemon config with user namespaces

### ISSUE THREAD

**Issue by domdom82** [openwhisk/openwhisk#1433]
Update environments with user namespace configuration:
- [ ] Vagrant
- [ ] Docker-machine
- [ ] Travis
- [ ] whiskhost role

Daemon needs to run with `--userns-remap=default` which will do the following:
1. Search for a user called `dockremap` or create it if needed
2. Search for `dockremap` entry in `/etc/subuid` and `/etc/subgid` or create it if needed.
3. Add a default range of 65536 uid/gid mappings or use existing mapping.

This issue depends on #898 which defaults `--userns=host` to all containers except user containers, effectively restoring previous behavior.

**Comment by markusthoemmes** [comment]
@domdom82 still relevant?

**Comment by domdom82** [comment]
this PR is still open: https://github.com/openwhisk/openwhisk/pull/1707 adds userns to docker-machine
