### ISSUE TITLE
Connection reset Error when setting up openwhisk using Vagrant way or setting up locally on mac

### ISSUE THREAD

**Issue by sanjeevghimire** [openwhisk/openwhisk#1448]
this is the log when running ./hello. I get lot of connection reset error from keyserver.ubuntu.com when setting up locally on my mac machine

==> default: For release candidates, go to https://launchpad.net/~git-core/+archive/candidate .
==> default:  More info: https://launchpad.net/~git-core/+archive/ubuntu/ppa
==> default: gpg:
==> default: keyring `/tmp/tmprsinaroo/secring.gpg' created
==> default: gpg:
==> default: keyring `/tmp/tmprsinaroo/pubring.gpg' created
==> default: gpg:
==> default: requesting key E1DF1F24 from hkp server keyserver.ubuntu.com
==> default: ?:
**==> default: [fd 4]: read error: Connection reset by peer**
==> default: gpg:
==> default: /tmp/tmprsinaroo/trustdb.gpg: trustdb created
==> default: gpg:
==> default: key E1DF1F24: public key "Launchpad PPA for Ubuntu Git Maintainers" imported
==> default: gpg:
==> default: Total number processed: 1
==> default: gpg:
==> default:               imported: 1
==> default:   (RSA: 1)
==> default: OK
==> default: ++ sudo apt-get update

**Comment by sanjeevghimire** [comment]
And while running locally through mac I get this:

gpg: directory `/root/.gnupg' created
gpg: new configuration file `/root/.gnupg/gpg.conf' created
gpg: WARNING: options in `/root/.gnupg/gpg.conf' are not yet active during this run
gpg: keyring `/root/.gnupg/secring.gpg' created
gpg: keyring `/root/.gnupg/pubring.gpg' created
gpg: /root/.gnupg/trustdb.gpg: trustdb created
gpg: key 412B37AD: public key "Swift Automatic Signing Key #1 <swift-infrastructure@swift.org>" imported
gpg: key 21A56D5F: public key "Swift 2.2 Release Signing Key <swift-infrastructure@swift.org>" imported
2016-10-27 22:22:39 URL:https://swift.org/keys/all-keys.asc [5063/5063] -> "-" [1]
gpg: key 91D306C6: public key "Swift 3.x Release Signing Key <swift-infrastructure@swift.org>" imported
gpg: Total number processed: 3
gpg:               imported: 3  (RSA: 3)
gpg: refreshing 3 keys from hkp://pool.sks-keyservers.net
gpg: requesting key 412B37AD from hkp server pool.sks-keyservers.net
gpg: requesting key 21A56D5F from hkp server pool.sks-keyservers.net
gpg: requesting key 91D306C6 from hkp server pool.sks-keyservers.net
?: [fd 6]: read error: Connection reset by peer
?: [fd 6]: read error: Connection reset by peer
?: [fd 6]: read error: Connection reset by peer
gpg: key 412B37AD: "Swift Automatic Signing Key #1 <swift-infrastructure@swift.org>" 1 new signature
gpg: key 21A56D5F: "Swift 2.2 Release Signing Key <swift-infrastructure@swift.org>" 4 new signatures
gpg: key 91D306C6: "Swift 3.x Release Signing Key <swift-infrastructure@swift.org>" not changed
gpg: Total number processed: 3
gpg:              unchanged: 1
gpg:         new signatures: 5
gpg: no ultimately trusted keys found

**Comment by rabbah** [comment]
@paulcastro any ideas what's up with swift?

**Comment by paulcastro** [comment]
I can't replicate this locally.  A transient problem with the key servers used by Swift.org?

**Comment by paulcastro** [comment]
Errors are benign, swift container appears to be functioning.  Will close this issue.
