### ISSUE TITLE
Discussion: invoke-only auth keys

### ISSUE THREAD

**Issue by sjfink** [openwhisk/openwhisk#1449]
I believe (?) our current design for "new" auth keys has a single master key per namespace, which allows all CRUD ops in that namespace, as well as permissions to invoke actions and fire triggers.
Please correct me if this has changed.

Suppose I want to expose actions as REST endpoints which are unauthenticated: I want to allow anyone in the world to hit my REST API, and I'll pay for it.

We could implement this via API Gateway.

However, maybe API Gateway is overkill.   This issue proposes to issue each namespace an auth key with permission to invoke and fire, but not CRUD.

Of course we could go even more fine-grained and associate auth keys with individual entities.  However, doing it only for namespaces is sufficient for some simple use cases.

This came up today as a potential requirement for a mobile app.

**Comment by rabbah** [comment]
Addressed by #1715.
