### ISSUE TITLE
Swift code does not compile with the latest CLI

### ISSUE THREAD

**Issue by trevorbodz** [openwhisk/openwhisk#1458]
I was on version 2016-09-XXXXXXXX of the CLI and this worked, upon upgrading to 2016-10-24T11:55:02+00:00 this now does not work.

wsk sdk install iOS

unzip OpenWhiskIOSStarterApp.zip

pod install

wsk package bind /whisk.system/weather myWeather13 -p username XXXXXXX -p password YYYYYY

cd OpenWhiskStarterApp

wsk action create filter13 FilterForecast.swift

wsk action create --sequence myForecast13 myWeather13/forecast,filter13

wsk action invoke -b myForecast13 -p latitude 43 -p longitude -79

wsk activation list filter13

wsk activation get c592ab7864ee4ae9830608759327533e

ok: got activation c592ab7864ee4ae9830608759327533e
{
    "namespace": "whisktest@hotmail.com",
    "name": "filter13",
    "version": "0.0.1",
    "publish": false,
    "subject": "whisktest@hotmail.com",
    "activationId": "c592ab7864ee4ae9830608759327533e",
    "start": 1477931713204,
    "end": 1477931719438,
    "response": {
        "status": "action developer error",
        "statusCode": 0,
        "success": false,
        "result": {
            "error": "The action failed to generate or locate a binary. See logs for details."
        }
    },
    "logs": [
        "2016-10-31T16:35:14.972006904Z stdout: Compiling",
        "2016-10-31T16:35:19.432291828Z stderr: /swift3Action/spm-build/main.swift:101:26: error: incorrect argument label in call (have 'args:', expected 'params:')",
        "2016-10-31T16:35:19.432338463Z stderr: let result = main(args:parsed)",
        "2016-10-31T16:35:19.432347455Z stderr: ^~~~~",
        "2016-10-31T16:35:19.432354969Z stderr: params",
        "2016-10-31T16:35:19.434989076Z stdout: swiftc status is 1",
        "2016-10-31T16:35:19.436192021Z stdout: Action did not compile"
    ],
    "annotations": [
        {
            "key": "limits",
            "value": {
                "logs": 10,
                "memory": 256,
                "timeout": 60000
            }
        },
        {
            "key": "path",
            "value": "whisktest_dev/filter13"
        }
    ]
}

**Comment by dubeejw** [comment]
@trevorbodz, thanks for the information. Looks like the iOS SDK needs to be updated.

**Comment by paulcastro** [comment]
@trevorbodz in the FilterForecast action, can you change `func main(params:[String:Any]) -> [String:Any]` to be `func main(args:[String:Any]) -> [String:Any]`?

**Comment by dubeejw** [comment]
There are three instances of `params` that must be changed to `args` in FileForecast.

**Comment by trevorbodz** [comment]
Proposed Fix worked

**Comment by trevorbodz** [comment]
@paulcastro Since swift has to compile code, if the compile fails, then it would have been nice if my action creation (same with update) failed (instead of success) so that I know immediately that I have an issue with bad code and I don't have to wait for the code to run and then dig through activations/logs. ALso, prevents me from deploying bad code to OpenWhisk

**Comment by paulcastro** [comment]
The code actually compiles on the first run, not on the action create.  This is the case for the other runtimes, too. I believe having the code compiled on create would involve a lot of changes.  This is likely something we would do in a significant update to how the platform operates.

**Comment by paulcastro** [comment]
resolved.
