### ISSUE TITLE
bug: sequences where a component takes more than 60 seconds

### ISSUE THREAD

**Issue by sjfink** [openwhisk/openwhisk#1464]
I believe the current sequence implementation will not work if any action in the sequence takes more than 60 seconds.

My theory: the current Pipecode.scala implementation just does blocking invokes of each action in sequence.   Our blocking invoke gives up after 60 seconds and converts the request to a non-blocking protocol.    I don't think Pipecode.scala handles this correctly.

Assuming this is true -- we need to either fix Pipecode.scala or promote a new sequence implementation that is not vulnerable.

@ioana-blue @rabbah

**Comment by rabbah** [comment]
This will be fixed with the new implementation. Since this is quite close I think it's not worth fixing with the existing implementation.

**Comment by bseyb** [comment]
What is the issue number of that fix? I am having this issue in my implementation and I'd love to keep track of when it is fixed :)

**Comment by rabbah** [comment]
https://github.com/openwhisk/openwhisk/issues/995.

Are you using openwhisk on bluemix or your own deployment? If the latter, I can suggest a workaround.

**Comment by bseyb** [comment]
I am using openwhisk on bluemix. At the moment as a work around I am implementing to trigger the sequence multiple times with different configuration so that the long running action runs under 1 min.

**Comment by ioana-blue** [comment]
This should be fixed with the current implementation of sequences.
