### ISSUE TITLE
cli improperly sets "code" in "exec" content for blackbox actions

### ISSUE THREAD

**Issue by rabbah** [openwhisk/openwhisk#1465]
```
> wsk -v action create bb --docker aa
...
{{"exec":{"kind":"blackbox","code":"","image":"aa"}}
```

The `code` property should not be defined. In any case, the controller will ignore it so it's harmless but is confusing, especially when doing this:

```
>  wsk -v action get bb
Response body received:
{
  "name": "bb",
  "exec": {
    "kind": "blackbox",
    "image": "aa"
  }, ...
}
```

but the CLI will render the `exec` as:

```
ok: got action bb
{
    "name": "bb",
    "exec": {
        "kind": "blackbox",
        "code": "",
        "image": "openwhisk/example"
    }, ...
}
```

**Comment by mdeuser** [comment]
@rabbah - Just confirming.  Upon action creation, when `code` is empty, should it be removed from the request body?

**Comment by rabbah** [comment]
It could be omitted but this one is harmless on PUT in that the controller ignores it correctly. The confusing one is on the get: the CLI is showing a code property that doesn't actually exist in the schema.

**Comment by dubeejw** [comment]
@rabbah, I am able to omit the code field if it is empty. There are several tests that failures that result though. These are related to NodeJS actions being created without and code field. The backend expects at least an empty string for NodeJS action code.

**Comment by dubeejw** [comment]
Looks like the failures are due to tests using a js file that has no code in it.

**Comment by rabbah** [comment]
This illustrates the problem with encoding the schema/types in the CLI - they're inconsistent wrt the API and complicate the CLI implementation. The `code` property exists for nodejs and other runtimes but not docker actions.

**Comment by ioana-blue** [comment]
I hit this issue as well during sequence cleanup. I'm removing `code` from the sequence exec. Can we make progress on #1469 which seems to be the fix to this issue?

**Comment by rabbah** [comment]
Fixed by https://github.com/openwhisk/openwhisk/commit/c4064ae0e93dd156682c36632924ae63cf719410.
