### ISSUE TITLE
Transient failures for `ConsulTests` in CI builds

### ISSUE THREAD

**Issue by psuter** [openwhisk/openwhisk#147]
Test test `services.ConsulTests` fails occasionally on TravisCI, possibly due to over-optimistic timeouts.

This issue is distinct from #79.

See for instance: [log.txt](https://github.com/openwhisk/openwhisk/files/197912/log.txt)

CC @perryibm

**Comment by perryibm** [comment]
Two thoughts:

1. What's tested here is subsumed but he ConsulKV tests.  Ioana to verify...  So delete this?
2. Otherwise, greatly lower the curl timeout and add retry.

**Comment by ioana-blue** [comment]
I agree, this test needs to be removed since it's subsumed by the ConsulKV tests. I'll submit a PR shortly.

**Comment by ioana-blue** [comment]
Merged. Closing.
