### ISSUE TITLE
document how to change the limits

### ISSUE THREAD

**Issue by csantanapr** [openwhisk/openwhisk#1479]
currently the limits are set low for activations this is only in open to allow test cases run in the limited amount of time

The docs should clarify that this limits are default values, that an operator would higher limits in production like Bluemix.

Also the docs should point how how an operator can change this limits.

originally requested by @sjfink 
>- in the open source docs, let's note that these are the default limits for the open source distribution, but let's document how to change them at deployment, and note that production deployments like BlueMix likely have higher limits.

**Comment by rabbah** [comment]
@csantanapr close?

**Comment by csantanapr** [comment]
closing already fixed
>Note: This default limits are for the open source distribution; production deployments like Bluemix likely have higher limits. As an operator or developer you can change some of the limits using ansible inventory variables.
