### ISSUE TITLE
CLI seems to have incorrect documentation around 'wsk action list' --limit flag

### ISSUE THREAD

**Issue by eweiter** [openwhisk/openwhisk#1483]
I was trying to view my actions on the CLI.  I was looking in particular for Sequences that were created through the UI. 
I ran the command `wsk action list` and I did not see the particular sequence show up.
I then ran `wsk list` and the actions I was looking for did indeed show up in that "actions" portion of the list returned. 

So I then ran `wsk action list -v` and I noticed that it was issuing a GET against 
```
[GET]	https://.../api/v1/namespaces/.../actions?limit=30&skip=0
```

Upon doing a `wsk action list -h` I see that the --limits flag is supposed to the maximum log size LIMIT in MB for the action (default 30)

but when I did `wsk action list --limit 100` my actions that were previously missing, so it seems that the --limits doc text may be incorrect.

**Comment by dubeejw** [comment]
@eweiter, can you clarify your last statement?

**Comment by rabbah** [comment]
```
> wsk action list -h
list all actions
Usage:
  wsk action list [NAMESPACE] [flags]

Flags:
  -l, --limit LIMIT   the maximum log size LIMIT in MB for the action (default 30)
```

the `-l` doc is not accurate for list.
