### ISSUE TITLE
support java actions

### ISSUE THREAD

**Issue by sjfink** [openwhisk/openwhisk#15]
First step: allow users to upload a jar file to define an action.

**Comment by domdom82** [comment]
What's the runtime specs for running Java code?

Do we have a running liberty server that loads the jar and calls a method?

Or is it a simple `java --jar useraction.jar`?

**Comment by psuter** [comment]
The current design is that users upload a jar and specify the fully qualified name of the entry-point class. That class must define a method with the signature:

```
public static JsonObject main(JsonObject args);
```

...where `JsonObject` is `com.google.gson.JsonObject`. The code is hosted by a proxy that handles the OpenWhisk container protocol. It is implemented using `com.sun.net.httpserver.HttpServer`, which comes with the JDK.

**Comment by psuter** [comment]
Basic support as of 11556af73e96c7070173f1191ae1b27c82080b72. Improvements shall be requested as separate issues.
