### ISSUE TITLE
Add ability to annotate activations (especially end-to-end response time)

### ISSUE THREAD

**Issue by starpit** [openwhisk/openwhisk#150]
Extend the API with the capability for clients to annotate activations. The initial use case will be annotating activations with end-to-end response time.

Primary value: this will allow clients to keep track of user experience degradations (where end-to-end response time is critical). 

Secondary value: this will allow OpenWhisk maintainers to track the effect of backend choices on user experience.

We could leave this as a generic "activation annotation", though I suggest we consider elevating the recording of end-to-end response time to a typed (rather than simply named) attribute, so that there is a consistent API for extracting this important metric.

**Comment by mbehrendt** [comment]
@starpit can you pls elaborate on how you envision the annotation of activations to work?

**Comment by starpit** [comment]
i believe that @rabbah already has this support in the backend, though it is not exposed through the controller as of it.

the thought is that we'd have a PUT/POST call which takes an activation ID and an annotation record e.g. `{key: "end-to-end-response-time-in-millis", value: 300}`, and the backend would merge this annotation into the existing annotation map of the given activation. we'll also need to expose a GET to fetch an activations annotations (or perhaps this would show up, as with other entities, at the LIST level of detail, given that they are annotations).

**Comment by rabbah** [comment]
More precisely the REST API does not permit a PUT on activations. They otherwise are the same as other entities in terms of their schema. So we can define a PUT (not POST) operation to activations which accepts only annotations and these are merged with the activation record. The user may use these activations as they like for example to add a note to the activation, to label it, or store other meta data. 

The UI and CLI clients can use it to store relevant information as well.

**Comment by mbehrendt** [comment]
i can imagine a good system-internal use case (eg the load balancer adding an annotaion with roundtrip time for a blocking invocation), but what is the (high prio) use case for externalizing this?

when millions of activations are getting produced as a result of invoking actions in a high-load scenario, it also seems like a perf-costly scenario to add annotations to each activation.

**Comment by sjfink** [comment]
I'm tempted to close this one as won't-fix.    I don't think it makes much sense to have activation records store arbitrary user annotation content.

It would seem to make more sense to provide a key-value store / annotation service somewhere entirely outside the whisk core itself.

@starpit ?

**Comment by starpit** [comment]
i'm ok with closing this.
