### ISSUE TITLE
template-couchdb-local.env is missing within openwhisk directory

### ISSUE THREAD

**Issue by daisy-ycguo** [openwhisk/openwhisk#151]
In README.md, it is said: Then within your openwhisk directory, copy the file template-couchdb-local.env to couchdb-local.env and edit as appropriate. Yet I failed to find template-couchdb-local.env within openwhisk directory. There is only template-cloudant-local.env.

I suggest to create a template-couchdb-local.env for users of couchdb.

Daisy

**Comment by rabbah** [comment]
You're right it should be there.

**Comment by rabbah** [comment]
Here's a sample of what it should contain:
```
OPEN_WHISK_DB_HOST=
OPEN_WHISK_DB_PORT=
OPEN_WHISK_DB_USERNAME=
OPEN_WHISK_DB_PASSWORD=
```

**Comment by psuter** [comment]
#153 has all the info.
