### ISSUE TITLE
allow to specify basepath value in wsk api create shortcut form

### ISSUE THREAD

**Issue by csantanapr** [openwhisk/openwhisk#1535]
If the user type `wsk api create /pets get pets`
basePath = `/` and path `/pets`
If user types
`wsk api create /store/pets get pets`
then basePath = `/store` and path `/pets`

basePath can't not have sub paths it will be the first string until the first `/`

This is base on feedback from #1495

**Comment by mbehrendt** [comment]
the one concern i have with this approach is that it might come across as an arbitrary decision if we establish such a split convention.

eg. what if it want to have `/` as the base path for `/store/pets` ?

**Comment by mdeuser** [comment]
@mbehrendt - The CLI behavior would depend on the number of argument provided.  Explicit basepath specification requires 4 arguments.  Implied basepath specification needs 3 argument.
- `wsk api create /bp /p get action` (TODAY BEHAVIOR)

 basepath = /bp
apipath = /p
- `wsk api create /p get action`   (TODAY BEHAVIOR)

 basepath = /
apipath = /p
- `wsk api create /bp/p1/p2/p3 get action` (PROPOSED BEHAVIOR)

 basepath = /bp
apipath = /p1/p2/p3

**Comment by csantanapr** [comment]
@mbehrendt 
>eg. what if it want to have / as the base path for /store/pets ?

This can be still be supported by specifying the [BASE_PATH] value explicit form: 
`wsk api create [BASE_PATH] API_PATH API_VERB ACTION [flags]`

In your example would be:
`wsk create / /store/pets get action`
BASE_PATH=`/`
API_PATH=`/store/pets`

**Comment by mbehrendt** [comment]
in my mind, there is too much implied behavior.

an alternative proposal: when there is not basepath parameter specified, its value is always `/` by default.

with that, we don't surprise developers with setting basepath to some implied value which might not be clear to the,. we just do exactly what they requested via the cli.

what are your thoughts on this?

**Comment by mdeuser** [comment]
@mbehrendt - What you described is the the current implementation behavior, with the added stipulation (per OpenAPI/Swagger spec) that the relative path begin with `/`.  I tend to agree that we should be careful how much implied configuration the tooling provides; API definitions should be carefully thought out to allow for longevity and future growth.

**Comment by mdeuser** [comment]
@csantanapr - Based on the above conversation, it seem the current implementation is the desired behavior.  OK to close this issue?

**Comment by csantanapr** [comment]
I agree with @mbehrendt 
> an alternative proposal: when there is not basepath parameter specified, its value is always / by default.

let's closed this one.
