### ISSUE TITLE
Add "random in range" option to alarms cron format

### ISSUE THREAD

**Issue by paulcastro** [openwhisk/openwhisk#1542]
There may exist use cases where scheduling an alarm to fire periodically and randomly in a range of time is useful.  For example, we may want to trigger lengthy backups of several images each day, but have these backups happen at different times.  In a operational environment it may be difficult to keep track of "different times." Rather than hard-code a time, it would be useful to specify fire the alarm "at a random time each day/month etc.". 

Jenkins allows a job to be scheduled by a hash of the job's name (which isn't random but handles the above use case).  Explanation below:

```To allow periodically scheduled tasks to produce even load on the system, the symbol H (for “hash”) should be used wherever possible. For example, using 0 0 * * * for a dozen daily jobs will cause a large spike at midnight. In contrast, using H H * * * would still execute each job once a day, but not all at the same time, better using limited resources.

The H symbol can be used with a range. For example, H H(0-7) * * * means some time between 12:00 AM (midnight) to 7:59 AM. You can also use step intervals with H, with or without ranges.

The H symbol can be thought of as a random value over a range, but it actually is a hash of the job name, not a random function, so that the value remains stable for any given project.```

**Comment by markusthoemmes** [comment]
Issue moved to [openwhisk/openwhisk-package-alarms #38](https://github.com/openwhisk/openwhisk-package-alarms/issues/38) via [**ZenHub**](https://www.zenhub.com/)
