### ISSUE TITLE
API now requiring namespace on rule creation (breaking change)

### ISSUE THREAD

**Issue by krook** [openwhisk/openwhisk#1577]
## Environment details:
Running the Mac CLI against the Bluemix API:

```
whisk CLI version	2016-10-11T11:00:00+00:00
whisk API build		2016-12-01T16:15:42Z
whisk API build number	whisk-build-2174-accelerate1
```

## Steps to reproduce the issue:
Yesterday I was able to create a new rule linking an action to a trigger by running the following commands. This no longer works.

1.  `wsk action create handler handler.js`
2.  `wsk trigger create every-20-seconds --feed /whisk.system/alarms/alarm --param cron "*/20 * * * * *"`
3.  `wsk rule create invoke-periodically every-20-seconds handler`

## Provide the expected results and outputs:

```
ok: created rule invoke-periodically
```

## Provide the actual results and outputs:

```
error: Unable to create rule 'invoke-periodically': The request content was malformed:
requirement failed: The fully qualified name of the entity must contain at least the namespace and the name of the entity. (code 11978)
```

## Additional information you deem important:
* This worked with the whisk API build before 12/1

**Comment by krook** [comment]
This was solved by downloading the latest CLI. 

Perhaps a better error message to prompt the user to upgrade?

**Comment by rabbah** [comment]
Hmm. This should not be a breaking change.

**Comment by rabbah** [comment]
This is an inadvertent breaking change in that my intention was to preserve the previous behavior but I did not have the right test in place. I've addressed the issue with this proposed change (and the accompanying test): https://github.com/openwhisk/openwhisk/commit/cffa53bdaf679cd7fe825a06a5d587d680bfee88#diff-c7a6ca91e16420b15c39ab67b4584401R289).

However, after further consideration, allowing this for rules only is asymmetric - in that for other API operations that permit references to entities, we do require a fully qualified name. This is true for a sequence components and for a package binding. Hence for consistency, I am inclined to close as won't fix in the API and instead resolve by documenting that a CLI upgrade is required instead.

@jthomas does npm openwhisk provide fully qualified names on rule creation? If not, the library is also affected by this change.

**Comment by jthomas** [comment]
@rabbah The module relies on the user to provide the correct name format for triggers and actions.
https://github.com/openwhisk/openwhisk-client-js/blob/master/lib/rules.js#L35

I think the API change above is more consistent.

I would change the library to still allow for unqualified names and default to providing a fully-qualified name in the request using the namespace parameter. 

Let me know when this goes in and I'll work on it.

**Comment by rabbah** [comment]
Closing with no action - when creating a rule via the API, one must provide the fully qualified name (consistent with other entities).
