### ISSUE TITLE
docker.timezone.mount - replace with UTC

### ISSUE THREAD

**Issue by domdom82** [openwhisk/openwhisk#160]
this issue meant as discussion / decision thread.

current deployments always mount local timezone into docker containers.

local timezone is currently hard-coded to "America/New_York"

I'd like to argue that this be changed to UTC for the following reasons:

- in the past this might have been convenient for developers in NY but with going open-source we can no longer make that assumption.
- neither our servers nor all of our developers are located in that timezone. once more regions are added it will become even more confusing
- log analysers like kibana expect UTC and convert it to local time of the user. so if a user selects a time frame e.g. "last 5 hours", the log timestamps should also reflect that. if they were UTC, you would only have to add/subtract your local timezone. currently, you have to add/subtract from NY timezone.
- it is good practise to use UTC everywhere in logs / tools to make times comparable. e.g. error message output from tests should be searchable in logs.

**Comment by ioana-blue** [comment]
AFAIK, our core (Scala) components log time in UTC already. They all (should) use `Logging.scala`. See [this](https://github.com/openwhisk/openwhisk/blob/master/common/scala/src/whisk/common/Logging.scala#L103). 

I'm fine with your proposal, specially that I don't think we'll notice a difference wrt logs.

**Comment by sjfink** [comment]
Is this fixed?

**Comment by domdom82** [comment]
the mount still remains but it is set to UTC. since the image itself has UTC as default timezone, I'd propose we remove the mount as well. Any objections?

**Comment by domdom82** [comment]
tz mount is no longer used with ansible deployments. so closing this as obsolete since we want to move away from ant anyway. we can open a new issue, should we run into any tz difficulties on ansible.
