### ISSUE TITLE
router.host always equal to cli.api.host?

### ISSUE THREAD

**Issue by rabbah** [openwhisk/openwhisk#1601]
I don't remember why we define both a `route.host` and a `cli.api.host` in our ansible hosts and whisk.properties files. @sjfink posits that `router.host == cli.api.host` now and I concluded the same... and we can't recall if that was always the case or why there needs to be a distinction. I think we should have just the `api.host` and the `edge.host`.

@jeremiaswerner @markusthoemmes input please.

**Comment by sjfink** [comment]
I vaguely recall now.   It originated in blue-green testing of the CLI.

When swapping from blue to green, we would first run regression tests on the green cluster, and then swap if tests all passed.   For the initial set of tests in green, the "cli api host" would be the green edge.    Of course the CLI used by customers would always point to router host.

I think at some point we changed the tests to use a different flag with cli set property api.host, but the ansible variable is probably legacy from the days when the CLI_API_HOST was a build-time property of the CLI.    This is old stuff -- python CLI and pre-ansible.

**Comment by domdom82** [comment]
The cli.api.host is the dns name per environment (e.g. "openwhisk.ng.bluemix.net")
The router.host is the actual host, e.g. "123.123.123.123"

Which makes sense in scenarios where they are not the same, e.g. loadbalancers, proxies etc.

Also `cli_api_host` is a property that is independent from the inventory, while `router.host` is always generated from the inventory of hosts for that particular environment.

**Comment by rabbah** [comment]
@domdom82 thanks for the clarification. In open, the router is not used/deployed and there is only the edge. The cli.api.host is an ip address, not a name. Should we make it clean in open as well then and define api.host to a name or leave it be? The complication with a name is for mac e.g., where the localhost isn't good enough and one needs a `dockerhost` aliased.

**Comment by rabbah** [comment]
Proposed renaming cli_api_host to whisk_api_host for clarity in #1602.
