### ISSUE TITLE
api-experimental returning double // in url when base path not passed in

### ISSUE THREAD

**Issue by csantanapr** [openwhisk/openwhisk#1638]
When creating an api and no base path is used the url return contains `//` and the action can't invoke with the http verb.
Also if the base path ends with a `/` same problem.

steps to reproduce, don't pass a base path default will be `/`
```
$ wsk api-experimental create /foo/bar get /whisk.system/utils/echo
ok: created API //foo/bar GET for action whisk.system/utils/echo
https://545303d4-gws.api-gw.mybluemix.net//foo/bar
```
Problem invoking action
```
$ curl https://545303d4-gws.api-gw.mybluemix.net//foo/bar
<html>
<head><title>404 Not Found</title></head>
<body bgcolor="white">
<center><h1>404 Not Found</h1></center>
<hr><center>nginx</center>
</body>
</html>
```

Workaround always pass use a base path explicit other than `/` like:
base path = `/foo` and path `/bar` (also make sure base path doesn't end in `/`)
```
$ wsk api-experimental create /foo /bar get /whisk.system/utils/echo
ok: created API /foo/bar GET for action whisk.system/utils/echo
https://545303d4-gws.api-gw.mybluemix.net/foo/bar
```
Then invoking works
```
$ curl https://545303d4-gws.api-gw.mybluemix.net/foo/bar?marco=polo
{
  "marco": "polo"
}
```

**Comment by mdeuser** [comment]
The CLI incorrectly displayed the extra `/`.  This was fixed via PR #1636.

The curl command failed due to a failure in the API GW - which is being investigated by the external API GW team.

**Comment by mdeuser** [comment]
@csantanapr - can this be closed?

**Comment by mdeuser** [comment]
@csantanapr - can this be closed?
