### ISSUE TITLE
The command "source docker.sh" fails on ubuntu destop and server

### ISSUE THREAD

**Issue by houshengbo** [openwhisk/openwhisk#164]
The command "source all.sh" and "source docker.sh" can work well on the Ubuntu launched via vagrant. However, these commands do not work well on the ubuntu desktop and server. I have already tried on both 14.04 and 15.01. 
For the desktop version: the terminal will surprising fade out during the execution of  "source all.sh" or "source docker.sh".
For the server version: the ubuntu will strangely reboot during the execution of  "source all.sh" or "source docker.sh".

**Comment by sjfink** [comment]
No one has reported seeing this problem lately.    Do we have a way to reproduce this?    If not, shall we close this issue as unactionable?

**Comment by mrutkows** [comment]
Hi Vincent, I have no problems running in Ubuntu Please verify the latest (refactored instructions from Carlos) and I will send you a PDF of my process to see if you can get working and if any changes to the .MD files needs to be made.  A
[Ubuntu + Ephemeral CouchDB (Docker).pdf](https://github.com/openwhisk/openwhisk/files/284757/Ubuntu.Ephemeral.CouchDB.Docker.pdf)
[Ubuntu 14.04.3 with ephemeral CouchDB.pdf](https://github.com/openwhisk/openwhisk/files/284758/Ubuntu.14.04.3.with.ephemeral.CouchDB.pdf)

llow me to attach 2 PDF files that show my Ubuntu VM creation/setup (using VMware Fusion) and also my CouchDB ephemeral setup/restart instructions.

**Comment by sjfink** [comment]
@houshengbo is this still a problem?   If not please close.

**Comment by csantanapr** [comment]
No longer an issue, @houshengbo re-open if you can reproduce with latest version
