### ISSUE TITLE
'wsk api-experimental list' : column headers not always aligned with column content

### ISSUE THREAD

**Issue by mbehrendt** [openwhisk/openwhisk#1646]
happens with long strings in the columns

**Comment by jthomas** [comment]
```
[09:21:09 ~]$ wsk api-experimental list
ok: APIs
Action                            Verb             API Name  URL
/james.thomas@uk.ibm.com_dev/weather     get                    /  https://1ed629eb-8082-45c8-970e-10a7280231ca-gws.api-gw.mybluemix.net/api/weather
```

**Comment by mdeuser** [comment]
@jthomas @mbehrendt - The CLI can provide dynamically sized columns - perhaps up to some maximum size, which when either the action name or API name length is beyond the column max size, the string is truncated.  How about a max action name column size of 40 and max API name colunm size of 30.. Does that sound reasonable?

**Comment by mbehrendt** [comment]
@mdeuser if the string is truncated, how can someone find out of full name of the action being used?

**Comment by mdeuser** [comment]
@mbehrendt - the entire API, including the actionName and actionNamespace, can be obtained (in swagger format) via the `wsk api-experimental get` command.

**Comment by mbehrendt** [comment]
@mdeuser i think my question is ....how do i know which parameter to pass to `wsk api-experimental get` , if i can see the full string in `wsk api-experimental list` ?

**Comment by mdeuser** [comment]
@mbehrendt - if i understand your question correctly, the command `wsk api-experimental get BASEPATH` will retrieve the entire API definition with all of the API's action names listed.

let's discuss the `api-experimental list` output.  unlimited column sizes are possible, but at the risk of overflowing the terminal row.  some possible options
- unlimited column size
- set an appropriate maximum column size that's expected to cover the large majority of use cases.  use `get` as a backup
- add an option to the command to display the list in such that the columns are vertical instead of horizontal

**Comment by rabbah** [comment]
why isn't the variable length content at the end of the table that way you can take up as much space as you need? so what if you overflow the terminal window. Inspiration: `ls`.

**Comment by mdeuser** [comment]
there are actual 3 columns that have variable length values - the action name, the basepath/apiname, and the full API url (that contains the basepath and relative path)
```
ok: APIs
Action                    Verb  API Name  URL
/myaction/whisk.system  delete       /bp  http://172.17.0.1:9001/api/51a0ad05-91ce-491e-9427-bedad3698e00/bp/rp
```

**Comment by rabbah** [comment]
So how about a different layout then?
```
Action:            /myaction/whisk.system
Verb:  		delete       
API Name: 	/bp  
URL:		http://172.17.0.1:9001/api/51a0ad05-91ce-491e-9427-bedad3698e00/bp/rp

```

**Comment by mdeuser** [comment]
Yeah.. that's was the third bullet option - switch the columns from running across the horizontal to run across the vertical... perhaps controlled by a CLI option

**Comment by mbehrendt** [comment]
i like the approach of offered a switch on the cli to enable it. i think the default should be the 'everything-in-one-row' view, due to better / more compact readability , while the alternative view can be used as a fallback on case of very long strings

**Comment by mdeuser** [comment]
Some example output.  The option flag label is up for discussion.  In this example, the flag label includes the word `rotate` since that is spreadsheet/image parlance for transposing the columns from horizontal/landscape orientation to vertical/portrait.
```
$ wsk -i api-experimental create /my/basepath/is/quite/long /and/so/is/my/path delete mylongpkgname/mylongactionname -n "And the API Name is also quite long"
ok: created API /my/basepath/is/quite/long/and/so/is/my/path DELETE for action /_/mylongpkgname/mylongactionname
http://172.17.0.1:9001/api/15c54aa3-6a07-4a78-9c4e-a70f73e73b93/my/basepath/is/quite/long/and/so/is/my/path
$ wsk -i api-experimental list
ok: APIs
Action                                      Verb                        API Name  URL
/whisk.system/mylongpkgname/mylongaction  delete  And the API Name is also quite  http://172.17.0.1:9001/api/15c54aa3-6a07-4a78-9c4e-a70f73e73b93/my/basepath/is/quite/long/and/so/is/my/path
$ wsk -i api-experimental list --rotate-output
ok: APIs
Action: /whisk.system/mylongpkgname/mylongactionname
  Verb: delete
  API Name: And the API Name is also quite long
  URL: http://172.17.0.1:9001/api/15c54aa3-6a07-4a78-9c4e-a70f73e73b93/my/basepath/is/quite/long/and/so/is/my/path
```

**Comment by mdeuser** [comment]
Just wanted to re-prime this discussion regarding the option flag.  I'm not entirely happy with the `--rotate-output` flag.   Another possible option: `--full`.   I suppose this option could equally be applied to the other `wsk [entity] list` commands.

**Comment by csantanapr** [comment]
@mdeuser I agree with your proposal on using `--full` this will match what we have today with `wsk activation list --full`
Which prints more details about each row/entry.

In addition I will request that we print two additional fields when using `--full` basepath and path

```
$ wsk -i api-experimental list --rotate-output
ok: APIs
Action: /whisk.system/mylongpkgname/mylongactionname
  Verb: delete
  Name:       And the API Name is also quite long
  Base Path:  /my-basepath/is/quite/long
  Path:       /and/so/is/my/path
  URL:        http://172.17.0.1:9001/api/15c54aa3-6a07-4a78-9c4e-a70f73e73b93/my/basepath/is/quite/long/and/so/is/my/path
```

**Comment by mdeuser** [comment]
@csantanapr Adding the additional API configuration details makes sense; I'll add those fields along with the `--full` flag (removing the `--rotate-output` flag)
