### ISSUE TITLE
travis builds are increasingly hitting the 50 minute build limit

### ISSUE THREAD

**Issue by rabbah** [openwhisk/openwhisk#1649]
inspection of the timed-out builds (#184009434), roughly 20 minutes are spent building (18:35:53 - 18:56:31). From the gradle build steps, these are the times taken in each steps from longest to shortest:

```
Building 'swift3action' took 3 minutes, 41.039 seconds
Building 'pythonaction' took 2 minutes, 19.008 seconds
Building 'swiftaction' took 1 minutes, 35.770 seconds
Building 'cli' took 1 minutes, 22.426 seconds
Building 'nodejs6action' took 1 minutes, 12.122 seconds
Building 'dockerskeleton' took 1 minutes, 11.187 seconds
Building 'nodejsaction' took 1 minutes, 6.654 seconds

Building 'nodejsactionbase' took 50.317 seconds
Building 'scala' took 32.600 seconds
Building 'javaaction' took 23.027 seconds
Building 'invoker' took 12.759 seconds
Building 'example' took 11.808 seconds
Building 'controller' took 9.485 seconds
Building 'badaction' took 1.461 seconds
Building 'badproxy' took 0.713 seconds
Building 'swiftaction' took 0.153 seconds
Building 'dockerskeleton' took 0.128 seconds
Building 'swift3action' took 0.123 seconds
Building 'pythonaction' took 0.110 seconds
Building 'example' took 0.119 seconds
Building 'javaaction' took 0.116 seconds
Building 'badproxy' took 0.112 seconds
Building 'nodejsaction' took 0.105 seconds
Building 'nodejsactionbase' took 0.102 seconds
Building 'badaction' took 0.101 seconds
Building 'nodejs6action' took 0.095 seconds
```

@paulcastro should we stop building `swift` container?
The runtime images swift, python, nodejs6 and docker skeleton are fairly stable at this point. Should we move export these to dockerhub (even manually now) and pin a specific tag for using in our builds?

Can we also move the CLI build to a pinned artifact generated outside the main build? This will roughly shave 12 minutes off our builds.

We really have gotten complacent on this and letting our build time continuing to increase. We used to have ~22 minutes build and test cycles. In the long run longer builds will just drag productivity with it.

Once we've made the build leaner, we can look to reduce the test times.

@csantanapr @bjustin-ibm @dubeejw @jasonpet can we reuse any of your scaffolding from the package repos to make this possible?

**Comment by paulcastro** [comment]
Yes, we should remove the swift container when its convenient.

**Comment by csantanapr** [comment]
Not sure what scaffolding you are referring. There is nothing in the packages repos to re-use.

But I agree with the stage approach and do not build the docker container during travis build, we should pull down the docker image from docker hub.

It's super easy to configure docker hub automatic builds with github webhooks, we are already doing this with the trigger providers.
It's all done in docker hub, it needs a github repo with and then we configure the image per repo, to be build when ever there is a git commit or a tag created, we are using tags in providers.

For example we could have the following repos:
```
openwhisk-runtime-nodejs
openwhisk-runtime-swift
openwhisk-runtime-python
```

**Comment by rabbah** [comment]
> easy to configure docker hub automatic builds with github webhooks, we are already doing this with the trigger providers.

this is what i was thinking of - so this would require that we split out each of the runtimes into their own repos?

**Comment by rabbah** [comment]
so one complication is that our action runtime images depend on some base skeleton and refer to that image `FROM dockerskeleton` - this appears to resolve to `library/dockerskeleton` on dockerhub and fails to build.

**Comment by rabbah** [comment]
We're not completely broken w.r.t. Travis CI - can't build PRs or master.

**Comment by sjfink** [comment]
perhaps now is the time to introduce a 'quick' build for travisCI, that doesn't build/test everything.    Jenkins would still run 'normal' builds.

'quick' build could e.g. elide swift and python.

**Comment by markusthoemmes** [comment]
#1675 implements @sjfink's proposal + a bit more.
