### ISSUE TITLE
Lack of guidance for Cloudant on bluemix

### ISSUE THREAD

**Issue by houshengbo** [openwhisk/openwhisk#165]
I have already registered in IBM bluemix.
I know my username, password and the api address. However, there is no document clearly describing how to configure the Cloudant on bluemix as the datastore.
Do we use the same configuration file cloudant-local.env as for Cloudant account directly with Cloudant? Or some other ways to configure?

**Comment by rabbah** [comment]
There is nothing more you need to do more in Bluemix.

**Comment by rabbah** [comment]
In the top level directory there is a file called template-cloudant-local.env copy it and edit the contents: The username and password from  Bluemix are filled out it template file  so you can create the required cloudant-local.env.

**Comment by houshengbo** [comment]
Hi rabbah. I tried as you said for cloudant from bluemix. It did not work, only work for cloudant account from direct cloudant.

**Comment by rabbah** [comment]
Hmm. The cloudant username from Bluemix should be a uuid followed by `-bluemix`. You can verify that you can login to the cloudant dashboard on cloudant.com.

**Comment by houshengbo** [comment]
Hi rabbah.
I finally went thru the configuration of cloudant on bluemix. Thanks to the instructions here:
https://developer.ibm.com/open/2016/02/22/openwhisk-a-quick-tech-preview/.

I finally realized that the username and password need to be retrieved via the command like "cf service-key cloudant-for-openwhisk openwhisk". However, I took my bluemix username and bluemix password at first, which was the reason I did not get the cloudant running on top of bluemix.

My suggestion is that we can add an additional sentence in the README like "the username and password should be retrieved via what kind of command." instead of "Make note of the username and password so you can create the required cloudant-local.env", which can mislead the users to pick up the bluemix username and password.

**Comment by rabbah** [comment]
The instructions you refer to are actually from the README file: https://github.com/openwhisk/openwhisk#create-a-cloudant-account-via-ibm-bluemix

**Comment by houshengbo** [comment]
I was following exactly what is written here https://github.com/openwhisk/openwhisk#create-a-cloudant-account-via-ibm-bluemix, but still got confused at the beginning and messed up with the bluemix username and password. 
I still think it is a good idea to add more explanation to avoid further confusion to folks who are at the early stage of openwhisk.

**Comment by rabbah** [comment]
Thanks for the feedback - will tweak the docs.
