### ISSUE TITLE
--shared flag for CLI wsk [action|trigger|rule] [create|update]

### ISSUE THREAD

**Issue by sjfink** [openwhisk/openwhisk#1656]
The CLI help says that entity create and update commands support --shared as an option.

Similarly the REST API ops are documented to support a 'publish' parameter.

https://console.ng.bluemix.net/apidocs/98?&language=node#introduction

Since only packages can be shared/public, I would think the --shared and publish options don't belong on individual entities, but only on packages.

**Comment by rabbah** [comment]
@dubeejw recently removed the `--shared` flag from all but the packages.
The remaining work is on the API/controller side.

Can we close as duplicate of https://github.com/openwhisk/openwhisk/issues/465?

**Comment by sjfink** [comment]
closing as duplicate.
