### ISSUE TITLE
Update the `actions.md` file to list all supported languages in the first paragraph

### ISSUE THREAD

**Issue by krook** [openwhisk/openwhisk#1659]
The [documentation for actions](https://github.com/openwhisk/openwhisk/blob/master/docs/actions.md) is comprehensive, but when a new user first takes a look at it they may not see all the current languages supported by OpenWhisk.

We should update the first paragraph to list the supported languages, and provide anchors to the language specific sections below. 

> Actions are stateless code snippets that run on the OpenWhisk platform. An action can be a function written in JavaScript, Swift, or Python, a method packaged as a JAR in Java, or a custom executable program packaged in a Docker container. For example, an action can be used to detect the faces in an image, aggregate a set of API calls, or post a Tweet.

> * JavaScript (Node.js)
> * Swift
> * Python
> * Java
> * Docker    

I'd submit a pull request myself but I'm waiting for my Apache ICLA to be processed.

**Comment by rabbah** [comment]
@krook still planning to do this?

**Comment by krook** [comment]
@rabbah Totally missed your earlier reply. My ICLA is in. I'll submit a PR for it soon.
