### ISSUE TITLE
CLI should prompt when new version is available

### ISSUE THREAD

**Issue by cfjedimaster** [openwhisk/openwhisk#1678]
Since the CLI is not installed via npm, there is no easy way to tell when a new version exists. The Ionic CLI will, not always, but a few times, tell you when a new version exists and your version is out of date.

Another option is to make the version display (I filed a bug report for that) *also* tell you what the most recent version is.

**Comment by rabbah** [comment]
Duplicate of https://github.com/openwhisk/openwhisk/issues/1492?

**Comment by cfjedimaster** [comment]
Looks like it - thanks.
