### ISSUE TITLE
Local Install

### ISSUE THREAD

**Issue by briviere** [openwhisk/openwhisk#1679]
Hello 

I ran the following successfully:

gradlw install

But I'm unable to find the windows cli binaries?

thanks

Brian

## Environment details:

* local deployment, vagrant, native ubuntu, Mac OS, Bluemix, ...   
* version of docker, vagrant, ubuntu, ...

## Steps to reproduce the issue:

1.   
2.   
3.   

## Provide the expected results and outputs:

```
output comes here
```

## Provide the actual results and outputs:

```
output comes here
```

## Additional information you deem important:
* issue happens only occasionally or under certain circumstances   
* changes you did or observed in the environment

**Comment by rabbah** [comment]
Try `gradlew -PcrossCompileCLI=true distDocker`  To cut down build time only one binary is built by default.

**Comment by briviere** [comment]
Closing this for now since I'm still trying to learn the OpenWhisk Architecture.
