### ISSUE TITLE
Refactor API GW actions to no longer use deprecated whisk SDK APIs

### ISSUE THREAD

**Issue by mdeuser** [openwhisk/openwhisk#1690]
Replace whisk.error() with JavaScript promise reject().  May need to create a new promise.  Keep the same error context

Replace whisk.invoke() with the `openwhisk` NPM package's actions.invoke() method.
https://www.npmjs.com/package/openwhisk

**Comment by nwspeete-ibm** [comment]
https://github.com/openwhisk/openwhisk/pull/1730 took out whisk.errror() and whisk.invoke()

**Comment by mdeuser** [comment]
PR #1730 fixed this issue; closing
