### ISSUE TITLE
whisk.core.controller.test.EntitlementProviderTests.Entitlement Provider should not authorize a user to CRUD or activate an entity in someone else's collection

### ISSUE THREAD

**Issue by nwspeete-ibm** [openwhisk/openwhisk#1708]
@rabbah java.util.concurrent.TimeoutException: Futures timed out after [1 second]

Futures time out in mainOpenwhisk Jenkins /4880 and /4879

**Comment by nwspeete-ibm** [comment]
limits.ThrottleTests > Throttles should throttle 'concurrent' activations of one action STANDARD_OUT
    exitCode = 173   stderr = error: Unable to invoke action 'checkConcurrentActionThrottle': The user has sent too many concurrent requests. (code 2549)
    exitCode = 173   stderr = error: Unable to invoke action 'checkConcurrentActionThrottle': The user has sent too many concurrent requests. (code 2550)
    Executed 30 requests, maximum was 30, need to retry 0 (retries left: 3)
    30 slow invokes (dur = 19 sec) took 0 seconds to issue
    Sleeping for 15 sec
    exitCode = 173   stderr = error: Unable to invoke action 'checkConcurrentActionThrottle':

**Comment by rabbah** [comment]
These are from Jenkins right? I don't think there's anything specific to open here.

**Comment by nwspeete-ibm** [comment]
ok closing.
