### ISSUE TITLE
move alarms documentation to a separate section of the docs

### ISSUE THREAD

**Issue by sjfink** [openwhisk/openwhisk#1713]
right now the alarms package is documented in https://github.com/openwhisk/openwhisk/blob/master/docs/catalog.md, along with other services like cloudant and watson.

I think alarms is qualitatively different since it's pretty fundamental -- suggest we lift it into it's own top -level chapter called "triggering based on a timer" or something, to make it easier to find.

**Comment by rabbah** [comment]
@csantanapr self-assign?

**Comment by csantanapr** [comment]
fixed
