### ISSUE TITLE
cli parsing of numbers to floating point considered suprising 

### ISSUE THREAD

**Issue by stevenoh93** [openwhisk/openwhisk#1717]
## Environment details:
I'm running `wsk trigger create...` command on Mac CLI.

## Steps to reproduce the issue:
When I passed in `-p clientId '12345.231452'`, the parameter in the trigger would be rounded to 12345.231.
But when I passed in `-p clientId 'a12345.231452'`, I would get the expected value: `a12345.231452`.
Seems like OW is converting the parameters as floating points and rounding them?

**Comment by rabbah** [comment]
I am not seeing this rounding error.

```
> wsk action create echo tests/dat/actions/echo.js
ok: created action echo
> wsk action invoke echo -p  clientId '12345.231452' -br
{
    "clientId": 12345.231452
}
```

I also verified that a trigger firing results in the same.

```
> wsk trigger create t
> wsk rule create r t echo
> wsk trigger fire t -p  clientId '12345.231452'
> wsk activation list
activations
583b5685cfe040188d5169a00f915782                 echo
6c2d8b897e0b412781bde4bd3c4c7b06                    r
04486f28b04c4f99bc5753121cf85238                    t
> wsk activation result 583b5685cfe040188d5169a00f915782
{
    "clientId": 12345.231452
}
```

Can you provide more detail?

**Comment by stevenoh93** [comment]
I passed in the parameters during the creation of the trigger:
```
wsk trigger create slackevents --feed slack_feed -p clientId "12345.12345" -p clientSecret 'muchsercret'
```
Is this not the best practice to create triggers?

**Comment by rabbah** [comment]
got it - so this is a feed, which means there's some action on the backside running and the rounding is likely happening there. we'll need to check the slack package. @houshengbo @jasonpet any ideas?

**Comment by stevenoh93** [comment]
I'm not using the Slack package here. `slack_feed` is actually a custom feed that I wrote, and it contains this:
```javascript
if (lifecycleEvent == 'CREATE') {
    var body = {
        "clientId": params.clientId.substring(1),
        "clientSecret": params.clientSecret,
        "name": triggerName[2],
	"namespace": triggerName[1]
    };
    ...
```
I had to add `.substring(1)` to temporarily fix the rounding issue by pre-pending  a character.

**Comment by rabbah** [comment]
I still can't replicate it.

```
# not a proper feed but at least checks that client id is not mangled
> cat slack_feed.js 
function main(args) {
    console.log(args.clientId)
    return { clientId: args.clientId }
}
>  wsk action create slack_feed slack_feed.js
ok: created action slack_feed
> wsk trigger create slackevents --feed slack_feed -p clientId "12345.12345" -p clientSecret 'muchsercret' -v
...
"response": {
    "result": {
      "clientId": 12345.12345
    },
    "success": true,
    "status": "success"
  },
...
```

**Comment by stevenoh93** [comment]
Weird.. maybe it only happens when the number is longer?
Could you try with this id? This one matches the length of my actual id.
`12345678912.123456789012`

**Comment by rabbah** [comment]
```
> wsk action create echo tests/dat/actions/echo.js
ok: created action echo
> wsk action invoke echo -br -p a '12345678912.123456789012' -v
REQUEST:
[POST]	https://192.168.99.100:443/api/v1/namespaces/_/actions/echo?blocking=true
Req Body
{{"a":1.2345678912123457e+10}
}
...
{
    "a": 1.2345678912123457e+10
}
```

@dubeejw seems the CLI is parsing the number and changing its notation.


```
> wsk action invoke echo -br -p a '"12345678912.123456789012"' 
{
    "a": "12345678912.123456789012"
}
> wsk action invoke echo -br -p a '12345678912.123456789012' 
{
    "a": 1.2345678912123457e+10
}
```

**Comment by dubeejw** [comment]
Looks like the Go programming language only supports 64-bit floating point numbers when encoding parameters into JSON.

**Comment by sjfink** [comment]
I think the CLI should treat all parameter values as strings.

**Comment by lzbj** [comment]
It seems someone already encounter the same issue,
http://stackoverflow.com/questions/22343083/json-marshaling-with-long-numbers-in-golang-gives-floating-point-number

So we add a flag to let user choose?  or By default use decoder as numbers? Any ideas?

**Comment by mbehrendt** [comment]
would it be possible to just everything as a string? any major downsides to that?

**Comment by lzbj** [comment]
Decode it as float64 as current, we can change the code to use string representation, just FYR @mbehrendt .

@rabbah @dubeejw help correct if I'm error.

**Comment by rabbah** [comment]
Does the UseNumber approach work for the wsk cli?

**Comment by lzbj** [comment]
Yes, I'll do some test and submit a pr if I can.

**Comment by lzbj** [comment]
diff --git a/tools/cli/go-whisk-cli/commands/util.go b/tools/cli/go-whisk-cli/commands/util.go
index 773170a..15bb987 100644
--- a/tools/cli/go-whisk-cli/commands/util.go
+++ b/tools/cli/go-whisk-cli/commands/util.go
@@ -159,14 +159,23 @@ func csvToQualifiedActions(artifacts string) ([]string) {
 }
 
 func getJSONFromStrings(content []string, keyValueFormat bool) (interface{}, error) {
-    var data map[string]interface{}
+    var data interface{} 
     var res interface{}
 
+    fmt.Println("hello")
     for i := 0; i < len(content); i++ {
-        if err := json.Unmarshal([]byte(content[i]), &data); err != nil {
-            whisk.Debug(whisk.DbgError, "Invalid JSON detected for '%s'\n", content[i])
-            return whisk.KeyValueArr{}, err
+        d:=json.NewDecoder(strings.NewReader(content[i]))
+        d.UseNumber()
+        if err:=d.Decode(&data);err!=nil{
+           fmt.Printf("decoded to %#v\n", data) 
+           whisk.Debug(whisk.DbgError, "invalid json detected '%s' \n", content[i])
+           return whisk.KeyValueArr{}, err
         }
+        fmt.Printf("decoded to %#v\n", data)
+        //if err:=json.Unmarshal([]byte(content[i]), &data); err!=nil{    
+        //    whisk.Debug(whisk.DbgError, "Invalid JSON detected for '%s'\n", content[i])
+        //    return whisk.KeyValueArr{}, err
+        //}
 
         whisk.Debug(whisk.DbgInfo, "Created map '%v' from '%v'\n", data, content[i])
     }
@@ -180,13 +189,13 @@ func getJSONFromStrings(content []string, keyValueFormat bool) (interface{}, err
     return res, nil
 }
 
-func getKeyValueFormattedJSON(data map[string]interface{}) (whisk.KeyValueArr) {
+func getKeyValueFormattedJSON(data interface{}) (whisk.KeyValueArr) {
     var keyValueArr whisk.KeyValueArr
 
     i := 0
-
ubuntu@dliu1:~/openwhisk$ ./bin/wsk action invoke echo2 -br -p a '12345678912.123456789012' -i -d
[/go-whisk/whisk.NewClient]:074:[Inf] Disabling certificate checking.
[mmands.parseQualifiedName]:112:[Inf] Qualified entityName: echo2
[mmands.parseQualifiedName]:113:[Inf] Qaulified namespace: guest
[sk-cli/commands/action.go]:149:[Inf] Parsing parameters: []string{"{\"a\": 12345678912.123456789012}"}
hello
decoded to map[string]interface {}{"a":"12345678912.123456789012"}
[mmands.getJSONFromStrings]:180:[Inf] Created map 'map[a:12345678912.123456789012]' from '{"a": 12345678912.123456789012}'
[k.(*ActionService).Invoke]:192:[Inf] HTTP route: actions/echo2?blocking=true
REQUEST:
[POST]	https://9.115.210.244/api/v1/namespaces/guest/actions/echo2?blocking=true
Req Headers
{
  "Authorization": [
    "Basic MjNiYzQ2YjEtNzFmNi00ZWQ1LThjNTQtODE2YWE0ZjhjNTAyOjEyM3pPM3haQ0xyTU42djJCS0sxZFhZRnBYbFBrY2NPRnFtMTJDZEFzTWdSVTRWck5aOWx5R1ZDR3VNREdJd1A="
  ],
  "Content-Type": [
    "application/json"
  ]
}Req Body
{{"a":12345678912.123456789012}
}
[-whisk/whisk.(*Client).Do]:219:[Inf] Req Body (ASCII quoted string):
{"{\"a\":12345678912.123456789012}\n"}
RESPONSE:Got response with code 200
Response body size is 546 bytes
Response body received:
{
  "duration": 6,
  "name": "echo2",
  "subject": "guest",
  "activationId": "d91f529d0115493da238b7163a6a7894",
  "publish": false,
  "annotations": [{
    "key": "limits",
    "value": {
      "timeout": 60000,
      "memory": 256,
      "logs": 10
    }
  }, {
    "key": "path",
    "value": "guest/echo2"
  }],
  "version": "0.0.1",
  "response": {
    "result": {
      "a": 12345678912.123457
    },
    "success": true,
    "status": "success"
  },
  "end": 1484901267906,
  "logs": [],
  "start": 1484901267900,
  "namespace": "guest"
}
[-whisk/whisk.(*Client).Do]:243:[Inf] Response body received (ASCII quoted string):
"{\n  \"duration\": 6,\n  \"name\": \"echo2\",\n  \"subject\": \"guest\",\n  \"activationId\": \"d91f529d0115493da238b7163a6a7894\",\n  \"publish\": false,\n  \"annotations\": [{\n    \"key\": \"limits\",\n    \"value\": {\n      \"timeout\": 60000,\n      \"memory\": 256,\n      \"logs\": 10\n    }\n  }, {\n    \"key\": \"path\",\n    \"value\": \"guest/echo2\"\n  }],\n  \"version\": \"0.0.1\",\n  \"response\": {\n    \"result\": {\n      \"a\": 12345678912.123457\n    },\n    \"success\": true,\n    \"status\": \"success\"\n  },\n  \"end\": 1484901267906,\n  \"logs\": [],\n  \"start\": 1484901267900,\n  \"namespace\": \"guest\"\n}"
[hisk.parseSuccessResponse]:351:[Inf] Parsing HTTP response into struct type: **whisk.Activation
[hisk.parseSuccessResponse]:358:[Inf] Successful parse of HTTP response into struct type: **whisk.Activation
{
    "a": 1.2345678912123457e+10
}
ubuntu@dliu1:~/openwhisk$ 







########################################################################################################


ubuntu@dliu1:~/openwhisk$ ./bin/wsk action invoke echo2 -br -p a '12345678912.123456789012' -i -d
[/go-whisk/whisk.NewClient]:074:[Inf] Disabling certificate checking.
[mmands.parseQualifiedName]:112:[Inf] Qualified entityName: echo2
[mmands.parseQualifiedName]:113:[Inf] Qaulified namespace: guest
[sk-cli/commands/action.go]:149:[Inf] Parsing parameters: []string{"{\"a\": 12345678912.123456789012}"}
[mmands.getJSONFromStrings]:171:[Inf] Created map 'map[a:1.2345678912123457e+10]' from '{"a": 12345678912.123456789012}'
[k.(*ActionService).Invoke]:192:[Inf] HTTP route: actions/echo2?blocking=true
REQUEST:
[POST]	https://9.115.210.244/api/v1/namespaces/guest/actions/echo2?blocking=true
Req Headers
{
  "Authorization": [
    "Basic MjNiYzQ2YjEtNzFmNi00ZWQ1LThjNTQtODE2YWE0ZjhjNTAyOjEyM3pPM3haQ0xyTU42djJCS0sxZFhZRnBYbFBrY2NPRnFtMTJDZEFzTWdSVTRWck5aOWx5R1ZDR3VNREdJd1A="
  ],
  "Content-Type": [
    "application/json"
  ]
}Req Body
{{"a":1.2345678912123457e+10}
}
[-whisk/whisk.(*Client).Do]:219:[Inf] Req Body (ASCII quoted string):
{"{\"a\":1.2345678912123457e+10}\n"}
RESPONSE:Got response with code 200
Response body size is 546 bytes
Response body received:
{
  "duration": 6,
  "name": "echo2",
  "subject": "guest",
  "activationId": "f27f84be0e094d98bb8eb192f3ee6e2e",
  "publish": false,
  "annotations": [{
    "key": "limits",
    "value": {
      "timeout": 60000,
      "memory": 256,
      "logs": 10
    }
  }, {
    "key": "path",
    "value": "guest/echo2"
  }],
  "version": "0.0.1",
  "response": {
    "result": {
      "a": 12345678912.123457
    },
    "success": true,
    "status": "success"
  },
  "end": 1484901571027,
  "logs": [],
  "start": 1484901571021,
  "namespace": "guest"
}
[-whisk/whisk.(*Client).Do]:243:[Inf] Response body received (ASCII quoted string):
"{\n  \"duration\": 6,\n  \"name\": \"echo2\",\n  \"subject\": \"guest\",\n  \"activationId\": \"f27f84be0e094d98bb8eb192f3ee6e2e\",\n  \"publish\": false,\n  \"annotations\": [{\n    \"key\": \"limits\",\n    \"value\": {\n      \"timeout\": 60000,\n      \"memory\": 256,\n      \"logs\": 10\n    }\n  }, {\n    \"key\": \"path\",\n    \"value\": \"guest/echo2\"\n  }],\n  \"version\": \"0.0.1\",\n  \"response\": {\n    \"result\": {\n      \"a\": 12345678912.123457\n    },\n    \"success\": true,\n    \"status\": \"success\"\n  },\n  \"end\": 1484901571027,\n  \"logs\": [],\n  \"start\": 1484901571021,\n  \"namespace\": \"guest\"\n}"
[hisk.parseSuccessResponse]:351:[Inf] Parsing HTTP response into struct type: **whisk.Activation
[hisk.parseSuccessResponse]:358:[Inf] Successful parse of HTTP response into struct type: **whisk.Activation
{
    "a": 1.2345678912123457e+10
}
ubuntu@dliu1:~/openwhisk$

**Comment by lzbj** [comment]
[results.txt](https://github.com/openwhisk/openwhisk/files/718837/results.txt)

**Comment by rabbah** [comment]
Add a unit test in WskBasicUsageTests?

**Comment by rabbah** [comment]
Patch proposed in #1754.

**Comment by rabbah** [comment]
Fixed by https://github.com/openwhisk/openwhisk/commit/03e041c416e19283cf1e1f2b58da85687c0c8dd5.
