### ISSUE TITLE
Invalid swagger file should not crash api create

### ISSUE THREAD

**Issue by nwspeete-ibm** [openwhisk/openwhisk#1732]
Unable to parse swagger file is expected on invalid swagger file...instead during testing we see:
    error: Unable to create API: API route creation failure: {"error":"API configuration failure: {\"error\":\"The action did not produce a valid response and exited unexpectedly.\"}"} (code 0)

**Comment by nwspeete-ibm** [comment]
{
    "swagger": "2.0",
    "info": {
        "title": "/",
        "version": "1.0.0"
    },
    "paths": {
        "/test1": {

            }
    }
}

**Comment by mdeuser** [comment]
@nwspeete-ibm - i tried to recreate the above failure manually using the following swagger file
```
{
  "swagger": "2.0",
  "info": {
  "title": "/",
    "version": "1.0.0
  },
  "paths": {
    "/test1": {
     }
  }
}
```
```
$ wsk -i api-experimental create -c nic.badswagger.json
error: Unable to parse swagger file: Swagger file is invalid (missing basePath, info, paths, or swagger fields
Run 'wsk --help' for usage.
```
Error message is missing a `)`, but it fails as expected.  Does this swagger file fail with the manual command in your environment?

**Comment by nwspeete-ibm** [comment]
Running manually works great: error: Unable to parse swagger file: Swagger file is invalid (missing basePath, info, paths, or swagger fields
Run 'wsk --help' for usage.

**Comment by nwspeete-ibm** [comment]
took out other parameters and this passes. closing.
