### ISSUE TITLE
size calculation for exec of kind sequence fails if component list is empty

### ISSUE THREAD

**Issue by rabbah** [openwhisk/openwhisk#1760]
From Exec.scala: `override def size = components.map(c => c.size).reduce(_ + _)` this must guard against the empty list. We should have additional tests for this case.

**Comment by ioana-blue** [comment]
I'll fix this. Can't assign to myself yet, hopefully soon...

**Comment by ioana-blue** [comment]
While at it, I'll also add a check for no components specified for the sequence (a different bug, really, but I'll use one stone).

**Comment by ioana-blue** [comment]
https://github.com/openwhisk/openwhisk/pull/1767
