### ISSUE TITLE
Alarms package documentation refers to node-cron rather than cron

### ISSUE THREAD

**Issue by hassenius** [openwhisk/openwhisk#1769]
The documentation for the alarms package refers to the format of node-cron (for example second field is optional)
https://github.com/openwhisk/openwhisk/blob/master/docs/catalog.md#firing-a-trigger-event-periodically

However, looking at the source, alarms uses the cron package:
https://github.com/openwhisk/openwhisk-package-alarms/blob/master/package.json
Which seems to require 6 fields, etc

Cron package documentation
https://www.npmjs.com/package/cron

**Comment by rabbah** [comment]
@csantanapr @jasonpet move?

**Comment by markusthoemmes** [comment]
Issue moved to [openwhisk/openwhisk-package-alarms #39](https://github.com/openwhisk/openwhisk-package-alarms/issues/39) via [**ZenHub**](https://www.zenhub.com/)
