### ISSUE TITLE
Crypt not implementing proper IV

### ISSUE THREAD

**Issue by DavidBenko** [openwhisk/openwhisk#1796]
`Crypt` is using AES in CBC mode with a fixed IV. CBC mode requires a 128-bit **random** IV for every use of the cipher. This ensures that the first block of the cipher is properly secured and changes the outcome of every subsequent block so that encrypting the same plaintext twice with the same key will result in different ciphertexts. 

[Code Link](https://github.com/openwhisk/openwhisk/blob/master/common/scala/src/main/scala/whisk/common/Crypt.scala#L43)

Additionally, proper key lengths of 128, 192, & 256-bit should probably be enforced.

**Comment by rabbah** [comment]
Wow that's really old code - pretty sure it's dead code.

**Comment by DavidBenko** [comment]
@rabbah okay, just happened across it and I noticed it.

**Comment by rabbah** [comment]
Thanks for pointing it out - I looked through the source, it's dead code (no imports). We can fix it and keep it around, it may be useful to keep around for the future. Or we can remove it and its test suite. Do you have a use for it? If so, we'd welcome a pr to fix it.

**Comment by DavidBenko** [comment]
No need for it from me, all good

**Comment by csantanapr** [comment]
resolved 32b8421e2e2a38157e0b303fb3385dd53024a898
