### ISSUE TITLE
function missing in the params

### ISSUE THREAD

**Issue by swizardlv** [openwhisk/openwhisk#1807]
## Environment details:

* bluemix

## Steps to reproduce the issue:

1. pass the params to openwisk as 
```
const uuid = require("node-uuid");
const params = Object.assign({}, {
    actionName: "testIngest"
}, {
    blocking: true,
    params: {
        "abc":"def",
        "uuid":uuid
    }
});
console.log(params);
openWhisk.actions.invoke(params)
```
2.   in the openwhisk, 
```
function main(params) {
	return { "message": "you sent me " + JSON.stringify(params) };
}
```
3.   

## Provide the expected results and outputs:

```
you sent me {"abc":"def", "uuid": xxxxxxxx}
```

## Provide the actual results and outputs:

```
you sent me {"abc":"def"}
```

## Additional information you deem important:
* issue happens only occasionally or under certain circumstances   
* changes you did or observed in the environment

**Comment by rabbah** [comment]
```
> node
> const uuid = require("node-uuid");
undefined
> JSON.stringify({x:uuid})
'{}'
```

Are you meaning to get a new `uuid` and pass that to openwhisk as a parameter rather than passing the `uuid` object itself anyway? Undefined/functions are not serialized anyway.

**Comment by rabbah** [comment]
Try this instead:

```
JSON.stringify({x:uuid.v1()})
'{"x":"98bf0460-e9d5-11e6-84e9-736ec63b0367"}'
```

**Comment by swizardlv** [comment]
@rabbah i want to pass some functions to openwhisk (maybe some rest call with credentials). in the action of openwhisk it can be called with some parameters.

is that possible?

**Comment by rabbah** [comment]
Parameters passed between actions are json objects - you have to serialize values otherwise it will be work. You can send a function as a string and eval it in some other action to run it.

**Comment by rabbah** [comment]
Closing as invalid.
