### ISSUE TITLE
wsk package list showing package versions as separate items

### ISSUE THREAD

**Issue by jthomas** [openwhisk/openwhisk#1808]
## Environment details:

IBM Bluemix - US South. 

## Steps to reproduce the issue:

```
$ wsk property get
whisk auth		xxx:yyy
whisk API host		openwhisk.ng.bluemix.net
whisk API version	v1
whisk namespace		_
whisk CLI version	2016-12-13T10:40:19+00:00
whisk API build		2017-01-30T14:37:50Z
whisk API build number	whisk-build-3033
$ wsk package list
packages
/james.thomas@uk.ibm.com_dev/kakfa                                     private
/james.thomas@uk.ibm.com_dev/kafka                                     private
```

Looking at the HTTP traffic, the kafka package has two versions due to being updated. 

## Provide the expected results and outputs:

```
$ wsk package list
packages
/james.thomas@uk.ibm.com_dev/kakfa                                     private
```

Single package identifer should be listed despite number of versions.

**Comment by csantanapr** [comment]
What's the problem? A typo when you created package?
I see two different packages spelled "kakfa" and "kafka"

**Comment by csantanapr** [comment]
By the way you have a very old version of the CLI

**Comment by jthomas** [comment]
I'm an idiot :) 

@csantanapr is correct.

**Comment by csantanapr** [comment]
Your awesome and I just need 👓 It took me a while to see it
