### ISSUE TITLE
ant clean does no longer clean build dir completely

### ISSUE THREAD

**Issue by domdom82** [openwhisk/openwhisk#184]
probably a leftover from gradle migration. due to CLI not being built by gradle, the gradle clean target does not clean the "build" folder the same way as the ant target did previously.

this leaves outdated CLI code in build dir which may cause problems (as it did with new scanCode in my case)

directories remaining so far:

`build/docker-scratch`
`build/tools/cli`

**Comment by rabbah** [comment]
@markusthoemmes can we close this as no longer relevant? (it requires a one time cleanup of the build directory and should not occur again, yes?)

**Comment by markusthoemmes** [comment]
@rabbah yeah correct.
