### ISSUE TITLE
Linked to packages docs instead of duplicating.

### ISSUE THREAD

**Issue by csantanapr** [openwhisk/openwhisk#1848]
Now that packages are implemented in their own repos like:
- openwhisk-catalog
  - github
  - slack
  - watson packages
  - weather
  - websockets
- openwhisk-package-kafka
- openwhisk-package-cloudant
- openwhisk-package-alarm
- openwhisk-package-pushnotifications
- 

I want to remove duplication efforts, and replace the content of [catalog.md](https://github.com/openwhisk/openwhisk/blob/master/docs/catalog.md) with a short description and links to corresponding doc in their repos.

this will help with maintaining the docs as changes and additions are made to those packages, the docs can be in sync with the implementation of the code in the same repo.

The same for the mobile sdk we have duplicates.

The idea will be to have a build system to pubish the docs as html to openwhisk.org website.

So users can use md file on github or website.

**Comment by romankhar** [comment]
This is a great idea and I fully support it! WIll make the job of updating and merging changes far easier.

**Comment by rabbah** [comment]
@csantanapr status?

**Comment by csantanapr** [comment]
this is done
