### ISSUE TITLE
web actions should not project return when using extension .http

### ISSUE THREAD

**Issue by csantanapr** [openwhisk/openwhisk#1850]
When using content extension `.http` with a path like `demo/hello.http/pets/123` it will automatically try to project the field `pets.123` from the return object.

This is not the use case I want, I want to be able to return a `body` and be able to access the path `pets/123` (`__ow_meta_path`) to parse it and use it a path parameter in my web action.

**Comment by rabbah** [comment]
Fixed by linked PR.

**Comment by rabbah** [comment]
I wonder if we should remove all projections. I'm finding them increasingly frustrating to use.

**Comment by csantanapr** [comment]
Ha ! Finally you came around

I never love them and found them very confusing. 

Don’t want to say “told you so”

**Comment by rabbah** [comment]
oh you told me so!!!
