### ISSUE TITLE
ApiGwRoutemgmtActionTests assume routemgmt package installed

### ISSUE THREAD

**Issue by rabbah** [openwhisk/openwhisk#1873]
the tests in `ApiGwRoutemgmtActionTests` assume the package `routemgmt` is already installed and more over owned by `whisk.system`. This seems like an unnecessary precondition for these tests: is there a reason these tests don't run with the standard test subject and use an asset cleaner to create/delete the actions as needed?

**Comment by mdeuser** [comment]
@rabbah - at the time the tests were written, the actions were assumed to be deployed/installed, so it was convenient to use validate the actions as they were deployed and configured with ansible managed environment specific values (i.e. api gw credentials)

**Comment by rabbah** [comment]
going to close as duplicate of https://github.com/openwhisk/openwhisk/issues/1959.
