### ISSUE TITLE
missing fields in 'wsk action get' 

### ISSUE THREAD

**Issue by glikson** [openwhisk/openwhisk#1875]
For nodejs zip actions, the output of 'wsk action get' is missing 'main' and 'binary' fields (which are required for programmatic introspection of actions).

**Comment by rabbah** [comment]
Duplicate of https://github.com/openwhisk/openwhisk/issues/1489 @dubeejw?

**Comment by dubeejw** [comment]
@rabbah, definitely a dupe.

**Comment by rabbah** [comment]
closing as duplicate then.
