### ISSUE TITLE
swift samples package

### ISSUE THREAD

**Issue by sjfink** [openwhisk/openwhisk#188]
currently the 'samples' package contains only node.js samples.

We should distribute equivalent examples in swift.

Discussion item:   what is a good naming convention for samples?   One 'samples' package or one per language?

**Comment by csantanapr** [comment]
Here is propose list:

- [ ] countdown.swift
- [ ] curl.swift
- [ ] echo.swift
- [ ] greeting.swift
- [ ] helloAsync.swift
- [ ] printParams.swift
- [ ] wc.swift
- [ ] wcbin.swift

**Comment by csantanapr** [comment]
FYI: Feedback from @rabbah on cleaning up file names like wcbin
https://github.com/openwhisk/openwhisk/issues/282#issuecomment-215720288

**Comment by bjustin-ibm** [comment]
I feel like as samples (code we show to the customer to instruct them in the ways of OpenWhisk) a lot of these are so simple as to not provide much educational value.  For example, the differences between Hello, Echo, and WordCount do not provide _any_ clarity on what can be done by running this code on OpenWhisk - they are really just showing some very trivial things that can be done with the Swift language on any platform.

If the purpose of these samples is to teach the customer useful things they need to know about OpenWhisk, then I think one very simple Hello action would be appropriate. This shows them the basic structure of a Whisk action in Swift.  Beyond that, we probably want to start showing them samples that show the unique capabilities of OpenWhisk like... invoking other actions, firing triggers, etc.

I realize that we don't currently have a `whisk` backend object that does these things in the same way that is available on, say, the Node.JS runtime, but maybe we should focus on creating that so we can implement more educational samples.

Thoughts?

@sjfink I know you had reservations about exposing Kitura to the customer, but if we encapsulated use of Kitura to the implementation of functions like `invoke()` and `fireTrigger()` inside a `whisk` object that we make available to the customer's Swift code, then the customer will never know or care how it works under the hood.

**Comment by csantanapr** [comment]
@bjustin-ibm I remove some actions that we are not going to implement based on discussion from #302 

- [ ] countdown.swift
We don't have whisk library for whisk.invoke
- curl.swift
We don't have whis.done or whisk.async

- helloAsync.swift
We are going to delete helloAync.js

- printParams.swift
We are going to delete printParams.js
- wcbin.swift
We are going to delete wcbin.js

**Comment by csantanapr** [comment]
I agree with https://github.com/openwhisk/openwhisk/issues/188#issuecomment-216608142 we can start  by using Kitura-Net under the hood, developer doesn't need to know anything about the implementation, to invoke an action or fire a trigger from inside swift, it's just a whisk context object with these methods attached. 
We can replace Kitura-Net with something else in the future and maintain the API on the whisk context object.

**Comment by sjfink** [comment]
I predict you'll find the kitura.net support is much more work and much uglier than you anticipate.   @paulcastro is implementing some user actions using kitura -- let's wait till we see these before we make any decisions.

**Comment by paulcastro** [comment]
I have a commit in my fork of openwhisk in branch "kituraRuntime" that has one example.  catalog/samples/helloSwift3.swift.  It uses KituraNet to make a "get" call and GCD to manage the async callback.  There are other patterns you could use in GCD that "may" work, depending on GCD implementation in Linux.

**Comment by bjustin-ibm** [comment]
As a result of #457 we now have `Whisk.invoke()` and `Whisk.trigger()` available for Swift actions.
