### ISSUE TITLE
rejections from controller are not specific enough

### ISSUE THREAD

**Issue by rabbah** [openwhisk/openwhisk#1886]
The rejection handler in the controller favors the first rejection vs a potentially more specific one later in the route matching. This is attributed to this method in `BasicHttpService`:

```
/** Rejection handler to terminate connection on a bad request. Delegates to Spray handler. */
    protected def customRejectionHandler(implicit transid: TransactionId) = RejectionHandler {
        case rejections =>
            logging.info(this, s"[REJECT] $rejections")
            BasicHttpService.customRejectionHandler.apply(rejections)
    }
```

The `rejections` list should be scanned and prioritized to take either the `last` rejection from the list, or a `CustomRejection` if present.

**Comment by starpit** [comment]
another odd variant of this:

if i nodejs request with `json: true, body: data` to a web-exported route `/my-action.text`, then i get back the "requires authentication" error. whereas if i use `headers: {content-type: 'application/json'}, body: JSON.stringify(data)` then things are happy.

this is i assume due to `json:true` also setting up the `accept` headers? i'm not sure, but this one was pretty opaque.

**Comment by dubeejw** [comment]
@starpit, this will happen as the content type must be JSON or Form Data.

**Comment by starpit** [comment]
A JSON:true option will set the content type to JSON. The puzzling thing is that whisk still rejects. I am guessing that this due to a mismatch of Accept. Because we are invoking with a .Text web exported suffix.

**Comment by dubeejw** [comment]
Can you post here the HTTP header being sent when you do a request with `json: true`?

**Comment by rabbah** [comment]
@starpit that's consistent with this issue.

**Comment by starpit** [comment]
@dubeejw i just verified: the difference seems to boil down to an `Accept: application/json' header, when invoking as `.text`

**Comment by rabbah** [comment]
@l2fprod, you're not alone :)

**Comment by rabbah** [comment]
@dubeejw want to take this one?

**Comment by starpit** [comment]
@rabbah the weird thing to me is that text *is* valid JSON. so an Accept: application/json should not be incompatible with a .text invocation?

**Comment by rabbah** [comment]
there is another related issue: when the `entity` is empty, this will run twice:
```
entity(as[Option[JsObject]]) {
    body => process(body)
} ~ entity(as[FormData]) {
     form => process(Some(form.fields.toMap.toJson.asJsObject))
}
```

**Comment by dubeejw** [comment]
@starpit, it'd be very helpful if you posted the exact options you are using to send the request. Below are some options I experimented with and the result.

Works as expected.
```
var options = {
  method: 'POST',
  url: "https://192.168.99.100/api/v1/experimental/web/.../default/headers.json",
  body: JSON.stringify({"key": "value"}),
  headers: {
    Content-Type': 'application/json'
  }
};

POST /api/v1/experimental/web/.../default/headers.json HTTP/1.1
Content-Type: application/json
host: 192.168.99.100
accept: application/json
content-length: 15
Connection: close
```

Works as expected.
```
var options2 = {
  method: 'POST',
  json: true,
  url: "https://192.168.99.100/api/v1/experimental/web/.../default/headers.json",
  body: {"key": "value"},
};

POST /api/v1/experimental/web/.../default/headers.json HTTP/1.1
host: 192.168.99.100
accept: application/json
content-type: application/json
content-length: 21
Connection: close
```

Does not work as a content-type is not sent. Maybe we should default to application/json if content-type isn't sent?
```
var options3 = {
  method: 'POST',
  url: "https://192.168.99.100/api/v1/experimental/web/lime%40us.ibm.com/default/headers.json",
  body: JSON.stringify({"key": "value"}),
};

POST /api/v1/experimental/web/.../default/headers.json HTTP/1.1
host: 192.168.99.100
content-length: 15
Connection: close
```

Does not work as expected because the body is a string not JSON
```
var options4 = {
  method: 'POST',
   json: true,
  url: "https://192.168.99.100/api/v1/experimental/web/lime%40us.ibm.com/default/headers.json",
  **body: '{"key": "value"}',**
};

POST /api/v1/experimental/web/lime%40us.ibm.com/default/headers.json HTTP/1.1
host: 192.168.99.100
accept: application/json
content-type: application/json
content-length: 22
Connection: close
```

**Comment by rabbah** [comment]
```
$ cat t.js 
function main() {
  return {
    headers: {
      'Content-Type': 'text/html'
    },
    body: 'hi there'
  };
}

$ curl -k https://guest.dockerhost/default/t.json
{
  "headers": {
    "Content-Type": "text/html"
  },
  "body": "hi there"
}

$ curl -k https://guest.dockerhost/default/t.http
hi there


$ curl -k https://guest.dockerhost/default/t.http -H 'Accept: application/json'
{
  "error": "The resource requires authentication, which was not supplied with the request",
  "code": 2644
}
```

**Comment by dubeejw** [comment]
There are actually two different defects in this issue. The defect discussed by @starpit is fixed by https://github.com/openwhisk/openwhisk/pull/2010.
