### ISSUE TITLE
Could we create a repo for openwhisk-client-python 

### ISSUE THREAD

**Issue by cclauss** [openwhisk/openwhisk#1902]
I would like to contribute https://raw.githubusercontent.com/cclauss/openwhisklib/18d299856e05bb1b85971bf81d470dab0e60418a/src/openwhisk.py to and seek some help in making it great.

**Comment by rabbah** [comment]
You may want to also look at the previous cli implementation if you haven't - maybe there are more bits to repurpose.

A python client sdk is something we'd like to have indeed. The repurposing of cli was one way to do that but we can consider your alternative for sure.

@csantanapr shall we create a new repo or rename the python cli repo?

**Comment by csantanapr** [comment]
Rename as I think a single repo can serve both purposes.

**Comment by rabbah** [comment]
Repo renamed.
