### ISSUE TITLE
Get https://172.17.0.1/api/v1/namespaces: x509: cannot validate certificate for 172.17.0.1 because it doesn't contain any IP SANs

### ISSUE THREAD

**Issue by rhdotone** [openwhisk/openwhisk#1908]
Running :
./bin/wsk property set --namespace guest 

error: Authenticated user does not have namespace 'guest '; set command failed: Get https://172.17.0.1/api/v1/namespaces: x509: cannot validate certificate for 172.17.0.1 because it doesn't contain any IP SANs

However if I run in insecure mode, 

./bin/wsk -i property set --namespace guest

It sets fine.

Due to this when I try to set "Service Node Config" in Node-RED UI, I also get 

[Error: Error encountered calling OpenWhisk: Error: self signed certificate]

I am assuming it is because I cannot setup insecure from Node-RED

Is there anyway I can fix this certificate issue in openwhisk?

**Comment by rabbah** [comment]
You can use certbot to generate a signed certificate https://certbot.eff.org/.

**Comment by rabbah** [comment]
Did you try to disable TLS for nodered? :

Try that by exporting NODE_TLS_REJECT_UNAUTHORIZED = "0" in your environment.

**Comment by tardieu** [comment]
@rabbah I encountered the same issue. The workaround does the trick. But is the certificate error the expected behavior? If it is, the doc should discuss it.

**Comment by rabbah** [comment]
They do but not in the best place: https://github.com/openwhisk/openwhisk/tree/master/tools/vagrant#ssl-certificate-configuration-optional.

See this discussion for a longer debate about this: https://github.com/openwhisk/openwhisk/issues/1570 (and related pr https://github.com/openwhisk/openwhisk/pull/1838).

**Comment by rabbah** [comment]
Closed by #2000.
