### ISSUE TITLE
CLI does not pass through -t (timeout) updates

### ISSUE THREAD

**Issue by starpit** [openwhisk/openwhisk#1918]
when calling `wsk action update myAction -t 60000`, the timeout update is not passed to the backend. observe the lack of the timeout update value in the request body below:

```
% wsk -v action update foo -t 60000
REQUEST:
[PUT]	https://openwhisk.ng.bluemix.net/api/v1/namespaces/_/actions/foo?overwrite=true
Req Headers
{
  "Authorization": [
    "Basic xxxxxx"
  ],
  "Content-Type": [
    "application/json"
  ]
}Req Body
{{"namespace":"_","name":"foo"}
}
```

**Comment by rabbah** [comment]
It seems the CLI ignores 60000 - not to sound like a broken record but the CLI should not try to be too smart wrt the API. 

```
./cli/go-whisk-cli/commands/action.go:  if flags.action.memory != MEMORY_LIMIT || flags.action.timeout != TIMEOUT_LIMIT ||
```

This should be removed.
