### ISSUE TITLE
Package listing only shows packages when subject and namespace match.

### ISSUE THREAD

**Issue by totherik** [openwhisk/openwhisk#1926]
When using packages, it appears that the only time the package listing is shown (via `wsk package list` or hitting `https://{host}/api/v1/namespaces/_/packages`) is when the subject and namespace match. Other views of packages (`wsk namespace get {namespace}` and `https://10.25.181.108/api/v1/namespaces/_/`) work as expected. 

## Environment details:
Vanilla local deployment on Ubuntu.

## Steps to reproduce the issue:

1. Create a user (subject) using the default subject-based namespace. Also, create a user setting the namespace to the previous subject/namespace.

```bash
$ wskadmin user create foobar
<auth:credentials>

$ wskadmin user create foobarbaz -ns foobar
<auth:credentials>
```

2.   Create a package using either user.

```bash
$ wsk package create test
```

3.   List packages using both user accounts.

## Expected Results
Both commands should result in the same list of packages.
```bash
# User `foobar`
$ wsk package list
packages
/foobar/test

# User `foobarbaz`
$ wsk package list
packages
/foobar/test
```

## Actual Results
Only the user/subject that matches the namespace list accounts correctly.
```
# User `foobar`
$ wsk package list
packages
/foobar/test

# User `foobarbaz`
$ wsk package list
packages
```

## Additional Information
* As mentioned at the top, using other commands to describe packages by name and/or in the namespace view seem to work as expected.

**Comment by rabbah** [comment]
```
rr ~> wskadmin user whois  c82e62aa-bcc6-4a0e-b23b-21b0bef5ea68:z9iZ1VQ3ott4I86m90tgBaiTdWtLdDdNk9x2GimRwzJBoLLDWlT32939Sh7kX52P
subject: foobar
namespace: foobar
rr ~> wskadmin user whois 496e5795-5539-4aa3-a7df-84dac606b89e:U01CYVK8gsbSqYvou3jgG4yMnbqjy3ADXR0cbSrEm1TE54eHu59LBAQCNf2HKhCe
subject: foobarbaz
namespace: foobar
rr ~> wsk package create test -u 496e5795-5539-4aa3-a7df-84dac606b89e:U01CYVK8gsbSqYvou3jgG4yMnbqjy3ADXR0cbSrEm1TE54eHu59LBAQCNf2HKhCe
ok: created package test

rr ~> wsk package list -u 496e5795-5539-4aa3-a7df-84dac606b89e:U01CYVK8gsbSqYvou3jgG4yMnbqjy3ADXR0cbSrEm1TE54eHu59LBAQCNf2HKhCe
packages
/foobar/test                                                           private
rr ~> wsk package list -u c82e62aa-bcc6-4a0e-b23b-21b0bef5ea68:z9iZ1VQ3ott4I86m90tgBaiTdWtLdDdNk9x2GimRwzJBoLLDWlT32939Sh7kX52P
packages
/foobar/test
```

**Comment by totherik** [comment]
Hrm. I'm not crazy I swear. Lemme see.

**Comment by totherik** [comment]
Well, on another fresh local install I can't reproduce either. Not sure what I did to get it to happen in the first place, but I verified several times prior to filing the bug. Sorry for the noise.

**Comment by rabbah** [comment]
Glad to hear it's not a big. Thanks for verifying.
