### ISSUE TITLE
"main" is not propagated to blackbox actions

### ISSUE THREAD

**Issue by glikson** [openwhisk/openwhisk#1927]
In some cases it is useful to use a customized version of a standard runtime base image (e.g., nodejs6action plus some OS packages, created with kind=blackbox, image=myFlavorOfNodejs6Action), but still use the regular flow to manage the action code (e.g., putting base64-encoded zip in 'code').
However, standard nodejs proxy fails because for blackbox actions "main" is not propagated down to the action container. This is still the case even if I specify "main" when creating the action via REST.

**Comment by rabbah** [comment]
This is potentially an easy one. Requires two changes:

1. https://github.com/openwhisk/openwhisk/blob/master/common/scala/src/main/scala/whisk/core/entity/WhiskAction.scala#L159
2. https://github.com/openwhisk/openwhisk/blob/master/common/scala/src/main/scala/whisk/core/entity/Exec.scala#L117

plus some tests, of course.

**Comment by kennu** [comment]
Was going to report exact same issue. I built a custom container based on openwhisk/nodejs6action and could not pass the main argument to it using kind blackbox.

**Comment by glikson** [comment]
@kennu until this is fixed, FYI, I've uploaded a modified version at glikson/nodejs6action which will work with kind="blackbox", "image" and "code" (I patched the proxy to inject message["main"]="main" into the init payload). Feel free to use/inherit.

**Comment by kennu** [comment]
Thanks @glikson, I patched my container image's service.js probably in a very similar way, to hard-code the main message when it's missing. I also submitted a PR to https://github.com/serverless/serverless-openwhisk for overriding the default Node.js image in Serverless apps, and that would benefit from the main parameter working automatically.

**Comment by rabbah** [comment]
A proposed patch: https://github.com/openwhisk/openwhisk/compare/master...rabbah:issue-1927?expand=1

**Comment by rabbah** [comment]
is shall be now.
