### ISSUE TITLE
blocking action invoke from CLI with result

### ISSUE THREAD

**Issue by rabbah** [openwhisk/openwhisk#1953]
To invoke an action and get its result, we currently require:
`wsk action create <name> --blocking --result`

We should just reduce this to `--result` (you can't get a result without `--blocking`, so why require both - is there a reason to continue to do that?).

**Comment by RSulzmann** [comment]
https://github.com/openwhisk/openwhisk/pull/2114

New behaviour:

`wsk action invoke <name> --result`
invokes the action implicit as blocking invocation.
If --result is specified, --blocking can be omitted.

Specifying --blocking and --result still works.

**Comment by csantanapr** [comment]
Closed by #2114
