### ISSUE TITLE
Vagrant + virtualbox VM GUI

### ISSUE THREAD

**Issue by uzzz** [openwhisk/openwhisk#196]
Is it necessary to have a `vb.gui = true` in vagrantfile for VirtualBox provider? You advise to use `vagrant ssh` in README, so what's the purpose of this useless login window?

**Comment by markusthoemmes** [comment]
You're right, good catch! GUI is only necessary if you choose to install the Ubuntu Desktop. That could be made clear in `README.md`

**Comment by domdom82** [comment]
We could disable it by default. Would not even use it on desktop.

**Comment by csantanapr** [comment]
Closing as default is not GUI, but if user wants GUI follow instructions in [tools/vagrant/README.md#using-vagrant-vm-in-gui-mode-optional](https://github.com/openwhisk/openwhisk/blob/master/tools/vagrant/README.md#using-vagrant-vm-in-gui-mode-optional)
