### ISSUE TITLE
Improve the Python code base to achieve PEP8 compliance

### ISSUE THREAD

**Issue by cclauss** [openwhisk/openwhisk#1963]
https://github.com/openwhisk/openwhisk/pull/1954 adds [flake8](http://flake8.pycqa.org/en/latest/) testing of all Python files for each pull request to this repo.  We ask Python contributors to review the associated errors and help us to eventually achieve no flake8 errors.  Currently the maximum-line-length is set to 127 (the width of the GitHub editor) but eventually it should be reduced to 79 characters so that our Python code achieves full [PEP8](https://www.python.org/dev/peps/pep-0008/) compliance.

**Comment by rabbah** [comment]
I appreciate that @mrutkows did this and applied pep8 in #1987. But I am not a fan of the 80 character lines - I find it silly (it's 2017, we don't print code to read, we have high res monitors, ...) and think longer lines are actually easier to read in _some_ cases.

This project is not a python project - we have a tiny amount of python code.
Can we at least relax the line limit to 127 characters as in the linter?

I'm not going to make a bigger deal about it; I'll relunctlantly relent and move on regardless.

**Comment by cclauss** [comment]
Agreed on all points...  With the recent migration of code over to [openwhisk-client-python](https://github.com/openwhisk/openwhisk-client-python), Python is now just 1.5% of this repo's code.  For me 127 chars per line is a good limit.  When I write new code, I keep it to 79 characters but lots of the argparse code makes that conversion difficult.

It will be interesting to see how we rationalize https://github.com/openwhisk/openwhisk/pull/1987 and https://github.com/openwhisk/openwhisk/pull/1973 as they touch many of the same files for similar but not identical purposes.  My sense is that once it passes review, you should merge @mrutkows 's 1987 and then I can go back through 1973 manually to see if there is anything left that should still come across.

Please also review https://github.com/openwhisk/openwhisk/pull/1975 which concerns just one file (PythonActionContainerTests.scala) which currently contains Python 2-only code.

Let's get @mrutkows to weigh in before we close this issue.

**Comment by cclauss** [comment]
Where do we want to go with this one?

Now that [tools/travis/flake8.sh](https://github.com/openwhisk/openwhisk/blob/master/tools/travis/flake8.sh) is run against every pull request, we get [pages and pages of style errors](https://travis-ci.org/openwhisk/openwhisk/builds/213435574#L339) on every Travis build.  This is similar to what you would get locally on each commit if you do [`flake8 --install-hook git`](http://flake8.pycqa.org/en/latest/user/using-hooks.html) on your workstation.

So now that we have access to the data, do we really want to fix these issue or do we just close this issue?

**Comment by rabbah** [comment]
As I stated before - we have so little python code that we should not obsess over it. It's functional, it's tested. If there's no interest in fixing the style error from others, I would disable the pages and pages of style errors and live with it.
