### ISSUE TITLE
move mobile/iOS/starterapp

### ISSUE THREAD

**Issue by rabbah** [openwhisk/openwhisk#1967]
@paulcastro is there a proper home to move `mobile/iOS/starterapp` to?

**Comment by paulcastro** [comment]
In the openwhisk-client-sdk code as an example app.

**Comment by rabbah** [comment]
https://github.com/openwhisk/openwhisk-client-swift?

**Comment by paulcastro** [comment]
Yes, sorry that one.

**Comment by rabbah** [comment]
OK opened a pr to move the content (with and w/o history - i think the history is not very deep/meaningful so not sure it's worth keeping). If we do remove the mobile directory, have to sort out the nginx build which packages the app for download.

Also have to check if there are doc changes needed.

**Comment by paulcastro** [comment]
Cool.  No need to keep the history.

**Comment by rabbah** [comment]
TODOs:

1. [ ]  build/store zip file from client repo
2. [ ] modify nginx build to pull zip file (or perhaps just proxy the url - even better)
3. [ ] check if any docs need an update

@paulcastro what do you think about 1/2?

**Comment by paulcastro** [comment]
For 1, we can manually zip and store in git repo as part of a tagged release as a baby step for anything more automated.

**Comment by paulcastro** [comment]
I created a 0.2.3 release of the SDK that has a [zipped starter app hosted on github](https://github.com/openwhisk/openwhisk-client-swift/releases/tag/0.2.3)

**Comment by rabbah** [comment]
Thanks. I'll proxy to it.

**Comment by rabbah** [comment]
Closed by https://github.com/openwhisk/openwhisk/compare/e0672abe9c02...bc1ef95e5caf.
