### ISSUE TITLE
invoker should gc on exit

### ISSUE THREAD

**Issue by domdom82** [openwhisk/openwhisk#198]
If an invoker gets stopped it should remove all of its managed containers as well.

Currently when invoker starts, it launches warmup actions to speed up user invocations.

However if the invoker receives SIGTERM (i.e. docker stop), it just exits and the warmup actions (or any other action for that matter) remains in a paused state. You then have to manually do a docker unpause and docker rm of the lingering action containers.

That seems like incomplete lifecycle management of action containers.

Suggestion: Instead of making the user manually unpause and remove remaining containers, the invoker should gc all actions it spawned in the pool on SIGTERM to get to a cleaned-up state on exit.

**Comment by perryibm** [comment]
From a RAS perspective, you can't rely on any infrstratucture container to do any followup action in the event of unexpected termination.  There is no normal shutdown path for the invoker and even adding one does not remove the job of dealing with an unexpected termination.  

We do in fact unpause/rm in teardown of VMs during testing.

**Comment by domdom82** [comment]
The two problems are orthogonal in my point of view. Yes, containers can crash at any time which is why there are nannies in place. But if you allocate stuff you should make sure to deallocate on exit just like the old days of malloc() and free().

Another way of dealing with this could a more fine-grained way of teardown that can be tailored to invoker-only stuff. I.e. if I had a regex for all action containers I could unpause + rm them. 

For ansible I need a way of un-deploying exactly one component without tearing down everything else.

**Comment by domdom82** [comment]
Take consul for example: If a server in the cluster gets terminated, it leaves the cluster and notifies the master about that. It doesn't just die and lets the others find out via timeout. Now of course a crash can still happen in which case RAS kicks in. However a graceful shutdown is also important.

**Comment by markusthoemmes** [comment]
It might be interesting to think about this in terms of draining the system. I.e. you send the invoker a `SIGTERM` signal, but it continues to finish the work it already has and exits afterwards, taking it ContainerPool with it.

**Comment by perryibm** [comment]
The plan is to do this after we can actually restart the invoker (kafka back pressure and activation count reset).  As it is, the cleanup here won't let you reclaim the machine anyhow.  Also, note that the invoker does clean up leftover stuff upon startup.

**Comment by perryibm** [comment]
Because we had to re-write the cleanup code on startup, the corresponding teardown on a graceful exit (SIGTERM via `docker stop`) has also been done and now merged.  We'll handle the draining as part of the invoker restart work - issue to be created soon.

**Comment by domdom82** [comment]
cool! thanks
