### ISSUE TITLE
Allow zip file to contain multiple swift source code files

### ISSUE THREAD

**Issue by paulcastro** [openwhisk/openwhisk#1985]
Allow Swift runtime to accept zip files that contain multiple source code files.

**Comment by akrabat** [comment]
Bonus points if you one of those swift files can be `Pacakge.swift` and so we can pull in dependencies!

**Comment by paulcastro** [comment]
@akrabat the cold start times may be killer with full Swift Package Manager support.  However, worth investigating!

The pre-compilation of a Swift Package seems like a better approach.

**Comment by akrabat** [comment]
Good point.
