### ISSUE TITLE
Whisk.invoke() for a Swift binary in a zip file doesn't work

### ISSUE THREAD

**Issue by akrabat** [openwhisk/openwhisk#1990]
When I create a Swift binary that I upload in a zip file, it crashes if there's a call to `Whisk.invoke()` in it, even though it compiles. 

**To reproduce:**

We need two files: `hello.swift` and `compile.sh`:

*hello.swift:*
```swift
func main(args: [String:Any]) -> [String:Any] {
    let result = Whisk.invoke(actionNamed: "/whisk.system/utils/echo", withParameters: ["name": "Rob"])
    return result ?? ["error": "No result from Whisk.invoke"]
}
```

*compile.sh:*
```bash
#!/bin/bash

docker run -it -v "$(pwd):/owexec" openwhisk/swift3action bash -e -c "
if [ -z \"$1\" ] ; then
    echo 'Error: Missing action name'
    exit
fi
if [ -f \"/owexec/$1.zip\" ] ; then
    rm \"/owexec/$1.zip\"
fi
# echo 'Installing zip...'
apt-get -qq install -y zip > /dev/null
# echo 'Setting up build...'
cp \"/owexec/$1.swift\" /swift3Action/spm-build/main.swift
cat /swift3Action/epilogue.swift >> /swift3Action/spm-build/main.swift
echo '_run_main(mainFunction:main)' >> /swift3Action/spm-build/main.swift
# echo 'Compiling $1...'
/swift3Action/spm-build/swiftbuildandlink.sh
# echo 'Creating archive $1.zip...'
cd /swift3Action/spm-build
zip \"/owexec/$1.zip\" .build/release/Action
"
```

**Command line operations:**

1. Compile `hello.swift` to a Swift binary and then zip it to create `hello.zip`:
```
$ ./compile.sh hello
Compiling
swiftc status is 0
Linking
  adding: .build/release/Action (deflated 68%)
```
This has placed `hello.zip` in the same directory as `hello.swift`.

2. Upload to OpenWhisk:
```
 $ wsk action update helloSwiftly hello.zip --kind swift:3
ok: updated action helloSwiftly
```

3. Invoke the action:
```
$ wsk action invoke helloSwiftly --blocking
ok: invoked /_/helloSwiftly with id f74dc69709194fa681d316486de89a8a
{
    "activationId": "f74dc69709194fa681d316486de89a8a",
    "annotations": [
        {
            "key": "limits",
            "value": {
                "logs": 10,
                "memory": 256,
                "timeout": 60000
            }
        },
        {
            "key": "path",
            "value": "19FT_dev/helloSwiftly"
        }
    ],
    "duration": 319,
    "end": 1489082272901,
    "logs": [],
    "name": "helloSwiftly",
    "namespace": "19FT_dev",
    "publish": false,
    "response": {
        "result": {
            "error": "The action did not return a dictionary."
        },
        "status": "action developer error",
        "success": false
    },
    "start": 1489082272582,
    "subject": "rob@19ft.com",
    "version": "0.0.8"
}
```

Note that the `response` is from within OpenWhisk somewhere - as the action didn't complete.

If we look at the activation log:
```
$ wsk activation logs f74dc69709194fa681d316486de89a8a
2017-03-09T17:57:52.900586524Z stdout:
```

**Non-zip way:**

To prove that it's the binary in the zip file that's not being executed correctly, we can also upload the same `hello.swift` directly to OpenWhisk and invoke it:

```
$ wsk action update hello hello.swift
ok: updated action hello

$ wsk action invoke -b -r hello
{
    "activationId": "a17fb68ba579437493e445f815659488",
    "annotations": [
        {
            "key": "limits",
            "value": {
                "logs": 10,
                "memory": 256,
                "timeout": 60000
            }
        },
        {
            "key": "path",
            "value": "whisk.system/utils/echo"
        }
    ],
    "duration": 2,
    "end": 1489082471888,
    "logs": [],
    "name": "echo",
    "namespace": "19FT_dev",
    "publish": false,
    "response": {
        "result": {
            "name": "Rob"
        },
        "status": "success",
        "success": true
    },
    "start": 1489082471886,
    "subject": "rob@19ft.com",
    "version": "0.0.69"
}
```

In this case, the response is the output from `/whisk.system/utils/echo` as expected.

**Comment by paulcastro** [comment]
I'm not sure of the root cause, but using `openwhisk/swift3action` seems to create a binary which isn't properly linked to the Whisk object -- it seems to crash silently when you use it.

I created a new container from the openwhisk/core/swift3action myself and modified the compile.sh script to use it.  I was able to get the code above to work.

Steps I did:

1. Copy action proxy code:
`$ cp  $openwhiskhome/core/actionproxy/actionproxy.py $openwhiskhome/core/swift3Action`

2. build image
`$ cd $openwhisk/core/swift3Action`
`$ docker build -t swifty .`

3. modify compile script to use swifty image

Change line 3:
`docker run -it -v "$(pwd):/owexec" openwhisk/swift3action bash -e -c " ` 
to:
`docker run -it -v "$(pwd):/owexec" swifty bash -e -c "`

4. compile `compile.sh hello`

**Comment by akrabat** [comment]
This issue is fixed with the updated `openwhisk/swift3action` action that's been uploaded to Docker hub! (Use`docker pull openwhisk/swift3action:latest` to grab…)

Note that the updated `openwhisk/swift3action`  includes `zip`, so no need for the `apt-get -qq install -y zip > /dev/null` line in `compile.sh`.
