### ISSUE TITLE
Can I query an OpenWhisk server for what language "kinds" are supported?

### ISSUE THREAD

**Issue by cclauss** [openwhisk/openwhisk#1995]
Get back something like (file suffix, versions available):

{
    "js": ["node", "node:6"],
    "java": ["java", "java:7", "java:8"],
    "py": ["python", python:2"],
    "swift": ["swift", "swift:2", "swift:3"]
}

As a bonus, any way to query a server for info on deprecated versions?

**Comment by rabbah** [comment]
See #1980. It's coming.

**Comment by rabbah** [comment]
Example https://github.com/openwhisk/openwhisk/issues/335#issuecomment-284982430.

**Comment by rabbah** [comment]
@cclauss close as duplicate?
