### ISSUE TITLE
Allow array as JSON result (The action did not produce a valid JSON response: [])

### ISSUE THREAD

**Issue by aslom** [openwhisk/openwhisk#2027]
## Environment details:

* Bluemix

## Steps to reproduce the issue:

1.   Run action

```
function main(params) {
	return [];
}
```

## Provide the expected results and outputs:

```
[]
```

## Provide the actual results and outputs:

```
{
  "error": "The action did not produce a valid JSON response: []"
}
```

## Additional information you deem important:
* returning empty {} works fine

```
function main(params) {
	return {};
}
```

**Comment by aslom** [comment]
I ended up with this workaround but it is kind of ugly to put it into every action that is returning JSON from REST API call ...

```
    if(json.constructor.name === 'Object') {
      resolve(json);
    } else { // openwhisk fails if response in not JSON
      resolve({ 'result' : json});
    }
```

**Comment by rabbah** [comment]
Actions by definition must return an JSON object - it is incorrect to return anything else. 
Your action may appear to return a JSON array (or any legal JSON value) if you use a web action, e.g., to return `{ body: []}` instead.

I don't see us relaxing this restriction otherwise - it's fundamentally part of the action definition (dictionary in, dictionary out) and permits action composition.

**Comment by aslom** [comment]
OK - it just makes for ugly code to check and convert output from REST API calls inside action (and I already need to check if output is JSON in first place ...)

Example:

```
function main(parameters) {
 return new Promise(function(resolve, reject) {
var request = require("request");

var options = { method: 'GET',
  url: 'http://api.wunderground.com/api/%7Bkey%7D/conditions/q/%7Bstate%7D/%7Bplace%7D' };

request(options, function (error, response, body) {
  if (error) {
    reject(error);
  } else {  
    var json = {};
    try {
      json = JSON.parse(body);
    } catch (e) {
      var len = Math.min(body.length, 10);
      var bodyStr = body.substring(0, len);
      json = { 'msg': bodyStr };
      console.log('body=' + bodyStr);
    }
    if(json.constructor.name === 'Object') {
      resolve(json);
    } else { // openwhisk fails if response in not JSON object {}
      resolve({ 'result' : json});
    }
 }
});

 })
}
```
