### ISSUE TITLE
CLI should support invocation of web actions

### ISSUE THREAD

**Issue by bjustin-ibm** [openwhisk/openwhisk#2055]
Perhaps by adding a `--web` argument to the `action invoke` command, we could allow users to invoke web actions. This flag would allow the CLI to construct the proper URL in order to invoke the web action. Additionally, this flag should apply to the `trigger create` and `trigger delete` commands to allow triggers to be created/deleted from feed actions that are web actions.

**Comment by bjustin-ibm** [comment]
FYI @rabbah

**Comment by mdeuser** [comment]
Other things to consider:
- The web action response context (i.e. the action extension - .http, .json, etc) would also need to be specified
- Response parsing.  Web action responses can be somewhat free form, so beyond the response status code, any other internal error structure will likely be beyond the CLI's capability.  The `-r` option does not apply to web-actions.
- Other `wsk action invoke` options.  web-actions are blocking by nature, so the `-b` option does not apply to web action invocation.

**Comment by dubeejw** [comment]
@csantanapr, this relates to the discussion we about CLI gaps related to web actions.

**Comment by csantanapr** [comment]
Yep bringing @bjustin-ibm into the loop as he has a use case to use web actions as trigger feed actions

**Comment by bjustin-ibm** [comment]
😏

**Comment by rabbah** [comment]
Tell me again why you want to invoke the action as a web action instead of a normal action? (A web action may be invoked with `wsk action invoke` of course.)

**Comment by rabbah** [comment]
Would `wsk action invoke --web` be the equivalent of doing a `curl`?

**Comment by bjustin-ibm** [comment]
> Tell me again why you want to invoke the action as a web action instead of a normal action?

Because I want to invoke the non-shared action but do not have the auth key for it. For the simple `action invoke` this **is** equivalent to using `curl`, but is more useful in the `trigger create` scenario. If we feel that the simple action invoke case is just too silly to support, then I'm ok scoping this down to just the trigger create one.

**Comment by rabbah** [comment]
> Additionally, this flag should apply to the trigger create and trigger delete commands to allow triggers to be created/deleted from feed actions that are web actions.

The web action in this case is serving as an API - it could be curl'ed from the trigger feed action (which is shared)?

Can you elaborate further on the scenario with triggers?

**Comment by dubeejw** [comment]
For consistency, if the CLI provides a means for creating a web action, there should also exist the ability to invoke a web action from the CLI even if it is the same as a curl.

**Comment by bjustin-ibm** [comment]
> Can you elaborate further on the scenario with triggers?

The scenario is that the feed action needs to be invokable by anyone, but non-shared because it will have bound parameters with sensitive values (super secret credentials). It _could_ be implemented with a shared action that posts to a web action as you suggest, but that is not as simple and performant (two activations for every trigger create) as having a single non-shared web action.

**Comment by rabbah** [comment]
considered changing the _trigger create with a feed_ to instead of accepting an action, to instead accept a url? would that be more general (either created feed by invoking an action or making an http call)?

**Comment by rabbah** [comment]
> For consistency, if the CLI provides a means for creating a web action, there should also exist the ability to invoke a web action from the CLI even if it is the same as a curl.

This could be a different set of sub commands, like the "gw" integration. FWIW do the api-experimental subcommands allow curling the gw endpoints?

**Comment by bjustin-ibm** [comment]
> considered changing the trigger create with a feed to instead of accepting an action, to instead accept a url?

Seems like a much heavier mental burden on the user to first find the URL for the feed action they want to invoke. Personally, I don't even like the idea that they have to know the feed action is a web action, but that seems unavoidable.

 It is much simpler to tell them to use (for example) `--web -f messageHubFeed` and have the CLI handle the sticky details of determining the correct URL for them. If we were to require them to pass in the feed action URL, then the documentation for the feed gets much trickier in that we can't just say "use these parameters" and will then have to document how to find the URL for the feed action and pass _that_ as a parameter.

Honestly, I doubt most users that have created a trigger even realize there is an action invocation happening on their behalf - and that is a good thing.

Also, something just feels icky about allowing them to pass an arbitrary URL to which we are going to POST their feed details. Security risk maybe?

**Comment by rabbah** [comment]
Seems from your explanations that the issue is with the entitlement model - it's not fine grained enough. Sharing a package means the action may be invoked or read where you only want to grant invoke rights. Web actions give you the right entitlement but leak implementation details. So another question: if we fixed the entitlement to be more fine grained, would it satisfy the requirement in this scenario?

**Comment by bjustin-ibm** [comment]
> if we fixed the entitlement to be more fine grained, would it satisfy the requirement in this scenario?

What I need is the ability to create an action that anyone can invoke without the auth key, but also they cannot see the code or parameter values for this action. If that were possible, ultimately then the CLI would not need to change to support invoking web feed actions.

**Comment by rabbah** [comment]
> that anyone can invoke without the auth key, 

two more thoughts: (sorry for not yet offering answers, i'm trying to clarify the requirements)

1. note that we define that a trigger life cycle event receives an apikey (to fire a trigger on behalf of the user) among other fields
2. invoking an action as a web action changes the cost model for the activation (from caller pays to owner pays)

**Comment by bjustin-ibm** [comment]
> note that we define that a trigger life cycle event receives an apikey (to fire a trigger on behalf of the user) among other fields

I'm curious why you chose to point this out. Is this to show that users may not be as blissfully ignorant about feed actions as I suspect, or something else?

> invoking an action as a web action changes the cost model for the activation (from caller pays to owner pays)

Now that is interesting! It makes sense, but is not optimal in the feed action scenario where the caller should be billed.

**Comment by rabbah** [comment]
> I'm curious why you chose to point this out...

In short yes.

The user should be aware they are in fact authorizing triggers to be fired on their behalf, with their apikey. It's arguable this flow should handshake more generally through an OAuth flow where the feed is given a limited access token to fire exactly one trigger, for example. As opposed to the current model where there is just one key.

This is more aligned with the negotiate the feed construction through a web action (API), in that then authentication/authorization are part of the web action flow where the user is more explicitly aware of what's happening, what tokens they are sharing, for what privilege, etc.

**Comment by bjustin-ibm** [comment]
> The user should be aware they are in fact authorizing triggers to be fired on their behalf

I agree. Instead, I was trying to point out that I suspect that users won't intuit that an action invocation is happening on their behalf during trigger creation (from a feed), and that it doesn't really benefit them in a practical sense to know this is happening.

**Comment by rabbah** [comment]
To invoke a web action and pass it the auth key is not sufficient. The validation of the key is required - somerwhere. We currently allow the controller to validate this key and pass on the corresponding namespace to the web action if it's valid (and no namespace otherwise). This is done now to allow API experimental to continue to operate as before. There was discussion and agreement to remove this feature although I don't think I noted this in an issue which I shall do.

So the desired `--web` feature discussed herein isn't really just about invoking a web action, you will need also the authorization key for the caller, right? Is the fact that it's part of a feed sufficiently different from say calling an arbitrary API call?

If the issue here is strictly with respect to entitlement (want to grant Activation rights but not CRUD), then should we focus on just solving that problem instead where a web action is just solving that problem for you indirectly? Or is it that a web action is the right solution to this problem and so perhaps we should just require that all feeds implement a web action as a way of handling the trigger life cycle management?

**Comment by bjustin-ibm** [comment]
@rabbah Ahhh... I think I'm starting to see it. Just to be clear, what would be the value of `__OW_API_KEY` if we made the feed action a web action and called it as such from the CLI (as proposed here)? Are you saying that it would be the key for the action owner and not the caller?

**Comment by rabbah** [comment]
That's correct and consistent with the key for web actions today.

**Comment by bjustin-ibm** [comment]
Ok, I have opened #2155 to discuss entitlement changes to allow this. Thanks @rabbah.
