### ISSUE TITLE
Update documentation for ansible usage

### ISSUE THREAD

**Issue by domdom82** [openwhisk/openwhisk#208]
Currently we have two parallel ways of deploying OpenWhisk: ant and ansible.

Once we flip the switch and drop ant, we should have some documentation ready for the users and devs.

Doc should include:

- How ansible works
- How we apply ansible for deployment
- Playbook structure (environments, roles, modes, conventions on variables: a.b vs. a_b)
- How a user can adapt existing or create new environments

User guide should be updated to make the new way of deploying like:

```
ansible-playbook -i env whisk.yml -e mode=initdb
gradle distDocker
ansible-playbook -i env whisk.yml
```

**Comment by mrutkows** [comment]
I've subscribed since we have several blogs (besides READMEs) that we may need to update that reference ant...

**Comment by rabbah** [comment]
I have reviewed the pull requests and tried it myself. I find the ansible commands much more verbose and expect we will want to sugar these to get back to the simplicity of `ant clean build deploy`.
