### ISSUE TITLE
Rewrite the test cases to use rest instead of CLI

### ISSUE THREAD

**Issue by houshengbo** [openwhisk/openwhisk#2135]
Since the Go CLI starts to leave the openwhisk repo, we need to rewrite the test cases for openwhisk by using rest interface to call openwhisk services instead of using CLI.

**Comment by jasonpet** [comment]
why?  won't openwhisk pull the binary as part of deploy?  if not then this breaks a lot of tests in many repos.

**Comment by houshengbo** [comment]
As long as the binaries are copied to the place we specified, there should be no effect on the tests in openwhisk. I will close this issue here. The CLI in the new repo may need tests.

**Comment by rabbah** [comment]
I liked the original thought. The cli tests should move to the cli repo in near future. The tests in this repo should be API based and in fact we should use that as a way of cleaning up and enforcing our swagger compliance.

**Comment by rabbah** [comment]
I won't reopen this issue though because we have another issue for the above which I'll cross link.
