### ISSUE TITLE
WhiskJsonUtils.dictionaryToJsonString takes surprisingly long time

### ISSUE THREAD

**Issue by rabbah** [openwhisk/openwhisk#2144]
I will attach a sample Swift action to demonstrate this (first reported by @meyumeapps); the dictionary to JSON serialization is adding several seconds of execution.

The action follows this pattern:
```
func main(args: [String:Any]) -> [String:Any] {
	let response = <stringified json object>
     	return [ "message" : response ]
}
```

Here's an example:
```
docker exec -it XX bash
cd /swift3Action/spm-build/.build/release
time ./Action
<prints result>
real	0m17.187s
user	0m15.790s
sys	0m0.040s
```

And *without [WhiskJsonUtils.dictionaryToJsonString(jsonDict: result)](https://github.com/openwhisk/openwhisk/blob/master/core/swift3Action/spm-build/WhiskJsonUtils.swift)*, the exec time:

```
real	0m0.026s
user	0m0.000s
sys	0m0.010s
```

Steps to reproduce:
`docker run -p 8080:8080 swift3action` to start a clean container
`core/actionProxy/invoke.py init t.swift` to initialize container directly with test code
`docker exec -it XX bash` to exec into the container
`cd swift3Action/spm-build` and rm `.build/release/Actio` and rerun `./swiftbuildandlink.sh`
`time .build/release/Action` is invariably 12s or more

**Comment by rabbah** [comment]
From @paulcastro: There were bugs in the JSONSerializer class on Linux so we switched to using an external library SwiftyJSON for serdes. Not sure this is the root cause but one thing to try is going back to vanilla JSONSerializer to rule out any strange SwiftyJSON behavior.

**Comment by paulcastro** [comment]
Looks like the culprit is in a recursion processing escaped strings in WhiskJSONUtils.  If I bypass that function I get 

```
real	0m0.025s
user	0m0.010s
sys	0m0.000s
```

**Comment by meyumeapps** [comment]
Just looking at that as well.

**Comment by paulcastro** [comment]
We can bypass the escaped string code using the standard JSONSeralizer class.  We didn't use it before because of a bug that has since been fixed.

Preliminary experiments show this time when using the JSONSerializer:

```
real	0m0.141s
user	0m0.040s
sys	0m0.020s
```

**Comment by paulcastro** [comment]
It's this line that seems to be very slow:
`<String>.replacingOccurrences(of:"\"", with:"\\\"")`
