### ISSUE TITLE
pass the activationId in to the activation

### ISSUE THREAD

**Issue by sjfink** [openwhisk/openwhisk#218]
There are many scenarios where it's useful to have a unique id for an activation accessible at runtime.

The simplest scenario might be just printing debug log messages that we later want to correlate with activation records in whisk.

Proposal: pass the activationId to the activation.   Perhaps expose it in javascript via whisk.getActivationId().

**Comment by mbehrendt** [comment]
i think this should be part of passing the full execution context (mem, name, etc) into an activation - the id being one field.

**Comment by rabbah** [comment]
Actions receive both the deadline and the activation id as of https://github.com/openwhisk/openwhisk/pull/1539.
