### ISSUE TITLE
Mongo use for python actions

### ISSUE THREAD

**Issue by Abiwax** [openwhisk/openwhisk#2181]
Is it possible to have pymongo and watson-developer-cloud packages for the python actions like we have in the Javascript actions, currently we have to run a Docker action to use those packages and because of the 60 second limit on docker actions, saving to mongo fails when saving large documents.

**Comment by csantanapr** [comment]
Hi @Abiwax Which 60 second limit on docker actions are you referring?

60 seconds is just a default.

Actions can run up to 5 minutes for example
```
wsk action create --docker example janesmith/blackboxdemo --timeout 300000
```

Also I would recommend you take a look on using virtualenv to package any 3rd party python libraries in a python zip action, check the docs here https://github.com/openwhisk/openwhisk/blob/master/docs/actions.md#packaging-python-actions-with-a-virtual-environment-in-zip-files

please re-open the issue if I miss understood your problem

**Comment by rabbah** [comment]
@csantanapr We can make for a large set of included python packages, in general, to include a few more popular SDKs. It could make it easier vs venv.

**Comment by csantanapr** [comment]
@rabbah 
I agree, I'm more or a nodejs guy and have a good feeling what are the "more popular" libraries to include.

Take into account that we will update to the latest version at our will at any time to keep it current, so users using them should not be surprised when a lib goes from 1.1.0 to 2.2.0 for example.

I'm OK if @rabbah and @cclauss take stab on picking a few popular libs, we start by matching the nodejs ones but for python.

PS: what about Java and swift? who wants to take on those?

**Comment by rabbah** [comment]
We should do Java on demand IMO or when we have more data that we've analyzed. For Swift maybe @paulcastro has some initial input on feasibility.

**Comment by Abiwax** [comment]
@csantanapr please note that docker actions do not run beyond 60 seconds even with the timeout cap.
Will try the new addition of using virtualenv with python actions instead.

**Comment by rabbah** [comment]
@Abiwax are you doing a blocking invoke? If so, that's true, a request/response must complete in 60s to retrieve the result.

**Comment by Abiwax** [comment]
@rabbah yes, the action is part of a sequence.

**Comment by rabbah** [comment]
Are you on slack.openwhisk.org? If so direct message me.

**Comment by Abiwax** [comment]
thanks @rabbah , will join the the slack team now.
