### ISSUE TITLE
AGET

### ISSUE THREAD

**Issue by Katiyman** [openwhisk/openwhisk#2191]
## Environment details:

* local deployment
* Docker version 17.04.0-ce, build 4845c56
* Ubuntu 16.04

## Steps to reproduce the issue:
while running the openwhisk build locally in Ubuntu I am getting unable to resolve 'github.com'
1.   execute docker build -t controller /home/nokia/openwhisk/core/controller

## Provide the expected results and outputs:

```
build should have been successfull
```

## Provide the actual results and outputs:

```
output comes here
```
Step 8/12 : RUN wget https://github.com/swagger-api/swagger-ui/archive/v2.1.4.tar.gz &&     mkdir swagger-ui &&     tar zxf v2.1.4.tar.gz -C /swagger-ui --strip-components=2 swagger-ui-2.1.4/dist &&     rm v2.1.4.tar.gz &&     perl -pi -w -e  's{http://petstore.swagger.io/v2/swagger.json}{/api/v1/api-docs}g;' /swagger-ui/index.html
 ---> Running in 754b8ca09b5e
--2017-04-27 05:35:41--  https://github.com/swagger-api/swagger-ui/archive/v2.1.4.tar.gz
Resolving github.com (github.com)... 192.30.253.113, 192.30.253.112
Connecting to github.com (github.com)|192.30.253.113|:443... failed: Connection timed out.
Connecting to github.com (github.com)|192.30.253.112|:443... failed: Connection timed out.
Retrying.

## Additional information you deem important:
* I have tried adding proxy server in the /etc/resolv.conf but dint help  
* Also exported HTTP_PROXY and HTTPS_PROXY in the docker file, but this also dint help
* if I do a wget from the directly from the prompt I am able to download the tar

**Comment by markusthoemmes** [comment]
I'm getting the feeling your docker/network setup is broken. This doesn't seem a problem with OpenWhisk itself but with the underlying docker system you use.

Can you run the following please:

```
docker run --rm buildpack-deps:trusty-curl wget https://github.com/swagger-api/swagger-ui/archive/v2.1.4.tar.gz
```

**Comment by Katiyman** [comment]
This is  resolved by adding following changes to the docker file.
RUN export http_proxy=<proxy_host>&& \
    export https_proxy=<proxy_host>&& \
    wget https://github.com/swagger-api/swagger-ui/archive/v2.1.4.tar.gz && \
    mkdir swagger-ui && \
    tar zxf v2.1.4.tar.gz -C /swagger-ui --strip-components=2 swagger-ui-2.1.4/dist && \
    rm v2.1.4.tar.gz && \
    perl -pi -w -e  's{http://petstore.swagger.io/v2/swagger.json}{/api/v1/api-docs}g;' /swagger-ui/index.html
