### ISSUE TITLE
Error while verifying the setup

### ISSUE THREAD

**Issue by Katiyman** [openwhisk/openwhisk#2202]
## Environment details:

* Ubuntu 16.04
* Docker version 17.04.0-ce, build 4845c56
## Steps to reproduce the issue:

1.   Do a build from the cloned git repository
2.   Follow the steps as given in the /tools/Ubuntu-setup/README.md 
3.   After the deployment run the below command to check the working
bin/wsk action invoke /whisk.system/utils/echo -p message hello --result --insecure

## Provide the expected results and outputs:

```
{
    "message": "hello"
}

```

## Provide the actual results and outputs:

```
error: Unable to invoke action 'utils/echo': Post https://172.17.0.1/api/v1/namespaces/whisk.system/actions/utils/echo?blocking=true&result=true: dial tcp 172.17.0.1:443: getsockopt: connection refused
```

## Additional information you deem important:
* I am locally setting up the openwhisk in the Ubuntu for on premise setup

**Comment by markusthoemmes** [comment]
From where are you running the `wsk` command? Inside the VM? (are you even using a VM?)

**Comment by Katiyman** [comment]
yes I am running the Ubuntu VM. 
I am running from the openwhisk home dir as the CLI is inside the bin folder

**Comment by Katiyman** [comment]
if i run this cmd bin/wsk action invoke /whisk.system/utils/echo -p message hello --result
I get the below error.
error: Unable to invoke action 'utils/echo': Post https://172.17.0.1/api/v1/namespaces/whisk.system/actions/utils/echo?blocking=true&result=true: Proxy Timeout ( The connection timed out.  )

**Comment by markusthoemmes** [comment]
In other issues you setup an HTTP Proxy. Could that be the culprit here? I'm assuming you're running the commands inside the Ubuntu VM, or are you running them from your local operating system?

**Comment by Katiyman** [comment]
thnx Mark for the  reply..
I have provided the HTTP and HTTPS proxy both here. by exporting the HTTP_PROXY and HTTPS_PROXY. donno if any thing else to be done for that.
And I am running this command from the inside of the VM

**Comment by Katiyman** [comment]
will revisit the installation and see if this issue reoccurs. closing for now

**Comment by PavaniGedala** [comment]
Me too getting the same error - 
  error: Unable to invoke action 'utils/echo': Post https://172.17.0.1/api/v1/namespaces/whisk.system/actions/utils/echo?blocking=true&result=true: dial tcp 172.17.0.1:443: getsockopt: connection refused.
