### ISSUE TITLE
document the environment variable WSK_CONFIG_FILE for wsk CLI

### ISSUE THREAD

**Issue by csantanapr** [openwhisk/openwhisk#225]
Document `WSK_CONFIG_FILE` for CLI

if env variable doesn't exist $HOME/.wskprops is used

**Comment by csantanapr** [comment]
@dubeejw @mdeuser Do we have this feature cover in new go-CLI? handling the environment variable?

**Comment by rabbah** [comment]
@csantanapr we do. Just need doc.
