### ISSUE TITLE
confusing error message on trying to create rule with shared action

### ISSUE THREAD

**Issue by csantanapr** [openwhisk/openwhisk#239]
Trying this in the CLI

```
$ wsk rule create ifGitThenEcho myGitTrigger /whisk.system/samples/echo
error: The request content was malformed:
entity name malformed (code 1385580)
```

In `wsk rule create name trigger action` trigger or action can't be private
User needs to copy the action to his space like

```
$ wsk action create echo --copy /whisk.system/samples/echo
ok: created action echo
```

CLI error should be more clear about this and the [docs](https://github.com/openwhisk/openwhisk/blob/master/docs/triggers_rules.md#using-rules-to-associate-triggers-and-actions) should be updated to reflect this

**Comment by rabbah** [comment]
The trigger and action that make a rule must be in the default package, which is in fact *private*. The docs should state this, you are right, and the API/CLI should report a better error message.

We plan to relax the noted constraint so that you can create a rule using an action in a package.

**Comment by rabbah** [comment]
@markusthoemmes this will need to be addressed as part of the activator work.

**Comment by lzbj** [comment]
@rabbah , is the default package means the system package or the package under the user namespace? I searched under the doc seems not mentioned this.
After the relax the constraint, is that user can create rule no matter the package or action is private or not?

**Comment by kurtismgit** [comment]
I'm a new OpenWhisk user (1 week or so) and hit this pretty quickly.  As you know the error wasn't helpful.  Found myself searching through github issues to figure out about this limitation.  Definitely have my vote for fixing it.

**Comment by sjfink** [comment]
not sure why this was closed -- still can't have package actions in rules AFAIK.

**Comment by csantanapr** [comment]
don't think is fix
```
$ wsk rule create r1 t1 /whisk.system/samples/echo
error: Unable to create rule 'r1': Request failure: The request content was malformed:
entity name malformed (code 35142)
```

**Comment by csantanapr** [comment]
current workarounds are 
1. put the action inside a sequence
2. copy the action to the namespace outside of a package
example for 1. :
```
$ wsk action create --sequence s1 /whisk.system/samples/echo,/whisk.system/samples/echo
ok: created action s1
$ wsk rule create r1 t1 s1
ok: created rule r1
```

**Comment by sjfink** [comment]
I was trying for this in my free time, but now I'm scared because I think it's a schema change -- it appears we'll have to store QualfiedNames in Rule entities, and I'm scared to do schema changes by myself.

Assigning to @rabbah since he's mentioned this was "easy".

**Comment by markusthoemmes** [comment]
It is not a schema change per-se. This can be solved incrementally.

As you noted, we'll need to store fully-qualified names instead of "just" the entity name. We'll also need to be able to disambiguate "old" entries (with just the entity name) and "new" entries (with the FQN).

Chances are, this detection is today a simple `name.contains("/")`.

**Comment by skaegi** [comment]
Currently am using a --sequence to work-around this and understand the problem however this is a  usability problem I run into every single time I use OpenWhisk

**Comment by rabbah** [comment]
Ok this is long overdue, I'll address shortly.

**Comment by rabbah** [comment]
@markusthoemmes and I reviewed necessary changes and he's on it.

**Comment by rabbah** [comment]
Adding @ioana-blue - the changes she'll be making for the entitlement interface for sequences will be directly useful to address this issue: for a rule, resolve its references resources and check the corresponding rights for a given subject.

**Comment by rabbah** [comment]
Closed by commits in referenced prs.

**Comment by csantanapr** [comment]
@rabbah we should update the docs
>The trigger and action that make a rule must be in the same namespace and cannot belong to a package. If you want to use an action that belongs to a package, you can copy the action into your namespace. For example: wsk action create echo --copy /whisk.system/utils/echo.
