### ISSUE TITLE
issue in swagger with TriggerLimits

### ISSUE THREAD

**Issue by cjolif** [openwhisk/openwhisk#241]
"TriggerLimits": {
            "description": "Limits on a specific trigger"
        },

I think it should have "type": "object" as it apparently returns arbitrary json?

**Comment by cjolif** [comment]
reference: https://github.com/openwhisk/openwhisk/blob/master/core/controller/src/resources/whiskswagger.json

**Comment by markusthoemmes** [comment]
Thanks for catching you're absolutely right
