### ISSUE TITLE
remove endTime from trigger activation records

### ISSUE THREAD

**Issue by sjfink** [openwhisk/openwhisk#245]
It would be nice to be able to simply determine that an activation record in cloudant represents a trigger and not an action.

As discussed with @rabbah , I propose that the endTime attribute be elided from trigger activation records.

This is logically (though not structurally) a schema-breaking change.   I think only reporting code would be affected, and this code is not yet written.

**Comment by rabbah** [comment]
Should also do this for a rule activation.

**Comment by mbehrendt** [comment]
> that an activation record in cloudant represents a trigger and not an action.

in whisk terminology, an activation results from the invocation of an action. why would an activation record represent a trigger? are we maybe overloading the term activation with multiple semantics?

**Comment by sjfink** [comment]
yes, we should discuss the terminology, especially pertaining to user-visible terms.

**Comment by sjfink** [comment]
current proposal on terminology:   an activation can refer to an action, a trigger, or a rule.

**Comment by rabbah** [comment]
Introducing another term to refer to an activation of a trigger and/or a rule is unnecessary. Generally (And this is consistent with the API and implementation) an activation of a trigger is analogous with "firing" a trigger. And an activation of a rule means that matching of a trigger to a rule, causing an action to be invoked. Just as well equate "invoke" with activating an action, we can equate "fire" of a trigger with an activation of the trigger and possibly a rule.

The causality of activations chains can also be tracked and we expect this will be helpful in the future - one can build a graph of the activations with edge representing activation causality.

We currently show activations of triggers, rules and actions in `wsk activation poll` and `wsk activation list`. What we are missing is the "type" annotation on the activation and adding this will make it clear which kind of activation occurred.

**Comment by mbehrendt** [comment]
that is fine with me as a baseline, but two items i think need to be refined:
- so far, all our collateral has been referring to an activation being equal to an invocation of an action. the rule & trigger flavor has never been discussed.
- we'll have to often talk about activations in the 'action invocation' sense. using the term 'action activation' seems very clunky, we should look for a short version here (so far that has been activation, but that is now overloaded)

**Comment by rabbah** [comment]
Intuition tells me activation will (has) quite often mean (meant) action activation and having to qualify it is not necessary. Introducing another term to disambiguate widens the vocabulary unnecessarily when, where necessary, one can qualify the type of activation as needed. For example, `wsk activation poll` shows the type - surely if we referred to activations of different types by different names, you would not use the same CLI command, for example, since that would certainly then be confusing.

**Comment by mbehrendt** [comment]
i think we need to consider that using 'activation' for various flavors implies a degree of commonality across action/rule/trigger activations which is not necessarily the case. eg an action activation has a duration, begin and end time, which trigger & rule activations do not have. so need to be careful to not confuse people about commonality of attributes which is not there in reality.

**Comment by rabbah** [comment]
The commonality is real today - they all have `begin` and `end` times. It's the case for triggers and rules that their activations are "instantaneous" hence `start = end`.

**Comment by mbehrendt** [comment]
we might be filling out these fields, but in reality it's hard to see a case where start != end time and where duration != 0.

**Comment by mbehrendt** [comment]
a trigger and rules activation is just a moment in time, while an action activation always takes time.

**Comment by rabbah** [comment]
> but in reality it's hard to see a case where start != end time and where duration != 0.
> a trigger and rules activation is just a moment in time, while an action activation always takes time.

We agree then, don't we?

**Comment by sjfink** [comment]
As discussed with @rabbah , I will send end = 0L for triggers and rules.

**Comment by sjfink** [comment]
pushed
