### ISSUE TITLE
Fix invoker to survive reboots

### ISSUE THREAD

**Issue by jeremiaswerner** [openwhisk/openwhisk#253]
we noticed that the invoker did not restart with automatically after a VM reboot. we do set the docker.restart.opts for each container so we should do for invoker as well.

when doing this, it's important that the invoker also recovers the numbers that are required for the calculation of the queue. we see that the loadbalancer is out of sync when the invoker restarts.

**Comment by perryibm** [comment]
This work is completed and merged.  The various counts are now reset and this was tested at least once by @markusthoemmes in a deployed system.
