### ISSUE TITLE
Add ws and socket.io-client to nodejs image

### ISSUE THREAD

**Issue by markusthoemmes** [openwhisk/openwhisk#268]
As pointed out in this [stackoverflow question](http://stackoverflow.com/questions/36834130/openwhisk-socket-io-client-possible) it could be a very common usecase to push to a websocket via an action. We should add at least [ws](https://www.npmjs.com/package/ws) and [socket.io-client](https://www.npmjs.com/package/socket.io-client) (the socket.io package, which is already included doesn't seem to be able to act as a client solely)

**Comment by bjustin-ibm** [comment]
Merged with 364e61ad03372eb80e0ba2b09e18df8b09e8859f

**Comment by bjustin-ibm** [comment]
@markusthoemmes Perhaps we should add a comment to the SO question saying that this change is making its way to Production?
