### ISSUE TITLE
docs should be clear on how to update docker actions

### ISSUE THREAD

**Issue by csantanapr** [openwhisk/openwhisk#280]
The docs should make it clear to the user that in addition of re-building and re-pushing the docker image, it also need to run `wsk action update` to make the system fetch the new image, and any new invocation to start using the new image and not a warm image with the old code.

**Comment by daisy-ycguo** [comment]
It has dependency on #74.

According to #74, dockerSkeleton is not available in OpenWhisk yet. I'm not able to run docker actions now. l have to wait for #74 fixed.

**Comment by daisy-ycguo** [comment]
I removed myself from the assignees. If someone else is able to change the doc, please work on it.
