### ISSUE TITLE
Epic: Tutorial and samples parity with Swift - Umbrella

### ISSUE THREAD

**Issue by csantanapr** [openwhisk/openwhisk#282]
This is an umbrella issues to capture all the requirements/issues 

This Swift actions need to be able to run on Swift 2.2 which is the current runtime supported in openwhisk

- [ ] #188 Add catalog actions for swift to have parity with nodejs current in [catalog/samples](https://github.com/openwhisk/openwhisk/tree/master/catalog/samples)
- [ ]  #284 Add catalog actions for swift to have parity with nodejs current in [catalog/utils](https://github.com/openwhisk/openwhisk/tree/master/catalog/utils)

**Comment by bjustin-ibm** [comment]
@csantanapr we're going to need some details about what is currently in the Swift runtime. Language version, available frameworks, etc.

**Comment by csantanapr** [comment]
@bjustin-ibm Yep, what we have today is swift 2.2 is listed in the docs, and you get default frameworks.

@paulcastro is driving to move to swift 3 and have some frameworks pre-installed in the runtime, like a kitura components to be able to do http/networking, and any other one that we need to add for the samples

I think we can start working on the simple actions like greetings that don't require frameworks and will work on swift 2.2 or 3, to get a head start and give a chance for swift 3 to get it in.

**Comment by rabbah** [comment]
should take the opportunity to clean up the catalog and samples and rename some of those files as well (can you tell what is `wcbin`'s purpose is - without looking at its code).

**Comment by paulcastro** [comment]
Just to confirm, as a stop-gap I'm looking into installing KituraNet as a framework to do network calls for Swift actions.  I already have an image for Swift 3.

**Comment by csantanapr** [comment]
@paulcastro the stop-gap is for swift 2? I think we should just go forward with Swift 3 if you already have it ready and not bother with Swift 2, team can use a docker image for develop the new swift actions

**Comment by csantanapr** [comment]
I think we should will skip [github/webhook.swift](https://github.com/openwhisk/openwhisk/blob/master/catalog/github/webhook.js) for now.
Since it's just a provider to setup the trigger to be invoke via webhook, and not an example the user will copy and modify to adjust to his need.
What others think?

**Comment by paulcastro** [comment]
The stopgap requires Swift 3, but that version of Swift does not have stable APIs yet.  I'd recommend keeping Swift 2 as our default and only moving to Swift 3 when it is stable.

**Comment by csantanapr** [comment]
Closing Epic, as children issues for Swift are done
