### ISSUE TITLE
Add swift actions to have parity with nodejs current in catalog/slack

### ISSUE THREAD

**Issue by csantanapr** [openwhisk/openwhisk#283]
Add catalog actions for swift to have parity with nodejs current in [catalog/slack](https://github.com/openwhisk/openwhisk/tree/master/catalog/slack)

Implement
- [ ] slack/post.swift

**Comment by sjfink** [comment]
I recommend we do not do this.   My reasons are twofold: 1) I don't want to have 2 slack  implementations to maintain, and 2) it will be a long time before Swift supports networking needed to implement this.

I recommend closing as "won't fix".
