### ISSUE TITLE
Add actions for swift to have parity with nodejs current in catalog/utils

### ISSUE THREAD

**Issue by csantanapr** [openwhisk/openwhisk#284]
Add catalog actions for swift to have parity with nodejs current in [catalog/utils](https://github.com/openwhisk/openwhisk/tree/master/catalog/utils)

- [ ] cat.swift
- [ ] date.swift
- [ ] head.swift
- [ ] pipe.swift
- [ ] sort.swift

**Comment by sjfink** [comment]
Since these are small, self-contained actions, I think it's reasonable to implement them in swift as tutorial examples.
