### ISSUE TITLE
Add catalog actions for swift to have parity with nodejs current in catalog/watson

### ISSUE THREAD

**Issue by csantanapr** [openwhisk/openwhisk#285]
Add catalog actions for swift to have parity with nodejs current in [catalog/watson](https://github.com/openwhisk/openwhisk/tree/master/catalog/watson)

- [ ] translate.swift
- [ ] languageId.swift

**Comment by sjfink** [comment]
I recommend we do not do this.   My reasons are twofold: 1) I don't want to have 2 watson implementations to maintain, and 2) it will be a long time before Swift supports networking needed to implement this.

I recommend closing as "won't fix".
