### ISSUE TITLE
Add catalog actions for swift to have parity with nodejs current in [catalog/weather]

### ISSUE THREAD

**Issue by csantanapr** [openwhisk/openwhisk#286]
Add catalog actions for swift to have parity with nodejs current in [catalog/weather](https://github.com/openwhisk/openwhisk/tree/master/catalog/weather)

- [ ]  forecast.swift

Using the new implementation that @nwspeete-ibm  is doing in nodejs with the IBM Weather Insights using twcweather

Do not do pollen, since there is no way to get a api key for get pollen with the current nodejs implementation, we need to find a new api provider that give us pollen data, if anyone knows of such source it's welcome to gives us the info.

**Comment by sjfink** [comment]
I recommend we do not do this.   My reasons are twofold: 1) I don't want to have 2 weather action implementations to maintain, and 2) it will be a long time before Swift supports networking needed to implement this.

I recommend closing as "won't fix".
