### ISSUE TITLE
Getting Exception:  'NoneType' object has no attribute '__getitem__' on wks and wskadmin commands

### ISSUE THREAD

**Issue by mdcarlson** [openwhisk/openwhisk#29]
On my Macbook, I followed the instructions for 'Vagrant cheat sheet (for Mac and Windows)' and 'Ubuntu cheat sheet'

My `vagrant up --provider=virtualbox` command completed successfully and I can `vagrant ssh` into the box.

When I attempt to execute the `wskadmin` command to create a new subject, I am getting an error of `

    Exception:  'NoneType' object has no attribute '__getitem__'

I get the same error when I install the command line tools on my Mac and attempt to run a wks command such as: 

    wsk property set --apihost 192.168.33.13 --auth $(cat config/keys/auth.guest)
    Exception:  'NoneType' object has no attribute '__getitem__'   

Any pointers?

--Mark

**Comment by rabbah** [comment]
Hi Mark, can you rerun the wskadmin command with `--verbose` and report the stack trace? You may get to see a more meaningful error with `--verbose`.

**Comment by mdcarlson** [comment]
Verbose output shows the following: 

    wsk -v property set --apihost 192.168.33.13 --auth $(cat config/keys/auth.guest)
    Exception:  'NoneType' object has no attribute '__getitem__'
    Traceback (most recent call last):
      File "/Users/mcarlson/workspace/openwhisk/bin/wsk", line 53, in main
        apihost = resolveOverrides(whiskprops['CLI_API_HOST'], userprops.get('APIHOST'), args.apihostOverride)
    TypeError: 'NoneType' object has no attribute '__getitem__'

**Comment by rabbah** [comment]
Which python version are you running on your mac? It should be 2.7+.

**Comment by mdcarlson** [comment]
python --version
    Python 2.7.11

**Comment by rabbah** [comment]
Thanks - reproduced. Here's a workaround (on your Mac):

```
cat openwhisk/tools/cli/default.props 
CLI_API_HOST=192.168.33.13
WHISK_VERSION_DATE=2016-02-28T00:16:32:z
```

**Comment by mdcarlson** [comment]
Workaround of creating default.props file allowed the `wsk` commands to proceed.
