### ISSUE TITLE
Cannot set apihost via CLI

### ISSUE THREAD

**Issue by nauerz-ibm** [openwhisk/openwhisk#291]
Error I get is:

```
whisky@openwhisk:~/openwhisk/bin$ ./wsk property set --apihost localhost
error: API host is not set. Set it with "wsk property set --apihost <host>".
```

**Comment by rabbah** [comment]
@nauerz-ibm `wsk property  get --cliversion` please.

**Comment by nauerz-ibm** [comment]
I've already cleaned-up my previous system.
But I used the latest version (downloaded it yesterday) from openwhisk/bin.

**Comment by domdom82** [comment]
I think I know this one:

https://github.com/openwhisk/openwhisk/blob/master/tools/cli/wsk#L69

It says 
```
args.subcmd != 'get'):
```

but it should say

```
args.subcmd != 'set'):
```

because we want to set the apihost.

**Comment by rabbah** [comment]
you're right @domdom82 - our test doesn't cover the case of a broken CLI build. If the `default.props` wasn't configured during the build, it will surface this bug.
