### ISSUE TITLE
Cannot install via Vagrant (latest version) under Windows even though this is supposed to work per documentation

### ISSUE THREAD

**Issue by nauerz-ibm** [openwhisk/openwhisk#292]
Per documentation:
https://github.com/openwhisk/openwhisk#vagrant-users-for-mac-and-windows

Some guys from development told me Vagrant under Windows would not be supported; but if this is the case I wonder the documentation tells something different?

Error I get is:

```
Stderr: 0%...
Progress state: E_INVALIDARG
VBoxManage.exe: error: Failed to create the host-only adapter
VBoxManage.exe: error: Assertion failed: [!aInterfaceName.isEmpty()] at 'F:\tind
erbox\win-5.0\src\VBox\Main\src-server\HostNetworkInterfaceImpl.cpp' (74) in lon
g __cdecl HostNetworkInterface::init(class com::Bstr,class com::Bstr,class com::
Guid,enum __MIDL___MIDL_itf_VirtualBox_0000_0000_0036).
VBoxManage.exe: error: Please contact the product vendor!
VBoxManage.exe: error: Details: code E_FAIL (0x80004005), component HostNetworkI
nterfaceWrap, interface IHostNetworkInterface
VBoxManage.exe: error: Context: "enum RTEXITCODE __cdecl handleCreate(struct Han
dlerArg *)" at line 71 of file VBoxManageHostonly.cpp
```

**Comment by rabbah** [comment]
@nauerz-ibm This seems like a Vagrant issue specific to your Windows machine, see https://www.virtualbox.org/ticket/15019.  The instructions assume you can run a Vagrant machine on your native host.

**Comment by nauerz-ibm** [comment]
Will try again tomorrow after having cleaned-up everything; will report the results here.

**Comment by csantanapr** [comment]
team members with Windows computers are working with Vagrant using new share folder flow. If you see problems in Windows please open a new issue.
