### ISSUE TITLE
ant clean build deploy needs to be run several times until it succeeds

### ISSUE THREAD

**Issue by nauerz-ibm** [openwhisk/openwhisk#293]
Yes, I know that this is even documented, but due to the fact that the entire process fails multiple times until it succeeds it takes hours to go through the setup process; this is unacceptable from a user-experience point of view. We need to improve.

**Comment by rabbah** [comment]
Did you try this tip from the docs? 

**Tip:** By default, each docker command will timeout after 240 seconds (4 minutes). If you're on a really slow connection, this might be too short. You can modify the timeout value in docker.gradle as needed.

**Comment by nauerz-ibm** [comment]
I just tried rerunning the process by over and over again running ant build - that is what the documentation suggests, too:

> Tip: Since the first build takes some time, it is not uncommon for some step to fail if there's a network hiccup or other interruption of some kind. If this happens you may see a Build FAILED message that suggests a Docker operation timed out. You can simply try ant build again and it will mostly pick up where it left off. This should only be an issue the very first time you build -- subsequent builds do far less network activity thanks to Docker caching.

Even though that finally worked and even though your proposal may help a bit, too, I think we need to improve to provide a much better user-experience (I know you guys are working hard... maybe this is something Matt & team can work on that)...

**Comment by rabbah** [comment]
closing as no longer valid.
