### ISSUE TITLE
Request to restart machine when installing under Ubuntu is not documented

### ISSUE THREAD

**Issue by nauerz-ibm** [openwhisk/openwhisk#294]
@markusthoemmes mentioned that one has to restart the machine after having followed the instructions here: https://github.com/openwhisk/openwhisk#ubuntu-users

Is this really the case?
If so, the documentation needs to be updated accordingly.

**Comment by rabbah** [comment]
@nauerz-ibm my understanding is that you are on a virtual box VM not a native ubuntu. Is that correct?

**Comment by nauerz-ibm** [comment]
That is correct.
@markusthoemmes said that a restart is necessary after the above mentioned steps - and indeed the restart helped to circumvent some initial issues. So if it is required we should update the doc.

**Comment by rabbah** [comment]
@csantanapr since you've worked on flow/installation process, is this still valid?

**Comment by csantanapr** [comment]
@rabbah not sure if a restart is required for ubuntu, I have not tried the ubuntu steps my self recently.

**Comment by csantanapr** [comment]
no need to restart, docker is ready after installation
