### ISSUE TITLE
Invoking actions via the CLI leads to connection refused errors

### ISSUE THREAD

**Issue by nauerz-ibm** [openwhisk/openwhisk#296]
Error I get:

```
whisky@openwhisk:~/openwhisk$ wsk action invoke /whisk.system/samples/echo -p message hello --blocking --result
error: [Errno 111] Connection refused
```

**Comment by rabbah** [comment]
Assuming you are running against a local deployment, your deployment is actually not up. This may be a duplicate of https://github.com/openwhisk/openwhisk/issues/31#issuecomment-190015793.

**Comment by nauerz-ibm** [comment]
Indeed this looks like the same issue.
What I wonder is: Why is that happening even though I followed the instructions step by step?

Proposal: Let me see if I can reproduce the issue tomorrow after having properly cleaned-up everything. Maybe I tried too many different things finally leading to a totally screwed system.

**Comment by nauerz-ibm** [comment]
Cannot reproduce this atm; let's close for now and reopen if it happens again.
