### ISSUE TITLE
wskadmin create user testuser returns "Database does not exist error:

### ISSUE THREAD

**Issue by mdcarlson** [openwhisk/openwhisk#30]
I have successfully created a Cloudant db and can interact with it from cURL and form Chrome using jsonview.

When I attempt to create a new subject using `wskadmin` I get a "Database does not exist error"

    wskadmin -v user create testuser1
    using CLOUDANT_PASSWORD = xxxxxxxx
    using CLOUDANT_USERNAME = yyyyyyyy
    using CLOUDANT_WHISK_AUTHS = <<auth.guest content>>

    ========
    REQUEST:
    POST http://xxxxxxxx.cloudant.com/23bc46b1-71f6-4ed5-8c54-816aa4f8c502:123zO3xZCLrMN6v2BKK1dXYFpXlPkccOFqm12CdAsMgRU4VrNZ9lyGVCGuMDGIwP
    Headers sent:
    {
        "Authorization": "Basic xxxxxxxxMhQ2xvdWRhbnQ=",
        "Content-Type": "application/json"
    }
    Body sent:
    {"_id": "testuser1", "uuid": "0d9292a2-2b1e-4e6c-84c9-c95dc2d23581", "key": "g6u7ryrkEVqWEE3nfFRosAXdLKZMX42D66f5fcEKCAuKq25RxNz1JhYyC1H7oO4X", "subject": "testuser1"}
    --------
    RESPONSE:
    Got response with code 404
    Body received:
    {"error":"not_found","reason":"Database does not exist."}

    ========
    Failed to create subject ({"error":"not_found","reason":"Database does not exist."})

Thanks!

**Comment by rabbah** [comment]
Did you run the script `tools/cloudant/createImmortalDBs.sh <cloudant username> <cloudant password>`? And did you do an `ant clean build deploy` already?

I see one thing that looks out of order in your wskadmin command:

> using CLOUDANT_WHISK_AUTHS=...

the right hand side of this assignment should be "subjects" not a key as your output shows.

**Comment by mdcarlson** [comment]
Changing the value of the CLOUDANT_WHISK_AUTHS property to `subjects` was the fix.  Thanks

**Comment by rabbah** [comment]
Great. Note that you shouldn't have to modify these settings manually as they're generated during the deploy process.

**Comment by mdcarlson** [comment]
The instructions in the "Ubuntu Users" section shows running two bash commands to set two of the properties in the config file.  The `CLOUDANT_WHISK_AUTH` property is not mentioned in the instructions, but the requirement for it is shown as an error message when running `wskadmin`.

    # create cloudant configuration file
    echo "OPEN_WHISK_DB_USERNAME=<cloudant username>" > cloudant-local.env
    echo "OPEN_WHISK_DB_PASSWORD=<cloudant password>" >> cloudant-local.env

**Comment by rabbah** [comment]
Thanks for the added explanation - I'll improve the docs. You have to run `ant build` at least once to generate whisk.properties before you can use wskadmin. If you don't your configuration will fail to validate with this error message:

```
$ rm openwhisk/whisk.properties
$ wskadmin user create testuser1
property "CLOUDANT_PASSWORD" not found in environment or property file
property "CLOUDANT_USERNAME" not found in environment or property file
property "CLOUDANT_WHISK_AUTHS" not found in environment or property file
```
