### ISSUE TITLE
wsk commands return "[Errno 111] Connection refused"

### ISSUE THREAD

**Issue by mdcarlson** [openwhisk/openwhisk#31]
After a successful build in a Vagrant container, I am getting 

    wsk --verbose list
    {'apihost': '172.17.0.1:443', 'namespace': '_', 'clibuild': '2016-02-28T08:53:30-05:00', 'apiversion': 'v1'}
    ========
    REQUEST:
    GET https://172.17.0.1:443/api/v1/namespaces/_
    Headers sent:
    {}
    error: [Errno 111] Connection refused

The box has the following interfaces configured:

    ifconfig | grep 'inet addr'
          inet addr:172.17.0.1  Bcast:0.0.0.0  Mask:255.255.0.0
          inet addr:10.0.2.15  Bcast:10.0.2.255  Mask:255.255.255.0
          inet addr:192.168.33.13  Bcast:192.168.33.255  Mask:255.255.255.0
          inet addr:127.0.0.1  Mask:255.0.0.0

The same error is returned when directing wsk commands to the 192.168.33.13 address from outside the VM.

[whisk.properties.txt](https://github.com/openwhisk/openwhisk/files/149948/whisk.properties.txt)

The sanitized whisk.properties file is attached.

Any pointers?

**Comment by rabbah** [comment]
suspect the router failed in your vagrant machine.
```
$ docker ps | grep nginx
```

if that returns nothing
```
$ ls -l /tmp | grep nginx
```

if that shows that nginx is owned by root, remove it.

```
vagrant@rr-wsk:~/openwhisk$ sudo rm -rf /tmp/nginx/
```

then `ant teardown deploy` and try again.

**Comment by mdcarlson** [comment]
Great.  Will try these steps this afternoon.

**Comment by mdcarlson** [comment]
I completely tore down the Vagrant box  (`vagrant destroy` + `vagrant box remove ubuntu/trusty64-2`) and then reinstalled from scratch following the steps in the `Build and deploy OpenWhisk` section.

I can successfully create a new subject using`wskadmin` and can set the `apihost` property on the command line with no errors.

However, when I attempt to run the sample action, I am still getting connection refused:

wsk --verbose action invoke /whisk.system/samples/echo -p message hello --blocking --result
    {'apihost': '192.168.33.13:443', 'namespace': '_', 'clibuild': '2016-02-28T19:03:52-05:00', 'apiversion': 'v1'}
    ========
    REQUEST:
    POST https://192.168.33.13:443/api/v1/namespaces/whisk.system/actions/samples/echo?blocking=true
    Headers sent:
    {
        "Authorization": "Basic YzUyYzJmZTgtODU4Mi00MjdmLWE3NDItZTg3NGJkMmYyMDJmOjFEUUJtVW9UdklQT2hsaWdodVhrMXJDSkdlS0x1V28zaW5QV1lHMnp0am5iQWFQYTFNVGhMa0xmMmpPWGpQSG8=",
        "Content-Type": "application/json"
    }
    Body sent:
    {"message": "hello"}
    error: [Errno 111] Connection refused

`docker ps` shows no results at all.  No running containers.
`ls -lah /tmp` does not show any nginx folders at all.

Not sure how to proceed.

Thanks for looking.

**Comment by sjfink** [comment]
Could you run 'ant clean build deploy >& /tmp/x' and attach /tmp/x here?

**Comment by rabbah** [comment]
note: scrub the file for any cloudant password.

**Comment by mdcarlson** [comment]
Will do.  Back in an hour.

**Comment by rabbah** [comment]
If it helps - this is the output of `docker ps` inside a clean vagrant machine I just created. So there was a failure in your case to either build or deploy. The logs will helps us diagnose what went wrong and improve the process. Thanks for your help and patience.

```
$ docker ps
CONTAINER ID        IMAGE                       COMMAND                  CREATED             STATUS              PORTS                                                                                                              NAMES
87a6405b714e        whisk/dispatcher:latest     "/startDispatcher.sh "   4 minutes ago       Up 4 minutes        0.0.0.0:12001->8080/tcp                                                                                            invoker0
cf1f1d0ed79a        whisk/loadbalancer:latest   "/startLoadBalancer.s"   4 minutes ago       Up 4 minutes        0.0.0.0:10003->8080/tcp                                                                                            loadbalancer
cfd15f5e26e3        whisk/dispatcher:latest     "/startDispatcher.sh "   4 minutes ago       Up 4 minutes        0.0.0.0:12000->8080/tcp                                                                                            activator
c5e96cc52cb1        whisk/controller:latest     "/startController.sh"    4 minutes ago       Up 4 minutes        0.0.0.0:10001->8080/tcp                                                                                            controller
e7d9ad87eeae        gliderlabs/registrator      "/bin/registrator -ip"   4 minutes ago       Up 4 minutes                                                                                                                           registrator
f85bf6923075        whisk/consul:latest         "/startconsulserver.s"   4 minutes ago       Up 4 minutes        8000/tcp, 53/udp, 8080/tcp, 8301-8302/tcp, 8301-8302/udp, 8400/tcp, 0.0.0.0:8500->8500/tcp, 0.0.0.0:8600->53/tcp   consulserver
6298c63f8a03        whisk/kafka:latest          "/start.sh"              5 minutes ago       Up 5 minutes        7203/tcp, 0.0.0.0:9092->9092/tcp, 0.0.0.0:9093->8080/tcp                                                           kafka
5ef6a2fcff67        whisk/zookeeper:latest      "/opt/zookeeper/bin/z"   5 minutes ago       Up 5 minutes        2888/tcp, 3888/tcp, 8080/tcp, 0.0.0.0:2181->2181/tcp                                                               zookeeper
212271a5a939        nginx                       "nginx -g 'daemon off"   5 minutes ago       Up 5 minutes        0.0.0.0:80->80/tcp, 0.0.0.0:443->443/tcp, 0.0.0.0:8443->8443/tcp      
```

**Comment by mdcarlson** [comment]
Attached.

[openwhisk.build.log.txt](https://github.com/openwhisk/openwhisk/files/150287/openwhisk.build.log.txt)

Running the sample action now produces a different result:

    wsk -v action invoke /whisk.system/samples/echo -p message hello --blocking --result
    {'apihost': '192.168.33.13:443', 'namespace': '_', 'clibuild': '2016-02-28T20:51:47-05:00', 'apiversion': 'v1'}
    ========
    REQUEST:
    POST https://192.168.33.13:443/api/v1/namespaces/whisk.system/actions/samples/echo?blocking=true
    Headers sent:
    {
        "Authorization": "Basic YzUyYzJmZTgtODU4Mi00MjdmLWE3NDItZTg3NGJkMmYyMDJmOjFEUUJtVW9UdklQT2hsaWdodVhrMXJDSkdlS0x1V28zaW5QV1lHMnp0am5iQWFQYTFNVGhMa0xmMmpPWGpQSG8=",
        "Content-Type": "application/json"
    }
    Body sent:
    {"message": "hello"}
    --------
    RESPONSE:
    Got response with code 502
    Body received:
    <html>
    <head><title>502 Bad Gateway</title></head>
    <body bgcolor="white">
    <center><h1>502 Bad Gateway</h1></center>
    <hr><center>nginx/1.9.11</center>
    </body>
    </html>

    ========
    error: connection failed or timed out

Results of `docker ps`

    docker ps
    CONTAINER ID        IMAGE                    COMMAND                  CREATED             STATUS              PORTS                                                                                                              NAMES
    dc4bac9de51f        19cb05bc7dbd             "/startDispatcher.sh "   58 minutes ago      Up 58 minutes       0.0.0.0:12001->8080/tcp                                                                                            invoker0
    38dfbc98c30e        aa18164df72d             "/startLoadBalancer.s"   58 minutes ago      Up 58 minutes       0.0.0.0:10003->8080/tcp                                                                                            loadbalancer
    2f399fef8a52        19cb05bc7dbd             "/startDispatcher.sh "   58 minutes ago      Up 58 minutes       0.0.0.0:12000->8080/tcp                                                                                            activator
    d3a59e3788bc        cdc281a58aa6             "/startController.sh"    58 minutes ago      Up 58 minutes       0.0.0.0:10001->8080/tcp                                                                                            controller
    af9ec87c23e0        gliderlabs/registrator   "/bin/registrator -ip"   58 minutes ago      Up 58 minutes                                                                                                                          registrator
    8d85b47cbcf4        whisk/consul:latest      "/startconsulserver.s"   58 minutes ago      Up 58 minutes       8000/tcp, 8080/tcp, 53/udp, 8301-8302/tcp, 8301-8302/udp, 8400/tcp, 0.0.0.0:8500->8500/tcp, 0.0.0.0:8600->53/tcp   consulserver
    f21efa06ec14        whisk/kafka:latest       "/start.sh"              59 minutes ago      Up 59 minutes       7203/tcp, 0.0.0.0:9092->9092/tcp, 0.0.0.0:9093->8080/tcp                                                           kafka
    3e1156e8b626        whisk/zookeeper:latest   "/opt/zookeeper/bin/z"   59 minutes ago      Up 59 minutes       2888/tcp, 3888/tcp, 0.0.0.0:2181->2181/tcp, 8080/tcp                                                               zookeeper
    e3d3fc9c9be1        nginx                    "nginx -g 'daemon off"   59 minutes ago      Up 59 minutes       0.0.0.0:80->80/tcp, 0.0.0.0:443->443/tcp, 0.0.0.0:8443->8443/tcp                                                   nginx

**Comment by rabbah** [comment]
The log you attached shows the controller failed to start up: "controller is not responding." And this would explain the bad gateway failure. 

How much RAM Does your Mac have?

**Comment by mdcarlson** [comment]
8GB.  Approx 1.5GB free.

**Comment by rabbah** [comment]
try manually restarting the controller only:

```
docker rm -f controller
ant -f openwhisk/core/controller/build.xml startController
```

then run `wsk list` it should respond with

```
$ wsk list
entities in namespace: default
packages
actions
triggers
rules
```

if that works, you can invoke the action again.

**Comment by rabbah** [comment]
If the previous works, I suggest this `ant clean build deploy -Dbuildthreads=1`

**Comment by mdcarlson** [comment]
That worked.    

@rabbah is the suggestion to specify the number of buildThreads something that I need to do now or just if I have to rebuild again in the future?

**Comment by rabbah** [comment]
I'm suspecting that the parallel builds and deploys are stressing the vms and the containers are slow to come up and respond. If with 1 build thread you're able to reliably bring up and deploy the system, you can create a custom config file that overrides the parameter so you don't have to type it regularly. I will post instructions here once you confirm that improves your build/deploy cycle.

**Comment by mdcarlson** [comment]
OK, I'll kick that off shortly and capture the output.

**Comment by mdcarlson** [comment]
With the single thread option specified (e.g. `ant clean build deploy  -Dbuildthreads=1` ) , the entire build process completed successfully and correctly deployed the sample actions. 

For reference, I was using a mid-2012 Macbook Air with 8Gb RAM and a 500Gb SSD drive.

The failure to deploy the proxy (nginx container) caused the authentication error shown in the subject line.

**Comment by rabbah** [comment]
I'll address the nginx build/deploy robustness in issue #32.

**Comment by AsmOK** [comment]
I have the same problem. However, the controller container is there.
The output for docker ps is:
![image](https://user-images.githubusercontent.com/14912966/36052995-95e5849c-0df8-11e8-80bc-5e7f9928d495.png)

**Comment by AsmOK** [comment]
I get a connection refused error.
![image](https://user-images.githubusercontent.com/14912966/36053844-15b87226-0dfc-11e8-9c3a-b76b7b2bc339.png)
However, the containers are all there. Comparing to a properly running version, only a couchdb container is missing for me, but I'm using Cloudant, so that's the reason it's missing. 
![image](https://user-images.githubusercontent.com/14912966/36053921-6d34c356-0dfc-11e8-87ef-7c90d880cfc0.png)

**Comment by rabbah** [comment]
Your nginx container is flopping. Likely the mount directly is owned by root. Check issue #32.
