### ISSUE TITLE
wsk activation list should show timestamp of activation (even in a human readable format)

### ISSUE THREAD

**Issue by nauerz-ibm** [openwhisk/openwhisk#313]
wsk activation list should show timestamp of activation (even in a human readable format).
Not sure if this is a dup; if so, please close.

**Comment by rabbah** [comment]
You mean `wsk activation list` - Why should a rule list show activations otherwise?

**Comment by nauerz-ibm** [comment]
@rabbah Sorry, yes, copy & paste error :)

**Comment by rabbah** [comment]
Duplicate of #279 and #20.
