### ISSUE TITLE
setting wsk cli to use vagrant host error supplied authentication is not authorized

### ISSUE THREAD

**Issue by csantanapr** [openwhisk/openwhisk#334]
Following the setup using vagrant.
Reach the point to use an external wsk cli to talk to openwhisk inside vagrant 

Did this
$ wsk list
error: The supplied authentication is not authorized to access this resource (code 287)

```
👻  $ wsk property set --apihost 192.168.33.13 --auth 23bc46b1-71f6-4ed5-8c54-816aa4f8c502:123zO3xZCLrMN6v2BKK1dXYFpXlPkccOFqm12CdAsMgRU4VrNZ9lyGVCGuMDGIwP
ok: whisk auth set
ok: whisk API host set
~/dev/whisk/demos/cleansetup
👻  $ wsk action invoke /whisk.system/samples/echo -p message hello --blocking --result
{
    "message": "hello"
}
~/dev/whisk/demos/cleansetup
👻  $ wsk list
error: The supplied authentication is not authorized to access this resource (code 287)
~/dev/whisk/demos/cleansetup
👻  $ wsk property get
whisk auth		23bc46b1-71f6-4ed5-8c54-816aa4f8c502:123zO3xZCLrMN6v2BKK1dXYFpXlPkccOFqm12CdAsMgRU4VrNZ9lyGVCGuMDGIwP
whisk API host		192.168.33.13
whisk API version	v1
whisk namespace		csantana@us.ibm.com_dev
whisk CLI version	2016-04-08T03:37:43-05:00
whisk API build		2016-05-04T19:45:38+00:00
whisk API buildno	latest
```

**Comment by rabbah** [comment]
you're using the wrong namespace - your clean setup not so clean ;)

`whisk namespace     csantana@us.ibm.com_dev`

suggest you remove property file.

**Comment by csantanapr** [comment]
I notice when I compare both
```
vagrant@carlosmacb-wsk:~/openwhisk$ wsk property get
whisk auth		23bc46b1-71f6-4ed5-8c54-816aa4f8c502:123zO3xZCLrMN6v2BKK1dXYFpXlPkccOFqm12CdAsMgRU4VrNZ9lyGVCGuMDGIwP
whisk API host		172.17.0.1
whisk API version	v1
whisk namespace		_
whisk CLI version	2016-05-04T19:45:38+00:00
whisk API build		2016-05-04T19:45:38+00:00
whisk API buildno	latest
```
```
~/dev/whisk/demos/cleansetup
👻  $ wsk property get
whisk auth      23bc46b1-71f6-4ed5-8c54-816aa4f8c502:123zO3xZCLrMN6v2BKK1dXYFpXlPkccOFqm12CdAsMgRU4VrNZ9lyGVCGuMDGIwP
whisk API host      192.168.33.13
whisk API version   v1
whisk namespace     csantana@us.ibm.com_dev
whisk CLI version   2016-04-08T03:37:43-05:00
whisk API build     2016-05-04T19:45:38+00:00
whisk API buildno   latest
```

**Comment by csantanapr** [comment]
@rabbah But how do I do it with the CLI? trying to find what do we need to put in the README

**Comment by rabbah** [comment]
`wsk property unset --namespace` would remove the namespace (and your command will work).
If you were starting from a clean box and following the instructions there would be no namespace (because there would be no property file).

For guest, the namespace would be (if you want to set it explicitly) `wsk property set --namespace guest`.

**Comment by csantanapr** [comment]
So the `subject` name is "guest" then, right?

**Comment by csantanapr** [comment]
I will close this one and fix with #321 by adding info in the README

**Comment by AsmOK** [comment]
so, I sort of have the same problem, but following the links, I don't know what to do!
some links do not exist any more.
![image](https://user-images.githubusercontent.com/14912966/36280154-12421200-12a2-11e8-8018-52bde21c653d.png)

**Comment by AsmOK** [comment]
![image](https://user-images.githubusercontent.com/14912966/36283975-cfab3518-12ae-11e8-824d-7575529495a8.png)

**Comment by AsmOK** [comment]
![image](https://user-images.githubusercontent.com/14912966/36284015-eaff246e-12ae-11e8-90f5-5b702e630b79.png)
