### ISSUE TITLE
Cloudant/CouchDB package should be available in open source

### ISSUE THREAD

**Issue by csantanapr** [openwhisk/openwhisk#336]
Follow the instructions for vagrant in README

I see that cloudant and alarms package are missing. Why?

```
$ wsk package list /whisk.system
packages
/whisk.system/slack                                               shared
/whisk.system/util                                                shared
/whisk.system/github                                              shared
/whisk.system/samples                                             shared
/whisk.system/system                                              shared
/whisk.system/watson                                              shared
/whisk.system/weather                                             shared
~/dev/whisk/demos/cleansetup
👻  $ wsk package get --summary /whisk.system/alarms
error: The supplied authentication is not authorized to access this resource (code 448)
~/dev/whisk/demos/cleansetup
👻  $ wsk package get --summary /whisk.system/cloudant
error: The supplied authentication is not authorized to access this resource (code 451)
~/dev/whisk/demos/cleansetup
👻  $ wsk package get --summary /whisk.system/alarms
error: The supplied authentication is not authorized to access this resource (code 453)
```

Also in the error message what does (code 448) (code 451) and (code 453) ?
If its an error code I would assume I see the same error code for the same command 448 !== 453

**Comment by rabbah** [comment]
They are not in openwhisk.

**Comment by csantanapr** [comment]
I think both will be useful to move to open.

1. alarms seems like a basic core component as a scheduler
2. cloudant, it seems to be focus on IBM Cloudant, but someone can take it as a base/example and create a package for CouchDB or another data store.

What do you think?

**Comment by rabbah** [comment]
Yes. It's in plan.

**Comment by csantanapr** [comment]
OK, I will hunt down those issues numbers and move to backlog

**Comment by csantanapr** [comment]
Found 1/2 #390 for alarm

**Comment by csantanapr** [comment]
Leaving this issue to track only cloudant/couchdb package, alarm is being tracked in another issue #390

**Comment by mrutkows** [comment]
opened a corresponding "documentation" issue #[514](https://github.com/openwhisk/openwhisk/issues/514), as packages.md is not usable by openwhisk users since it assumes cloudant is avail. as a pre-installed openwhisk package. We may wish to fix the packages.md if this sits too long on the backlog...

**Comment by rabbah** [comment]
Cloudant package now in https://github.com/openwhisk/openwhisk-package-cloudant repo.

**Comment by mrutkows** [comment]
Thanks @rabbah
