### ISSUE TITLE
Document files and process limits for docker actions

### ISSUE THREAD

**Issue by csantanapr** [openwhisk/openwhisk#342]
Update [System Limits](https://github.com/openwhisk/openwhisk/blob/master/docs/reference.md#system-limits) with docker limits
```
val fileHandleLimit = Array("--ulimit", "nofile=64:64")
val processLimit = Array("--ulimit", "nproc=512:512")
```
Above info comes from : https://github.com/openwhisk/openwhisk/blob/master/core/dispatcher/src/whisk/core/container/ContainerUtils.scala#L71

Any other to document @rabbah @perryibm ?

**Comment by perryibm** [comment]
Those are the only global ones for now.  Of course there is memory and cpu limits but those are action-specific.

**Comment by csantanapr** [comment]
Thanks @perryibm for the feedback
