### ISSUE TITLE
Improve vagrant experience by updating settings in Vagranfile

### ISSUE THREAD

**Issue by csantanapr** [openwhisk/openwhisk#343]
- Look into using vagrant provision to automate the steps to install git, clone, and run all.sh
- update vagrantfile to allocate less CPUs than 8, maybe 4 or 2

**Comment by rabbah** [comment]
Note that in shared mode the provisioning is automatic.

**Comment by csantanapr** [comment]
Yep, being thinking on having multiple Vagran files
And have one that is super simple that just doing vagrant up get's a system up where wsk cli can be called and that's it one command setup. it will be using ephemeral couchdb but it will be for the first time use case I just want to try it out and that's it nothing else, what's the fastest way.
Talking to @bjustin-ibm he said easiest to get the wsk cli available to user with no config, is to use folder share in vagrant, why is this not the default @rabbah ? It doesn't work everywhere( i.e. windows) ?

Other vagrant files can be more custom.

**Comment by rabbah** [comment]
A vagrant machine with just the CLI to avoid installing python on the host? With go CLI (or if we had distributed binaries for our current CLI), would you still want this?

I suppose you can provide a vagrant machine or a docker container with the CLI installed.

**Comment by csantanapr** [comment]
Not a vagrant to just for the CLI a vagrant file `tools/vagrant/simple/Vagrantfile` for simple scenario with just 3 commands have openwhisk hello running 

```
# 1. Fetch Vagrantfile
  wget https://raw.githubusercontent.com/openwhisk/openwhisk/master/tools/vagrant/simple/Vagrantfile
```

```
# 2. Start virtual machine
  vagrant up
```
```
# 3. Run Hello Action
  vagrant ssh -c "wsk action invoke /whisk.system/samples/echo -p message hello --blocking --result
```

**Comment by csantanapr** [comment]
And the most important piece `vagrant up` always works, docker doesn't timeout, ant build or deploy doesn't fail sometimes.

**Comment by csantanapr** [comment]
Have this in the README.md, and for other use cases and combinations have links in the README to another md file or files

**Comment by csantanapr** [comment]
Closing as dup #360
