### ISSUE TITLE
Make it easier to understand what a feed is

### ISSUE THREAD

**Issue by nauerz-ibm** [openwhisk/openwhisk#345]
Based on the latest labs/user studies we ran, it seems that people still have a lot of trouble with understanding what a feed is (cp. the feedback I have shared via mail already).

Quote: "_I do not really get what a feed is; all other concepts are easy to understand, but this feed thing puzzles me even though I saw it several times_"

Since I got similar feedback several times now, the question is: What can we do to address this?
Better docu? 
Better samples?

**Comment by ioana-blue** [comment]
I was initially confused by "feed" as well and the relationship between feeds and triggers. I think we could benefit from a better terminology. So maybe we ask for some alternative names. 

In my mind, "feed" is a trigger family or a trigger source. Not sure whether this type of names would add to the confusion, though, instead of clarifying things.

**Comment by rabbah** [comment]
It's called feed, as in web feed. When a wsk user creates a trigger, they can subscribe to a feed such that new content (an event) from the feed results in a trigger activation.

**Comment by sjfink** [comment]
Attempt 1 at definitions:

* an **event** is something that happens at runtime
* a **Trigger** is a name for a class of events.    It is similar to a "topic" in pub-sub systems.
* a **Feed** is an abstraction for a stream of events, all of which belong to a Trigger T.    A feed provides lifecycle operations _create_, _delete_, _pause_, and _resume_, via a whisk action interface.   The whisk system can use a feed's action to control the stream of events.

**Comment by nauerz-ibm** [comment]
@rabbah I think we all understand what it is and also the reason why we named it that way.
But imho that does not help if a significant amount of users do not get it and that is what the user studies/lab show :(

@ioana-blue I agree, another name may help as well but changing things others already got used too may be dangerous as well (not sure).

@sjfink Even though I understand what you are saying I doubt it will help (gut feeling); maybe explaining along samples may help? Maybe we should make a concrete sample part of the docu and explain the diff between all these concepts?
At least me would help that if I would be a user.

Thoughts?

**Comment by mbehrendt** [comment]
agree with @nauerz-ibm . while all these definitions are technically accurate, many people are struggling to understand them intuitively -- we should work on some simplification here (not a new topic :-) )

**Comment by rabbah** [comment]
i'd like to understand why "people are struggling" because there could be many reasons (poor presentation, lack of proper definitions, no intuition given, etc.).

**Comment by nauerz-ibm** [comment]
I can try to get more details.
What do you think about using concrete samples to explain the differences between our concepts and how to apply them?

**Comment by rabbah** [comment]
there are several experiments we can do (perhaps as part of the user studies) to learn from and adapt.

**Comment by sjfink** [comment]
@nauerz-ibm I agree we should write a doc which shows the definitions along with examples.

**Comment by mbehrendt** [comment]
i don't think it's lack of proper definitions -- we have them, but they're i think too abstract / not intuitive enough. we should think about a way how to present the definitions in a more tangible / practical way

**Comment by sjfink** [comment]
I don't know how to make the definitions above any simpler.

**Comment by rabbah** [comment]
to @mbehrendt's point, we might need some examples to accompany the definitions (or analogies to RSS feeds for example - among others). this is why understanding what the issue really is matters.

**Comment by nauerz-ibm** [comment]
So it seems we have an action plan:

- Reword the definitions to make them more intuitive (less "technical" != inaccurate)
- Accompany them with some simple samples to deepen understanding

Who volunteers to give this a 1st try? :)

**Comment by mbehrendt** [comment]
i'll give it a try

**Comment by julicjung** [comment]
Just chipping in my 2 cents:
My understanding of a "feed" in whisk context is roughly "a stream of events".
I struggle a little with distinguishing this cleanly from the concept of a trigger and my mind came up with something like "a feed is a kind of configuration when triggers" get fired. Or is it more like an input channel through which my trigger gets repeatedly fired? 

When I browsed the docs I never really felt like I found the place to say "Ah, now this is the section where feeds and triggers are explained". E.g. I still do not know I can create my own feed or if I am constrained to the system provided ones.
The info may very well be somewhere in the docs - it might just that I did not readily found them this is the entire problem.

**Comment by rabbah** [comment]
We haven't described yet in the docs how to create your own feed.

**Comment by mbehrendt** [comment]
what about this, as a first stab for defining terminology? any feedback welcome, pls feel free to throw tomatoes :-)

feed — a feed implements the knowledge for how to setup receiving events from a particular source. for instance, a github feed knows how to setup github webhooks, a cloudant feed knows how to configure cloudant for sending events about data changes.


trigger — a trigger is created to express the interest in a particular event — it specifies all information needed to let the trigger fire whenever an event occurs. triggers are always created based on feeds. for instance, someone might create a trigger for their specific github account, such that the trigger always fires when a new file is committed.

**Comment by jthomas** [comment]
I struggled to understand the event, trigger, feed dichotomy until I implemented my own feed. 
As a developer, I associate "feed" with passive data sources, an RSS feed. 
Looking through the catalogue packages, I discovered the a "feed" is closer to a service broker. It receives lifecycle events for registered triggers, which it can register with an external provider.

**Comment by csantanapr** [comment]
Related to #559

**Comment by rabbah** [comment]
@csantanapr @sjfink since this is now merged: https://github.com/openwhisk/openwhisk/blob/master/docs/feeds.md#difference-between-feed-and-trigger

is this issue resolved?

**Comment by sjfink** [comment]
I'll say yes.   Closing.

**Comment by csantanapr** [comment]
sorry, I forgot to close the issue when I merged. I'm used to github auto closing for me :-) when using Fixes Closes #xxx
