### ISSUE TITLE
Allow for better error handling

### ISSUE THREAD

**Issue by nauerz-ibm** [openwhisk/openwhisk#348]
During the recent labs/user studies many people asked how they can add proper error handling to their actions.

Quote: "_I miss some better means  for error handling. How about patterns already existing in functional programming environments? How about something like this: http://fsharpforfunandprofit.com/posts/recipe-part2/ ?)_"

Hence, the question is: What can we do to address this?

**Comment by rabbah** [comment]
With the addition of node 6 and support for promises, I think this is resolved.
