### ISSUE TITLE
Controller reports NotAuthorized rather than InternalError if it cannot connect to db

### ISSUE THREAD

**Issue by rabbah** [openwhisk/openwhisk#352]
While investigating #337, the controller logs showed that if there is a failure to connect to the `subjects` database, the controller rejects the request with a misleading NotAuthorized message. instead of an InternalServerSerror or a more informative message.

**Comment by domdom82** [comment]
yep ran into that one a couple of times, too. rather confusing to the user. he thinks is credentials are wrong.

I suggest to return either 500 or 503 (service unavailable) if cloudant connection is the cause.

**Comment by psuter** [comment]
Fixed as of a2d222af87dbe4c4a36f7f56e2852a778e94b5cf
