### ISSUE TITLE
add text2voice action to catalog

### ISSUE THREAD

**Issue by csantanapr** [openwhisk/openwhisk#364]
We could use as an example the Watson API

**Comment by lzbj** [comment]
@csantanapr , I updated the catalog.md for this issue and created a pull request. Is it necessary?

**Comment by csantanapr** [comment]
Hi @lzbj Thanks for the contribution, but the docs are ready in https://github.com/IBM-Bluemix/docs/pull/169

The content just needs to be sync with the content in this repo.

**Comment by lzbj** [comment]
@csantanapr , Ok, thanks.

**Comment by lzbj** [comment]
@csantanapr , sorry if bother you, we also have a documentation for the SpeechToText action already, right?

**Comment by csantanapr** [comment]
@jasonpet-ibm is working on the speechtotext docs already

**Comment by lzbj** [comment]
thank you.

**Comment by csantanapr** [comment]
Closing this one since implementation and docs are merged now in this repo for text2speech
Tracking speech2text in another issue #510
