### ISSUE TITLE
Question&Answer (Dialog) package

### ISSUE THREAD

**Issue by csantanapr** [openwhisk/openwhisk#365]
We could use as an example the [Watson Dialog API](http://www.ibm.com/smarterplanet/us/en/ibmwatson/developercloud/dialog.html)

**Comment by lzbj** [comment]
@csantanapr ,could you please assign this task to me?

**Comment by lzbj** [comment]
The latest recommended soluitons here:
http://watson-qa-demo.mybluemix.net/
https://developer.ibm.com/watson/blog/2015/11/11/watson-question-and-answer-service-to-be-withdrawn/

**Comment by csantanapr** [comment]
Good catch, then instead we can create actions using the replacements services: Natural Language Classifier, Dialog, Retrieve and Rank, and Document Conversion. 

What do you think we use this issue to implement Dialog and create new issues for the other ones?

**Comment by lzbj** [comment]
Thanks, yes, agree with you. Then maybe we can think of using of those created actions in a pipline to achieve some more complex apps, such as Q&A etc. Another solution is to utilize several Watson api in one action to compose a complex app, but in my opinion, the former one is more flexible.

**Comment by csantanapr** [comment]
@lzbj I agree that's we have sequences to create more complex scenarios, but we should have generic actions in a package that user can copy/clone and adjust and create their own sequence or trigger an event from inside an action to make a rule run with another actions

**Comment by lzbj** [comment]
Yes, sure.

**Comment by lzbj** [comment]
@csantanapr , could you please help create 4 issues with Package label, that associated with replacements services as you mentioned above and assign to me? thank you.

**Comment by csantanapr** [comment]
@lzbj I converted this issue to be for Dialog action, and created 3 more 587, 588, 589
Take into account that each one should have proper tests, and docs cover
I suggest to work on one first, this issue is already assigned to you, as you finish this one and is ready to pick the next one then assign at that time.

**Comment by lzbj** [comment]
@csantanapr Thank you, yes, I'll do as you pointed out.

**Comment by lzbj** [comment]
https://github.com/openwhisk/openwhisk/pull/641
@csantanapr , could you help review it when available, thank you.

**Comment by markusthoemmes** [comment]
@csantanapr still valid/in the right place?

**Comment by markusthoemmes** [comment]
Issue moved to [openwhisk/openwhisk-catalog #209](https://github.com/openwhisk/openwhisk-catalog/issues/209) via [**ZenHub**](https://www.zenhub.com/)
