### ISSUE TITLE
"all.sh" bash script kills terminal at conclusion (Ubuntu 14.04.3) 

### ISSUE THREAD

**Issue by mrutkows** [openwhisk/openwhisk#368]
The Ubuntu instruction:
# Install all required software

  (cd openwhisk/tools/ubuntu-setup && source all.sh)

When executed (and all.sh is invoked) results in a lengthy series of download/install/config/setup.  Upon completion, the terminal exits so there is now way to verify success/failure.

**Comment by csantanapr** [comment]
This is fixed now https://github.com/openwhisk/openwhisk/commit/2416a3bcb486e08a8df42816f8f28f6d9f3b6f4c#diff-e126e24da7c91b97670918c1c6440cc0
