### ISSUE TITLE
Provide a way to define credentials using VCAP to be leverage by tests

### ISSUE THREAD

**Issue by csantanapr** [openwhisk/openwhisk#374]
There should be docs, and tests that shows contributors how to use their own credentials when running tests

**Comment by csantanapr** [comment]
Maybe we should visit the docs folder structure

I think we need to have different sub directories per end user of the docs.
- User documentation (just using openwhisk)
- Contributor documentation (a developer making contributions to the repo), I would name this "Developer docs" but that could get confuse with user docs, which is also a developer focusing in something else.
- Integrator documentation (operations, running on a server, deploying, i.e. setup and run openwhisk in production)

Maybe have a directory structure like:
```
docs/user/
docs/contributor/ 
docs/operations/
```

**Comment by csantanapr** [comment]
@jasonpet what do you think of starting a doc in `docs/contributor/testing.md` to doc a section for about using VCAP credentials in openwhisk tests

**Comment by markusthoemmes** [comment]
Not valid in this repository.
