### ISSUE TITLE
Add user documentation for Java Actions

### ISSUE THREAD

**Issue by houshengbo** [openwhisk/openwhisk#375]
Currently, OpenWhisk is still lack of the documentation for the part of Java runtimes. This issue is open to add the corresponding documentation.

**Comment by daisy-ycguo** [comment]
I would like to work on this issue. I can add a section "## Creating and invoking Java actions" to https://github.com/openwhisk/openwhisk/edit/master/docs/actions.md and explain how to create and use Java actions. Does it make sense ?

**Comment by mrutkows** [comment]
Assigned to Daisy

**Comment by csantanapr** [comment]
@daisy-ycguo Go ahead and work on documenting java in [docs/actions.md](https://github.com/openwhisk/openwhisk/edit/master/docs/actions.md)

Send a Pull request with WIP in title so we people can review, I think @rabbah might be the SME for java runtime.

**Comment by csantanapr** [comment]
This is merged into master now
