### ISSUE TITLE
Add user documentation for Python Actions

### ISSUE THREAD

**Issue by houshengbo** [openwhisk/openwhisk#376]
OpenWhisk is lack of the documents in the part of Python runtimes.
This issue is open to add the documentation to the Python runtimes.

**Comment by lzbj** [comment]
Do we have runtime documents for Nodejs and Swift/Swift3, it's better also we have an overall doc to introduce about runtimes, what is runtimes, how runtimes is weavered in OpenWhisk and used etc,.

**Comment by csantanapr** [comment]
@lzbj All current docs about languages/runtimes are located here [docs/actions.md](https://github.com/openwhisk/openwhisk/blob/master/docs/actions.md)

@paulcastro it's involved with Swift runtime and will be helping with the corresponding docs for Swift 3

**Comment by mrutkows** [comment]
Assigned to Vincent

**Comment by lzbj** [comment]
@csantanapr, thanks.

**Comment by csantanapr** [comment]
@lzbj I think @ioana-blue is the SME for python actions/runtime she will be able to review and answer questions.

Send a Pull Request with WIP in title so people can provide feedback as you progress

**Comment by lzbj** [comment]
@csantanapr Yes, thank you.

**Comment by csantanapr** [comment]
This is already merged.
