### ISSUE TITLE
add whisk.getContext() to js SDK

### ISSUE THREAD

**Issue by csantanapr** [openwhisk/openwhisk#387]
From @sjfink 
 in a nutshell, the proposal is to add a getContext() method to the whisk object in the javascript SDK which returns a JSON object (key-values) which holds deployment-specific properties.

call it whisk.getContext()

Would be nice if passing context to js container were the same as passing context to the black box container. If the /init protocol works for black box, can it work for nodeJsaction too?

From @psuter 
Just a quick note that I ran into a similar desideratum today, as I wanted to be able to determine the namespace & name of an action from within itself.

It should be possible to write a recursive action without knowing the name[space] we'll use at deployment time.

Regarding how this mechanism should be implemented, both the SDK and a magic field in the input object are acceptable to me.

**Comment by sjfink** [comment]
Addendum:   we earlier decided to additionally move the 'whisk' object to an imported npm module, so we can run whisk actions in normal node.js runtimes rather than relying on the nodejsaction base docker image to provide the whisk object.

**Comment by psuter** [comment]
In my view #1539 addressed this through environment variables and by deferring to the `openwhisk` npm package. Close?
