### ISSUE TITLE
Alarm/Scheduler package should be in open source

### ISSUE THREAD

**Issue by csantanapr** [openwhisk/openwhisk#390]
There is an implementation of that alarm/schedule feed implemented in internal repository, this should be moved to open source. It's also looks weird to have docs in this open repo for a package that source code is not available here.

**Comment by mrutkows** [comment]
Missing period. Regardless of Vagrant or not.

**Comment by mrutkows** [comment]
Opened corresponding issue #[515](https://github.com/openwhisk/openwhisk/issues/515) which describes how packages.md examples on how to create "trigger feeds" using the alarm package is done; however without this code in "open" the user can never actually try this.  If this sits in backlog too long we may want to provide an alternative example (although I do not believe we have any available strictly in openwhisk).

**Comment by markusthoemmes** [comment]
This is done.

**Comment by mimy2001** [comment]
I installed Openwhisk two weeks ago and I'm still not seeing the alarms package.  I downloaded the openwhisk-package-alarms and did the installCatalog.sh but I keep getting errors.  How do I get the /whisk.system/alarms package for open whisk to work?

**Comment by rabbah** [comment]
@mimy2001 see this issue: https://github.com/openwhisk/openwhisk-package-alarms/issues/50

the alarm (and cloudant) package is not installed as part of the catalog, you have to do it explicitly.

**Comment by mimy2001** [comment]
When will it be a part of the catalog?

**Comment by mrutkows** [comment]
@mimy2001 Perhaps we can discuss this on the Apache OpenWhisk project email list?  In general, we have tried to minimize the system catalog to very basic actions/packages to allow greater customization of the open source (and Alarms is a special case as it is a Feed Action which has a Provider service/server and trigger DB).

**Comment by hsane2001** [comment]
I still dont see the alarms package, and the one at "https://github.com/apache/incubator-openwhisk-package-alarms" has no install instructions
