### ISSUE TITLE
email notification package

### ISSUE THREAD

**Issue by csantanapr** [openwhisk/openwhisk#392]
From @sjfink :
We could use SendGrid -- though there have been some concerns about dropped messages and spam filters.

We need an action to send outgoing emails and a feed to receive incoming emails as triggers.

**Comment by mbehrendt** [comment]
i'd suggest to prioritize the event source higher than the action

**Comment by browezilla** [comment]
This was previously assigned to Sebastian Aschoff for his Master's thesis. I chatted with him, and since we are ready to start on it now, we will pull it over and start working on it. If Andreas feels that it is critical for Sebastian's thesis, then Sebastian will take if over from us. (the same for issue 391 - Twilio). Please note that both require legal clearance before we can release them into the wild.

**Comment by mbehrendt** [comment]
from a priority perspective, the feed should be worked on first, this is way more important.

**Comment by tareqmamari** [comment]
Hi
Andreas assigned a task to me and Sebastian to implement IMAP for incoming emails. I have created a service provider for that, it is now available , to use it :
- The feed action is available as a public action within my namespace: 
`/talmaam@de.ibm.com_mainSpace/imapFeed`

- Create trigger and pass the needed parameters: 
`wsk trigger create imapTrigger -p user 'EMAIL' -p pass 'PASSWORD' -p host 'HOST' -p mailbox 'MAILBOX' --feed imapFeed 
`
**Example:** 
`wsk trigger create imapTrigger -p user 'almaamaritest@gmail.com' -p pass 'XXXX' -p host 'imap.gmail.com' -p mailbox 'INBOX' --feed imapFeed
`

**Comment by sjfink** [comment]
>  i'd suggest to prioritize the event source higher than the action

why?   sending emails is a very useful facility.

**Comment by mbehrendt** [comment]
a precanned action is essentially 'just' a code sample (of which there a many available here, for simple copy & paste: https://sendgrid.com/docs/Integrate/Code_Examples/index.html) . however, having an email-based feed implemented is non-trivial value-add to openwhisk. it's good to have an action, but i just don't see the priority as being as high.

**Comment by browezilla** [comment]
https://sendgrid.com/docs/API_Reference/Webhooks/event.html
- HJason, please note I do not have legal clearance yet for us to even start using this yet to create the package/action. Hopefully it will come today

**Comment by browezilla** [comment]
We have legal clearance to create the package/action, but not to externalize it yet. We must expose the need for the customer to have an ID of their own.

**Comment by csantanapr** [comment]
@browezilla let's clarify what does "but not to externalize", I think we are OK here since how packages are not going to be install by default, user will be the one to install the package in openwhisk.

Installing the senGrid package in a comercial offering of openwhisk like bluemix, it's up to that company (i.e. IBM) to make the decision if they want to install the package in their production openwhisk for their customers.

For now the developer doing this work, I suggest follows the same pattern as [openwhisk/wsk-pkg-pushnotifications](https://github.com/openwhisk/wsk-pkg-pushnotifications) and make it public here in opensource. We can create a new repo (i.e. openwhisk/openwhisk-package-email)
 
We just need to like business as usual that any code or 3rd party libraries are compatible with the main openwhisk one Apache 2.0 (https://github.com/openwhisk/openwhisk/blob/master/LICENSE.txt) License

**Comment by markusthoemmes** [comment]
@csantanapr move to catalog?

**Comment by markusthoemmes** [comment]
Issue moved to [openwhisk/openwhisk-catalog #200](https://github.com/openwhisk/openwhisk-catalog/issues/200) via [**ZenHub**](https://www.zenhub.com/)
