### ISSUE TITLE
websocket package

### ISSUE THREAD

**Issue by csantanapr** [openwhisk/openwhisk#393]
build a package which contains an action to send a message as a client over a web socket to a web socket server (like socket io)

possible parameter for action
- server url (string)
- message (json obj)
- (optional) #channel string or array of strings

**Comment by bjustin-ibm** [comment]
@csantanapr Please see #484 

Since this is just one action, I wonder if it really needs to be a separate package, or can just be part of the "utils" package.

**Comment by csantanapr** [comment]
separate package same as `slack` with one action

**Comment by csantanapr** [comment]
don't want for `utils` and `samples` to be a grab all.

I think eventually this catalog content will be split into git repos, that user can clone/fork/copy into his namespace without a package.

for now package is all we have to separate things

**Comment by bjustin-ibm** [comment]
Resolved by #484
