### ISSUE TITLE
RSS package

### ISSUE THREAD

**Issue by csantanapr** [openwhisk/openwhisk#394]
A package which can subscribe to an RSS feed and generate events.

RSS is a very common way to notify people about events.

package should include feed (pooling 15 minutes) to see if there is a new atom item in rss xml url.

CDC health alerts as an RSS feed -- for health care customer scenario
New PodCast (i.e. iTunes) available - action to download mp3 and translate, or speach2text and store in cloud storage.
New version release of software (i.e. cordova.io)

**Comment by lzbj** [comment]
@csantanapr ,can you assign this issue to me?

**Comment by rabbah** [comment]
Is the goal to include this as part of the openwhisk repository or a standalone repository?

**Comment by csantanapr** [comment]
@rabbah For now we are accepting all new catalog content into this repo under the catalog folder, eventually will move into [openwhisk-openwhisk-catalog](https://github.com/openwhisk/openwhisk-catalog) repo when the whole folder get's moved out.

**Comment by rabbah** [comment]
There are other packages however (eg push notification) that are already in a different repo. Why not do it for this as well? We can move the discussion elsewhere.

As for this pr, it's not complete - not clear if this is a feed or just an action? no installation script. no tests.

**Comment by fellerj** [comment]
An rss package for OpenWhisk has been recently contributed!   Check out https://github.com/openwhisk/openwhisk-package-rss
