### ISSUE TITLE
Mobile push notifications from actions

### ISSUE THREAD

**Issue by csantanapr** [openwhisk/openwhisk#395]
For example we could use the IMF Push Service in Bluemix so it can be used in mobile solutions.

Use cases are like, when push to git send push notification to phone

**Comment by tareqmamari** [comment]
I think Sebastian Aschoff is working on that

**Comment by csantanapr** [comment]
Thanks @tareqmamari , can you put a name in your profile I can't tell if you are an IBMer.

**Comment by csantanapr** [comment]
@tareqmamari Sebastian Aschoff is going to work on Message Hub #400 

@nwspeete-ibm is going to work on IMF Push

They can collaborate on IMF push

**Comment by csantanapr** [comment]
cc @nauerz-ibm

**Comment by nwspeete-ibm** [comment]
.sh scripts are ready for installing this push package into open.  One decision to be made is how to integrate the tests from outside packages: https://github.com/openwhisk/openwhisk/issues/562
