### ISSUE TITLE
Object Storage package

### ISSUE THREAD

**Issue by csantanapr** [openwhisk/openwhisk#396]
Object Storage pacakge provides an unstructured cloud data store.

User can read and write files on object storage service like bluemix

object storage in bluemix currently doesn't support change feeds, and pooling feed/provider implementation would be suboptimal. **So this issue should only cover read and write.**

**Comment by tareqmamari** [comment]
I will work on that as a part of my master thesis

**Comment by csantanapr** [comment]
Hi @tareqmamari please coordinate with @jasonpet he has some code working and maybe you two can work together or split the work.

**Comment by tareqmamari** [comment]
Sure, will do that
Thanks

**Comment by JacopoMangiavacchi** [comment]
Definitely ObjectStorage is the best repository for blob storage but what about using Cloudant attachment as a front end to ObjectStorage?  

We already have excellent cloudant package supporting feed and it should be possible to use Cloudant as a blob storage frontend, automatically exporting the attachment writing the blob on ObjectStorage with a simple whisk action and then remove it from Cloudant.  It should be nice to deliver a sample for that.

**Comment by csantanapr** [comment]
@JacopoMangiavacchi Thanks for posting a comment, 
Once there is a simple objectstore write and read actions, then is open to be use to compose solutions, like you describe. to take out the attachment (i.e. photo, mp3, pdf, etc..) and write it to object store with the action. 

The action can be invoke directly or indirectly thru an event, or just have a single action that does multiple things on a single cloudant change event, it can process the doc including transferring the attachment  to objectstore using the objectstore api, and adding a reference to the file in objectstore item back in the cloudant doc.

**Comment by starpit** [comment]
was progress every made on this? if not, i can take it up

**Comment by markusthoemmes** [comment]
@csantanapr move to catalog?

**Comment by csantanapr** [comment]
Issue moved to [openwhisk/openwhisk-catalog #198](https://github.com/openwhisk/openwhisk-catalog/issues/198) via [**ZenHub**](https://www.zenhub.com/)
