### ISSUE TITLE
BOX package (box.com)

### ISSUE THREAD

**Issue by csantanapr** [openwhisk/openwhisk#397]
Use case is to have actions to read and write to box and possible a change feed provider

From daniel-federschmidt :
It would be nice if the package also would provide feeds which trigger events when something happens on Box. This could be facilitated through the Event Notifications delivered over webhooks. I already did some experiments with whisk and the API two months ago. Unfortunately, I couldn't find a way to programatically create a webhook which is not really optimal in terms of UX.

https://developers.box.com/webhooks/

it would need to deal with oAuth tokens properly

**Comment by csantanapr** [comment]
@paulcastro if you ware not working on this, please unassigned yourself

**Comment by markusthoemmes** [comment]
@csantanapr move to catalog?

**Comment by markusthoemmes** [comment]
Issue moved to [openwhisk/openwhisk-catalog #201](https://github.com/openwhisk/openwhisk-catalog/issues/201) via [**ZenHub**](https://www.zenhub.com/)
