### ISSUE TITLE
Message Hub package

### ISSUE THREAD

**Issue by csantanapr** [openwhisk/openwhisk#400]
It will be good to have a package for message hub with action, and feeds
We can use the Bluemix Message Hub service to implement for example.

As always assume code, tests, and docs are covered to close the issue.

**Comment by csantanapr** [comment]
Hi @nauerz-ibm Can you add Sebastian Aschoff to openwhisk team and  assigned this issue to him?

**Comment by rabbah** [comment]
@bjustin-ibm close?

**Comment by bjustin-ibm** [comment]
I'm ok closing this. @csantanapr agree?

**Comment by csantanapr** [comment]
closed
