### ISSUE TITLE
In Swagger file, payload described as KeyValue model does not correspond to what server is expecting

### ISSUE THREAD

**Issue by fabdslv** [openwhisk/openwhisk#401]
KeyValue defines an object as-is : ```{'key': 'name', 'value':'Phil'}``` while server only accepts ```{'name':'Phil'}```.

**Comment by paulcastro** [comment]
Just a clarification, this is for action POST.

**Comment by rabbah** [comment]
confirmed - related to #270.

**Comment by rabbah** [comment]
Closing as duplicate of 270.
