### ISSUE TITLE
spray-client for couch reporting error-level log messages when it shouldn't

### ISSUE THREAD

**Issue by rabbah** [openwhisk/openwhisk#402]
the logs show that a 'get' for an entity that doesn't exist results in a log message at level `ERROR` when it should be `INFO`.

```
[2016-05-11T21:55:04.033Z] [INFO] [#tid_9] [CouchDbRestStore] [GET] 'guest_whisks', document: 'id: guest/hello rev: null'; not found.
[2016-05-11T21:55:04.034Z] [ERROR] [#tid_9] [CouchDbRestStore] [GET] 'guest_whisks' internal error, doc: 'id: guest/hello, rev: null', failure: 'not found on 'get''
```

**Comment by psuter** [comment]
Would it make sense for the method to accept a boolean indicating whether we expect the retrieval to be successful?

**Comment by rabbah** [comment]
A "document not found" from the controller's point of view is invariably not an error. In the invoker, it is invariably always an error. Viewed in this way, yes. Of course there are other operation, which if they fail should generate an error-level log message (connection failure for example).

**Comment by sjfink** [comment]
i would suggest simply logging no errors in the library, and let the caller log an appropriate error if desired.

**Comment by psuter** [comment]
The problem was double-reporting of errors. Addressed in #556.

**Comment by rabbah** [comment]
@psuter confirm done and close.

**Comment by psuter** [comment]
Done.
