### ISSUE TITLE
Document --dropit flag on db create for readme

### ISSUE THREAD

**Issue by mrutkows** [openwhisk/openwhisk#408]
section : Initialize datastore containing authorization keys
  tools/db/createImmortalDBs.sh 

can avoid several instructions by simply supply the cmd. line parm. --dropit which is accepted by the script.

**Comment by mrutkows** [comment]
Applies to file:
https://github.com/openwhisk/openwhisk/blob/master/README.md

**Comment by rabbah** [comment]
This was deliberate omission because it's dangerous but we need it however for Travis automation. If documented, it should be accompanied with the warning since this is an irreversible action and offers no confirmation of which db is being wiped.

**Comment by mrutkows** [comment]
Interesting as this was taught as mainstream usage for developers...

**Comment by rabbah** [comment]
What does this mean? It's not a document features and is used in exactly one place `travis/build.sh`:

```
> grep -r dropit /openwhisk
./tools/db/createImmortalDBs.sh:if [[ "$1" != "--dropit" ]]; then
./tools/travis/build.sh:./tools/db/createImmortalDBs.sh --dropit
```

**Comment by mrutkows** [comment]
It is in the readme.md as described above... the createImmortalDBs.sh is not just invoked in travis its mainstream instructions for developers installing running openwhisk in their local setup/env....

section : Initialize datastore containing authorization keys
tools/db/createImmortalDBs.sh 

During our team education sessions we were shown that we could use --dropit to avoid the manual intervention.

**Comment by rabbah** [comment]
You're conflating `createImmortalDBs.sh` and the option to drop automatically. The former is documented, obviously as is a required step. The latter is not. It is special. Don't use it.

**Comment by mrutkows** [comment]
on the contrary, since being shown it, I use it several times a day (it seems) using the ephemeral CouchDB...

**Comment by mrutkows** [comment]
Closing for now, but its a lovely shortcut that clearly is used by devs.

**Comment by rabbah** [comment]
FYI There are new instructions coming for couchdb that will make the db init no longer necessary.

**Comment by mrutkows** [comment]
Issue #?
