### ISSUE TITLE
local CouchDb over https with self-signed certificate 

### ISSUE THREAD

**Issue by rabbah** [openwhisk/openwhisk#413]
Our docs for a local Couch instance [state](https://github.com/openwhisk/openwhisk#using-couchdb) that it must be available over `https` 
>	the CouchDB instance must be accessible over https (although the certificate does not need to be valid)

However this leads to an error accessing the database because the implementation does not permit a self-signed certificate. For example

```
Aborting encrypted connection to /192.168.33.1:6984 due to 
[SSLHandshakeException:General SSLEngine problem] -> 
[SSLHandshakeException:General SSLEngine problem] -> 
[ValidatorException:PKIX path building failed:
sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to
requested target] -> [SunCertPathBuilderException:unable to find valid certification path to requested
target]
[spray.can.client.HttpClientConnection:65] 
```

This is also related to #352. @psuter.

**Comment by psuter** [comment]
Ouch. Doc is outdated, `http` is fine. In fact, this is what the default scripts use.

**Comment by rabbah** [comment]
Should we allow `https` with self-signed?

**Comment by l2fprod** [comment]
These are the steps I followed to generate the certificate for CouchDB: https://cwiki.apache.org/confluence/pages/viewpage.action?pageId=48203146

**Comment by rabbah** [comment]
Document requirements.
