### ISSUE TITLE
binary CLI distribution (go-CLI)

### ISSUE THREAD

**Issue by csantanapr** [openwhisk/openwhisk#415]
Provide a better experience to install the WSK CLI

Work already started implementing a new WSK CLI using go.

Platforms to support are similars to the ones the CloudFoundry supports:
Developer workstations: Linux, Mac, and Windows

**Comment by csantanapr** [comment]
Work already in progress in PR #238

**Comment by mdeuser** [comment]
@csantanapr - Is this a duplicate of #577 or is there some additional subtlety this issue is covering?

**Comment by csantanapr** [comment]
This one is duplicate of #577 I will close this one.
