### ISSUE TITLE
wsk action copy only copies exec not parameters or annotations

### ISSUE THREAD

**Issue by csantanapr** [openwhisk/openwhisk#418]
From @rabbah "i think it be convenient to copy parameters, and also the annotations.
it is less useful to copy the exec and miss out on all the rest."

**Comment by dubeejw** [comment]
@csantanapr, can you explain this one more? I'm not sure what `wsk action copy` is?

**Comment by rabbah** [comment]
`wsk action create X --copy Y` is a way to create action `X` by copying the `exec` from action `Y`. It does not copy parameters or annotations from `Y` to `X`. The suggestion above was to make the copy more complete.

**Comment by mdeuser** [comment]
@csantanapr - Just confirming...  If this action were part of a package, the above proposal would NOT include the package parameters/annotation values, but only the parameter/annotation values directly associated with the action.

At some point, would there ever be a need to allow the action developer to prohibit a specific action parameter/annotation from being copied?  I suppose this would also affect `wsk action get` as well.

**Comment by csantanapr** [comment]
@mdeuser 
>@csantanapr - Just confirming... If this action were part of a package, the above proposal would NOT include the package parameters/annotation values, but only the parameter/annotation values directly associated with the action.

Correct, I would not copy parameters annotations from package, since this parameter values come into play at invocation time, also user could be copying the action into a new package, which could have a different set of default parameters set.

>At some point, would there ever be a need to allow the action developer to prohibit a specific action parameter/annotation from being copied? I suppose this would also affect wsk action get as well.

Correct, if the subject is using a key that allows him visibility to read that information, then there is no harm to allow them to copy that information.

**Comment by dubeejw** [comment]
Do we still want this functionality? If not, please close. If so, please merge the corresponding PR.

**Comment by csantanapr** [comment]
I think it would be good to have it in and merge #1662, lets continue conversation there, about the concern that @rabbah express.
