### ISSUE TITLE
Improve JSON processing in CLI by allowing file input

### ISSUE THREAD

**Issue by csantanapr** [openwhisk/openwhisk#426]
Reported by @nauerz-ibm 

Also, users found an error passing data FROM a JS action INTO a Swift action. JSON that is perfectly valid was failing when passed from a Swift action into a JSON action. The JSON contained a single quote within a double quote, and once the single quote was removed, then it worked as expected.<br/>
<br/>
For example:<br/>
<br/>
This failed (part of a larger JSON array):<br/>
<br/>
<code>{rating:"3.5",name:”Bally's Las Vegas",lat:"36.113579",city:"Las Vegas",lon:"-115.172792",price:"117"}</code><br/>
<br/>
Changing to this succeeded:<br/>
<br/>
<code>{rating:"3.5",name:”Ballys Las Vegas",lat:"36.113579",city:"Las Vegas",lon:"-115.172792",price:"117"}</code><br/>
<br/>
The only difference is the removal of a single quote from Bally's in the name field, which worked without issue.

**Comment by rabbah** [comment]
Why is this a CLI issue?

**Comment by csantanapr** [comment]
Because it's a problem an user hit using the CLI

After reading closely I think this one it's an user error of not escaping the single quote in shell or cmd

I think there nothing the CLI can do to fix it but we can discuss here how to improve it

Brainstorm:
Passing JSON in terminal for simple things works fine but for complex strings it's not that good, what I did in another project I did a CLI was to have a flag in the CLI   to pass a JSON file containing the a json object with the information that the user would pass in terminal instead so you can pass the params as args or as a file input

**Comment by rabbah** [comment]
I would generalize this issue then to have better support for sending JSON - eg you cannot now send a top level json as in `wsk action invoke /whisk.system/samples/greeting '{"name":"..."}'`.

**Comment by csantanapr** [comment]
Yep I agree more generic way to send json in CLI I just need help from someone deciphering original bug report 😬

**Comment by psuter** [comment]
This has bugged me for a while too. I'll take a stab at it.

**Comment by csantanapr** [comment]
@psuter go ahead and do it on go-CLI branch take a look at WIP PR

**Comment by psuter** [comment]
Postponed in light of the Go CLI progress.

**Comment by dubeejw** [comment]
@csantanapr, looks like there are two different issues here. One is adding JSON file input support. The other is passing JSON to the CLI. Both the provided JSON strings are invalid as there are not quotes around the key values. The single quote bug is fixed in the Go CLI. I will ignore the invalid JSON pieces here, and use the issue to track the file input enhancements.

**Comment by dubeejw** [comment]
@csantanapr, here's what I had in mind for the new flags.

filename points to a file containing JSON content.

```wsk action create actionName artifactName -pf keyName filename```
```wsk action create actionName artifactName -paramFile keyName filename```

```wsk action create actionName artifactName -af keyName filename```
```wsk action create actionName artifactName -annotationFile keyName filename```

**Comment by csantanapr** [comment]
@dubeejw yes that was the agreement to use this issue to track enhancement to the Go CLI to allow user to pass JSON data by file.
I think starting with parameters and annotations would be a good start.

I was thinking on having it more generic and simpler one file for all parameters, one file for all annotations, not one file per parameter or annotation.
For example:
`wsk action create actionName artifactName -pf filename`
`wsk action create actionName artifactName -paramfile filename`
filename =
```
{
   "param1":"param1_value",
   "param2":"param2_value"
}
```

**Comment by dubeejw** [comment]
Params, and annotations take two values. One is a name, and the other is a value. Where the value can be JSON. This is why I recommend the second argument be a file name. Existing commands look like the following:

```
wsk action create actionName artifactName -param paramName "{\"key\": \"value\"}"
```

**Comment by csantanapr** [comment]
Yes I'm aware how it works today, that's why I want JSON file not work in the same and work in a better way.
Wow that sounded like a riddle 😄

**Comment by csantanapr** [comment]
```
 -p, --param KEY VALUE        default action parameter values in KEY VALUE format (default [])
```

**Comment by csantanapr** [comment]
@dubeejw Now I'm confuse, the CLI usage says that its `--param key value` not -param paramName "{\"key\": \"value\"}"

**Comment by csantanapr** [comment]
Anyway have a JSON with the keys and the values is what I'm proposing. And we can still keep composition if you think is something we can do also like
`wsk action invoke -pf fileparamset1.json -p anotherp pvalue -pf fileparamset2.json`

I say for first stab MVP to support a simple use case first.

**Comment by dubeejw** [comment]
The key is just a name for that parameter, it isn't JSON.

**Comment by dubeejw** [comment]
If we want to provide the ability to create parameters and annotations via ```wsk action create actionName artifactName -pf params.json -af annots.json``` we will need to update the database schema.

**Comment by rabbah** [comment]
as a transition step, the CLI could remap the JSON to the required schema. These two features can be added separately.

**Comment by dubeejw** [comment]
Not sure that parsing the user provided JSON the way we need it for the key/value fields will be possible in Go since it is a strongly-typed language. We are thinking about having the user input from a file be what is sent directly to the REST interface. For example, a file could contain this JSON ```{"paramKey": "paramValue"}```, which would be forwarded to the backend. With our current functionality that would be the equivalent of passing ```-p paramKey paramValue```, which would be converted to ```{"key": "paramKey", "value": "paramValue"}``` before sent to the backend.

**Comment by rabbah** [comment]
Forgive my ignorance - below is my first `go` code. If we read a JSON object and then can separate the key and value pairs, I don't see why the mapping can't happen entirely in the CLI for now.


```
package main

import "encoding/json"
import "fmt"

func main() {
    bytes := []byte(`{"a":"A","b":["B","C"]}`)
    var data map[string]interface{}
    if err := json.Unmarshal(bytes, &data); err != nil {
        panic(err)
    }
    fmt.Println(data)

    keys := make([]string, len(data))
    values := make([]interface{}, len(data))

    i := 0
    for k, v := range data {
       keys[i] = k
       values[i] = v
       i++
    }

    fmt.Println(keys)
    fmt.Println(values)
}
```

```
> go run main.go 
map[a:A b:[B C]]
[a b]
[A [B C]]
```

**Comment by dubeejw** [comment]
@rabbah, yes I was able to achieve the above. From here we need to add the key/value labels, then encode the JSON back into a struct.

**Comment by dubeejw** [comment]
Added key/value labels and encoded the JSON. Will have to test to see if we can go further with this example.

```package main

import "encoding/json"
import "fmt"

type KeyValue struct {
    Key  string 	`json:"key"`
    Value interface{}	`json:"value"`
}

func main() {
    bytes := []byte(`{"a":"A","b":["B","C"], "testBool": false}`)
    var data map[string]interface{}
    if err := json.Unmarshal(bytes, &data); err != nil {
        panic(err)
    }

    keys := make([]string, len(data))
    values := make([]interface{}, len(data))

    i := 0
    for k, v := range data {
       keys[i] = k
       values[i] = v
       
	keyValue := KeyValue{
		Key:  keys[i],
		Value: values[i],

    	}

       p, _ := json.Marshal(keyValue)
       s := string(p)
       fmt.Println("str " + s)

       i++
    }
}```
