### ISSUE TITLE
add ability to distinguish plain actions from sequences at the "list" level

### ISSUE THREAD

**Issue by csantanapr** [openwhisk/openwhisk#427]
From @starpit : 
right now, the `wsk action list` output doesn't not allow me to distinguish sequences from actions, at least for sequences created on the CLI

for sequences created in the UI, i have been adding an annotation `{ key: "isSequence", value: true }`

it'd be great if we could update the CLI to adopt this behavior. otherwise, i cannot know how to render an action, without doing a "get" on it.

**Comment by csantanapr** [comment]
From @rabbah : 
Doing it in the CLI is of course doable but the better place to do this and enforce it is in the controller.

**Comment by rabbah** [comment]
Doing it in the CLI is of course doable but the better place to do this and enforce it is in the controller.

**Comment by csantanapr** [comment]
Thanks that's why I added the API label, I will remove the CLI label since it should be available in API the. All clients can benefit

**Comment by starpit** [comment]
is this doable for BETA? it would help the UI.

**Comment by starpit** [comment]
@perryibm will the new sequence support address this issue?

**Comment by markusthoemmes** [comment]
With the new sequencing, this is related to #522 as sequence is a `kind` now aswell.

**Comment by rabbah** [comment]
Yes but won't work for pre-existing sequences though.

**Comment by starpit** [comment]
Kind won't help anyway with this request, unless there are plans to move kind to the lost level?

**Comment by starpit** [comment]
List level I meant

**Comment by rabbah** [comment]
That's how I interpreted the comment from Markus (put the kind in the view returned by list requests).

**Comment by starpit** [comment]
Ok Awesome!

**Comment by rabbah** [comment]
Fixed by #1497.
