### ISSUE TITLE
Go CLI Receives a Certificate Error from the Local Server

### ISSUE THREAD

**Issue by csantanapr** [openwhisk/openwhisk#428]
From @dubeejw : 

When running Go CLI commands that communicate with the local server a certificate error occurs. This can be solved by enabling the InsecureSkipVerify property for TLS in go-whisk/client.go NewClient(). However, this may not be ideal for security reasons.

Error: 
Get https://172.17.0.1/api/v1/namespaces/whisk.system/packages: x509: certificate has expired or is not yet valid

**Comment by csantanapr** [comment]
From @rabbah : 
deally we just add -i, --insecure option to not verify SSL certificate of API endpoint.

**Comment by rabbah** [comment]
ideally we just add -i, --insecure option to not verify SSL certificate of API endpoint.

**Comment by csantanapr** [comment]
-i is implemented in Go CLI Now closing

**Comment by rabbah** [comment]
What is the default 
Not sure what the GO default is - making insecure false for python CLI is wrong because all of the devs will need to use -i. This is probably something we can put in the config file (for the GO cli). I certainly don't want to type -i all the time.

**Comment by csantanapr** [comment]
Yeah I agree
As part lf a local build we can set the property
We can added to the propeties like
wsk property set --i true

**Comment by mdeuser** [comment]
Just thinking... Do we really want to put a security override in an external properties file?  If that file is hacked or accidentally carried forward, the intended security check can be compromised.

If we leave it as a CLI option only, developers can use `alias wsk='wsk -i'`

**Comment by rabbah** [comment]
i was thinking this is saved in the user's wskprops file. `wsp property set --insecure true`.

**Comment by csantanapr** [comment]
I agree with @rabbah on https://github.com/openwhisk/openwhisk/issues/428#issuecomment-229198377
I can add `wsk property set --insecure true` and we can add to the docs, this way it also works for windows users.

I don't think windows has "alias", it's being a while since I used "windows", and we should not assume they will have `bash` or `cygwin`

**Comment by rabbah** [comment]
done although #1570 is left.

**Comment by g12megha** [comment]
When i try to curl to list the triggers under a namespace by providing the openwhisk-self signed cert along the parameter --cacert, it throws the error of unmatching OPENWHISK_API_HOST. When i try to search this variable, i cannot find it .Where is it defined?  
![wskerror](https://cloud.githubusercontent.com/assets/3980709/23638359/25672158-0296-11e7-82bb-fcf7637b6aa7.JPG)

**Comment by rabbah** [comment]
I think this is a bug in the cert generation: 
https://github.com/openwhisk/openwhisk/blob/master/ansible/setup.yml#L34 ->
https://github.com/openwhisk/openwhisk/blob/master/ansible/roles/nginx/files/genssl.sh#L10

**Comment by csantanapr** [comment]
@rabbah yep it looks like it's missing {{ }} in lookup

**Comment by rabbah** [comment]
With pr #1977, I'm proposing a patch to fix the CN name.

```
$ OPENWHISK_API_HOST=guest.dockerhost redo setup edge
$ wsk action create hello tests/dat/actions/echo.js -a web-export true
$ curl https://guest.dockerhost/api/v1/experimental/web/guest/default/hello.json --cacert /Users/Shared/nginx/openwhisk-cert.pem 
{
  "__ow_meta_verb": "get",
  "__ow_meta_headers": {
    "host": "192.168.99.100:10001",
    "connection": "close",
    "user-agent": "curl/7.43.0",
    "accept": "*/*"
  },
  "__ow_meta_path": ""
}
```

**Comment by csantanapr** [comment]
PR #1977 is now merged
