### ISSUE TITLE
two-phase processing of activation records

### ISSUE THREAD

**Issue by csantanapr** [openwhisk/openwhisk#460]
From @sjfink :
Right now when an activation finishes, we try to drain the logs and create the activation record as an atomic operation.

@rabbah has an idea to split the activation processing into two phases: 1. get the result and then 2. fetch the logs. The idea is that we can return the activation status immediately after step 1. without waiting for step 2., which currently must wait for the dreaded "slack".

Note that we would still not release the container to the pool until step 2. is done. So, the "slack" would not manifest as latency, but it would still impact efficiency since the container would not be reusable until the logs are drained.

**Comment by sjfink** [comment]
done?

**Comment by rabbah** [comment]
https://github.com/openwhisk/openwhisk/pull/868 Yes.

**Comment by rabbah** [comment]
To clarify - done for blocking invokes (fast response is sent to client and logs/activation record written later).
