### ISSUE TITLE
refactor util/cat into only doing join and create a new split action

### ISSUE THREAD

**Issue by csantanapr** [openwhisk/openwhisk#467]
Currently `cat` does both split and join. It makes sense to have separate `split` and `join` functions.

leaving `join` as `cat` so it doesn't have to be removed from catalog, just the function `split` is moved into a new action `util/split.js`

for `split` the separator is hardcoded to default `/\r?\n/` and we can make it an optional parameter for user to overwrite default.

**Comment by csantanapr** [comment]
TODO on this workitem is to search the docs and see if they need updating.

**Comment by jasonpet** [comment]
Code is done for this as part of issue #466.  All that remains is a doc update in the actions.md file.
