### ISSUE TITLE
discussion: relax convention on main() entrypoint in javascript

### ISSUE THREAD

**Issue by sjfink** [openwhisk/openwhisk#47]
One user has suggested that forcing the action method to be main() is too constraining and we should allow the user to specify the main method.

Originally we did this via module.exports.    As we move to support more languages, it may be better to define a language-neutral attribute on actions.   

Alternatively, we could decide not to support this.

**Comment by markusthoemmes** [comment]
Any details on what is constraining about it?

**Comment by mbehrendt** [comment]
imho, it feels unnatural to prescribe a 'main' function to exist in js code

**Comment by markusthoemmes** [comment]
@sjfink Can you elaborate what you meant with "it may be better to define a language-neutral attribute on actions".

The way I understand it is: We would have a CLI parameter which determines the entry point for the script like we do in Java but in a standardized way for all languages?

Additionally, several languages could make use of their own ecosystem specificities (like `module.exports` in Node) to lift hard-coded `main` requirement.

**Comment by csantanapr** [comment]
I think we should think of the UX as a developer focusing in a specific language, and then later see what's common across.
For example me a NodeJS fanboy :-) , I have the same complaint that forcing me to create a function and name it `main` is not natural, also not natural not allowing me to export my action thru as the module using `module.exports`

We should start with good and simple way, to allow to export the module as the action function like:
```
//es6
module.exports = (params)=> params;
//es5
module.exports = function (params) {return params};
```
I like that zip nodejs actions today use `module.exports` but I don't like this `module.exports.main`
Why the extra `main` ? Not need it I think. I prefer the anonymous (just a preference :-)) 
I know that lambda and other have this extra level like `modules.exports.handler`, I think having the extra handler is OK but not necessary as a base level to get started with simple actions.

For nodejs we can have customization with nice fall back defaults allowing for backwards compatibility.

Let's say we added a property to the action metadata call `Handler: string`
If Handler is defined (let's say `Handler: 'handler'`) then we assume user did this:
```
module.exports.handler = (params)=> params;
``` 
Then if Handler is not defined we can check for `main` to see if user did this (for backwards compatibility, or deprecated)
```
module.exports.main = (params)=> params;
```
Then if Handler not defined, and no function in `module.exports.main`, then we can check if the user exported the action as the module like
```
module.exports = (params)=> params;
```

One more benefit or having a metadata `Handler` also allows for folks getting in the serverless space to try out openwhisk re-using code where they are already exporting a [named function](https://darrenderidder.github.io/talks/ModulePatterns/#/7)

**Comment by sjfink** [comment]
@markusthoemmes "it may be better to define a language-neutral attribute on actions" -- I'm imagining an attribute called "entrypoint" (or something) in the standard scheme for all actions.

**Comment by csantanapr** [comment]
@sjfink this "entrypoint" is what I'm referring in my comment https://github.com/openwhisk/openwhisk/issues/47#issuecomment-261955764 as `Handler` we are same page on that, but would like it to see it as an optional thing, not required at least for nodejs.

**Comment by sjfink** [comment]
@csantanapr I'm discussing only the schema for action records in our cloudant database -- just an implementation detail -- not anything user-visible.

**Comment by jthomas** [comment]
It would be nice to support both 
`module.exports =`
and 
`module.exports.handler =`
where handler is a user-defined value as this would make it easier to migrate functions over from Azure and Lambda.

**Comment by psuter** [comment]
As of #1544 you get to name your entrypoint. This applies to both single-script actions:

    function myMain(args) = { ... }

...and Node module actions:

   ...
   modules.exports.myHandler = ...

Both are achieved through the `--main` flag with the CLI. The pattern is the same for Swift and Python, and for Java `--main` specifies the fully-qualified class name.

We do not support `module.exports = function (args) { ... }` (i.e. top-level export is treated as main).

I move to mark as resolved?
