### ISSUE TITLE
Error messages thrown by single actions get lost in the context of sequences

### ISSUE THREAD

**Issue by csantanapr** [openwhisk/openwhisk#473]
From @nauerz-ibm : 
Error messsages that occur inside of an action within a sequence are not returned back to the invocation. A generic "fatal application error" message is returned that does not help the developer identify the root of the error. You can only find the real error if you invoke the action directly (outside of a sequence).

**Comment by ioana-blue** [comment]
@rabbah With the new implementation the error from an action will be propagated to the encapsulating sequence. I think we have tests for this. Close if you agree.

**Comment by rabbah** [comment]
There does appear to be a gap with internal errors not surfacing correctly. Will open a separate issue. The history for that comment dates back to pipe.js.
