### ISSUE TITLE
cloudant configuration checker tool

### ISSUE THREAD

**Issue by csantanapr** [openwhisk/openwhisk#475]
From @sjfink : 
We should have a script run as part of deployment that checks that the cloudant configuration is kosher. These checks should include that the username/password are valid, that the required databases and indices exist, the subjects table meets its invariants, and anything else that a user can screw up.

We have `openwhisk/config/dbSetup.sh` but we need another script
1. Added bogus username in openwhisk/cloudant-local.env

provide a standalone tool /script that checks that a users cloudant configuration is valid, including all the properties listed above.
I'd like this so that when a user complains "wsk cli is giving me an error", we ask them to run "checkDatabase.sh" to rule out misconfigured or corrupted databases.

**Comment by rabbah** [comment]
This can be done as part of `wskadmin db` operations, e.g., `wsadmin db verify`.

**Comment by rabbah** [comment]
`wskadmin db get -h`.
