### ISSUE TITLE
python code with C-style comments gives "action did not return a JSON object" error

### ISSUE THREAD

**Issue by starpit** [openwhisk/openwhisk#493]
expected: "parse error"
instead received: "action did not return a JSON object" as the error message

**Comment by ioana-blue** [comment]
I'm guessing the compilation fails and, as a result, when the action is run, an error is thrown, not the expected json is returned and the error above is sent to the user. Not sure how to fix this. Perhaps compile the code ahead of time and check it compiled properly and if that's not the case try to send a different error as part of initialization?

**Comment by rabbah** [comment]
can't you wrap with a try and report error as response?

**Comment by starpit** [comment]
i think this could work? if i recall, the "ugly whisk stack trace" part of the error response gave an indication of the problem, it's just the top level error message whisk returns is deceptive.

**Comment by ioana-blue** [comment]
there is probably a try already. it might work, but not sure how to differentiate between compilation error or other type of error. if we just want to capture "error with code", that's probably easier.

**Comment by starpit** [comment]
hmm, now i'm getting a different response. i'll continue to try to replicate my original error message. this one is pretty close, though it'd be nice to find a way to avoid displaying internal stack traces to the user.

```
{
  "error": "Initialization has failed due to: SyntaxError: Unexpected token ILLEGAL\n    at new NodeActionRunner (/nodejsAction/runner.js:32:21)\n    at doInit (/nodejsAction/src/service.js:129:22)\n    at initCode (/nodejsAction/src/service.js:62:39)\n    at safeEndpoint (/nodejsAction/app.js:57:13)\n    at Layer.handle [as handle_request] (/nodejsAction/node_modules/express/lib/router/layer.js:82:5)\n    at next (/nodejsAction/node_modules/express/lib/router/route.js:110:13)\n    at Route.dispatch (/nodejsAction/node_modules/express/lib/router/route.js:91:3)\n    at Layer.handle [as handle_request] (/nodejsAction/node_modules/express/lib/router/layer.js:82:5)\n    at /nodejsAction/node_modules/express/lib/router/index.js:267:22\n    at Function.proto.process_params (/nodejsAction/node_modules/express/lib/router/index.js:321:12)"
}
```

**Comment by starpit** [comment]
here is the example code i used for my previous comment:
```
/**
  *
  * main() will be invoked when you Run This Action.
  * 
  * @param Whisk actions accept a single parameter,
  *        which must be a JSON object.
  *
  * @return The return value must also be JSON.
  *         It will be the output of this action.
  *
  */
import sys

def main(dict):
    if 'message' in dict:
        name = dict['message']
    else:
        name = 'stranger'
    greeting = 'Hello ' + name + '!'
    print(greeting)
    return {'greeting':greeting}
```

**Comment by rabbah** [comment]
Looking at the python action, the `init` accepts the input unchecked. I would lift the eval to init and return an appropriate error if it fails: that will allow you to dictate that it was bad code vs a bad run.

**Comment by rabbah** [comment]
The stack trace suggests you're running as a node action not Python.

**Comment by starpit** [comment]
```
        "2016-05-24T23:07:40.172012449Z stderr: Traceback (most recent call last):",
        "2016-05-24T23:07:40.17210871Z  stderr: File \"pythonaction.py\", line 63, in run",
        "2016-05-24T23:07:40.172148171Z stderr: exec(flask.g, namespace)",
        "2016-05-24T23:07:40.172167695Z stderr: File \"<string>\", line 1",
        "2016-05-24T23:07:40.172178694Z stderr: /* */",
        "2016-05-24T23:07:40.172510231Z stderr: ^",
        "2016-05-24T23:07:40.172537692Z stderr: SyntaxError: invalid syntax"
```

**Comment by starpit** [comment]
that is the logs field, which points exactly at the problem, whereas the response field has
```
    "response": {
        "result": {
            "error": "the action did not return a dictionary"
        },
        "status": "action developer error",
        "success": false
    },
```
