### ISSUE TITLE
alarm example is wrong on docs

### ISSUE THREAD

**Issue by csantanapr** [openwhisk/openwhisk#496]
catalog.md contains the following example

It contains the following example for 8th day of the month
```
* * * 8 * *: sometime on the eighth day of every month
```

This is not clear, this actually runs every second for the whole day. It's better to give a more clear example
```
`0 0 9 8 * *`: at 9:00:00AM (UTC) on the eighth day of every month
```

```
 $ wsk trigger create periodic --feed /whisk.system/alarms/alarm --param cron '/20 * * * * *' --param trigger_payload '{"name":"Odin","place":"Asgard"}'
```
Produces the following error:
alarm: Error invoking whisk action: 400 { error: 'cron seems to be malformed' }"

It should be `*/20` not `/20` to specify every 20 seconds

**Comment by lzbj** [comment]
@csantanapr , the document is helpful, but under the catalog folder I didn't find the alarm action or feed, is it installed by default?

**Comment by csantanapr** [comment]
@lzbj there is an issue open and we will be working bring the alarm package to open source soon

**Comment by lzbj** [comment]
Thank you.
