### ISSUE TITLE
wsk activation poll with a parameter will get no response.

### ISSUE THREAD

**Issue by lzbj** [openwhisk/openwhisk#499]
I followed the doc:
https://github.com/openwhisk/openwhisk/blob/e5c4e58f8dfe63601f5e4395e7582b626c426678/docs/packages.md#creating-and-using-trigger-feeds

then I wrongly typed the command 
wsk activation poll activationID,

I got below output, but it seems the poll not responding.
Hit Ctrl-C to exit.
Polling for logs

The correct command should be:
wsk activation result activationID
Then I can get result.

So is it a issue? I searched the issues list title before open this one, sorry if duplicated.

**Comment by rabbah** [comment]
```
> wsk activation poll -h
usage: wsk activation poll [-h] [-u AUTH] [-e EXIT] [-ss SINCE_SECS]
                           [-sm SINCE_MINS] [-sh SINCE_HRS] [-sd SINCE_DAYS]
                           [name]

positional arguments:
  name                  the namespace to poll
```

The value you provided is interpreted by the CLI as a namespace. Since it's a namespace that doesn't exist, you get an empty activation list.

**Comment by lzbj** [comment]
Ah, got it, thank you, I'll close it.
