### ISSUE TITLE
stop mounting filesystem from vagrant host

### ISSUE THREAD

**Issue by sjfink** [openwhisk/openwhisk#5]
Right now the instructions say to git clone on the host, then map the filesystem into the virtual machine.

This is problematic on Windows where the host filesystem permissions are inconsistent with Linux/Mac.

Instead:   change the directions to simply wget our Vagrantfile (or just download it if wget not available), and then do the git clone directly to the filesystem inside the Ubuntu VM.

**Comment by rabbah** [comment]
@vinodmut @sjfink for your review #26.

**Comment by rabbah** [comment]
Fixed in this commit: https://github.com/openwhisk/openwhisk/commit/3b51155c11276ed8ccaaa786aa697f7dbb0e7ed8
