### ISSUE TITLE
ios app example with sdk should be available in open source

### ISSUE THREAD

**Issue by csantanapr** [openwhisk/openwhisk#502]
[docs/mobile_sdk.md](https://github.com/openwhisk/openwhisk/blob/master/docs/mobile_sdk.md) point that user can get ios sample app with sdk included.

>You can use the OpenWhisk CLI to download example code that embeds the OpenWhisk SDK framework. To install the starter app example, enter the following command:

```
wsk sdk install ios
```

Running this after setting up openwhisk on local system produces errors
```
$ wsk sdk install ios
Unknown SDK component: ios
```

**Comment by houshengbo** [comment]
I will take this issue. Thank you, Carlos.

**Comment by csantanapr** [comment]
close with 75f6615e37b54a7a9d01272c2cac60570fb787b2
