### ISSUE TITLE
Confusing error message from Whisk server on an invalid 'package bind' CLI

### ISSUE THREAD

**Issue by mdeuser** [openwhisk/openwhisk#506]
$>wsk package bind nonexistentpkg mypkgbinding
error: not found on 'get' (code 900656)

The "not found on 'get'" is a bit confusing to the end user.  In my experience, if this command is run multiple times, the numeric code changes.

Running the CLI with the -v option shows that this error message is originating from the Whisk server.
```RESPONSE:
Got response with code 400
Body received:
{
  "error": "not found on 'get'",
  "code": 898071
}

**Comment by mdeuser** [comment]
The CLI output should be beefed up to certainly say that the 'package bind' failed; however, the root cause at this point (i.e. specified package does not exist) should be more clear.  When using CURL, our CLI is out of the picture and the only error details would be in the HTTP response.

**Comment by rabbah** [comment]
@mdeuser the controller was missing a case match against this scenario to tailor the error message. I added a path for this in the above patch.

```
wsk package bind nonexistentpkg mypkgbinding
error: binding specified a package that does not exist (code 3)
```
