### ISSUE TITLE
packages.md describes how to use Cloudant package which does not exist in OpenWhisk

### ISSUE THREAD

**Issue by mrutkows** [openwhisk/openwhisk#514]
Please see issue [336](https://github.com/openwhisk/openwhisk/issues/336) as this might resolve the issue; however it has been backlogged for 21 days as of this authoring.

The file docs/[packages.md](https://github.com/openwhisk/openwhisk/blob/master/docs/packages.md) assumes that both **cloudant** and **alarms** packages are available (neither are).

Therefore steps: 
2. _Get a list of entities in the /whisk.system/cloudant package._
`$ wsk package get --summary /whisk.system/cloudant`

and:
3. _Get a description of the /whisk.system/cloudant/read action._
`$ wsk action get --summary /whisk.system/cloudant/read`

of course, will never work for the user (if it wasn't apparent from step 1. which shows a package list that does not include these missing packages).

In addition, for open source, we should likely have **couchdb** be the default example (and provide **cloudant** as an alternative).  In any event, we need to be aware that the openwhisk user doc on packages is not usable until this the corresponding package is made available.

I am happy to open another issue to default to **couchdb** over **cloudant** if you like.

**Comment by rabbah** [comment]
@csantanapr since we now have a cloudant package in the open can we address this high priority issue? otherwise remove the label?

**Comment by csantanapr** [comment]
cloudant repo and docs https://github.com/openwhisk/openwhisk-package-cloudant
