### ISSUE TITLE
packages.md describes how to use Alarm package which does not exist in OpenWhisk

### ISSUE THREAD

**Issue by mrutkows** [openwhisk/openwhisk#515]
Please see issue [390](https://github.com/openwhisk/openwhisk/issues/390) as this might resolve the issue; however it has been backlogged for 14 days as of this authoring.

The file docs/[packages.md](https://github.com/openwhisk/openwhisk/blob/master/docs/packages.md) assumes that both **cloudant** and **alarms** packages are available (neither are).

Therefore the entire section titled:

**Creating and using trigger feeds**
All steps assume use of alarm trigger:
1. Get a description of the feed in the /whisk.system/alarms package.
   `$ wsk package get --summary /whisk.system/alarms`
2. Create a trigger that fires every eight seconds.
   `$ wsk trigger create everyEightSeconds --feed /whisk.system/alarms/alarm -p cron '*/8 * * * * *' -p trigger_payload '{"name":"Mork", "place":"Ork"}'`

and all subsequent steps will not work... (if it wasn't apparent from step 1. which shows a package list that does not include these missing packages).

**Comment by csantanapr** [comment]
alarm repo and docs now here https://github.com/openwhisk/openwhisk-package-alarms
