### ISSUE TITLE
Provide a way to return "Kind" when fetching the actions from the backend

### ISSUE THREAD

**Issue by eweiter** [openwhisk/openwhisk#522]
In the UI there is a new table being developed to provide users with a tabular way to manage their entities.  

For the actions section there is a field that was expected which is the "kind" of the action (NodeJS, Swift, Java, etc).  Currently on the high level fetch of the actions the resultant data does not contain the "kind" of the action.  In order to get the "kind" a successive GET call has to made on each action that is in the list.  This is excessive for the UI.

Two solutions that were proposed are:
1) Update the schema to return the "kind" of the action in the high-level fetch of the actions.
2) Provide a new another possibility is to add a bulk query/filter API for this
e.g. filter: “select \* from actions where exec.kind=swift”; e.g. bulk query “select exec.kind from actions"

Either one of these will satisfy what we are trying to accomplish in the UI.

**Comment by csantanapr** [comment]
@eweiter I think both are good things to enhance API with.

I think option 1 is easier to implement than 2, and not much design need it.
The second one about query, I think it needs more design, as it's a query support in the API but I think it can be implemented across all entities and not just actions. And the query could be in different properties not just kind for action.

**Comment by rabbah** [comment]
@eweiter I did this some time ago - confirm and close?

**Comment by eweiter** [comment]
@rabbah 
I wasn't aware this was done but I just tested it and it doesn't appear that the kind is being returned in the api call to fetch all the actions.  I know work was done to expose sequence actions from that call. 

This is still needed and it would be nice to have the memory and timeout included as well as the time.  Those are the three fields currently needed for the Manage page that require the additional fetch for each action a user has. 

In the api call that returns all the actions as a list each action object only has
![image](https://cloud.githubusercontent.com/assets/19595703/22254328/47976e2a-e222-11e6-9012-73b8e2082744.png)

**Comment by eweiter** [comment]
I was incorrect above.  As you can clearly see the action has the field "exec" which has the action's kind, which is "nodejs:6".  Closing this issue now.
