### ISSUE TITLE
Ephemeral CouchDB needs to be manually created each time for redeploy

### ISSUE THREAD

**Issue by houshengbo** [openwhisk/openwhisk#532]
After the first time we successfully deploy the OpenWhisk by vagrant, the default ephemeral CouchDB does not stay consistent when we try "ant redeploy", because it would be removed as the docker get cleaned up. The only way to fix it is to run ant clean build, launch a new CouchDB, create the database again and run ant deploy.

We need to keep the ephemeral CouchDB from deleting, when we do ant redeploy, to make sure ant redeploy is valid.

**Comment by csantanapr** [comment]
closing with 3796dbeeef9dd882b3b7d94e21ca4ff3de09af94
