### ISSUE TITLE
DOCKER_HOST not set after the first vagrant up

### ISSUE THREAD

**Issue by houshengbo** [openwhisk/openwhisk#533]
When running the commands like "docker ps", we will see the message "Cannot connect to the Docker daemon. Is the docker daemon running on this host?"

The root cause is that the env variable DOCKER_HOST is not set. We should fix it during the vagrant set up.

**Comment by houshengbo** [comment]
I am able to work on it. Please assign it to me.

**Comment by csantanapr** [comment]
This also fixes the another problem @mdeuser found today running `ant redeploy` docker will not be able to run correctly and fail to clean the docker instances.

**Comment by csantanapr** [comment]
merged #544
