### ISSUE TITLE
Users can't tell if their action is terminated because of action time limit

### ISSUE THREAD

**Issue by csantanapr** [openwhisk/openwhisk#550]
I have seeing two users report this, as they try to figure out why their actions are failing.

I'm not sure if we already print to stderr logs, so they can easily tell from the logs that action was terminated.
Also from activation id information might be another way to inform them that activation was terminated because it reach limit.

cc @rabbah @markusthoemmes

**Comment by rabbah** [comment]
The activation start and end times in the activation record will allow a user to know: if `end - start >= action limit` then it was a time out vs an application error. We could adjust the error message accordingly.

**Comment by ryanjbaxter** [comment]
I think having an error message/code that indicates a timeout error as opposed to the current error which just indicates that the action did not return valid json, would be a better way of handling the situation

**Comment by csantanapr** [comment]
having user do calculation on end - start, it's too low level, I agree error message is more usable to users.

**Comment by mbehrendt** [comment]
+1

on top of that, should there be a corresponding error code, eg a 504?

**Comment by csantanapr** [comment]
I think having the 3 are very useful 
1. return code
2. return string
3. stderr message in user logs (user will see it in `wsk activation poll` or UI console)

**Comment by rabbah** [comment]
I favor doing _only_ 2 from the list above. 

We can achieve `3` by projecting the error from the activation during an activation poll. 

We return `BadGateway` already for application/developer errors including actions that timeout and don't produce a response. Consider this nodejs action as an example `function main() { return whisk.async(); }`. This is a developer error and the action will timeout.

**Comment by csantanapr** [comment]
I'm OK not writing to stderr 3 above, if we can achieve goal of letting user know what happens when his running `wsk activation poll`

**Comment by rabbah** [comment]
The error message will now indicate the action timed out. `3` from above is not yet done.

**Comment by markusthoemmes** [comment]
As @rabbah mentioned, warnings are in place. @csantanapr close?

**Comment by rabbah** [comment]
The status code returned by an invoke is covered by #645.
To generate a message in the wsk activation poll, if the result of the activation is an error, it could be printed to the console. This would be the last remaining bit from the items listed in this issue.
