### ISSUE TITLE
Make bash scripts cross platform and more powerful

### ISSUE THREAD

**Issue by csantanapr** [openwhisk/openwhisk#552]
Some scripts have potential to be useful across Windows, Linux and Mac.
They are currently written in bash which makes them not suitable for Windows, and at the same time not powerful enough to handle executing commands and handle input and outputs.

Some example are the catalog package installation scripts:

```
./catalog/installCatalog.sh
./catalog/installGit.sh
./catalog/installSlack.sh
./catalog/installSystem.sh
./catalog/installWatson.sh
./catalog/installWeather.sh
./catalog/util.sh
```

Converting these scripts to higher level language like nodejs will be a well receive enhancement
I think nodejs it would be better converting from bash to nodejs, using modules like [shelljs](https://www.npmjs.com/package/shelljs) making it easy and readable code when it comes on execute and handling stdout and stderr.

Related to discussion in #484

**Comment by markusthoemmes** [comment]
We previously preferenced python for the task of replacing our bash scripts. I personally found it way easier to write little scripts in python due to the non-async nature of the language.

**Comment by csantanapr** [comment]
@markusthoemmes With [shelljs](https://www.npmjs.com/package/shelljs) you write the scripts in a non-async way, that's why their are easy. 

Like
```
require 'shelljs/global'

if (exec `wsk action install ${CATALOG_HOME}/slack/post.js" slack/post`).code != 0
  echo 'Error: wsk commit failed'
  exit 1
```

In summary both python and nodejs can be use to write synchronous looking scripts.
My team is more familiar with nodejs, but with wsk we are getting familiar with all programming languages 😸

**Comment by rabbah** [comment]
@csantanapr should be in openwhisk-catalog.

**Comment by markusthoemmes** [comment]
Issue moved to [openwhisk/openwhisk-catalog #205](https://github.com/openwhisk/openwhisk-catalog/issues/205) via [**ZenHub**](https://www.zenhub.com/)
