### ISSUE TITLE
Allow actions to return JS Promise directly

### ISSUE THREAD

**Issue by jthomas** [openwhisk/openwhisk#56]
With Promises now part of the JS standard library (ES6 onwards+), it would be nice to replace the return value for async actions from the whisk function calls to a native Promise. See the example below. 
This would have many benefits for the user including allow them to directly return responses from many third-party modules that return Promises without having to add unnecessary boilerplate to handle the response and then return. 

<pre>
function main() {
   setTimeout(function() {
       return whisk.done({done: true});
   }, 20000);
   return whisk.async();
}
</pre>

to....

<pre>
function main() {
   return new Promise(function (resolve, reject) {
       setTimeout(function() {
           resolve({done: true});
       }, 20000);
   })
}
</pre>

**Comment by sjfink** [comment]
As mentioned in the discussion on PR #78,   we currently plan to revisit this after supporting Node 6

**Comment by csantanapr** [comment]
Now that we support NodeJS6 we can start work on this.
Also according to http://node.green/ we should be able to support Promises in NodeJS 0.12
@jasonpet did this work but his taking a well deserve break, and I think this is something that @bjustin-ibm can pick up

cc @browezilla

**Comment by csantanapr** [comment]
I recommend that we mark deprecated whisk.async() and whisk.done() once we get this in.
We can also discuss the ability to support callback as a parameter in addition of supporting Promises like: 
```
function main(params, context, callback) { 
... }
```

**Comment by csantanapr** [comment]
@tuler this might be a topic that might interest you.
