### ISSUE TITLE
Integration of tests from Packages in their own repo

### ISSUE THREAD

**Issue by nwspeete-ibm** [openwhisk/openwhisk#562]
Tests from their own repo will be cloned into openwhisk from a .sh script. A "tests/" folder should be included in packages in their own repo.  One idea for test integration into openwhisk is to have the build.xml copy the tests to openWhisk/tests/src/package directory. @rabbah @csantanapr what are your thoughts?

**Comment by csantanapr** [comment]
@nwspeete-ibm why the need to copy into `tests/src/package` ? 
Why not just leave the source code for the tests in place `catalog/wsk-pkg-pushnotifications/tests/` and configure gradle to resolve dependencies and run the tests.

**Comment by nwspeete-ibm** [comment]
@csantanapr leaving the tests in catalog/wsk-pkg-pushnotifications/tests/ is a valid option.  @rabbah can we all agree on this option?

**Comment by nwspeete-ibm** [comment]
We all agreed on leaving the tests in catalog/wsk-pkg-pushnotifications/tests/ . Will work on a way to configure gradle to resolve dependencies and run the tests.

**Comment by nwspeete-ibm** [comment]
VCAP_SERVICES property must be set in open ,  or set this property in whisk.propeties;
vcap.services.file=

**Comment by nwspeete-ibm** [comment]
Tests integrated into blue for push.
