### ISSUE TITLE
whisk CLI updates action with a nonexistent file

### ISSUE THREAD

**Issue by MandyYan** [openwhisk/openwhisk#565]
When I tried to update an existing action with an nonexistent file, the update succeeds. I think it should give me an error showing that the file doesn't exist.

**Comment by rabbah** [comment]
Confirmed - this is related to an ambiguity in the positional argument in the CLI on an update.
Thanks for reporting this.

**Comment by mdeuser** [comment]
I'll take this one.  Since the Go CLI and tests are not yet full incorporated right now, I'll add a test and fix the python CLI as well.

**Comment by mdeuser** [comment]
Fixed via PR #862
