### ISSUE TITLE
Discuss support for different type of payload format for fire (trigger) and invoke (action)

### ISSUE THREAD

**Issue by csantanapr** [openwhisk/openwhisk#567]
Related to different types of Feeds, can produce events with payload, see #559 for background info.

Today `application/json` is the only format supported.

We can support other use cases by supporting other type of formats.

Please discuss here use cases and formats to support.

cc @sjfink @mbehrendt

**Comment by mbehrendt** [comment]
msg types; we need to support msg types like application/x-www-form-urlencoded (see https://api.slack.com/slash-commands)

event payload:
i think we should consider having some canonical attributes, such as 
- event source type
- event source instance guid
- timestamp
- maybe more

we need to investigate how this ca be realized without changing the msg payload coming from the source (we need to expect people will want to reuse existing code snippets for parsing the webhook msg)

**Comment by rabbah** [comment]
One way to do this is via the controller imposing a mapping from a form or query string into a json object.

**Comment by csantanapr** [comment]
@rabbah In the short term can we at the minimum start by supporting invoking an action with `application/x-www-form-urlencoded` in addition of what we have today `application/json` ?

This will allow Slack commands to work, and any other webhooks that only support `application/x-www-form-urlencoded`

How much effort would this be? In which controller class is the change required?

**Comment by rabbah** [comment]
@csantanapr with web support coming via #1715 do we still need this?
