### ISSUE TITLE
Deploy travis using ansible

### ISSUE THREAD

**Issue by domdom82** [openwhisk/openwhisk#572]
This spawned off #560 to make logical separation between changes to travis and changes to how blackbox and ios sdks are deployed.

This issue covers only the travis change. 

Travis should conform to our overall strategy to deploy with ansible.

- [x] build using gradle
- [x] deploy using ansible
- [x] for time being, test still executed using ant

**Comment by markusthoemmes** [comment]
Is there a reason to continue to execute tests via ant?

**Comment by domdom82** [comment]
Not really. Just not in scope for this issue. Needs to be swapped to gradle on all other occasions as well.
