### ISSUE TITLE
CLI should support http proxy

### ISSUE THREAD

**Issue by csantanapr** [openwhisk/openwhisk#586]
The CLI connects directly to the API HOST on default port 443
But if the user needs to use an http proxy (very typical inside corporations) the CLI needs to provide a way for the user to use the WSK CLI.

We should take same approach as CF CLI, using an environment variable
https_proxy

```
If you have an HTTP proxy server on your network between a host running the cf CLI and your Cloud Foundry API endpoint, you must set https_proxy with the hostname or IP address of the proxy server.

The https_proxy environment variable holds the hostname or IP address of your proxy server.

https_proxy is a standard environment variable. Like any environment variable, the specific steps you use to set it depends on your operating system.

Format of https_proxy
https_proxy is set with hostname or IP address of the proxy server in URL format: https_proxy=http://proxy.example.com

If the proxy server requires a user name and password, include the credentials: https_proxy=http://username:password@proxy.example.com

If the proxy server uses a port other than 80, include the port number: https_proxy=http://username:password@proxy.example.com:8080


```

**Comment by csantanapr** [comment]
Some more notes
It looks like http_proxy is something that the golang http library handles, user can use both HTTP_PROXY or http_proxy

If we use the golang net http library to connect to openwhisk API it should be easy to implement, but as always we will need to write some test cases to have confident in the integration.

cc @dubeejw @mdeuser

**Comment by rabbah** [comment]
Closed by #612.

**Comment by rabbah** [comment]
The Go CLI may not have this feature, and #612 did not add a test when this feature was added to the Python CLI.

@mdeuser @dubeejw FYI.

**Comment by rabbah** [comment]
Added for Python CLI with tests as part of #925 as I ran into the need for this. There is a tangentially related issue for the Go CLI in #924.

**Comment by dubeejw** [comment]
It looks like setting an environment variable for HTTP_PROXY, or HTTPS_PROXY will cause the Go CLI to use a proxy. Would need a proxy to verify this though.

**Comment by rabbah** [comment]
```
Starting test Wsk CLI usage should show api build using http apihost at 2016-07-30 11:07:53.774
expected exit code = 0
exit code = 3
stdout: whisk API host		 
whisk API build		 Unknown

stderr: error: Unable to obtain API build information: Request failure: Get https:///api/v1: http: no Host in request URL
```

**Comment by csantanapr** [comment]
@dubeejw @mdeuser supporting http proxy very important to users behind corporate firewall.

**Comment by dubeejw** [comment]
@csantanapr, I believe @rabbah comment above is not related to proxy support. As I stated above we need a proxy to test with.

**Comment by csantanapr** [comment]
@dubeejw OK, I think I miss interpreted @rabbah comments then.
I think using a container that runs the proxy for our tests will be ideal.

**Comment by dubeejw** [comment]
@csantanapr, I believe the HTTP transport package we are using supports HTTP, and HTTPS proxies by default. I do not believe SOCKS5 is supported. Here's an excerpt from the package's documentation (https://golang.org/pkg/net/http/).

```
DefaultTransport is the default implementation of Transport and is used by DefaultClient. It establishes network connections as needed and caches them for reuse by subsequent calls. It uses HTTP proxies as directed by the $HTTP_PROXY and $NO_PROXY (or $http_proxy and $no_proxy) environment variables.
```

**Comment by dubeejw** [comment]
@csantanapr, looks like CF utilizes the same technique for proxy support. Here's a link to their doc: https://docs.cloudfoundry.org/cf-cli/http-proxy.html.

**Comment by csantanapr** [comment]
Yes I was aware of CF CLI and BluemIx CLI supporting some soft of http proxy.
OK So it looks like all we are todo is document the support similar to bluemix

>Note: If your network contains an HTTPS proxy server between the host that runs the CLI and the Bluemix, you must specify the host name or IP address of the proxy server by setting the HTTPS_PROXY environment variable.

**Comment by dubeejw** [comment]
HTTPS proxy support definitely works currently with the Go CLI, I just tried it out.

**Comment by csantanapr** [comment]
@dubeejw want to close this one?
