### ISSUE TITLE
Add new action for Watson Natural Language Classifier

### ISSUE THREAD

**Issue by csantanapr** [openwhisk/openwhisk#587]
Add new action for Watson Natural Language Classifier
Related to #365 
Ref: http://www.ibm.com/smarterplanet/us/en/ibmwatson/developercloud/nl-classifier.html

**Comment by markusthoemmes** [comment]
@csantanapr move to catalog?

**Comment by markusthoemmes** [comment]
Issue moved to [openwhisk/openwhisk-catalog #208](https://github.com/openwhisk/openwhisk-catalog/issues/208) via [**ZenHub**](https://www.zenhub.com/)
