### ISSUE TITLE
Add new action for Watson Retrieve and Rank 

### ISSUE THREAD

**Issue by csantanapr** [openwhisk/openwhisk#588]
Add new action for Watson Retrieve and Rank
Related to #365 
http://www.ibm.com/smarterplanet/us/en/ibmwatson/developercloud/retrieve-rank.html

**Comment by markusthoemmes** [comment]
@csantanapr move to catalog?

**Comment by markusthoemmes** [comment]
Issue moved to [openwhisk/openwhisk-catalog #207](https://github.com/openwhisk/openwhisk-catalog/issues/207) via [**ZenHub**](https://www.zenhub.com/)
