### ISSUE TITLE
Add new action for Watson Document Conversion 

### ISSUE THREAD

**Issue by csantanapr** [openwhisk/openwhisk#589]
Add new action for Watson Document Conversion 
Related to #365 
http://www.ibm.com/smarterplanet/us/en/ibmwatson/developercloud/document-conversion.html

**Comment by markusthoemmes** [comment]
@csantanapr move to catalog?

**Comment by markusthoemmes** [comment]
Issue moved to [openwhisk/openwhisk-catalog #206](https://github.com/openwhisk/openwhisk-catalog/issues/206) via [**ZenHub**](https://www.zenhub.com/)
