### ISSUE TITLE
cloudant action annotations for dbname erroneously omit bindTime: true

### ISSUE THREAD

**Issue by starpit** [openwhisk/openwhisk#593]
we would like a way to distinguish `dbname` as a special parameter, one that we suggest the user provide at package binding time, rather than invocation time.

for example, the `read-document` action throws an exception if `dbname` is not provided, and it is unlikely that in normal scenarios `dbname` will be provided as input from a prior action in a sequence, or by a trigger as part of a rule.

whereas the `docID` field is much more likely to be in-flow data. therefore, `dbname` should be prompted for at package binding time

**Solution**: every cloudant action that specifies `dbname` as required should also specify it as **bindTime: true**

**Comment by starpit** [comment]
ugh, never mind

**Comment by starpit** [comment]
All of the cloudant actions that specify dbName as required must also specify bindTime: true

**Comment by markusthoemmes** [comment]
@csantanapr move to catalog?

**Comment by markusthoemmes** [comment]
Issue moved to [openwhisk/openwhisk-package-cloudant #67](https://github.com/openwhisk/openwhisk-package-cloudant/issues/67) via [**ZenHub**](https://www.zenhub.com/)
