### ISSUE TITLE
Provide steps to re-deploy after restarting Vagrant VM

### ISSUE THREAD

**Issue by lfzCarlosC** [openwhisk/openwhisk#596]
problem description
--------------------------
For Hello case 
./wsk action invoke /whisk.system/samples/echo -p message hello --blocking --result

returns   "error: [Errno 111] Connection refused"

steps to reproduce
--------------------------
1. Clone openwhisk
git clone --depth=1 https://github.com/openwhisk/openwhisk.git

2. Change directory to tools/vagrant/simple
cd openwhisk/tools/vagrant/simple

3. Run script to create vm and run hello action
vagrant up 
./wsk action invoke /whisk.system/samples/echo -p message hello --blocking --result

**Comment by lfzCarlosC** [comment]
I try the quickcase following  the guide         https://github.com/openwhisk/openwhisk

**Comment by lfzCarlosC** [comment]
I run it locally on my laptop

**Comment by csantanapr** [comment]
Hi @lfzCarlosC could you provide more info on your environment to be able to reproduce?

I tried today with latest hash `bf3fe240ff56f772837f7c9ccf909483b1893a8c`

I'm using Mac OSX El Capitan
```
$ uname -a
Darwin carlosmacbookpro.raleigh.ibm.com 15.5.0 Darwin Kernel Version 15.5.0: Tue Apr 19 18:36:36 PDT 2016; root:xnu-3248.50.21~8/RELEASE_X86_64 x86_64
```

```
$ vagrant -v
Vagrant 1.8.1
```

```
Virtual Box Version 5.0.20 r106931
```
I clean ~/.vagrant.d/ just in case
I made sure no whisk VMs are listed or running on Virtual Box
No other VMs are running 
Steps: 

```
$ rm -rf ~/.vagrant.d/
$ git clone --depth=1 https://github.com/openwhisk/openwhisk.git
$ cd openwhisk/tools/vagrant/simple/
$ ./hello

wait for a while, downloading new vagrant ubuntu to cache (10 minutes) then whisk setup (20 minutes)

==> default: ++ bin/wsk action invoke /whisk.system/samples/echo -p message hello --blocking --result
==> default: {
==> default:     "message": "hello"
==> default: }
{
    "message": "hello"
}
```

```
$ git log
commit bf3fe240ff56f772837f7c9ccf909483b1893a8c
Author: Perry Cheng <perry@us.ibm.com>
Date:   Wed Jun 8 21:34:48 2016 -0400
```

**Comment by lfzCarlosC** [comment]
I clean all the things and re-ran the whole steps,This time the behaviour is a little bit different. Hello action work fine the first time when vagrant vm is created , but then if I try to restart vm(via GUI from virtual box) and run hello action , the error happens.I will attach the log info then

**Comment by domdom82** [comment]
@csantanapr I have run a travis build that does install a vagrant box. It would work in theory, however you need to install virtualbox first which in conjunction with our own build + test flow takes longer than travis allows on the free tier and the build gets killed. I suggest making a build on our Jenkins that does a vagrant up and checks the output.

**Comment by csantanapr** [comment]
@lfzCarlosC Ah I think you are hitting some of the UX, we are seeing and working on fixing.
Restarting I think will cause problems, since you have to deploy `ant deploy` but the inmortal DB is not up. @houshengbo is working on fixing this workflow.

For now don't restart the VM, just suspend it and then up (not resume). you can use vagrant cli, we have that in the [simple/README.md(https://github.com/openwhisk/openwhisk/blob/master/tools/vagrant/simple/README.md)

**Comment by csantanapr** [comment]
@domdom82 thanks for volunteering 😆 
> I suggest making a build on our Jenkins that does a vagrant up and checks the output.

I would prefer to see something externally test this, but I guess for now we will use an internal server, but even with that I will suggest to have all the scripts in open (i.e. `tools/travis/test-vagrant.sh`)

**Comment by sjfink** [comment]
I don't think you can run vagrant inside an SL VM.   Virtualization inside virtualization usually doesn't work.

**Comment by domdom82** [comment]
relate issue #311

**Comment by lfzCarlosC** [comment]
But I was considering a real development case.If I developed new updates for action/trigger/rule and test it on local vagrant env,  next time these updates are not useful because I am not allowed to restart the vm? Or what is the process of development based on local vagrant env?

**Comment by rabbah** [comment]
I don't understand the last comment. If you restart the vm you expect the whisk deployment to still be up?

**Comment by lfzCarlosC** [comment]
let us consider a case. If I develop an action A on vagrant vm from my host machine, and then the vm for some reasons dump ,so how should I do to make action A rerun?

**Comment by csantanapr** [comment]
Suspending the machine is like shutting it down. It doesn't take resources. Just suspend , when you start the VM your actions, rules, etc are still available. 

We also have a custom setup where you can use a persistent remote DB like cloudant or a remote CouchDB

Regardless if you restart the VM the whisk system doesn't start automatically, you need to deploy/start the whisk system.

**Comment by lfzCarlosC** [comment]
So, can I use this guide https://developer.ibm.com/open/2016/02/22/openwhisk-a-quick-tech-preview/  if I want to deploy whisk system once I need?

**Comment by domdom82** [comment]
> Regardless if you restart the VM the whisk system doesn't start automatically, you need to deploy/start the whisk system.

@csantanapr not entirely true. The system should come back up in general. Ephemeral couch is a different story, however. If you use cloudant or other peristent db it should recover from a reboot. Part of our RAS strategy.

**Comment by lfzCarlosC** [comment]
@csantanapr  I clean all and try today's build. This is my log info:

$ uname -a
MINGW64_NT-6.1 BPK1MZ87 2.5.0(0.295/5/3) 2016-03-31 18:47 x86_64 Msys

$ vagrant -v
Vagrant 1.8.1

virtual box 5.0.10 r104061

$ rm -rf ~/.vagrant.d/
$ git clone --depth=1 https://github.com/openwhisk/openwhisk.git
$ cd openwhisk/tools/vagrant/simple/
$ ./hello
.........
==> default: ++ bin/wsk action invoke /whisk.system/samples/echo -p message hello --blocking --result
==> default: {
==> default:     "message": "hello"
==> default: }
error: name 'C:' contains illegal characters (code 29)
wsk failed, build might be broken try running ./resume_build

$vagrant ssh   //to the vagrant vm

Then:
create js file hello.js:
function main() {
   return {payload: 'Hello world'};
}

wsk action create hello hello.js

wsk action invoke --blocking hello
vagrant@vagrant-ubuntu-trusty-64:~$ error: org.apache.kafka.common.errors.NetworkException: The server disconnected before a response was received. (code 63)

**Comment by csantanapr** [comment]
I'm working on providing instructions on how to re-deploy openwhisk after restarting the Vagrant VM.

**Comment by csantanapr** [comment]
This is fix now instructions in vagrant/README.md
