### ISSUE TITLE
cloudant package actions do not provide any sampleInput or sampleOutput annotations

### ISSUE THREAD

**Issue by starpit** [openwhisk/openwhisk#610]
See weather or utils or slack for examples of packages that provide sampleInput and sampleOutput annotations on their actions.

These annotations help quite a bit with UX.

**Comment by rabbah** [comment]
@johnsolm @dubeejw if still relevant please move to proper repo.

**Comment by markusthoemmes** [comment]
Issue moved to [openwhisk/openwhisk-package-cloudant #69](https://github.com/openwhisk/openwhisk-package-cloudant/issues/69) via [**ZenHub**](https://www.zenhub.com/)
