### ISSUE TITLE
Gitter

### ISSUE THREAD

**Issue by tuler** [openwhisk/openwhisk#615]
How about creating a [gitter](https://gitter.im/home) channel to talk about openwhisk?

Or a slack if you prefer.

**Comment by danielfederschmidt** [comment]
Hi! We have a slack right over here: https://dwopen.slack.com
You can get yourself an invite over there: https://developer.ibm.com/open/slackin/
Discussion on OpenWhisk takes place in #openwhisk, come join us!

**Comment by tuler** [comment]
The invite page only opens a blank page for me.

**Comment by danielfederschmidt** [comment]
Yes it looks like it requests some stuff over HTTP. You can enable the loading of unsafe scripts at the top right of your adress bar.

![image](https://cloud.githubusercontent.com/assets/2430239/16046559/2fa790ea-324d-11e6-936e-f23c4d73e028.png)

**Comment by sjfink** [comment]
http://slackindwo.mybluemix.net/  may be a better signup page.
