### ISSUE TITLE
Getting error when running ansible-playbook setup.yml

### ISSUE THREAD

**Issue by csantanapr** [openwhisk/openwhisk#625]
Running this on mac

```
$ ansible-playbook setup.yml
ERROR! Unexpected Exception: (setuptools 1.1.6 (/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python), Requirement.parse('setuptools>=11.3'))
```

Fix by running
```
pip install --upgrade setuptools --user python`
```

We should do this for the user, or put in README.

**Comment by rabbah** [comment]
+1 had to do the same and should be documented.

**Comment by rabbah** [comment]
@csantanapr the ansible docs already list this fix (https://github.com/openwhisk/openwhisk/tree/master/ansible). Is this still valid?

**Comment by csantanapr** [comment]
Addressed in ansible README closing
