### ISSUE TITLE
Update ansible readme with some steps on how to setup the wsk cli after deploy

### ISSUE THREAD

**Issue by csantanapr** [openwhisk/openwhisk#629]
Using mac I went thru the ansible/README at the end after running last command `ansible-playbook -i environments/mac openwhisk.yml` I was like "now what?"

It's not obvious to the user a few things:

wsk cli is located in `../bin/wsk`
Need to set the apihost and auth key in the cli before using it
apihost can be found using `docker-machine ip whisk`
wsk property set --apihost `docker-machine ip whisk`
auth can be found in `../config/keys/auth.guest`
`cat ../config/keys/auth.guest | xargs wsk property set --auth`

then try hello action
`wsk -v action invoke /whisk.system/samples/echo -p message hello --blocking --result`

**Comment by lehoanganh** [comment]
i think, the README.md for ansible should only cover the part: how to deploy openwhisk with ansible. The overall README would take the part of ansible README for deploying and add post steps like setting up api key, etc..

What do you think @rabbah @jeremiaswerner @domdom82

**Comment by rabbah** [comment]
A link to a next step is logical - in particular how to verify the deployment is operational. This is in scope for ansible readme.
