### ISSUE TITLE
ansible playbook failures if paths include spaces

### ISSUE THREAD

**Issue by rabbah** [openwhisk/openwhisk#632]
First reported in #605:

```
ansible-playbook -i environments/mac initdb.yml 

PLAY [ansible] *****************************************************************

TASK [setup] *******************************************************************
Saturday 11 June 2016  22:14:50 -0400 (0:00:00.016)       0:00:00.016 ********* 
ok: [ansible]

TASK [include] *****************************************************************
Saturday 11 June 2016  22:14:50 -0400 (0:00:00.284)       0:00:00.301 ********* 
included: /Volumes/Macintosh HD/Users/rabbah/projects/openwhisk/ansible/tasks/initdb.yml for ansible

TASK [check if the immortal {{ db.auth }} db with {{ db_provider }} exists?] ***
Saturday 11 June 2016  22:14:50 -0400 (0:00:00.076)       0:00:00.378 ********* 
fatal: [ansible]: FAILED! => {"failed": true, "msg": "need more than 1 value to unpack"}

PLAY RECAP *********************************************************************
ansible                    : ok=2    changed=0    unreachable=0    failed=1   

Saturday 11 June 2016  22:14:50 -0400 (0:00:00.031)       0:00:00.409 ********* 
=============================================================================== 
TASK: setup ------------------------------------------------------------- 0.28s
TASK: include ----------------------------------------------------------- 0.08s
TASK: check if the immortal {{ db.auth }} db with {{ db_provider }} exists? --- 0.03s
command failed
```

The problem arises from statements like these:
`db_provider: "{{ lookup('ini', 'db_provider section=db_creds file={{ playbook_dir }}/db_local.ini') }}"`

where `file` cannot handle a space in the path.

Although I found several ansible issues marked "closed" that appear related to this issue (and we are using a recent version that should have these fixes), I had to relocate my openwhisk project to be operational.

A fix or workaround is desirable or reporting this back with an issue if confirmed to be an ansible bug.

**Comment by domdom82** [comment]
documented in https://github.com/openwhisk/openwhisk/blob/master/ansible/README.md for now.

**Comment by lehoanganh** [comment]
@rabbah should we close this one?

**Comment by rabbah** [comment]
Was it reported to the ansible project? If so cross link and put in ice box or close as won't fix.

**Comment by lehoanganh** [comment]
Issue opened at ansible repo: https://github.com/ansible/ansible/issues/16468
Our issue is back to icebox

**Comment by lehoanganh** [comment]
https://github.com/ansible/ansible/issues/16468#issuecomment-229052799 showed it is reproducible.

**Comment by rabbah** [comment]
https://github.com/ansible/ansible/issues/16468#event-706665661 fixed/closed.

**Comment by rabbah** [comment]
is there a new ansible release that includes this fix? if so, can we upgrade?

**Comment by rabbah** [comment]
Closing to be handled with #967.
