### ISSUE TITLE
Eclipse (Scala IDE) project files don't work

### ISSUE THREAD

**Issue by tuler** [openwhisk/openwhisk#643]
I'm trying to generate project files for Scala IDE using the eclipse gradle plugin, but the generated files don't work. Controller project is linked to dispatcher src.

I executed:
gradle cleanEclipse
gradle eclipse

I would move the source code into a standard structure (src/main/scala, src/main/resources), as described at:
https://docs.gradle.org/current/userguide/scala_plugin.html#N1664C

If this is the way to go I can open a pull request.

**Comment by markusthoemmes** [comment]
I don't see any objections on why we shouldn't follow the convention. Pull request very welcome!

The link to certain projects (i.e. loadbalancer) is "works as designed". Which problems do you experience with the files otherwise?

**Comment by tuler** [comment]
loadBalancer is not linked at controller project (as it should).
controller project is linked to dispatcher src (instead of controller src)

I'm using Scala IDE 4.4.1
Build id: 4.4.1-vfinal-2016-05-04T11:16:00Z-Typesafe

**Comment by rabbah** [comment]
The link to dispatcher src is not necessary and about to get removed in #578. I agree the linking should be at project level otherwise instead of src if that's the suggestion.

**Comment by tuler** [comment]
#646 fixes this.
