### ISSUE TITLE
move echo action to util package

### ISSUE THREAD

**Issue by sjfink** [openwhisk/openwhisk#644]
I claim that's where it belongs.

**Comment by mrutkows** [comment]
Hi Stephen, can we do this as part of the "openwhisk-catalog" move? See issue #2 👍 
[https://github.com/openwhisk/openwhisk-catalog/issues/2](https://github.com/openwhisk/openwhisk-catalog/issues/2)

in the new openwhisk-catalog repo.  

We can create that issue there or I can amend #2 to include  echo.js.

**Comment by mrutkows** [comment]
@houshengbo Please be aware of this as part of issue #2 for the catalog move.

**Comment by rabbah** [comment]
done.
