### ISSUE TITLE
Move install scripts and util.sh from openwhisk to openwhisk-catalog 

### ISSUE THREAD

**Issue by houshengbo** [openwhisk/openwhisk#658]
Note: This issue is pre-req for other issues for "move" of catalog.

Please note that other issues (e.g., Issue 2, Issue 3) which are moving "utils" and "samples" package actions to new locations (and adjusting namespaces) will be updating these files. It may be a good idea to address (i.e., commit and merge) this issue before other issues titled "Move".

Please move the following files from the current repo. / directory "openwhisk-openwhisk/catalog" to this repo. under "openwhisk-catalog/packages":

-     installCatalog.sh
-     installGit.sh
-     installSlack.sh
-     installSystem.sh
-     installWatson.sh
-     installWeather.sh
-     util.sh

**Comment by houshengbo** [comment]
Refer to the issue in openwhisk-catalog: https://github.com/openwhisk/openwhisk-catalog/issues/4
Refer to the issue in IBM internal bluewhisk: https://github.ibm.com/BlueMix-Fabric/bluewhisk/issues/2032

**Comment by rabbah** [comment]
Move implies the copy on this repo is deleted. But it's not. So are we keeping utils.sh?
