### ISSUE TITLE
Language runtimes need to send a sentinel marker to mark the end of an activation

### ISSUE THREAD

**Issue by perryibm** [openwhisk/openwhisk#661]
Currently, only nodejs does this and so we are at risk of losing some output in case docker log flushing is tardy.  We mitigate this with a sleep (around 100ms I believe) which is slow and still not correct.  We should fix this for all our languages - starting with Swift/Python.

Once the marker is in place, we can enable support for it in the invoker which must happen at the same time as generating the markers.  Markers should be generated on both stdin and stdout and both streams should be flushed after the markers are generated.

**Comment by paulcastro** [comment]
PG 675

**Comment by ioana-blue** [comment]
As far as I understand, there is no test in place for this, correct? Once we add the markers, @perryibm will add code in the Invoker to deal with this, right?

**Comment by paulcastro** [comment]
For Swift, I had to modify the existing tests since they were expecting stdout to be empty.  That may not be necessary for Python?

If @perryibm is busy I can help add the code to the Invoker since I just did it for Swift.

**Comment by rabbah** [comment]
Go for it :+1:.
