### ISSUE TITLE
Move /whisk.system/util from openwhisk to openwhisk-catalog as /whisk.system/utils (plural)

### ISSUE THREAD

**Issue by houshengbo** [openwhisk/openwhisk#663]
Issue #4 is a prereq.

Please note that as part of this move, there are 3 special changes that need to be made apart from the move of the action files.

1) The current JavaScript (JS) actions in the "openwhisk-openwhisk" repo. are installed into the catalog with the namespace "/whisk.system/util" which is incorrect. It should be plural "utils" with an "s". Please fix the install script "installSystem.sh" to reflect this name change.
2) The action file "pipe.js" is not supposed to be in the "utils" directory; it is actually installed (by "installSystem.sh) into the "/whisk.system/system" namespace. As part of this move, we will need to create a "system" directory under the top-level "packages" directory with the name "system" and update the "installSystem.sh" script to look for it there.
3) This issue should move the " openwhisk/catalog/installSystem.sh" script to the "openwhisk-catalog/packages/" directory (with the updates mentioned above).

The action files affected by this issue currently reside under repo. "openwhisk-openwhisk" in the "/openwhisk/catalog/utils". They will now live in the "openwhisk-catalog" repo. in the "openwhisk-catalog/packages/utils" directory; these include:

    cat.js
    date.js
    head.js
    sort.js

except for "pipe.js" which will reside in the "openwhisk-catalog/packages/system" directory.

**Comment by houshengbo** [comment]
Refer to openwhisk-catalog: https://github.com/openwhisk/openwhisk-catalog/issues/2
Refer to blue: https://github.ibm.com/BlueMix-Fabric/bluewhisk/issues/2037

**Comment by rabbah** [comment]
Same comment as in #664.
