### ISSUE TITLE
More recent version of watson-developer-cloud?

### ISSUE THREAD

**Issue by l2fprod** [openwhisk/openwhisk#671]
NodeJS action currently uses watson-developer-cloud 1.4.1:
https://github.com/openwhisk/openwhisk/blob/master/core/nodejsAction/Dockerfile

The latest is 1.9.3 which adds support for the new Visual Recognition service (the merge of Alchemy and the old Visual Recognition). This updated service is not supported in 1.4.1 thus if I want to call the new API, I need to rely on direct calls to the REST API instead of the nice methods on the Watson SDK.

Is there a plan to update the dependency? or to let me specify it.

**Comment by csantanapr** [comment]
Thanks @l2fprod for opening issue and bringing awareness of the new Watson SDK and the benefits of updating the npm package in the nodejs actions.

Consider this issue the feature request. I will add it to the backlog

**Comment by csantanapr** [comment]
@l2fprod nodejs6 it's using watson-developer-cloud@1.8.0 would that version work in the mean time?
https://github.com/openwhisk/openwhisk/blob/master/core/nodejs6Action/Dockerfile#L54

**Comment by l2fprod** [comment]
@csantanapr looks like the Visual Recognition V3 appears after 1.8.0 so I'd say no.

**Comment by csantanapr** [comment]
Good to know thanks for checking.

**Comment by csantanapr** [comment]
watson-developer-cloud is updated now to use 1.12.4
https://github.com/openwhisk/openwhisk/blob/master/core/nodejs6Action/Dockerfile#L59

Use default nodejs6 runtime,
if you have already deploy actions as nodejs 0.12, would need to change the kind to nodejs:6
