### ISSUE TITLE
docker-machine: not found   Persistent couch db

### ISSUE THREAD

**Issue by lfzCarlosC** [openwhisk/openwhisk#672]
```
-----host machine-------
$ ./hello
...........
{
    "message": "hello"
}
$  vagrant ssh

------vm environment    intend to setup a persistant couch db------
$ export OW_DB=Cloudant
$ export OW_DB_USERNAME=admin
$ export OW_DB_PASSWORD=password
$ export OW_DB_PROTOCOL=https
$ export OW_DB_HOST=http
$ export OW_DB_PORT=6000
ansible-playbook setup.yml


PLAY [localhost] **************************************************************


TASK [setup] ******************************************************************

Thursday 16 June 2016  10:42:16 +0000 (0:00:00.038)       0:00:00.038 *********

ok: [localhost]

TASK [find the ip of docker-machine] ******************************************

Thursday 16 June 2016  10:42:19 +0000 (0:00:03.213)       0:00:03.251 *********

fatal: [localhost -> localhost]: FAILED! => {"changed": true, "cmd": "\"docker-
achine\" \"ip\" \"whisk\"", "delta": "0:00:00.003987", "end": "2016-06-16 10:42
19.515486", "failed": true, "rc": 127, "start": "2016-06-16 10:42:19.511499", "
tderr": "/bin/sh: 1: docker-machine: not found", "stdout": "", "stdout_lines":
], "warnings": []}
...ignoring

TASK [set_fact] ***************************************************************

Thursday 16 June 2016  10:42:19 +0000 (0:00:00.203)       0:00:03.454 *********

ok: [localhost]

TASK [gen hosts for docker-machine] *******************************************

Thursday 16 June 2016  10:42:19 +0000 (0:00:00.042)       0:00:03.497 *********

skipping: [localhost]

TASK [prepare db_local.ini] ***************************************************

Thursday 16 June 2016  10:42:19 +0000 (0:00:00.032)       0:00:03.529 *********



ok: [localhost -> localhost]

PLAY RECAP ********************************************************************

localhost                  : ok=4    changed=0    unreachable=0    failed=0

Thursday 16 June 2016  10:42:19 +0000 (0:00:00.367)       0:00:03.897 *********

===============================================================================

setup ------------------------------------------------------------------- 3.21s
prepare db_local.ini ---------------------------------------------------- 0.37s
find the ip of docker-machine ------------------------------------------- 0.20s
set_fact ---------------------------------------------------------------- 0.04s
gen hosts for docker-machine -------------------------------------------- 0.03s
```

**Comment by lfzCarlosC** [comment]
the issue can be reproduced on Ephemeral CouchDB case

**Comment by markusthoemmes** [comment]
What exactly is the issue you experience?

**Comment by lfzCarlosC** [comment]
fatal: [localhost -> localhost]: FAILED! => {"changed": true, "cmd": "\"docker-
achine\" \"ip\" \"whisk\"", "delta": "0:00:00.003987", "end": "2016-06-16 10:42
19.515486", "failed": true, "rc": 127, "start": "2016-06-16 10:42:19.511499", "
tderr": "/bin/sh: 1: docker-machine: not found", "stdout": "", "stdout_lines":
], "warnings": []}
...ignoring

not sure this means the command failed to execute sth?

**Comment by lehoanganh** [comment]
@lfzCarlosC 
*setup.yml* is used to covered all environments (local, mac, etc). If you use docker-machine, setup will try to find the ip of the docker-machine and fill it in ansible hosts for you. But if you dont use docker-machine, the step is still executed cause setup.yml is not bind to a specific ansible env. In this case, you have this error (cause you don't have docker-machine in your dev env). Ansible will stop if any non-zero is returned, so in order to tell ansible go forward, we have to skip the "fatal" error.

Hope that I can give you a enough explanation. This error message is still very annoying, i agree with you

**Comment by lehoanganh** [comment]
btw, i"m not sure if your env variables are correct :)

```
------vm environment    intend to setup a persistant couch db------
$ export OW_DB=Cloudant
$ export OW_DB_USERNAME=admin
$ export OW_DB_PASSWORD=password
$ export OW_DB_PROTOCOL=https
$ export OW_DB_HOST=http
$ export OW_DB_PORT=6000
```

**Comment by lfzCarlosC** [comment]
I tested and found if I change the port to 5984, it work well

**Comment by lfzCarlosC** [comment]
I change it to 
$ export OW_DB=couchdb
$ export OW_DB_USERNAME=admin
$ export OW_DB_PASSWORD=password
$ export OW_DB_PROTOCOL=https
$ export OW_DB_HOST=http
$ export OW_DB_PORT=5984

the same issue happens,but then I execute installing DB command(couchdb.sh, initDB.sh...) and couchDB can be created successfully.

**Comment by markusthoemmes** [comment]
Issue being the "fatal error" mentioned above? As @lehoanganh mentioned, this is an expected "error" currently and skipped for a reason. You can ignore it for the moment, if you're not using a `docker-machine` based setup.

**Comment by lfzCarlosC** [comment]
ok,thanks

**Comment by mbehrendt** [comment]
@lehoanganh given this seems to be a recurring issue -- do we have a github issue to track and eliminate this?

**Comment by lehoanganh** [comment]
@mbehrendt let's use this issue to track. a pull is opened: https://github.com/openwhisk/openwhisk/pull/686

It also fixes the issue that `setup.yml` does not work at the 1. run (you have experienced it ;) )

**Comment by lehoanganh** [comment]
https://github.com/openwhisk/openwhisk/pull/688 is merged. Issue closed.
