### ISSUE TITLE
OW_DB_USERNAME/OW_DB_PASSWORD does not work to create couch db

### ISSUE THREAD

**Issue by lfzCarlosC** [openwhisk/openwhisk#678]
```
------host machine------
$ OW_DB=couchdb OW_DB_USERNAME=admin OW_DB_PASSWORD=86889125 OW_DB_PROTOCOL=http OW_DB_HOST=172.17.0.1 OW_DB_PORT=5984 vagrant up
......
$ vagrant ssh
.....
------ vm machine-------
$  cd openwhisk/ansible
$  cat db_local.ini
[db_creds]
db_provider=CouchDB
db_username=whisk_admin
db_password=some_passw0rd
db_protocol=http
db_host=172.17.0.1
db_port=5984

$  curl -X GET http://whisk_admin:some_passw0rd@localhost:5984/_users
{"db_name":"_users","doc_count":1,"doc_del_count":0,"update_seq":1,"purge_seq":0,"compact_running":false,"disk_size":4194,"data_size":2141,"instance_start_time":"1466098303406181","disk_format_version":6,"committed_update_seq":1}

$  curl -X GET http://admin:86889125@localhost:5984/_users
{"error":"unauthorized","reason":"Name or password is incorrect."}
```

**Comment by houshengbo** [comment]
OW_DB=couchdb OW_DB_USERNAME=admin OW_DB_PASSWORD=86889125 OW_DB_PROTOCOL=http OW_DB_HOST=172.17.0.1 OW_DB_PORT=5984 vagrant up
Is it the command that you run for the first time?

I think the vagrantfile has not updated to adjust to the ansible build, so that db_local.ini is not updated, even if the database information is input.
@csantanapr

**Comment by domdom82** [comment]
it should set the props but only on vagrant up and only when provisioning. after that you have a db_local.ini so if you need to change anything just edit the file.

**Comment by lfzCarlosC** [comment]
@houshengbo   yes,I run just after I download openwhisk from Git

**Comment by lehoanganh** [comment]
@lfzCarlosC is this issue still valid?

**Comment by csantanapr** [comment]
Closing as not reproducible with the new Vagrant flow.
https://github.com/openwhisk/openwhisk/tree/master/tools/vagrant

**Comment by lfzCarlosC** [comment]
I check it with the new build today.Seems that there is no simple directory. I execute ./hello under tools/vagrant  but this time vm creation throws an error:

 ==> default: PLAY [ansible] *****************************************************************
==> default:
==> default: TASK [setup] *******************************************************************
==> default: Friday 01 July 2016  13:10:37 +0000 (0:00:00.027)       0:00:00.027 ***********
==> default: ok: [ansible]
==> default:
==> default: TASK [include] *****************************************************************
==> default: Friday 01 July 2016  13:10:40 +0000 (0:00:02.417)       0:00:02.445 ***********
==> default: included: /home/vagrant/openwhisk/ansible/tasks/initdb.yml for ansible
==> default:
==> default: TASK [check if the immortal subjects db with CouchDB exists?] ******************
==> default: Friday 01 July 2016  13:10:40 +0000 (0:00:00.221)       0:00:02.666 ***********
==> default: fatal: [ansible]: FAILED! => {"changed": false, "content": "", "failed": true, "msg": "Status code was not [200, 404]: Request failed: <urlopen error [Errno 111] Connection refused>", "redirected": false, "status": -1, "url": "http://172.17.0.1:5984/subjects"}
==> default:
==> default: PLAY RECAP *********************************************************************
==> default: ansible                    : ok=2    changed=0    unreachable=0    failed=1
==> default: Friday 01 July 2016  13:10:40 +0000 (0:00:00.346)       0:00:03.012 ***********
==> default: ===============================================================================
==> default: setup ------------------------------------------------------------------- 2.42s
==> default: check if the immortal subjects db with CouchDB exists? ------------------ 0.35s
==> default: include ----------------------------------------------------------------- 0.22s
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.

**Comment by lfzCarlosC** [comment]
This is my command

OW_DB=couchdb OW_DB_USERNAME=admin OW_DB_PASSWORD=86889125 OW_DB_PROTOCOL=http OW_DB_HOST=127.0.0.1 OW_DB_PORT=5984   ./hello
