### ISSUE TITLE
Add issue template to repository

### ISSUE THREAD

**Issue by danielfederschmidt** [openwhisk/openwhisk#687]
Provide an issue template as suggested here:
https://github.com/blog/2111-issue-and-pull-request-templates

For inspiration, this is the issue template of the Docker project: https://github.com/docker/docker/blob/master/CONTRIBUTING.md

**Comment by danielfederschmidt** [comment]
PR: https://github.com/openwhisk/openwhisk/pull/676

**Comment by csantanapr** [comment]
This is merged https://github.com/openwhisk/openwhisk/commit/711f50a54eb6f24e65d4632b36d17fd55ed587d8
