### ISSUE TITLE
Set your OpenWhisk Namespace and Authorization Key

### ISSUE THREAD

**Issue by rtang03** [openwhisk/openwhisk#69]
I had ever connected via CLI successfully. After I build my local OpenWhisk development environment, the CLI does not work. 

I input the same command "wsk property set --auth <my OpenWisk key>" in my terminal, it returns

> error: The supplied authentication is invalid (code 599)

**Comment by rabbah** [comment]
`wsk property set --auth xxx:yyy` for some xxx:yyy as the auth key does not make an API call. It just write to the wsk property file. Are you saying that after you set the auth key to an appropriate value, a subsequent API call fails?

If so, 
1. are you using cloudant or couchdb and did you run the script `createImmortalDbs`?
2. are you using one of the built in keys or a new key?
3. if using a new key, did you add the key to the db using `wskadmin create user ...`?

**Comment by rtang03** [comment]
I figure out what is wrong. After setting up the local development environment; I run `wsk property set --apihost ` pointing to Vagrant. I forget to change the apihost back to openwhisk.ng.bluemix.net. Be better, you may add documentation mentioning the proper --apihost
