### ISSUE TITLE
Have we lost our wsk in the new ansible deployment?

### ISSUE THREAD

**Issue by houshengbo** [openwhisk/openwhisk#694]
I have just tried the ansible build for the latest openwhisk code in vagrant. When everything is up and running, the command "wsk" is not available.

I believe we used to have it. Is it because we have just got rid of python cli? Go is still not available?

**Comment by rabbah** [comment]
1. CLI was not removed (and still using the Python CLI by default).
2. Ansible is for deployment. Gradle is for builds.

Suggest you confirm that `wsk` exists in your openwhisk/bin directory and provide more steps to reproduce your problem.

**Comment by houshengbo** [comment]
wsk is under openwhisk/bin, but still not found. I just followed the ansible readme step by step to deploy as  below:
cd ansible;
ansible-playbook -i environments/local prereq.yml;
cd ..;
gradle distDocker;
cd ansible;
ansible-playbook setup.yml
ansible-playbook -i environments/local couchdb.yml;
ansible-playbook -i environments/local initdb.yml
ansible-playbook -i environments/local openwhisk.yml

When I check the wsk:
```
vagrant@vagrant-ubuntu-trusty-64:~/openwhisk/bin$ ls
go-cli  wsk  wskadmin
vagrant@vagrant-ubuntu-trusty-64:~/openwhisk/bin$ wsk
No command 'wsk' found, did you mean:
 Command 'wsl' from package 'wsl' (universe)
 Command 'ask' from package 'ask' (universe)
 Command 'wmk' from package 'wml' (universe)
wsk: command not found
vagrant@vagrant-ubuntu-trusty-64:~/openwhisk/bin$ wsk action list
No command 'wsk' found, did you mean:
 Command 'ask' from package 'ask' (universe)
 Command 'wmk' from package 'wml' (universe)
 Command 'wsl' from package 'wsl' (universe)
wsk: command not found
vagrant@vagrant-ubuntu-trusty-64:~/openwhisk/bin$ 
```

**Comment by lehoanganh** [comment]
`bin` folder in your vagrant is not added in `PATH` after deployment, i'm not sure if we had this before. History does not show it. If you do this in your `bin`: ` ./wsk`?

**Comment by csantanapr** [comment]
@houshengbo Vagrantfile setups the VM with the $PATH to include `/home/vagrant/openwhisk/bin/wsk`    for example in simple here https://github.com/openwhisk/openwhisk/blob/master/tools/vagrant/simple/Vagrantfile#L59
with `sed -i.bak s/:\\\\/bin/:\\\\/bin:\\\\/home\\\\/vagrant\\\\/openwhisk\\\\/bin/g /etc/environment`

**Comment by mdeuser** [comment]
@houshengbo - Are you running on a vagrant VM under Windows?  If so, when cloning the openwhisk repo, the symlink for that bin/wsk file is lost and you will need to re-create that link.  Double check the link with `ls -al openwhisk/bin`.

To add the symlink back, run `cd openwhisk/bin && ln -s ../tools/cli/wsk wsk`

**Comment by dubeejw** [comment]
Please close this issue if it has been fixed.
