### ISSUE TITLE
Update swift 3 build to latest 

### ISSUE THREAD

**Issue by csantanapr** [openwhisk/openwhisk#697]
I think latest is from June 13  Swift 3.0 Preview 1
https://swift.org/builds/swift-3.0-preview-1/ubuntu1404/swift-3.0-preview-1/swift-3.0-preview-1-ubuntu14.04.tar.gz

The one we use today is old from May 3rd

**Comment by sjfink** [comment]
I've been advised to stay away from any Swift 3 build post May 5.

**Comment by paulcastro** [comment]
We've merged Swift 3.0.2
