### ISSUE TITLE
github package should specify accessToken field as type:password

### ISSUE THREAD

**Issue by starpit** [openwhisk/openwhisk#698]
In general, any protected/confidential fields should be marked with type:password, so that the UI can occlude entered text ******

**Comment by starpit** [comment]
related: https://github.com/openwhisk/openwhisk/issues/731

**Comment by starpit** [comment]
related https://github.com/openwhisk/openwhisk/issues/702

**Comment by csantanapr** [comment]
Moving issue to catalog repo https://github.com/openwhisk/openwhisk-catalog/issues/150
