### ISSUE TITLE
github webhook.js is hard-wired to openwhisk.ng.bluemix.net

### ISSUE THREAD

**Issue by starpit** [openwhisk/openwhisk#699]
if one wants to set up openwhisk on some other endpoint, the git webhook will not work
```
  var endpoint = 'openwhisk.ng.bluemix.net';
```

**Comment by starpit** [comment]
for one, this affects the IBM Bluemix OpenWhisk staging services.

**Comment by starpit** [comment]
related https://github.com/openwhisk/openwhisk/issues/731

**Comment by csantanapr** [comment]
This is fix now https://github.com/openwhisk/openwhisk-catalog/blob/master/packages/github/webhook.js#L34

cc @bjustin-ibm
