### ISSUE TITLE
Excessive CPU usage during no load using "vagrant/simple"?

### ISSUE THREAD

**Issue by jthomas** [openwhisk/openwhisk#701]
Following the [Quick Start](https://github.com/openwhisk/openwhisk#quick-start) guidelines, I have successfully set up a local instance of the OpenWhisk platform.

**Looking at the VM instance, I've noticed the system is under high CPU load at all times, even when the system is idle.**

Here's the output from _top_ on the system. 
<img width="673" alt="ow" src="https://cloud.githubusercontent.com/assets/2322/16191879/447dc71a-36de-11e6-8028-b53b0ef26535.png">
Those top four processes (10264, 10216, 10990 & 11772) remain at similar CPU usage whilst the system is idle. 

10264 is the Kafka process, 10216 is docker-proxy for the 9092 (kafka's port), the other two processes are the controller and invoker instances.

I've increased the VM memory from 4GB to 8GB with no difference.

Is this expected behaviour?

**Comment by rabbah** [comment]
Addressed with #796. @jthomas can you confirm and close?

**Comment by jthomas** [comment]
Having tested locally, I can confirm this issue has been resolved.
