### ISSUE TITLE
no  /whisk.system/alarms package found for the install couchDB

### ISSUE THREAD

**Issue by lfzCarlosC** [openwhisk/openwhisk#715]
on the host machine:
$ OW_DB=couchdb OW_DB_USERNAME=admin OW_DB_PASSWORD=86889125  OW_DB_PROTOCOL=http OW_DB_HOST=172.17.0.1  OW_DB_PORT=5984 vagrant up

then,
$ vgarant ssh

on the vm env,
$ wsk package list /whisk.system

packages
/whisk.system/github                                              shared        
/whisk.system/samples                                             shared        
/whisk.system/weather                                             shared        
/whisk.system/system                                              shared        
/whisk.system/slack                                               shared        
/whisk.system/watson                                              shared        
/whisk.system/util                                                shared

But following the guide https://github.com/openwhisk/openwhisk/blob/master/docs/packages.md#browsing-packages . It lists /whisk.system/alarms and uses feed in the package.

So, do I lack some installation steps? like  ant clean build deploy?

**Comment by rabbah** [comment]
Alarms and cloudant packages are not in openwhisk yet.

**Comment by lfzCarlosC** [comment]
So,there is no feed in those package for trying ,right?

**Comment by rabbah** [comment]
That's correct. Closing as duplicate.
