### ISSUE TITLE
Make nodejs:6 kind the default for JavaScript actions

### ISSUE THREAD

**Issue by bjustin-ibm** [openwhisk/openwhisk#716]
When the `kind` is either specified to be "nodejs" or is unspecified for a .js file, then it should be assumed to be a Node 6 action.

This will require a new kind value to specify Node 0.12 actions.

**Comment by bjustin-ibm** [comment]
Somewhat related to #618

**Comment by bjustin-ibm** [comment]
In order to future-proof the value for the Node 0.12.x `kind`, I suggest it be "node:0.12" as opposed to "node:12".

**Comment by markusthoemmes** [comment]
Note that this is a breaking API change as existing actions might stop working when run in nodejs 6.

**Comment by bjustin-ibm** [comment]
Resolved by #738

**Comment by bjustin-ibm** [comment]
> Note that this is a breaking API change as existing actions might stop working when run in nodejs 6.

This was implemented in such a way that existing "nodejs" actions are unaffected, and will continue to run on the Node 0.12 runtime.
