### ISSUE TITLE
Add the sh script to install the openwhisk-catalog

### ISSUE THREAD

**Issue by houshengbo** [openwhisk/openwhisk#719]
Since openwhisk-catalog is ready to use, a script should be added into openwhisk to install all the catalog from openwhisk-catalog.

**Comment by rabbah** [comment]
@nwspeete-ibm this is related to the push notification package. Is there a reusable solution?

FYI @csantanapr.

**Comment by csantanapr** [comment]
I think we need to wait to see what can be consolidated and refactor.

For now I would suggest to

1. Re-use the file name `catalog/installCatalog.sh`
The new content will be something like 
````
git clone https://github.com/openwhisk/openwhisk-catalog
cd  openwhisk-catalog
/.install.sh
```
2. Move the contents of `catalog/installCatalog.sh` into new `openwhisk-catalog/install.sh`

**Comment by houshengbo** [comment]
I can definable change to the re-usable way. We do not need to create the install.sh, because I have already made the installcatalog.sh under openwhisk-catalog/packages, able to call and install all the packages.

**Comment by csantanapr** [comment]
Closing with #885
