### ISSUE TITLE
Provide educational videos for selected topics

### ISSUE THREAD

**Issue by nauerz-ibm** [openwhisk/openwhisk#729]
Provide educational videos for selected topics supposed to be made available via our OW Youtube channel.

**Comment by rabbah** [comment]
@bjustin-ibm has created some videos that are part of the learn more page on bluemix. Is there a plan to make these available on youtube? (cc @csantanapr).

**Comment by bjustin-ibm** [comment]
They have already been posted to the [official OpenWhisk channel](https://www.youtube.com/channel/UCbzgShnQk8F43NKsvEYA1SA)
