### ISSUE TITLE
Setup guide for mac-only using docker machine

### ISSUE THREAD

**Issue by domdom82** [openwhisk/openwhisk#73]
As a second way of setting up a dev machine there is the option to use docker machine
instead of vagrant.

The advantage is greatly improved performance on a mac. 
Also it eliminates problems with shared folders and symlinks.
The result is a mac that builds OpenWhisk locally and deploys it into a very small VM that is managed by docker machine.

These steps should later be turned into a setupguide.md under docs.

**Comment by markusthoemmes** [comment]
As a first shot, let's assume the user has [**homebrew**](http://brew.sh/) with [Caskroom](https://caskroom.github.io/) installed. That will greatly simplify the setup process.

**Comment by markusthoemmes** [comment]
Above list has been updated to include version pinning of docker

**Comment by sjfink** [comment]
I needed ```brew install python``` on a new Mac.

**Comment by sjfink** [comment]
I also found the following to be helpful:
```
sjfinks-mbp:blue sjfink$ cat ~/.bashrc
export OPENWHISK_HOME=/Users/sjfink/whisk/openwhisk
export DOCKER_HOST=tcp://192.168.99.100:2375
```

**Comment by domdom82** [comment]
```
export ANSIBLE_TARGET_HOST=192.168.99.100
export ANSIBLE_TARGET_USER=docker
export ANSIBLE_TARGET_KEY=~/.docker/machine/machines/whisk/id_rsa
```
also python is needed in the docker machine.

install via
```
tce-load -wi python
```

**Comment by markusthoemmes** [comment]
These can probably be added to the existing setup scripts for docker-machine for convenience.

**Comment by domdom82** [comment]
@rabbah ran into a version problem of `setuptools` using Ansible.

So we need to make sure setuptools is at a current version also.

```
sudo pip install --upgrade setuptools
```

seeing as there are so many commands to run we should incorporate those into some `all.sh` for mac script.

**Comment by rabbah** [comment]
@domdom82 @lehoanganh 

```
$ tce-load -wi python
Downloading: python.tcz
Connecting to repo.tinycorelinux.net (89.22.99.37:80)
wget: can't connect to remote host (89.22.99.37): Connection refused
md5sum: python.tcz.md5.txt: No such file or directory
Error on python.tcz
```

having trouble with `bootsynch.sh`.

**Comment by domdom82** [comment]
hm weird. I just set up a new docker-machine which worked perfectly fine with the python install. seems like a hiccup?

**Comment by rabbah** [comment]
appears to be so - thanks.

**Comment by rabbah** [comment]
worked well for a fresh mac. @csantanapr suggest turning the instructions into a readme, what do you think?

**Comment by csantanapr** [comment]
In the main README we should have a pointer to `tools/macos/README.md` , but this `tools/macos/README.md` needs love and testing to make it into an easy one command to go from zero to hello action in reproducible manner, always be able to start fresh and check that all pre-req software is install and updated.
