### ISSUE TITLE
`wsk action update` does not support the `--kind` flag

### ISSUE THREAD

**Issue by bjustin-ibm** [openwhisk/openwhisk#739]
While this is supported in the Python CLI, it is not for the Go CLI. I think (hope?) this is just an oversight.

**Comment by rabbah** [comment]
You can update the kind if you also update the exec artifact. You cannot update the kind independently. This is a restriction from the API side. This prevents for example updating a swift action with a kind nodejs.

**Comment by bjustin-ibm** [comment]
Once I discovered that (at least in the Python CLI) `wsk action update` will actually create the action if it does not yet exist, then I just stopped using `wsk action create` entirely. Sadly though, I can't do this with the Go CLI because `update` doesn't support `--kind` at all.

**Comment by dubeejw** [comment]
Resolved by : https://github.com/openwhisk/openwhisk/commit/b8f333497ff1df2b190ece2dc4f97a2f4eb683e8.
