### ISSUE TITLE
Allow creating a container action just working with std in & out

### ISSUE THREAD

**Issue by mbehrendt** [openwhisk/openwhisk#740]
as a low-barrier-of-entry alternative to the perf-optimized, instrumented way of providing a docker container as an action, we should offer providing a docker container accepting input via stdin and returning it via std out.

**Comment by rabbah** [comment]
When one created/runs a docker action in openwhisk, the executable does read and write to std in/out. Using one of the base images we provide means the action benefits from the built in proxy. As such, I'm inclined to close this.
