### ISSUE TITLE
ansible setup.yml wipes out database settings in db_local.ini

### ISSUE THREAD

**Issue by sjfink** [openwhisk/openwhisk#745]
## Environment details:

* MacOS w/docker-machine 

## Steps to reproduce the issue:

1.   set up a working Mac docker-machine environment
2.   restart your docker-machine
3.   re-run ansible-playbook setup.yml (required to do since docker-machine restarted)

## Provide the expected results and outputs:

This procedure should not wipe out the existing database settings in db_local.ini

## Provide the actual results and outputs:

But it does.

**Comment by rabbah** [comment]
Note on docker machine restart you run prereq not setup.

**Comment by sjfink** [comment]
Secondary bug: there is no documentation about setup, prereq, or any other tasks related to docker-machine restart at this page: https://github.com/openwhisk/openwhisk/tree/master/tools/macos

**Comment by lehoanganh** [comment]
@sjfink : like @rr said, after each restart of docker-machine, only prereq is required, not setup.yml. However, the bug with the setup.yml is going to be fixed.

**Comment by rabbah** [comment]
@sjfink should setup/prereq be on the macos doc age? They are general deployment instructions I think they belong elsewhere.

**Comment by lehoanganh** [comment]
pr is opened: https://github.com/openwhisk/openwhisk/pull/747

**Comment by sjfink** [comment]
@rabbah the fact that I must re-run prereq.xml when my docker-machine is restarted should be documented with the docker-machine instructions, I think.

**Comment by rabbah** [comment]
It is - https://github.com/openwhisk/openwhisk/tree/master/ansible#install-prerequisites

> Caveat: Mac users who have a docker-machine setup will have to re-run this playbook every time the boot2docker machine is rebooted. This is because installed prereqs are not persisted on TinyCore Linux.

I have suggested a workaround to @lehoanganh @domdom82 so that we don't need this step in the future (which is ideal).

**Comment by sjfink** [comment]
I suggest repeating the instruction on the page that describes docker-machine stuff.

**Comment by lehoanganh** [comment]
@sjfink: The Ansible README.md https://github.com/openwhisk/openwhisk/blob/master/ansible/README.md points to the docker-machine set up in https://github.com/openwhisk/openwhisk/blob/master/tools/macos/README.md.

Your first bug is fixed in https://github.com/openwhisk/openwhisk/pull/747, so i would close this issue. Pls reopen / create a new one if needed.
