### ISSUE TITLE
doc bug in Mac setup for docker

### ISSUE THREAD

**Issue by sjfink** [openwhisk/openwhisk#746]
https://github.com/openwhisk/openwhisk/tree/master/tools/macos

gives instructions to install docker 1.10.   However, we are currently running 1.9 on the server and the 1.10 client cannot talk to the 1.9 server:

sjfinks-MacBook-Pro:openwhisk sjfink$ docker ps
Error response from daemon: client is newer than server (client API version: 1.22, server API version: 1.21)

**Comment by rabbah** [comment]
> docker ps
expected to fail because we disable TLS but docker machine still tries to docker on port 2376.
this is a known docker-machine bug (will link the issue here).

**Comment by rabbah** [comment]
curious, > `docker-machine -v` ?

**Comment by sjfink** [comment]
sjfinks-MacBook-Pro:openwhisk sjfink$ docker-machine -v
docker-machine version 0.7.0, build a650a40

**Comment by sjfink** [comment]
I further suggest moving this content to somewhere under docs/

**Comment by csantanapr** [comment]
docs updated to use 1.9.1
