### ISSUE TITLE
 Circular dependency of openwhisk and openwhisk-catalog

### ISSUE THREAD

**Issue by houshengbo** [openwhisk/openwhisk#748]
Since the packages and install scripts are moved into openwhisk-catalog, how shall we cope with the dependencies between openwhisk and openwhisk-catalog?

If we still keep an install script in openwhisk, each time we run it, it git clone the openwhisk-catalog repo and install the packages.
If we run the install script in openwhisk-catalog, it will clone the openwhisk repo and install the packages.

This situation sustains in the Travis CI as well. openwhisk and openwhisk-catalog both need Travis CI to run the tests on each PRs to ensure the code quality. However, each of them needs one another's repo to install the catalog.

We need to break the circular dependency in either of the projects.

**Comment by houshengbo** [comment]
The pair issue in openwhisk-catalog: https://github.com/openwhisk/openwhisk-catalog/issues/24

**Comment by houshengbo** [comment]
I personally suggest to remove the install script in openwhisk. The openwhisk-catalog will pull openwhisk repo for the catalog installation tests each time the code is changed.

I also prefer to split catalog installation from the installation of openwhisk. Now we are trying to install everything when we install openwhisk, which I think there is a potential to improve.

Installation of OpenWhisk can be abstracted into a general project or somewhere we feel comfortable (like the role of devstack plays in openstack). It may install the openwhisk core(we can define late what it means), it may install the catalogs, it may install third party action... The role is to be responsible for deployment.

**Comment by tuler** [comment]
I like the idea of keeping the installation of OpenWhisk as a separate entity. The current ansible approach is confusing, and it supports only simple and specific deployment scenarios. In addition to that the building and installation are too connected. We should be capable of building and producing artifacts (as docker images) and use the same images for different deployment scenarios.

**Comment by markusthoemmes** [comment]
@tuler in which way are building and deployment connected currently? If you find the current approach confusing, feedback will be very welcome so we can improve the processes.

**Comment by houshengbo** [comment]
From the OpenWhisk's perspective, to break the dependency on the installation of the catalog packages, I propose to work on the following item(s):

*Remove or replace the catalog installation from the test in OpenWhisk. By far, OpenWhisk installs all the packages by default and there are tests regarding all the package installation. We should either remove them out as well or replace them with some fixtures or mocks. This could be the first step to break the catalog dependencies in OpenWhisk. After this, the Travis CI build to check each PR won't break at the catalog package check.

**Comment by tuler** [comment]
@markusthoemmes build and deployment are connected at least in terms of documentation. Check the current Ubuntu deployment doc:
https://github.com/openwhisk/openwhisk/blob/master/tools/ubuntu-setup/README.md

Then it says:

### Build and Deploy
```
# Build and deploy
ant clean build deploy
```

There should be pre-built docker images published at docker hub, and deployment docs based on those images.

**Comment by houshengbo** [comment]
@rabbah @jeremiaswerner @csantanapr @starpit 
I need you folks' comments on this issue and the related PR (WIP) https://github.com/openwhisk/openwhisk/pull/780.

**Comment by rabbah** [comment]
I don't understand the proposal. Can you clarify and break down the proposed steps?

**Comment by csantanapr** [comment]
I discuss the proposal with @houshengbo here is my summary:

The split will be `openwhisk` and `openwhisk-catalog`

## openwhisk
`openwhisk` does not depend on `openwhisk-catalog`
The `catalog` folder doesn't exist anymore
No packages will be install by default (build, deploy, vagrant) on this repo
User will need to manually (or via script) install packages repos
Tests in openwhisk should not depend on any package repos including `openwhisk-catalog`
Any current tests that depend on catalog, should be refactor to use a new test fixture, or move the test to the package repo if it make sense. 
Need to look at each test to see if the test is testing the package, or testing a core functionality

## openwhisk-catalog 
`openwhisk-catalog` depends on `openwhisk`
Contain the a core set of packages
Contain the test cases to test the packages
Configured with Travis for CI to run the tests
Any package that requires a credential for testing, it should use the Travis encryption service so test can run automatically in the Travis Cloud
User should be able to run the tests locally by providing his own credentials for the any services that test cases depend on (Slack, Watson, Github, etc..)
To work with the repo an user will do something like this:
```
git clone https://github.com/openwhisk/openwhisk-catalog
cd openwhisk-catalog
git clone https://github.com/openwhisk/openwhisk
OPENWHISK_HOME=$(cd openwhisk && pwd)
cd $OPENWHISK_HOME
git checkout (pinned hash or master)
.... build and deploy (redo setup prereq couchdb initdb deploy) 
../packages/install.sh $APIHOST $AUTH $WSK_CLI
... use the packages as normal using WSK CLI
... run tests the packages 
edit ../packages/tests/credentials.json 
cp -a ../packages/tests/  tests/src/packages/
gradlew tests:test --tests packages.*
```

**Comment by houshengbo** [comment]
@csantanapr Thank you, Carlos.

@rabbah This issue is where to break the circular dependency, and we propose to remove the catalog(packages) installation in openwhisk. Instead, where are we going to install and test the catalog(packages)? Go to openwhisk-catalog. This is destination, where we can move all the catalog((packages) and the tests into.

As @csantanapr described in the previous comment. Both openwhisk and openwhisk-catalog need some changes to make this happen, including catalog folder, tests of catalog(packages), travis ci for openwhisk-catalog, etc.

**Comment by houshengbo** [comment]
@rabbah @markusthoemmes @csantanapr 
In order to have a seamless transition from openwhisk to openwhisk-catalog, I think we can create a script named installExtraCatalog.sh under openwhisk/catalog to install the scripts, which have already moved to openwhisk-catalog. At the same time we still keep the installCatalog.sh to install the packages, which are still in openwhisk.

In the ansible file postdeploy.yml, we can add installExtraCatalog.sh, so that after running installCatalog.sh, we can run installExtraCatalog.sh. In this case, we can make sure that no package is missed during the transition from openwhisk/catalog to openwhisk-catalog. It is possible that some packages are installed twice(e.g. openwhisk-catalog has merged that package with tests, but openwhisk has not deleted it yet), but I think it is better than some packages missing in this transition.

How to break the circular dependency? 
The good approach can be we create a new separate repo to host the install scripts. Go to <openwhisk_home> to install openwhisk and then go to <openwhisk_catalog_home> to install the catalogs based on openwhisk. **However**, since our install scripts still exist in openwhisk, we can use an additional parameter for openwhisk.yml, e.g. withExtraCatalog and withoutExtraCatalog, to determine whether to clone the openwhisk-catalog repo or not.

By default, openwhisk.yml will install the extraCatalog from openwhisk-catalog(we can change to withoutExtraCatalog for the default value if possible):
```
ansible-playbook -i environments/local openwhisk.yml 
ansible-playbook -i environments/local openwhisk.yml -e mode=withExtraCatalog or something similar
```
The above commands behave the same.

While we are able to choose the installation withoutExtraCatalog to skip the catalog installation from openwhisk-catalog by:
```
ansible-playbook -i environments/local openwhisk.yml -e mode=withoutExtraCatalog or something similar
```

**If the user starts the installation from openwhisk:** in openwhisk.yml or even postdeploy.yml, check if it is withExtraCatalog. 
If so, download the openwhisk-catalog repo and put it in the same dir as openwhisk is located, run the install scripts under openwhisk-catalog. 
If not, skip the catalog installation from openwhisk-catalog.

**If the user starts the installation from openwhisk-catalog:** in the installation script of openwhisk-catalog, check if <openwhisk_home> exists. 
If so, use this variable and install the catalog packages;
If not, download the openwhisk repo and put it in the same dir as openwhisk-catalog, install the openwhisk with the mode of withoutExtraCatalog, so that openwhisk would not check openwhisk-catalog this time. Then install the catalog packages in openwhisk-catalog.

I can come up with some PRs for POCs.
