### ISSUE TITLE
process for migrating build to go cli

### ISSUE THREAD

**Issue by rabbah** [openwhisk/openwhisk#752]
As the GO CLI is brought online, I suggest the following process for rolling it out into master:

1. gate python vs go with a global flag or better, a constructor parameter since many if not all of the tests create a `new Wsk()` instance (Scala and Java)
2. set flag to python now
3. confirm all devs have succeeded in building go cli and have not had issues/hiccups
4. switch from python to go for only a small number of tests (by changing predicate on `new Wsk()`)
5. confirm all devs are not affected and CI is ok
6. continue enabling more tests cut over
7. when all tests are cut over, remove flag and clean up

An alternative is to run tests twice, with go cli and with python cli since the latter will be around still and we don't want to lose test coverage. For the Scala tests, it's easy to extend the suites and override the `wsk` instance. For the Java tests, this will require some work.

@mdeuser @dubeejw @csantanapr @sjfink

**Comment by mdeuser** [comment]
The good news is that prior PRs have enabled the building of the Go binaries inside the `gradle distDocker` builds.  Everyone now has a python and Go binary in their local builds.

**Comment by rabbah** [comment]
All but 3 tests are using the go cli - see #962 for the remaining ones which are covered by another issue. The flag that was added and code specialization for go vs python is quite compact/non-intrusive and we may or may not remove it (and when this is determined it should be covered by another issue). @mdeuser close?

**Comment by mdeuser** [comment]
@rabbah - Yes, I think this can be closed.  The Go CLI is now being used as the build CLI.
