### ISSUE TITLE
go cli build is not hitting docker cache 

### ISSUE THREAD

**Issue by rabbah** [openwhisk/openwhisk#759]
## Environment details:

* mac + docker-machine

## Steps to reproduce the issue:

1.   cd openwhisk
2.   ./gradlew tools:go-cli:distDocker
3.   ./gradlew tools:go-cli:distDocker

## Provide the expected results and outputs:

expecting the second gradle build to be fast ant to skip the go-cli build entirely since there are no intervening changes.

## Provide the actual results and outputs:

```
long docker build for both steps 2 and 3 above, each taking several minutes.
```

@mdeuser @dubeejw

**Comment by dubeejw** [comment]
We are building for a lot of operating system/CPU architecture combinations. We could reduce the number of binaries that are generated to speed up the build.

**Comment by rabbah** [comment]
That's fine if the hit is once but where there are no changes, building the go cli back to back should not take 2 minutes each time. If we can't resolve this, I suggest we pull the go cli distDocker target out of the main gradle file and make it a separate, explicit build step.

**Comment by dubeejw** [comment]
@mdeuser, completely remove the logic to setup the timestamp from Gradle. Modify the Dockerfile file to build the Go CLI like so:       go build -ldflags "-X main.CLI_BUILD_TIME=`date -u '+%Y-%m-%dT%I:%M:%SZ'`" -v -o build/$GOOS/$GOARCH/$EXEC main.go && \.

**Comment by mdeuser** [comment]
@rabbah - I've played around with the Dockerfile a bit and have the following proposal.
- As PhiIippe suggest, I moved the `ARG BUILDTIME` down in the file so that the common tool download/installation is always pulled from the cache.
- The go-cli build checks for a `WHISK_BUILD_TIMESTAMP` environment variable.  If it exists, it uses that value as the timestamp.  Subsequent builds will use this same timestamp value, and if it is not changed and there are no Go CLI code changes, the build pulls from the cache (10-20 second Go CLI builds).  If that env variable is not set, a timestamp is dynamically generated, causing the Go build to occur (i.e. cache is ignored).

**Comment by rabbah** [comment]
The commit above doesn't noticeably improve the build I'm observing that two successive builds with no changes take a total time of `Total time: 2 mins 28.43 secs` (excluding go CLI, two successive builds with no changes take `Total time: 6.582 secs` otherwise).

**Comment by mdeuser** [comment]
Are these results from your local builds with the `WHISK_BUILD_TIMESTAMP` environment variable set?

**Comment by rabbah** [comment]
I ran `ant build` twice in a row - I didn't grok from the comment above that I'm suppose to set the env var myself explicitly. Eh.

Existential question - what if we dropped this build time from the CLI? This was not really the best way to version the CLI anyway.

**Comment by dubeejw** [comment]
Perhaps the information needed about should be included in the README?

**Comment by psuter** [comment]
I had missed it too. Combining your ideas: what if the build only adds the version timestamp if the variable is defined, defaulting to `SNAPSHOT` otherwise? Fast builds for devs, properly timestamped for releases?

**Comment by rabbah** [comment]
Even if documented - The default way of building should be the pessimal route.

**Comment by mdeuser** [comment]
We can go that route.  Is there a good gradle property already set by the production systems that identifies the build as a production build?

**Comment by rabbah** [comment]
These two are defined in the property playbook:

whisk.version.name={{ whisk_version_name }}
whisk.version.date={{ whisk.version.date }}

**Comment by mdeuser** [comment]
Are those values available at gradle time?  I was under the impression those were set during the ansible deployment phase.

**Comment by rabbah** [comment]
The build does generate this file at some point - can't run tests without it. @markusthoemmes @lehoanganh without ant, when will this file be generated and will the values above be available to gradle?

**Comment by mdeuser** [comment]
In the meantime, I'll change the timestamp generation to no longer use the docker ARG as the build timestamp so that build times are improved.  I'll open an issue for discussion of whisk-wide build timestamps to see if and how build timestamps should be generated and used.

**Comment by rabbah** [comment]
The PR above improved the experience for the second build.
Is there any way to speed up the first build? It takes me roughly `Total time: 3 mins 53.77 secs` to build the go CLI on a 2.8 GHz Intel Core i7 with 16GB RAM (docker machine has 4GB RAM).

**Comment by markusthoemmes** [comment]
@rabbah: no, `gradle` should **not** rely on `whisk.properties` being written. Tests are the only exemption.

**Comment by mdeuser** [comment]
Right now, the Go CLI is building binaries for all of the Go supported platforms and architectures.  If some of these binaries are not needed we can removed them from the build.
- windows: 386, amd64
- mac: 386 amd64 arm arm64
- linux: 386 amd64 arm arm64 ppc64 ppc64le mips64 mips64le

@nauerz-ibm - Do you have a suggestion for the recommended Go `wsk` CLI binaries?  From the Bluemix CLI download page: Linux amd64 only, Windows amd64 only, Mac: ?? (I only have Windows)
Here's the Bluemix CLI download page: https://clis.ng.bluemix.net/ui/home.html

**Comment by csantanapr** [comment]
@rabbah @mdeuser please close if the problem on docker is fix now.

**Comment by mdeuser** [comment]
Go CLI is now fully using the docker cache.  Closing this issue.
