### ISSUE TITLE
go cli binary not being generated for mac

### ISSUE THREAD

**Issue by csantanapr** [openwhisk/openwhisk#761]
## Environment details:

Mac El Capitan

## Steps to reproduce the issue:

1.   git clone latest using hash bf409c1aabc0087cbca0a65ae19683b1d07437f1
2.   Not using vagrant using native mac dev
3.   Run $ gradle :tools:go-cli:distDocker

## Provide the expected results and outputs:

The binary in `/../../bin/go-cli/wsk` is built for mac

## Provide the actual results and outputs:

The binary in `/../../bin/go-cli/wsk` is built for linux

fyi @mdeuser @dubeejw

**Comment by markusthoemmes** [comment]
I think this line actually matches for Mac aswell: https://github.com/openwhisk/openwhisk/blob/master/tools/go-cli/build.gradle#L8

**Comment by csantanapr** [comment]
Yep I think that true 
I started looking into it, I don't think we should use ant.condition

Can I change it to use gradle to detect is and arch?

Also I think we should not check anything and just copy out all the binary types and then have a script go-CLI/wsk that is wrapper that detects os and runs the real binary for any os Linux Mac Windows
