### ISSUE TITLE
go cli binary tar/zip not being generated

### ISSUE THREAD

**Issue by csantanapr** [openwhisk/openwhisk#762]
## Environment details:

Mac OS El Capitan

## Steps to reproduce the issue:

1.   git clone https://github.com/openwhisk/openwhisk
2.   cd openwhisk/tools/vagrant/custom
3.   vagrant up

## Provide the expected results and outputs:

Expect to see go cli binaries tar/zip generated in `tools/go-cli/bin/`

## Provide the actual results and outputs:

Only one binary is for linux is get's generated in `bin/go-cli/wsk`

**Comment by mdeuser** [comment]
@csantanapr - the openwhisk build `gradle distDocker` is now producing the Go CLI binaries under the `/bin` folder.  The conmplete set of platform/cpu-architecture specific binaries are in sub folders under `/bin/go-cli/` organized by platform/arch.  Also, a softlink to the current platform (running the build) specific binary is created at `/bin/go-cli/wsk`.  You confirmed this a few days ago, so I'm closing out this issue.  Feel free to reopen if there's something else missing.
