### ISSUE TITLE
Missing Test Coverage for CLI

### ISSUE THREAD

**Issue by dubeejw** [openwhisk/openwhisk#771]
1. Adding default parameters is not tested

2. All tests pass auth, apihost, and, apiversion as arguments to the CLI. Tests should run using the mentioned values from the property file

3. No negative tests for passing invalid arguments to all commands
    wsk action create hello
        Missing artifact

    wsk action create hello hello.js extra
        Too many arguments

    wsk action create hello hello.cpp
        Invalid runtime artifact

    wsk action create hello hello.js --kind cpp
        Invalid kind

    wsk action invoke
        Missing action name

    wsk action get
        Missing action name

    wsk action get name extra
        Too many arguments

    wsk action list name extra
        Too many arguments

    wsk action delete
        Missing action name

    wsk action delete name extra
        Too many arguments

**Comment by rabbah** [comment]
See #565 also.

**Comment by dubeejw** [comment]
Missing test for creating an action without a source file: https://github.com/openwhisk/openwhisk/issues/805.
