### ISSUE TITLE
Support for Github Wiki Updates

### ISSUE THREAD

**Issue by jsloyer** [openwhisk/openwhisk#775]
Currently with Github there ins't  any webhooks to pick  up updates on wiki’s. I know some dev’s that have built custom webhooks to pick up wiki changes and then post to slack. It would be cool if openwhisk built this into an action.

**Comment by csantanapr** [comment]
@jsloyer The current `webhook` from the github package should already work, can you pass an event from this list https://developer.github.com/v3/activity/events/types/

It looks from the Gihub docs you can use `gollum`

Can you give it a try and let us know if it covers your use case?

**Comment by jsloyer** [comment]
@csantanapr I was thinking of having this built into the new you all have for system actions.  If you could have this built into that as a prebuilt action that would be super cool!  Specifically [this new editor(https://new-console.ng.bluemix.net/openwhisk/editor)

**Comment by csantanapr** [comment]
Jeff that's what I mean it's already built in, use the Github package with the webhook feed to create a trigger that fires everyone the wiki changes 

 
Carlos Santana
IBM OpenWhisk Developer Experience Architect
Mobile/SMS 919.332.9619
Email csantana@us.ibm.com    Twitter @csantanapr
Time Zone GMT-5

**Comment by jakepeyser** [comment]
@jsloyer GitHub also recently added this capability into the repo webhook settings UI

**Comment by markusthoemmes** [comment]
@csantanapr move to catalog?

**Comment by markusthoemmes** [comment]
Issue moved to [openwhisk/openwhisk-catalog #204](https://github.com/openwhisk/openwhisk-catalog/issues/204) via [**ZenHub**](https://www.zenhub.com/)
