### ISSUE TITLE
Go CLI Should Not Send Request if Auth Key is Not Set

### ISSUE THREAD

**Issue by dubeejw** [openwhisk/openwhisk#778]
Currently the Go CLI sends request if an auth key is not set. This request is rejected by the Whisk backend, and an error is displayed to the user. This logic should be reworked so that the Go CLI does not send the request if the auth key is not set, and display an error to the user.

Tests must be updated to handle this change.

See comments: https://github.com/openwhisk/openwhisk/pull/614#discussion-diff-68622642

**Comment by mdeuser** [comment]
I'm picking this one up.

@dubeejw - Are there particular tests you know of that will require updating?
