### ISSUE TITLE
Add test cases for nginx

### ISSUE THREAD

**Issue by houshengbo** [openwhisk/openwhisk#782]
This is something we have been missing so far. nginx need test cases to check if all the vailable download links are valid, including ios, docker, go cli binaries, etc.

**Comment by rabbah** [comment]
https://github.com/openwhisk/openwhisk/blob/master/tests/src/system/basic/WskSdkTests.scala

**Comment by csantanapr** [comment]
@mdeuser and @dubeejw is this something you guys take on as part of the new Go-CLI adventure?

**Comment by markusthoemmes** [comment]
Recent failures greatly raise priority of this one. I propose to attack this next to avoid any regressions.

**Comment by rabbah** [comment]
Closed via #849.
