### ISSUE TITLE
Transient failures for `ConsulKVTests` in CI builds

### ISSUE THREAD

**Issue by psuter** [openwhisk/openwhisk#79]
The test fails occasionally, mostly on Travis CI runs (e.g. [this one](https://s3.amazonaws.com/archive.travis-ci.org/jobs/115372956/log.txt)). The most obvious symptom being:
```
Test whisk.consul.ConsulKVTests FAILED
```
The issue is likely to be that timeouts are too short for the performance the machines provide. Alternatively, the test should retry a few times before giving up.

**Comment by perryibm** [comment]
@psuter Still happening?

**Comment by psuter** [comment]
Looks good so far, thanks.

**Comment by psuter** [comment]
Here is one from this morning: https://s3.amazonaws.com/archive.travis-ci.org/jobs/119780915/log.txt

**Comment by psuter** [comment]
I'll reopen when I have non-vanishing proof.
