### ISSUE TITLE
go CLI loses bash tab completion available with python CLI

### ISSUE THREAD

**Issue by rabbah** [openwhisk/openwhisk#802]
The python CLI offers tab completion in bash (see [here](https://github.com/openwhisk/openwhisk/blob/master/tools/ubuntu-setup/bashprofile.sh)) which is referenced in the documentation [here](https://github.com/openwhisk/openwhisk/tree/master/tools/vagrant/custom#use-the-wsk-cli-inside-the-vm) (we used to have more than this reference @csantanapr):

    **Tip:** Login into the VM using `vagrant ssh` then use the `wsk` CLI with tab completion on commands and parameters.

The go CLI loses tab completion.

@dubeejw @mdeuser

**Comment by mdeuser** [comment]
@rr - here's a proposal for the Go CLI implementation.  Sound reasonable?
1. `wsk genBashCompletion`  or similar command
2. In the current working directory, a file called `wsk_cli_bash_completion.sh` is generated
3. Run `. ./wsk_cli_bash_completion.sh`  also can add command to bash profile
4. Bash completion is enabled.

**Comment by rabbah** [comment]
I was looking around at other go clis for inspirations, this project provides a cli framework (used by minio mb object store service): https://github.com/minio/cli?files=1 It had bash completion and it looks like your model has some precedence so that's 👍.

Since we have wsk sdk install how about wsk sdk install bash?

**Comment by mdeuser** [comment]
@rabbah - Thanks for the feedback.  The command line parsing package we use, cobra, has built in bash auto-completion support via an API that will generate the script.

Distribution choices are:
1. generate the script at build time and package it with the binary for download
2. generate the script at build time and make the script a separate download
3. silently generate the script (if the script has not already been generated) when the CLI is used
4. generate the script on demand.
Personally, I like option 4 as the latest and correct script is always available with whatever version of the wsk binary you have.

Yeah.  Not exactly an sdk, but I like the idea of not introducing another subcommand.  Maybe `wsk sdk install bashauto` to remove any possible thought that we have a script based SDK?

**Comment by rabbah** [comment]
+1 for 4.
