### ISSUE TITLE
go CLI assumed api host is bluemix when no api host is set for a local deployment

### ISSUE THREAD

**Issue by rabbah** [openwhisk/openwhisk#803]
## Environment details:

* mac + docker-machine

## Steps to reproduce the issue:

-  `redo couchdb initdb deploy` which runs these commands:
```
ant clean
ansible-playbook -i environments/mac couchdb.yml
ansible-playbook -i environments/mac initdb.yml
gradlew distDocker --parallel -PdockerHost=192.168.99.100:4243
ansible-playbook -i environments/mac openwhisk.yml
```
- `./bin/go-cli/wsk property get --apihost --apibuild --apibuildno`

## Provide the expected results and outputs:

```
whisk API host		192.168.99.100
whisk API build		2016-06-29T04:51:10Z
whisk API buildno	latest
```

## Provide the actual results and outputs:

```
whisk API host		 openwhisk.ng.bluemix.net
whisk API build		 2016-06-27T18:51:10Z
whisk API build number	 jenkins-mainWhisk-18130
```

The API host should be pointing to my local deployment. No API host would be better than pointing me to a external/public deployment. At least then the CLI should require me to do an initialization.

This is surely related to the loss of the property file and #783.

@mdeuser @dubeejw

**Comment by mdeuser** [comment]
@rabbah - OK to close this based on discussion and merged solution in #927?
