### ISSUE TITLE
go CLI cannot create docker action

### ISSUE THREAD

**Issue by rabbah** [openwhisk/openwhisk#804]
## Environment details:

* mac + docker-machine

## Steps to reproduce the issue:

1. build and deploy locally
2. set API host to local deployment
3.  ./bin/go-cli/wsk action create example some/image --docker  

## Provide the expected results and outputs:

```
> ./bin/wsk action create example some/image --docker  # using python CLI
ok: created action example
```

## Provide the actual results and outputs:

```
> ./bin/go-cli/wsk action create example some/image --docker -i
error: Unable to create action: error: Request failure: error: The request content was malformed:
'kind' must be a string defined in 'exec' (code 86)
```

It looks like we're missing a CLI test for docker actions.

@mdeuser @dubeejw

**Comment by dubeejw** [comment]
https://github.com/openwhisk/openwhisk/pull/795
