### ISSUE TITLE
go CLI cannot create action from empty file

### ISSUE THREAD

**Issue by rabbah** [openwhisk/openwhisk#805]
## Environment details:

* mac + docker-machine

## Steps to reproduce the issue:

1.   build and deploy locally
2.   set API host to local deployment
3.   touch foo.js
4. ./bin/go-cli/wsk action update example foo.js -i -v

## Provide the expected results and outputs:

Expect request body:

```
{"exec": {"kind": "nodejs", "code": ""}}

```

And result of CLI command to be:

```
ok: updated action example
```

## Provide the actual results and outputs:

Actual body sent:

```
{"exec":{"kind":"nodejs"}
```

And output of CLI command is:

```
error: Unable to update action: error: Request failure: error: The request content was malformed:
'code' must be a string defined in 'exec' for 'nodejs' actions (code 133)
```

Related to #804.

Notice the several `error:` messages as well on the same line and the improperly formatted `code` reference.

@mdeuser @dubeejw

**Comment by mdeuser** [comment]
@rabbah - I'll create a separate issue for the multiple "error:" strings in the error message.

As for the `code` reference in the error message, this is the numeric `code` property returned in the failing HTTP response json.  Does this have particular diagnostic meaning for the CLI user?  Should this value be ignored in the error message?

**Comment by rabbah** [comment]
Yes it should be there in the error message. Note that for other error message the code is nicely formatted.

**Comment by dubeejw** [comment]
Will add this to the missing test coverage issue as well.

**Comment by dubeejw** [comment]
@mdeuser, taking this one.

**Comment by mdeuser** [comment]
@rabbah - Since the issue results contain two different `code` values (actual action code sent to server, numeric error code in server response).  I wanted to to be sure we are talking about the same `code` value wrt the nice formatting of its value.  Currently, the Go CLI formats the numeric code value as `(code N)` at the end of the error message when an error response is received from the server, so any other error message should have this value formatted in the same manner.

**Comment by rabbah** [comment]
My eyes failed me. `(code N)` was what I was expecting but saw `code:` and stopped reading.

**Comment by mdeuser** [comment]
Sound good.  The `(code N)` will continue to be in error messages that originate from the server.  Are these values described/documented yet?  If not, I'll open a doc issue for it

**Comment by dubeejw** [comment]
Resolved by: https://github.com/openwhisk/openwhisk/commit/51817283c204c055456646c8bfb536ab78d2fdf1.
