### ISSUE TITLE
add Tone Analyzer action to watson package

### ISSUE THREAD

**Issue by starpit** [openwhisk/openwhisk#814]
https://new-console.ng.bluemix.net/catalog/services/tone-analyzer/

in addition to being generally useful, i think this could give us some fun demos :)

**Comment by rabbah** [comment]
@jasonpet @csantanapr move to proper repo?

**Comment by markusthoemmes** [comment]
Issue moved to [openwhisk/openwhisk-catalog #203](https://github.com/openwhisk/openwhisk-catalog/issues/203) via [**ZenHub**](https://www.zenhub.com/)
