### ISSUE TITLE
go CLI does not show response.result.error

### ISSUE THREAD

**Issue by jasonpet** [openwhisk/openwhisk#815]
The response.result.error field is not being shown in the go CLI.  You can verify this by calling whisk.error() in an async action.  The go CLI simply shows the following: 
error: Unable to invoke action <action name>: error: Request failure: error:  (code 0)

**Comment by mdeuser** [comment]
@rabbah - What is the expected HTTP response status code for an action invocation of an action that calls whisk.error() ?
