### ISSUE TITLE
go cli accepts more than one action name on delete

### ISSUE THREAD

**Issue by rabbah** [openwhisk/openwhisk#819]
## Steps to reproduce the issue:

```
1.   touch t.js
2.   bin/go-cli/wsk action create t.js t.js
3.   bin/go-cli/wsk action create j.js t.js
3.   bin/go-cli/wsk action delete t.js j.js
```

## Provide the expected results and outputs:

expected error message
```
wsk: error: unrecognized arguments: j.js
```

## Provide the actual results and outputs:

```
ok: deleted action t.js
```

I did not check the behavior for the other entities - I'd expect all of them to report a usage error.

@mdeuser @dubeejw

**Comment by rabbah** [comment]
I also tried this command

```
./bin/go-cli/wsk action create a b c -i
error: Unable to create action: error: Request failure: error: exec undefined (code 201)
```

This should report a usage error, not make an API request.

**Comment by mdeuser** [comment]
@rabbah - PR #770 fixes this extra argument handling issue for action and other entities.
```
main action create delme1 a.js
main action create delme2 a.js
main action create delme3 a.js
main action delete delme1 delme2 delme3
error: Invalid argument(s): delme2, delme3.
Run 'wsk --help' for usage.
```
