### ISSUE TITLE
Regression: vagrant up failed

### ISSUE THREAD

**Issue by lfzCarlosC** [openwhisk/openwhisk#822]
> note: obfuscate all passwords, credentials or other confidential information

## Environment details:

* windows 7  as host machine
* vagrant 1.8.1

## Steps to reproduce the issue:
try the updated vagrant workflows and met error:

1.    git clone --depth=1 https://github.com/openwhisk/openwhisk.git
2.   cd openwhisk/tools/vagrant
3.   ./hello

## Provide the actual results and outputs:

==> default: Step 11 : RUN rm -rf /javaAction/.classpath /javaAction/.gitignore /javaAction/.gradle /javaAction/.project /javaAction/.settings /javaAction/Dockerfile /javaAction/build
==> default:  ---> Using cache
==> default:  ---> 93bb4c52e747
==> default: Step 12 : RUN cd /javaAction; ./gradlew oneJar
==> default:  ---> Running in 8e1d45a252b6
==> default: /usr/bin/env: bash
==> default: : No such file or directory
==> default: The command '/bin/sh -c cd /javaAction; ./gradlew oneJar' returned a non-zero code: 127
==> default:
==> default: Command 'docker build -t whisk/javaaction /home/vagrant/openwhisk/core/javaAction' failed with exitCode 1, no more retries left, aborting...
==> default: :core:javaAction:distDocker
==> default: FAILED
==> default: :core:javaAction:tagImage
==> default: Executing 'docker tag -f whisk/javaaction whisk/javaaction:latest'
==> default: Error response from daemon: could not find image: no such id: whisk/javaaction
==> default: Command 'docker tag -f whisk/javaaction whisk/javaaction:latest' failed with exitCode 1, 2 retries left, retrying...
==> default: Executing 'docker tag -f whisk/javaaction whisk/javaaction:latest'
==> default: Error response from daemon: could not find image: no such id: whisk/javaaction
==> default: Command 'docker tag -f whisk/javaaction whisk/javaaction:latest' failed with exitCode 1, 1 retries left, retrying...
==> default: Executing 'docker tag -f whisk/javaaction whisk/javaaction:latest'
==> default: Error response from daemon: could not find image: no such id: whisk/javaaction
==> default: Command 'docker tag -f whisk/javaaction whisk/javaaction:latest' failed with exitCode 1, no more retries left, aborting...
==> default: :core:javaAction:tagImage FAILED
==> default: FAILURE: Build completed with 2 failures.
==> default: 1: Task failed with an exception.
==> default: -----------
==> default: * Where:
==> default: Script '/home/vagrant/openwhisk/docker.gradle' line: 71
==> default: * What went wrong:
==> default: Execution failed for task ':core:javaAction:distDocker'.
==> default: > Command 'docker build -t whisk/javaaction /home/vagrant/openwhisk/core/javaAction' failed with exitCode 1
==> default: * Try:
==> default: Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
==> default: ==============================================================================
==> default: 2: Task failed with an exception.
==> default:
==> default: -----------
==> default: * Where:
==> default: Script '/home/vagrant/openwhisk/docker.gradle' line: 71
==> default:
==> default: * What went wrong:
==> default: Execution failed for task ':core:javaAction:tagImage'.
==> default: > Command 'docker tag -f whisk/javaaction whisk/javaaction:latest' failed with exitCode 1
==> default: * Try:
==> default: Run with
==> default: --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
==> default: ==============================================================================
==> default: BUILD FAILED
==> default: Total time: 3 mins 37.397 secs
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.

## Additional information you deem important:
* issue happens only occasionally or under certain circumstances   
* changes you did or observed in the environment

**Comment by csantanapr** [comment]
I can reproduce with latest changes for gradle wand ansible install, please try again

**Comment by csantanapr** [comment]
I meant I CAN'T reproduce it :-)

**Comment by reiz** [comment]
@clambertus I'm having the same issue. Shared some more details about my environment [here](https://github.com/apache/incubator-openwhisk/issues/2538).
