### ISSUE TITLE
Command 'docker tag -f whisk/nodejs6action whisk/nodejs6action:latest' failed with exitCode

### ISSUE THREAD

**Issue by houshengbo** [openwhisk/openwhisk#855]
The openwhisk build fails due to nodejs6action when running "gradle distDocker". It happened this morning on the latest code. It showed in every travis ci build as well.

```
2: Task failed with an exception.

-----------

* Where:

Script '/home/travis/build/openwhisk/openwhisk/docker.gradle' line: 71

* What went wrong:

Execution failed for task ':core:nodejs6Action:tagImage'.

> Command 'docker tag -f whisk/nodejs6action whisk/nodejs6action:latest' failed with exitCode 1
```

**Comment by sjfink** [comment]
The tag operation failed because the docker build failed with:

[91mnpm[0m[91m [0m[91mERR![0m[91m [0m[91mfetch failed[0m[91m https://registry.npmjs.org/abab/-/abab-1.0.3.tgz

**Comment by markusthoemmes** [comment]
NPM has been down for hours.

**Comment by houshengbo** [comment]
I think npm is back online
This issue is gone.
