### ISSUE TITLE
go cli does not provide list of namespaces to select from

### ISSUE THREAD

**Issue by rabbah** [openwhisk/openwhisk#857]
## Steps to reproduce the issue:
1.   `./bin/go-cli/wsk  property set --auth $(cat ansible/files/auth.guest) --namespace`
## Provide the expected results and outputs:

```
expecting a list of namespaces to select from:
  1. guest
  x. abort and exit

```
## Provide the actual results and outputs:

```
flag needs an argument: --namespace
```

This is a problem since sometimes the set of namespaces is not known and must be retrieved from the entitlement service.

**Comment by dubeejw** [comment]
@mdeuser, looks like the Python CLI generates an interactive prompt when "property set --namespace" is called.

**Comment by mdeuser** [comment]
Alas, cobra does not currently support interactive command line argument prompting.  We'll have to handle this option flag separately - similar to the special handling of the `--param` and `--annotation` arguments.

**Comment by dubeejw** [comment]
@rabbah, I'm assuming this issue is no longer valid as the namespace is meant to be the default one at this point.

**Comment by rabbah** [comment]
I'll defer to Markus. We do need a lookup though so given a key you can know what your namespace is.

**Comment by rabbah** [comment]
Going to close this as it's not longer relevant as is, and this is related to https://github.com/openwhisk/openwhisk/issues/1135.

**Comment by mdeuser** [comment]
@rabbah - there's a BMX specific CLI change that will be coming soon that will provide a list of namespaces from which to choose when logging into BMX
