### ISSUE TITLE
gradlew bash script must preserve Unix EOL chars

### ISSUE THREAD

**Issue by mdeuser** [openwhisk/openwhisk#859]
## Environment details:
- local deployment, vagrant, Windows  
## Steps to reproduce the issue:
1.   Clone the openwhisk/openwhisk repo
2.   Examine the <topdir>/gradlew and <topdir>/core/javaAction/proxy/gradlew files for EOL chars
## Provide the expected results and outputs:

File should have Unix EOL chars - 0x0A (LF) only - no 0x0D (CR)
## Provide the actual results and outputs:

Files have CRLF EOL chars

**Comment by rabbah** [comment]
@mdeuser is this still valid?

**Comment by mdeuser** [comment]
Fixed via https://github.com/openwhisk/openwhisk/commit/46701d99071996aaaaa373cd8d07da6e91a29853
