### ISSUE TITLE
Go Cli needs /whisk.system in the command lines for packages and actions

### ISSUE THREAD

**Issue by houshengbo** [openwhisk/openwhisk#864]
If we want to do the CRUD operations on any package or action, we need tow write /whisk.system in the command line. For example, to check list all the action, we need to run "wsk action list /whisk.system"
instead of "wsk action list"; 
we need to get one package by running "wsk package get /whisk.system <package name>" instead of "wsk package get <package name>".
This applies to all the commands regarding packages and actions.

However, we do need to add /whisk.system for python cli.

**Comment by dubeejw** [comment]
@mdeuser, I'll look at this one.

**Comment by rabbah** [comment]
You can't omit the `whisk.system` prefix. This is part of the fully qualified name of the package. Maybe I don't follow the issue. `wsk action list` lists actions in the namespace that the CLI is configured for. `wsk action list /whisk.system` lists actions in `whisk.system` namespace. They are semantically different. Are you saying the go cli does not support the latter yet?

**Comment by dubeejw** [comment]
Works fine for me. My namespace is set to _ in the CLI properties.

**Comment by mdeuser** [comment]
@houshengbo - Per @rabbah 's comment above, the packages you want to access reside in a separate namespace, `whisk.system` which is not your default namespace.  The CLI can be configured with a default namespace `wsk property set --namespace NAME`; all subsequent CLI commands will default to that namespace.  Use `wsk property get --namespace` to see your current default namespace configuration.  If you want to access another namespace while retaining the default namespace configuration, the target entity must include the target namespace (i.e. `/whisk.system/weather` is the qualified name of the weather package).

Entities in have access control protection via --auth key and the entity's public(shared)/private setting.  So even though you know the namespace, you might not have access to a particular entity in that namespace.  Currently, this access control implementation has issues per the following conversation I had with @rabbah.
```
Mark Deuser [8:17 AM]  
ah.. `wsk package list /whisk.system` does work
are the /whisk.system entities shared?
maybe that's where i'm confused.. does a `public` entity give read rights (i.e. list, copy) ?
packages, actions, triggers, and rules can all be created as `public`

Rodric Rabbah [8:24 AM]  
Yeah that's misleading we have defects to address
Only carries meaning on a package today
```
So, at the moment, the public/private setting is only applicable to packages right now; this means that even though a non-package entity in another namespace may be configured as `public (shared)`, it won't be directly accessible via the CLI.  To have that access to that entity, you will need to supply the namespace's auth key.

@rabbah - Feel free to confirm and/or correct.
