### ISSUE TITLE
two github.webhook error handling bugs

### ISSUE THREAD

**Issue by starpit** [openwhisk/openwhisk#886]
github.webhook has two bugs with regards to error handling. here is the relevant source:

```
      if (error) {
        whisk.error();
      }
      console.log("Status code: " + response.statusCode);
      whisk.done({response: body});
```

issue 1: it should be `return whisk.error();`

issue 2: there is a missing clause, to handle non-200 responses from github. proposed code:

```
      if (error) {
        return whisk.error({response: "Internal Error"});
      }
      console.log("Status code: " + response.statusCode);
      if (response.statusCode >= 400) { /* or != 200? */
        return whisk.error({response: body});
      } else {
        return whisk.done({response: body});
      }
```

@bjustin-ibm raised a related UI issue: https://github.ibm.com/BlueMix-Fabric/Bluemix-Whisk-UI/issues/473

**Comment by psuter** [comment]
FWIW you don't need to `return` `whisk.done(...)` or `whisk.error(...)`.

There's an [example here](https://github.com/openwhisk/openwhisk/blob/master/docs/actions.md#using-actions-to-call-an-external-api), for instance, where `whisk.done(..)` is called without `return`.

**Comment by starpit** [comment]
the first return is i think needed? it is there for flow control, not returning a value. i figured i'd leave the others, to avoid future regressions in control flow.

**Comment by rabbah** [comment]
It is a user error to not terminate the control flow correctly as in this case - because the next time the action runs, if assigned to the same container, the call stack is not popped and so execution will resume for the previous call while also executing the new call.

**Comment by bjustin-ibm** [comment]
> the first return is i think needed?

@starpit Ahhh... I see it now. The trouble is that without the first `return` there is a possibility of calling `error()` followed by another call to either `error()` or `done()` in the `request` callback.

I added an `else` to my implementation in #893 (as I am personally not a fan of functions with lots of `returns`) to avoid this possibility:

```javascript
    request(options, function(error, response, body) {
      if (error) {
        whisk.error(error);
      } else {
        console.log("Status code: " + response.statusCode);

        if(response.statusCode != 200) {
          console.log("Response from Github: " + body);
          whisk.error({response: body});
        } else {
          whisk.done({response: body});
        }
      }
    });
```

**Comment by starpit** [comment]
i think this one is closable now that #893 has been merged?

**Comment by psuter** [comment]
Indeed.
