### ISSUE TITLE
go cli does not separate a long package (binding) name with a space from "private"

### ISSUE THREAD

**Issue by rabbah** [openwhisk/openwhisk#887]
## Steps to reproduce the issue:

1.   `wsk package create aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa`
2.   `wsk package list`

## Provide the expected results and outputs:

```
/{namespace}/aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa private        
```

note the space before `private`

## Provide the actual results and outputs:

```
/{namespace}/aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaprivate
```

note the lack of space before `private` - making for a subtle error when copy pasting package names into say the iOS SDK.

@mdeuser @dubeejw

**Comment by mdeuser** [comment]
@rabbah - is there a need for the `private` column to be at a particular location (i.e. column 70 vs 71)?

**Comment by rabbah** [comment]
no - the requirement i would say is that it shouldn't appear to be part of the string appearing in an adjacent column.
