### ISSUE TITLE
Update team in iOS Starter App

### ISSUE THREAD

**Issue by paulcastro** [openwhisk/openwhisk#907]
Add a team to the iOS Starter App configuration to allow inclusion in CI.  This setting can easily be changed by developers who download the code and want to build using their own team.

Without this being set, CI for the starter app will fail because of Xcode code signing issues.  Its likely this can be set using the command line, however you need the UUID of a valid provisioning profile, which must be installed on the build machine.

**Comment by paulcastro** [comment]
We can move to command line driven provisioning profile settings, just a thorny issue on getting the UUID of the currently used profile.

**Comment by rabbah** [comment]
@paulcastro Is this done?

**Comment by paulcastro** [comment]
Yes, this is all set.  We can build the starter app in CI now.
