### ISSUE TITLE
Feature: remove a default parameter from an action

### ISSUE THREAD

**Issue by ioana-blue** [openwhisk/openwhisk#912]
Assume you updated your action by mistake with a default parameter. There is no way to remove it, or at least I can't find one. This is a feature request for the CLI to remove an existing parameter from an action.

**Comment by ioana-blue** [comment]
On a related note, I thought that updating the code for the action would remove the default params, but it doesn't seem to be so.

**Comment by rabbah** [comment]
duplicate of #76?

**Comment by ioana-blue** [comment]
yes, closing.
