### ISSUE TITLE
Valid activation ids with addtional characters appended are treated as valid activation ids

### ISSUE THREAD

**Issue by mdeuser** [openwhisk/openwhisk#917]
## Environment details:

* local deployment, native Windows, Bluemix

## Steps to reproduce the issue:

1.   `wsk action create test ..\..\..\catalog\samples\hello.js`
2.   `wsk action invoke test`
3.   Note the activation id
4.   `wsk activation get <activationid>`
5.   `wsk activation get <activationid>1234567890`  - appending 1234567890

## Provide the expected results and outputs:

Step 4 - activation id in this test run output is `a559d854f6f943f0930e4d512abdeaac`
```
ok: got activation a559d854f6f943f0930e4d512abdeaac
{
    "namespace": "mdeuser@us.ibm.com",
    "name": "test",
    "version": "0.0.1",
    "subject": "mdeuser@us.ibm.com",
    "activationId": "a559d854f6f943f0930e4d512abdeaac",
    "start": 1468876430035,
    "end": 1468876430514,
    "response": {
        "status": "success",
        "success": true
    },
    "logs": [
        "2016-07-18T21:13:50.507146226Z stdout: hello undefined!"
    ]
}
```
Step 5.
Expected an error stating that the activation id was invalid

## Provide the actual results and outputs:

Step 5 output
```
ok: got activation a559d854f6f943f0930e4d512abdeaac1234567890
{
    "namespace": "mdeuser@us.ibm.com",
    "name": "test",
    "version": "0.0.1",
    "subject": "mdeuser@us.ibm.com",
    "activationId": "a559d854f6f943f0930e4d512abdeaac",
    "start": 1468876430035,
    "end": 1468876430514,
    "response": {
        "status": "success",
        "success": true
    },
    "logs": [
        "2016-07-18T21:13:50.507146226Z stdout: hello undefined!"
    ]
}
```

## Additional information you deem important:
* The activation ID with the appended characters is sent in the GET HTTP request.  It appears that anything after the first 32 characters is truncated by the server.

**Comment by rabbah** [comment]
Fixed by #918.
