### ISSUE TITLE
go cli wsk property get with --apihost override does not work correctly

### ISSUE THREAD

**Issue by rabbah** [openwhisk/openwhisk#924]
The Go CLI is not properly overriding the API host. Some command that should fail run instead against Bluemix's deployment of openwhisk.
## Environment details:
- mac + docker machine
## Steps to reproduce the issue:
1.   ./bin/go-cli/wsk --apihost xxx.yyy property get --apibuildno
## Provide the expected results and outputs:

From python CLI:

```
> ./bin/wsk --apihost xxx.yyy property get --apibuildno
[Errno 8] nodename nor servname provided, or not known
whisk API build     Cannot determine API buildno:
```
## Provide the actual results and outputs:

and here is the Go CLI output.

```
whisk API host       openwhisk.ng.bluemix.net
whisk API build number   jenkins-mainWhisk-18211
```

Setting the API host to something outside the local deployment by default is dangerous and prone to subtle errors. The CLI should either not set the API host at all (thus requiring one to configure it before using it) or it should set it based on the local environment.

FYI @mdeuser @dubeejw.

**Comment by mdeuser** [comment]
The solution will be to not provide a default api host at all.  This solution will also address #803

**Comment by rabbah** [comment]
Note however that the --apihost should override whatever host is set (or not set) when doing a property get.

**Comment by mdeuser** [comment]
For this particular capability addressed by this issue, the Go command line package behaves a bit differently than the Python command line parser.  In particular, when a command line argument (i.e. `--apihost`) is defined against the root command and sub-commands, the sub-command definition "wins".

The Go `wsk` command defines `--apihost`, `--auth` and `--apiversion` flags that each take a string argument; the Go `wsk property get` command defines the same flags; however, these flags are boolean switches and do not take string arguments.  When the command arguments are merged, it appears that the final command's definition (`get` in this scenario) will override any previous argument definitions having the same name.

Consequently, the Go CLI behavior will differ from the Python CLI for this scenario.
```
>wsk property get --apihost
whisk API host           openwhisk.ng.bluemix.net
>wsk --apihost openwhisk.stage1.ng.bluemix.net property get --apihost
whisk API host           openwhisk.ng.bluemix.net
```

One solution may be to have two commands - one command that manages CLI configuration and another command that obtains whisk server settings.

**Comment by rabbah** [comment]
while i find the behavior of the previous cli more convenient, the current behavior is acceptable; closing as won't fix.
