### ISSUE TITLE
couchdb requests hang if no db is present in deployment

### ISSUE THREAD

**Issue by rabbah** [openwhisk/openwhisk#926]
## Environment details:
- mac + docker-machine
## Steps to reproduce the issue:
1.   redo teardown deploy
2.   wsk list
3.   wsk list
## Provide the expected results and outputs:

Except both `wsk list` commands to fail with this error message:

```
error: The server is currently unavailable (because it is overloaded or down for maintenance).
```
## Provide the actual results and outputs:

The first `wsk list` responds as expected. The second hangs until terminated by nginx. Digging a bit into the Couch REST client, it appears the second request is offered into the db request queue but the corresponding future does not complete. It does not help if a db instance is brought online after the second request. All subsequent `wsk list` commands hang.

This behavior is only observed/reproduced if running the controller within a container. I have tried but to no avail to reproduce the behavior without a container and by using @psuter's #900 chaos proxy (which also runs without a container)... will need to dig deeper.

**Comment by psuter** [comment]
To make matters more "interesting", the client doesn't hang if you wait "long enough" between 2. and 3. (experimental fiddling suggests ~1mn, could be less).

**Comment by psuter** [comment]
Also stuck for today. Have confirmed through additional logging that the queue in `CouchDbRestClient` is not the culprit in the scenario above: requests go through it instantly (in `akka-stream` terms: the connection pool never back-pressures).

**Comment by rabbah** [comment]
> To make matters more "interesting", the client doesn't hang if you wait "long enough" between 2. and 3. (experimental fiddling suggests ~1mn, could be less).

Indeed - but then issue yet another `wsk list` and it will hang.

**Comment by psuter** [comment]
Close?

No longer reproducible as such. I believe we established it was tied to the deploy sequence, and went away when we added the "proper" wait instructions.

**Comment by rabbah** [comment]
No longer reproducible indeed.
