### ISSUE TITLE
KafkaTests depends on KafkaConnectorTests

### ISSUE THREAD

**Issue by domdom82** [openwhisk/openwhisk#93]
Commit https://github.com/openwhisk/openwhisk/commit/ef0c02606d803839a26612af0408af0483f29414

ignores KafkaTests for now.

We found out that the test works if KafkaConnectorTests run first. It fails if not, so I assume a connection between the two. 

Related to gradle work in https://github.com/openwhisk/openwhisk/pull/6 which changed order of test execution and revealed this dep.

**Comment by rabbah** [comment]
closing - this test suite no longer exists.
