### ISSUE TITLE
Port uses of async/done/error to Promises

### ISSUE THREAD

**Issue by psuter** [openwhisk/openwhisk#932]
For JavaScript feeds, actions, etc., as `Promise`s are the way forward.

An exception should be made for tests that explicitly exercise the `async`/`done`/`error` patterns as long as they are not deprecated.

To get a crude estimate of the changes required (as of 9fceba2ee3f9a06e6466f6fe71f2d1235c4dbde1):

    $ grep -lrI --include '*.js' async .
    ./catalog/github/webhook.js
    ./catalog/samples/countdown.js
    ./catalog/samples/curl.js
    ./catalog/samples/helloAsync.js
    ./catalog/samples/helloPromises.js
    ./catalog/samples/wcbin.js
    ./catalog/slack/post.js
    ./catalog/utils/pipe.js
    ./catalog/watson/languageId.js
    ./catalog/watson/speechToText.js
    ./catalog/watson/textToSpeech.js
    ./catalog/watson/translate.js
    ./catalog/weather/forecast.js
    ./catalog/websocket/sendWebSocketMessageAction.js
    ./core/nodejsActionBase/runner.js
    ./core/nodejsActionBase/src/whisk.js
    ./core/nodejsActionBase/test.js
    ./tests/dat/actions/helloAsyncDoneTwice.js
    ./tests/dat/actions/ping.js

FYI @bjustin-ibm @jasonpet

**Comment by jasonpet** [comment]
We should make these changes in openwhisk-catalog for all actions that have been moved there.

**Comment by bjustin-ibm** [comment]
@jasonpet do you want to take this, or perhaps split the chore between us?

**Comment by jasonpet** [comment]
We can split it.  I will do it for all of the actions that will now exist in openwhisk-catalog if you can do it for the ones staying behind.

**Comment by bjustin-ibm** [comment]
Sounds good, can you give me a concrete list of the ones that are staying?

**Comment by psuter** [comment]
If you could also make a note of which ones are actually tested? (hopefully all of them)

**Comment by jasonpet** [comment]
@houshengbo - do you have a list already of all the actions that are actually tested?
