### ISSUE TITLE
weather package has multiple breakages; it's not usable in its current form

### ISSUE THREAD

**Issue by starpit** [openwhisk/openwhisk#937]
- [ ] description is wrong, as the bluemix service name has changed to 
  "Weather Company Data for IBM Bluemix"
- [ ] no bluemixServiceName attribute, so auto-binding won’t work. the attribute value should be `weatherinsights`
- [ ] parameters need to change from apiKey to username+password

here is an example of the credentials:

```
 "credentials": {
        "username": "xxx",
        "password": "yyy",
        "host": "twcservice.mybluemix.net",
        "port": 443,
        "url": "https://yyy@twcservice.mybluemix.net"
      }
```

**Comment by rabbah** [comment]
@jasonpet is this addressed now in the new package?

**Comment by rabbah** [comment]
@csantanapr is this still relevant?

**Comment by csantanapr** [comment]
yep all this is fixed now
