### ISSUE TITLE
the sampleInput of util.split is not valid JSON

### ISSUE THREAD

**Issue by starpit** [openwhisk/openwhisk#946]
the sampleInput for split is not JSON it is a string. compare these two:

sort has proper JSON:
![screen shot 2016-07-25 at 2 58 21 pm](https://cloud.githubusercontent.com/assets/4741620/17113378/8557fec6-5278-11e6-98d1-e29ad36136c7.png)

and split does not:
![screen shot 2016-07-25 at 2 58 18 pm](https://cloud.githubusercontent.com/assets/4741620/17113380/89648fa2-5278-11e6-9542-0f36c046a27b.png)

**Comment by csantanapr** [comment]
@jasonpet can you take a look?

**Comment by jasonpet** [comment]
sure

**Comment by starpit** [comment]
there is a missing close quote in the description annotation

**Comment by starpit** [comment]
see this one, from way back: https://github.com/openwhisk/openwhisk/issues/137

the backend is accepting invalid json, and, worse, stringifying it.

**Comment by csantanapr** [comment]
@dubeejw why you close this issue?

**Comment by jasonpet** [comment]
@csantanapr - he closed it because he merged the fix in already.

**Comment by csantanapr** [comment]
@jasonpet Thanks for the info. @dubeejw When we close issues because the PR is merged, It's good to add a message like "closing merged with commit xxxxxxx"  this way give reason but also can find the commit that fixed the issue, then we can track when it makes it to production.

**Comment by csantanapr** [comment]
@jasonpet What's the PR that fixed this issue? I was not able to see a mentioned reference here.

Yes I know I know, if I look very hard I eventually will find it 😃

**Comment by jasonpet** [comment]
PR - https://github.com/openwhisk/openwhisk/pull/951
