### ISSUE TITLE
go cli should fail with a nicer error when api host is not set

### ISSUE THREAD

**Issue by rabbah** [openwhisk/openwhisk#979]
## Steps to reproduce the issue:

1.   fresh build and deploy
2.   `wsk list`

## Provide the actual results and outputs:

```
> bin/go-cli/wsk list
error: Unable to obtain namespace entities for namespace '': Request failure: Get https:///api/v1/namespaces/_/: http: no Host in request URL
```

This is because the go cli no longer sets an api host by default - but then it should fail with a nicer and clearer error.

FYI @mdeuser @dubeejw.

**Comment by lzbj** [comment]
@rabbah , is it already fixed? I assign myself to look into some go code and try some fix, feel free to reassign if not appropriate, thank you.
