### ISSUE TITLE
Remove limitation of 1MB code for JS-actions

### ISSUE THREAD

**Issue by cbickel** [openwhisk/openwhisk#982]
https://github.com/openwhisk/openwhisk/blob/master/core/nodejsActionBase/app.js#L36

There's a limit, that prohibits actions that are greater than 1MB. Since we check the size of actions on creating them (and have a limit of 48MB) this limit is obsolete an can be removed.

**Comment by csantanapr** [comment]
@ChrBi What this means that with the latest changes, a JS action can be created successfully larger than 1MB, but it will failed when the user tries to invoke it ?

Other languages don't this type of hardcoded limits?

**Comment by rabbah** [comment]
Patch in #1038.
