### ISSUE TITLE
Go CLI argument parity with Python CLI

### ISSUE THREAD

**Issue by mdeuser** [openwhisk/openwhisk#986]
The following command arguments are not consistent across the Go and Python `wsk` CLI.
1. `wsk action list` - The Go CLI has a `--full` argument, the Python CLI does not
2. `wsk package list` - The Go CLI has `--full` and `--shared s` arguments, the Python CLI does not
3. `wsk rule get` - The Python CLI has a `--summary` argument, the Go CLI does not
4. `wsk trigger get` - The Python CLI has a `--summary` argument, the Go CLI does not
5. `wsk package create` - The Go CLI has a `--service_guid` argument, the Python CLI does not
6. `wsk package update` - The Go CLI has a `--service_guid` argument, the Python CLI does not

The following commands take an additional non-flag argument which acts as a property selector.  The Python CLI supports this argument, the Go CLI does not.
1. `wsk action get ACTION_NAME [PROPERTY_NAME]`
2. `wsk activation get ACTION_NAME [PROPERTY_NAME]`
3. `wsk package get ACTION_NAME [PROPERTY_NAME]`
4. `wsk rule get ACTION_NAME [PROPERTY_NAME]`
5. `wsk trigger get ACTION_NAME [PROPERTY_NAME]`

**Comment by rabbah** [comment]
Package (and action summaries) are not working correctly in the go cli (another test gap):

```
openwhisk> wsk package update p -a parameters '[ {"name":"someP", "required":false}, {"name":"anotherP", "required":false} ]'
ok: updated package p
openwhisk> ./bin/go-cli/wsk -i --apihost 192.168.99.100 package get p --summary
package /guest/p
openwhisk> wsk package get p --summary
package /guest/p
   (params: someP anotherP)
```

**Comment by dubeejw** [comment]
For bookkeeping sake, the above mentioned ```--full```, and ```---serviceguid``` issues have been fixed.

**Comment by markusthoemmes** [comment]
>wsk package create - The Go CLI has a --service_guid argument, the Python CLI does not
>wsk package update - The Go CLI has a --service_guid argument, the Python CLI does not

These should not be in the go-cli, they are entirely Bluemix specific.

**Comment by csantanapr** [comment]
@dubeejw @mdeuser 
What work is left here to implement?   Just the get a specific property from the entity?

>The following commands take an additional non-flag argument which acts as a property selector.  The Python CLI supports this argument, the Go CLI does not.
1. `wsk action get ACTION_NAME [PROPERTY_NAME]`
2. `wsk activation get ACTION_NAME [PROPERTY_NAME]`
3. `wsk package get ACTION_NAME [PROPERTY_NAME]`
4. `wsk rule get ACTION_NAME [PROPERTY_NAME]`
5. `wsk trigger get ACTION_NAME [PROPERTY_NAME]`

**Comment by csantanapr** [comment]
I was going over the docs, and we document this feature for the CLI, in python is used to work.
Now with Go CLI, it doesn't I would consider this a regression from the customer point a view.
From the docs [packages.md#creating-a-package](https://github.com/openwhisk/openwhisk/blob/master/docs/packages.md#creating-a-package)

From the docs we document the following three commands that are broken

1. `package get PACKAGE_NAME parameters`
  ```
  $ wsk package get custom parameters
  ```

2. `action get ACTION_NAME parameters`
  ```
  $ wsk action get custom/identity parameters
  ```

3. `package get PACKAGE_NAME publish`
  ```
  $ wsk package get custom publish
  ```


This needs to be high on our priority list

@dubeejw Can you comment on how difficult would be to fix this?

**Comment by dubeejw** [comment]
@csantanapr, it should not be too difficult after we get https://github.com/openwhisk/openwhisk/pull/1175 merged.

**Comment by csantanapr** [comment]
Linking to PR https://github.com/openwhisk/openwhisk/pull/1376 so we revert back the docs when this is fix in CLI
