### ISSUE TITLE
Consistent KIND configuration

### ISSUE THREAD

**Issue by mdeuser** [openwhisk/openwhisk#988]
When creating an action, a KIND can be specified to provide run-time and run-time version requirements.  NodeJS support has the following KINDs that cover all Whisk supported NodeJS environments.
- nodejs:6
- nodejs:default  (aka latest nodejs version supported by Whisk)
- nodejs  (aka nodejs 12)

Swift support currently has the following KINDs
- swift:3
- swift  (aka swift 2)

Unlike the nodejs KIND values, there is no default swift KIND value, "swift:default" that would map to the latest swift supported by Whisk.

Other run-times, such as Java and Python, should consider similar KIND version support so that customers can recreate actions with a pinned run-time version.

Related PR #738 (for creating nodejs:default)

**Comment by bjustin-ibm** [comment]
Getting the backend to recognize more `--kind` aliases is as simple as adding a new entry to the `match` found here: https://github.com/openwhisk/openwhisk/blob/master/common/scala/src/main/scala/whisk/core/entity/DefaultRuntimeVersions.scala

After that, it is just a matter of getting the CLI to recognize/tolerate/default to the new alias.

**Comment by dubeejw** [comment]
@csantanapr, looks like this one can be closed.
