### ISSUE TITLE
Provide sequence ID in addition to activation IDs

### ISSUE THREAD

**Issue by nauerz-ibm** [openwhisk/openwhisk#992]
To track the behavior of a sequence (e.g. when debugging going through logs) comprised of multiple activations the same way one would use a transaction or session ID on other products customers suggested the introduction of a sequence ID being associated with each action invoked as part of a particular sequence.

Thoughts?

**Comment by bjustin-ibm** [comment]
I think this is a great idea, and I would like to see it generalized to include rules. Now that I have several rules in place, activations from several rules are interleaved. This makes it difficult to determine the "thread" of activations - which is really an important key to debugging. 

Some kind of activation metadata (like a new id) that ties multiple activations together would not only allow users to more effectively debug logs, but would also allow clients like the CLI or Bluemix UI to present activation records in a grouped or threaded fashion that would make it clear to the user the chain of events to which the activations belong.

**Comment by rabbah** [comment]
Activations have a `caused` property which was introduced for this reason. We lost this causality tracking when we rewrote the activator but we will be adding it back. And with the new sequence implementation, we will have this feature. @nauerz-ibm timely issue.

**Comment by nauerz-ibm** [comment]
Awesome.
Thanks @rabbah , @ioana-blue , and @bjustin-ibm !

**Comment by ioana-blue** [comment]
Timely issue. I'm changing our implementation of sequences and as a consequence, we'll have activation ids for sequences. More details about the implementation are discussed in #995
