### ISSUE TITLE
Discussion: Keep containers warm as first-class primitive/option

### ISSUE THREAD

**Issue by ioana-blue** [openwhisk/openwhisk#994]
One potential use for OW actions is any machine-learning prediction. Usually, the heavy computation happens off-line when training the model. In theory, the prediction can be encapsulated in an action that is invoked each time a prediction needs to be performed. 

However, some models are large enough that "loading" the model on each action invocation takes in the order of seconds, while executing the prediction is fast (in the order of ms). Given that we reuse containers, we could write the user code in such a way that we check whether the model is loaded or not and have some "fake" actions that do not execute anything, they just make sure the containers stay warm for potential real actions to execute. 

This "hack" could be replaced by a first-class citizen option in our system: offer the ability to run "special" containers that the system keeps warm. 

This came up in a discussion with one of our interns that is building a specialized search service that needs to load a classification model in the order of 500MB-1GB.

**Comment by mbehrendt** [comment]
@ioana-blue one increasingly common 'hack' is to run actions in a scheduled fashion, just for the sake of keeping them warm.

would that do the trick?

**Comment by ioana-blue** [comment]
@mbehrendt Yes, I'm wondering if we were to replace this 'hack" with an option at the runtime level. I guess we would benefit from it because we would get rid of all these additional (useless) invokes; instead, we would know at the runtime level to treat some containers differently.

Related, I would have to check the implementation we have for python. I may clear the "namespace" of previous invocations unintentionally (not sure how python works wrt using `namespace = {}` when starting to run the user code)

**Comment by csantanapr** [comment]
My two cents: If the developer requires a long running container containing previous state (i.e. cache files) from previous state, then maybe the workload is not best fit for to be solve using serverless. The workload looks like is best solve by normal deamon/server platform.

I not familair with the specific use case but I would solve the problem in a different way if I was going to use serverless. 
If there is a large archive 500MB-1GB that the function needs to be initialize, then I would consider this archive part of the definition of the action. I would create a new docker action specific for the function include the 500MB archive and push the docker image.
Then whisk will use the container at the time of doing the computation and run the docker container containing logic code and archive (model).

Today there is small delay for whisk to pull down and cache the docker action, but this can be optimized in the future if whisk were to offer a docker registry that user can push their docker images to.

**Comment by mbehrendt** [comment]
i think there are many use cases where a warm action is desirable  (warm action = more consistency in terms of fast invocation time), however, i don't think we shouldn't yet be spending effort on implementing native support for this yet. this feature can technically clearly be done, but introduces more complexity to how the engine behaves, another parameter that needs to be taken account across the board, etc. we should rather focus on improving the primitives first, and add this feature once the foundation is ready for it -- specifically given there is a reasonable workaround available.

**Comment by ioana-blue** [comment]
@csantanapr Including the "archive" in the image helps only with having the data hopefully closer, but you still have to load it in the memory of the action. not sure how long that takes, but I would think it takes some non-negligible  time

@mbehrendt I agree that we don't have time for this now.

**Comment by hsane2001** [comment]
Can we consider this enhancement at this time? There is a real need to either keep containers alive with neural network models loaded so that inference actions can be launched quite quickly.
